### ISSUE TITLE
Haxe Roundup 638

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1000]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` Unable to create a `Map<Float, Int>` [issue](https://github.com/HaxeFoundation/haxe/issues/10762).

**Comment by skial** [comment]
- [ ] `[core/php]` Possible runtime metadata field name bug [issue](https://github.com/HaxeFoundation/haxe/issues/10764).

**Comment by skial** [comment]
- [ ] `[open source]` [Ceramic `0.15.0`](https://github.com/ceramic-engine/ceramic/releases/tag/v0.15.0) has been released!

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` Process: Do not create console on Windows OS [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1004).

**Comment by skial** [comment]
- [ ] `[core]` Needless allocation for the last of multiple identical operations [fixed](https://github.com/HaxeFoundation/haxe/issues/10765).

**Comment by skial** [comment]
- [ ] `[core]` Compilation server. Wrong error position info [issue](https://github.com/HaxeFoundation/haxe/issues/10763).

**Comment by skial** [comment]
- [ ] `[video]` In Your Books [Trailer](https://www.youtube.com/watch?v=6oxaCdu6TNk&widget_referrer=haxe.io).

**Comment by skial** [comment]
- [ ] `[video]` I am the king of Octodad combos [video](https://www.youtube.com/shorts/gWDU_2sjyes&widget_referrer=haxe.io) by Fraymakers.

**Comment by skial** [comment]
- [ ] `[open source]` [extension-kizzyrcp `git`](https://github.com/MAJigsaw77/extension-kizzyrcp) - A android extension that uses Kizzy RPC android library.

**Comment by skial** [comment]
- [ ] `[open source]` [Penguin-Dash `git`](https://github.com/PhilipU21/Penguin-Dash) - A penguin themed endless runner game made using the Stencyl engine. A lecture and laboratory activity for the creators' Human-computer interaction (HCI) subject during the second semester of their second year. Available on [itch.io](https://philipu.itch.io/penguin-dash).

**Comment by skial** [comment]
- [ ] `[closed source]` New sound effects to add some atmosphere in Rogue of Vallas by [Merrak](https://twitter.com/merrak/status/1551798800028762112).

**Comment by skial** [comment]
- [ ] `[open source]` HaxeUI now has an experimental Canvas component, which is quite functional, currently implemented for Html5, OpenFL, Heaps and Raylib. :star2:
   - [Animation](https://twitter.com/IanHarrigan1982/status/1551245169260986368) component.
   - [Simple paint](https://twitter.com/IanHarrigan1982/status/1551480574522654724) tool.
   - [Colour picker](https://twitter.com/IanHarrigan1982/status/1552272962618904576)

**Comment by skial** [comment]
- [ ] `[community/event]` Aurel will be talking about the ammer framework at the upcoming [HaxeHybrid LAX](https://twitter.com/osakared/status/1550896415794114561) event.

**Comment by skial** [comment]
- [ ] `[open sourced]` [Michael Bickel](https://twitter.com/dazKind/status/1550829129376972801) has opened source the first steps to get Haxe natively integrated with Godot.

**Comment by skial** [comment]
- [ ] `[community]` ⛏️Cave Generator `1.0.1` and ideas for further development [article](https://www.patreon.com/posts/cave-generator-1-69424288) by [Oleg Dolya](https://twitter.com/watawatabou/status/1550501575700914177).

**Comment by skial** [comment]
- [ ] `[community]` Wartales Community [Update `#4`](https://store.steampowered.com/news/app/1527950/view/3383909822381942160) featuring new content, community requests and full Chinese localisation!

**Comment by Beeblerox** [comment]
- [ ] New [editor screenshot](https://twitter.com/dylnavas36/status/1550778437673140226) from the game by SavanDev

**Comment by Beeblerox** [comment]
- [ ] torcado: [Being a Solo Game Developer](https://80.lv/articles/torcado-being-a-solo-game-developer) interview

**Comment by Beeblerox** [comment]
- [ ] Footgolf - [some questionable QB ratings](https://twitter.com/jano_games/status/1550507242570539008) by JanoGames

**Comment by Beeblerox** [comment]
- [ ] ["Papers, Please" but small](https://twitter.com/dukope/status/1550895020861181952). August 5th. Android and iOS, phones and tablets.

**Comment by Beeblerox** [comment]
- [ ] [HaxeJam 2022: Summer Jam](https://itch.io/jam/haxejam-2022-summer-jam) has started, with theme "Lose it All"

**Comment by Beeblerox** [comment]
- [ ] Prexot shares [progress on rhythm rpg](https://discord.com/channels/162395145352904705/162664383082790912/1001204744053870712) game, which is being made with Ceramic engine and Spine animation.

**Comment by Beeblerox** [comment]
- [ ] [Skyfire2008](https://discord.com/channels/162395145352904705/162664383082790912/1001946053790142474) has made a new enemy for [TD2S](https://kurt-c0caine.itch.io/td2s)
