### ISSUE TITLE
Haxe Roundup 642

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1008]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core/haxelib]` Migrate to argon2id for storing passwords [pull requests](https://github.com/HaxeFoundation/haxelib/pull/564).

**Comment by skial** [comment]
- [ ] `[open source/weblink]` Add OAuth2 support [pull request](https://github.com/PXshadow/weblink/pull/18).

**Comment by skial** [comment]
- [ ] `[core]` Restore macOS 10.13 (High Sierra) support [pull request](https://github.com/HaxeFoundation/haxe/pull/10778).

**Comment by skial** [comment]
- [ ] `[open source]` [Ceramic `0.16.0`](https://github.com/ceramic-engine/ceramic/releases/tag/v0.16.0) has been released.

**Comment by skial** [comment]
- [ ] `[open source/heaps]` Fixed 8-bit WAV files playing with glitches due to incorrect sample rate calculation [merged](https://github.com/HeapsIO/heaps/pull/1093).

**Comment by skial** [comment]
- [ ] `[core]` Restoring Lua tests [issue](https://github.com/HaxeFoundation/haxe/issues/10777).

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` Inconsistent overflow behavior for Int32 [issue](https://github.com/HaxeFoundation/haxe/issues/10780).

**Comment by skial** [comment]
- [ ] `[community]` Neighbourhood Generator `1.2.0`: new template, integration with mansions, lots of visual changes [article](https://www.patreon.com/posts/70917627) by [Oleg Dolya](https://twitter.com/watawatabou/status/1562381273196265472).

**Comment by skial** [comment]
- [ ] `[closed source]` New stage incoming to [Fraymakers](https://twitter.com/FraymakersGame/status/1560752620528025600)!

**Comment by skial** [comment]
- [ ] `[open source]` [Michael Bickel](https://twitter.com/dazKind/status/1561841280908496898) [hxgodot-cpp `git`](https://github.com/dazKind/hxgodot-cpp) repo is _"slowly taking shape. Basic Variants are working, I put down the first issues for people to track, comment and pick up"_.

**Comment by Beeblerox** [comment]
- [ ] [Unept](https://twitter.com/Unept/status/1560283003921674240) has updated [their games](https://apps.apple.com/us/developer/unept/id1159852090) to work on new iPhones

**Comment by Beeblerox** [comment]
- [ ] SnkyGames will add an option for [different low resolutions](https://twitter.com/SnkyGames/status/1560352175523504129) in Starwing. Here is [low resolution Arwing](https://snkygames.com/_hx/) on display

**Comment by Beeblerox** [comment]
- [ ] Chester's adventures continue in the [free Water Theatre update](https://twitter.com/AdventIslands/status/1560914542355423233) for Tightrope Theatre. Coming soon!

**Comment by Beeblerox** [comment]
- [ ] Ian Harrigan shows [new example](https://twitter.com/IanHarrigan1982/status/1560938476631097344) in the HaxeUI explorer: todos

**Comment by Beeblerox** [comment]
- [ ] [Fight intro](https://twitter.com/joelgervasi/status/1561032198383337472) from Scraps of Light. The player can skip this intro by spam-clicking as well

**Comment by Beeblerox** [comment]
- [ ] Some updates on Chibi Ninja Shino-kun: Treasure of Demon Tower by Ando:
    * [pixeling away](https://twitter.com/ohsat_games/status/1560027907216625664) at my new game
    * reworked Shino-kun's [sprite and animations](https://twitter.com/ohsat_games/status/1561050682513362944)
    * Since Shino-kun is a ninja, [he can slide](https://twitter.com/ohsat_games/status/1562502498820169728). Ninjas can slide, right?
    * A look at more Shino-kun animations is [available for Ando's patrons](https://www.patreon.com/posts/shino-kun-70913738?utm_medium=social&utm_source=twitter&utm_campaign=postshare_creator)
- [ ]

**Comment by Beeblerox** [comment]
- [ ] [Axol Studio](https://twitter.com/AxolStudio) has updated [Bring It On!](https://store.steampowered.com/app/2020460/Bring_It_On/) to v0.5.1 to fix the issues with the 2nd level's end-boss (and a few minor tweaks).
- [ ] Here is also Level 3: [Fallow Fields preview](https://twitter.com/AxolStudio/status/1562537730709417985) from Bring It On!

**Comment by Beeblerox** [comment]
- [ ] [grapefrukt](https://twitter.com/grapefrukt/status/1562046468873125891) has updated [rymdkapsel](https://grapefrukt.itch.io/rymdkapsel) with fix for broken mission completion (this game turns TEN next year, that's uh, a very long time)

**Comment by Beeblerox** [comment]
- [ ] Even when you have the shroomed status effect in [Renaine](https://store.steampowered.com/app/662340/Renaine/) you can still [have that sick shroovement](https://twitter.com/squuuidly/status/1562108024168251392)

**Comment by Beeblerox** [comment]
- [ ] Maybe [Michael Bickel](https://twitter.com/dazKind/status/1561840496963633154) will talk at upcoming HaxeIn event

**Comment by Beeblerox** [comment]
- [ ] The [Shiro Games booth](https://twitter.com/icopartners/status/1562392775554908160) at Gamescom 2022 is looking spectacular

**Comment by Beeblerox** [comment]
- [ ] Sébastien Bénard is [testing a few old school tricks](https://discord.com/channels/162395145352904705/162664383082790912/1009831768502833233) to create a 2.5D engine (Dungeon Master, Eye of the Beholder), without relying on 3D.

**Comment by Beeblerox** [comment]
- [ ] Skyfire2008 has [added bloom](https://discord.com/channels/162395145352904705/162664383082790912/1010096598564491294) to [TD2S](https://kurt-c0caine.itch.io/td2s)

**Comment by Beeblerox** [comment]
- [ ] [Another hxcpp debugger update](https://discord.com/channels/162395145352904705/162664383082790912/1010490853225136169) by Aidan Lee: stepping, breakpoints, exceptions, and local variables are now working in VSCode

**Comment by Beeblerox** [comment]
- [ ] Jeremy Fa has [added "nine slice" support](https://discord.com/channels/162395145352904705/162664383082790912/1010890717721280643) to Ceramic. Here is [live sample](https://ceramic-engine.com/examples/nine-slice/)

**Comment by Beeblerox** [comment]
- [ ] Shahar got around to implementing borders for shapes in OpenFL: [for circles and ovals](https://discord.com/channels/162395145352904705/162664383082790912/1010935588188336129)

**Comment by Beeblerox** [comment]
- [ ] [Aidan Lee](https://discord.com/channels/162395145352904705/162664383082790912/1011012473903661197) has made [a small bot](https://github.com/Aidan63/mnc_bot) for a discord server

**Comment by Beeblerox** [comment]
- [ ] ZwodahS has [added the new ambition](https://discord.com/channels/162395145352904705/162664383082790912/1011526903460548608) for [Dice Tribes: Ambitions](https://store.steampowered.com/app/1965800/Dice_Tribes_Ambitions/)

**Comment by Beeblerox** [comment]
- [ ] Redfill The Canadien's [first program](https://discord.com/channels/162395145352904705/162664383082790912/1011626669905289336) made with Haxe, Heaps and HaxeUI

**Comment by Beeblerox** [comment]
- [ ] jefvel is [trying out some lights](https://discord.com/channels/162395145352904705/162664383082790912/1011765817274277958) in WIP game which is being made with Heaps

**Comment by Beeblerox** [comment]
- [ ] [Party planet](https://discord.com/channels/162395145352904705/162664383082790912/1012191456879984750) from [Minicology](https://store.steampowered.com/app/1471700/Minicology/) by Isaac Denner

**Comment by Beeblerox** [comment]
- [ ] Spitko is rendering Quake maps in Heaps:
    * [Got the camera working](https://discord.com/channels/162395145352904705/501408700142059520/1010104575698669578) the dumb way
    * [Meanwhile, have a door](https://discord.com/channels/162395145352904705/501408700142059520/1010331514204061736)
    * [Working on an AO baking process](https://discord.com/channels/162395145352904705/501408700142059520/1011172782823964733)
    * [Baked lighting](https://discord.com/channels/162395145352904705/501408700142059520/1011533561389654028)
    * [More tweaking of heaps shadows](https://discord.com/channels/162395145352904705/501408700142059520/1011559556117180436)

**Comment by skial** [comment]
- [ ] `[open source]` [haxe-checkstyle `2.8.0`](https://github.com/HaxeCheckstyle/haxe-checkstyle/releases/tag/v2.8.0) has been released.

**Comment by skial** [comment]
- [ ] `[core/hashlink]` Wrong code generation for bit shift + assignment in while loop header [issue](https://github.com/HaxeFoundation/haxe/issues/10783).

**Comment by skial** [comment]
- [ ] `[core]` Operators are inconsistent with block expressions [issue](https://github.com/HaxeFoundation/haxe/issues/10782).

**Comment by skial** [comment]
- [ ] libs
   - [chsub `0.1.1`](https://lib.haxe.org/p/chsub)
   - [checkstyle `2.8.0`](https://lib.haxe.org/p/checkstyle)
   - [hxmoralis `0.0.1`](https://lib.haxe.org/p/hxmoralis)
   - [hscript_template `2.0.0`](https://lib.haxe.org/p/hscript_template)
   - [deflatex `1.0.0`](https://lib.haxe.org/p/deflatex) :star:
   - [haxeium `1.0.0`](https://lib.haxe.org/p/haxeium) :star:

**Comment by skial** [comment]
- [ ] `[video]` First person player Armory 3D tutorial (only nodes) [part 1](https://www.youtube.com/watch?v=pH7byi2yQaY&widget_referrer=haxe.io) and [part 2](https://www.youtube.com/watch?v=4RNUX7ZE_Ao&widget_referrer=haxe.io) by Exceptional 3D tutorials.

**Comment by skial** [comment]
- [ ] `[video]` Introducing The Spire! [video short](https://www.youtube.com/shorts/G53MtzcXr1k&widget_referrer=haxe.io) by Fraymakers.

**Comment by skial** [comment]
- [ ] `[open source]` [kluez-resizer `git`](https://github.com/MatthijsKamstra/kluez-resizer) .

**Comment by skial** [comment]
- [ ] `[open source]` [chsub `git`](https://github.com/jonypawks/chsub) - Change the subsystem of a PE executable between console and windows applications.

**Comment by skial** [comment]
- [ ] `[open source]` [haxe-deflatex `git`](https://github.com/4as/haxe-deflatex) - Implementation of the deflate and inflate functions in pure Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [heaps-msdf-text `git`](https://github.com/4as/heaps-msdf-text) - Simple extension of the Heaps' Text class that supports outlines using multi-channel SDF.

**Comment by skial** [comment]
- [ ] `[open source]` [sneaker_api `git`](https://github.com/yonzay/sneaker_api) - Old and novice API made awhile back using Haxe to help automate the purchase of sneakers from footsites.
