### ISSUE TITLE
Haxe Roundup 645

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1014]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` Missing semicolon not a problem for object literals [issue](https://github.com/HaxeFoundation/haxe/issues/10796).

**Comment by skial** [comment]
- [ ] `[community]` Armory3D Release Notes - [September Release](https://forums.armory3d.org/t/armory3d-release-notes-2022-09-september-release/4970?u=skial).

**Comment by skial** [comment]
- [ ] libs
   - [qbittorrent `2.83.0`](https://lib.haxe.org/p/qbittorrent)
   - [initools `1.0.1`](https://lib.haxe.org/p/initools)
   - [hxdist `0.1.6`](https://lib.haxe.org/p/hxdist)
   - [swf `3.1.1`](https://lib.haxe.org/p/swf)
   - [feathersui-cairngorm `1.0.0`](https://lib.haxe.org/p/feathersui-cairngorm)
   - [pony `1.9.3`](https://lib.haxe.org/p/pony)
   - [hxmoralis `0.0.2`](https://lib.haxe.org/p/hxmoralis)
   - [feathersui-rpc-services `1.0.0`](https://lib.haxe.org/p/feathersui-rpc-services)

**Comment by skial** [comment]
- [ ] `[community]` RPC Services `1.0` for Feathers UI [announcement](https://feathersui.com/blog/2022/09/08/feathers-ui-rpc-services-1-0-0-remote-object-http-service-haxe) by Josh Tynjala.

**Comment by skial** [comment]
- [ ] `[community]` PogoGirl Devlog `#31`: PogoGirl is [Bouncing to Consoles!](https://www.ohsat.com/post/pogogirl-devlog/post31/) by Andrej.

**Comment by skial** [comment]
- [ ] `[community]` Webpack OpenFL Loader `1.0` [announcement](https://feathersui.com/blog/2022/09/09/webpack-openfl-loader-plugin-1-0-0) by Josh Tynjala.

**Comment by skial** [comment]
- [ ] `[community]` Bug Hunt -- [DQ2 Progress Report](https://www.fortressofdoors.com/dq2-progress-report-for-august-2022/) for August 2022 by Lars Doucet.

**Comment by skial** [comment]
- [ ] `[community]` Cairngorm `1.0` MVC framework for Feathers UI [announcement](https://feathersui.com/blog/2022/09/12/feathers-ui-cairngorm-1-0-0-mvc-microarchitecture-framework) by Josh Tynjala.

**Comment by skial** [comment]
- [ ] `[community]` OpenFL Plugin for Vite `1.0` [annoucement](https://feathersui.com/blog/2022/09/13/vite-openfl-plugin-1-0-0) by Josh Tynjala.

**Comment by skial** [comment]
- [ ] `[video/shorts]` Axol Studio Bring It On! [quick intro](https://www.youtube.com/shorts/YG2dOdH6t4k&widget_referrer=haxe.io) and [early release short](https://www.youtube.com/shorts/P3Cg2V48Ksg&widget_referrer=haxe.io).

**Comment by skial** [comment]
- [ ] `[open source]` [go2hxdoc `git`](https://github.com/go2hx/go2hxdoc) - Generate documentation with tests for go2hx generated Haxe code.

**Comment by skial** [comment]
- [ ] `[open source]` [Haxe-UnrealEngine5 `git`](https://github.com/RobertBorghese/Haxe-UnrealEngine5) - Haxe externs and tools for UE5.

**Comment by skial** [comment]
- [ ] `[open source]` [initools `git`](https://github.com/Eventretta/initools) - Tools for parsing INI files and using them in Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [RayGen `git`](https://github.com/thepercentageguy/RayGen) - Haxe engine built on top of Raylib. Not designed to be used yet, very early in development.

**Comment by skial** [comment]
- [ ] `[open source]` [hlsteam `git`](https://github.com/HeapsIO/hlsteam) - Haxe native extension for the Steam API.

**Comment by skial** [comment]
- [ ] `[community]` Renaine Kickstarter Update `#37`: [Rollin' Waves](https://www.kickstarter.com/projects/585676804/renaine-a-game-about-overcoming-failure/posts/3542407) by [Renaine](https://twitter.com/RenaineGame/status/1569388073242198017).

**Comment by skial** [comment]
- [ ] `[community]` 🏡Village Generator `1.3.0`: new trees and buildings [article](https://www.patreon.com/posts/71653886) by [Oleg Dolya](https://twitter.com/watawatabou/status/1567885542624215041).

**Comment by Beeblerox** [comment]
- [ ] Dead Cells Enter the Panchaku update is [available on consoles](https://twitter.com/motiontwin/status/1567890095797149696)

**Comment by Beeblerox** [comment]
- [ ] Bring It On! [v0.6 is now Live!](https://store.steampowered.com/news/app/2020460/view/3423321392355617914)

**Comment by Beeblerox** [comment]
- [ ] [PureMVC demos for Feathers UI and OpenFL](https://feathersui.com/blog/2022/09/14/puremvc-haxe-openfl-feathers-ui-demos)

**Comment by Beeblerox** [comment]
- [ ] Dead Cells - [Break the Bank, Breaking Barriers and Enter the Panchaku mobile updates](https://www.youtube.com/watch?v=XSsDHKB9IPs) video

**Comment by Beeblerox** [comment]
- [ ] Better to [avoid the giant swinging balls](https://twitter.com/ohsat_games/status/1568660703959023616) in Chibi Ninja Shino-kun by Ando

**Comment by Beeblerox** [comment]
- [ ] ysaml is [working on CRYPTID](https://twitter.com/mielsmiels/status/1568784912597262340) - a roguelite deck building game

**Comment by Beeblerox** [comment]
- [ ] [Mixup Factory v0.2.0](https://kyatt7.itch.io/there-was-a-mixup-at-the-factory/devlog/427805/mixup-factory-v020) changelog by [kyatt7](https://twitter.com/kyatt7/status/1570046252074639362)

**Comment by Beeblerox** [comment]
- [ ] Renegade Racing by [Paul Gene](https://twitter.com/PaulGene/status/1568209602151432192) is now available on Amazon Fire Tablets and the Amazon Fire Stick

**Comment by Beeblerox** [comment]
- [ ] [Sébastien Benard](https://discord.com/channels/162395145352904705/162664383082790912/1017691415880400936) has updated [Dungeon Crawler prototype](https://deepnight.net/blog/dungeon-crawler-prototype/) with smoother rotations

**Comment by Beeblerox** [comment]
- [ ] [The Transparent Windows And Multi-Windows](https://github.com/DuskieWhy/Transparent-and-MultiWindow-FNF) for Haxeflixel are now public. via [TaeYai](https://twitter.com/taeyai_/status/1568847758190350336)

**Comment by Beeblerox** [comment]
- [ ] [Platformer sample for Ceramic](https://discord.com/channels/162395145352904705/162664383082790912/1019015997040115742) is coming along, with ladders, one-direction collisions working...

**Comment by Beeblerox** [comment]
- [ ] Naoya has tried [CRT shader in HITTER](https://discord.com/channels/162395145352904705/162664383082790912/1019292143422025829)

**Comment by Beeblerox** [comment]
- [ ] New pre-alpha version of [Rhythm Magus](https://www.newgrounds.com/projects/games/1895598/preview/filetype/2) game (made with Ceramic) by [Prexot](https://discord.com/channels/162395145352904705/162664383082790912/1019350972209823764)

**Comment by skial** [comment]
- [ ] `[open source]` [haxe-checkstyle `2.8.2`](https://github.com/HaxeCheckstyle/haxe-checkstyle/releases/tag/v2.8.2) has been released!
