### ISSUE TITLE
Haxe Roundup 649

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1022]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by kLabz** [comment]
Hi! Can you add me to "looking for work" section again please? :)

* [ ] [Rudy Geslin](https://github.com/kLabz) is available for freelance work

**Comment by skial** [comment]
- `[bounty]` remove https://github.com/chosencharacters/squidBounties/issues/8#issuecomment-1273946731

**Comment by skial** [comment]
- [ ] `[core/lua]` Improve codegen for handling instance `Var` functions [pull request](https://github.com/HaxeFoundation/haxe/pull/10817).

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` Wrong result for `true == 1` comparison when variables typed as `Dynamic` or `Any` [issue](https://github.com/HaxeFoundation/hxcpp/issues/1009).

**Comment by skial** [comment]
- [ ] `[core]` `Warning : (WVarShadow)` This variable shadows a previously declared variable [issue](https://github.com/HaxeFoundation/haxe/issues/10819).

**Comment by skial** [comment]
- [ ] `[community]` Terranion and research tracker [updates](https://yellowafterlife.itch.io/terrasavr/devlog/436478/terranion-and-research-tracker-updates) for [Terrasavr](https://yellowafterlife.itch.io/terrasavr) by YellowAfterLife.

**Comment by skial** [comment]
- [ ] `[community]` Armory3D Release Notes - [October 2022.10](https://forums.armory3d.org/t/release-notes-october-2022-10/4984?u=skial).

**Comment by skial** [comment]
- [ ] `[community]` Add missed pr from last week to this https://github.com/skial/haxe.io/pull/1023

**Comment by skial** [comment]
- [ ] `[community]` [Rebalancing](https://www.fortressofdoors.com/rebalancing-dq2-progress-report-for-september-2022/) -- DQ2 Progress Report for September 2022 by Lars Doucet.

**Comment by skial** [comment]
- [ ] `[video]` There's something for [everyone](https://www.youtube.com/shorts/Hhzg-9B6exo&widget_referrer=haxe.io) in this short for Bring It On! by Axol Studios.
- [ ] `[video]` Missing [cool math](https://www.youtube.com/shorts/KIJWNUKYhLo&widget_referrer=haxe.io) games, check out Axol Studio games!
- [ ] `[video]` Looking for a Halloween game, try [Heck House](https://www.youtube.com/shorts/YVBZS6PGzNw&widget_referrer=haxe.io) by Axol Studio.

**Comment by Beeblerox** [comment]
- [ ] [A small one](https://twitter.com/watawatabou/status/1578007681884983296) cave by Oleg Dolya

**Comment by Beeblerox** [comment]
- [ ] [Big lizard momma](https://twitter.com/THCGourami/status/1578515793301544960) by Gourami for [Renaine](https://store.steampowered.com/app/662340/Renaine/)

**Comment by Beeblerox** [comment]
- [ ] Ando made [Chibi Ninja Shino-kun Devlog #2](https://www.patreon.com/posts/72815977) public
- [ ] New quick videos from Chibi Ninja Shino-kun:
    * [Giant spinning balls?](https://twitter.com/ohsat_games/status/1578815043168505856) No problem for a true ninja
    * A place called [Demon Tower was bound to have spikes](https://twitter.com/ohsat_games/status/1579535553627713536). Let's be real here
    * Did you think a place called Demon Tower wouldn't have [any demons in it](https://twitter.com/ohsat_games/status/1580259531548151814)? Don't be silly

**Comment by Beeblerox** [comment]
- [ ] [Michael Bickel](https://twitter.com/dazKind/status/1578119229898997761) has covered the interop of all GodotEngine built-in types with Haxe types with the help of some macros, abstracts, operator overloading and some type-safety + error reporting with callstacks

**Comment by Beeblerox** [comment]
- [ ] [NPC design](https://twitter.com/mauvecow/status/1579216880765927425) in Addlemoth by mauve

**Comment by Beeblerox** [comment]
- [ ] Dune: Spice Wars [has been nominated](https://twitter.com/DuneSpiceWars/status/1579468686506987522) for 'Best Early Access Launch' at this years Golden Joystick Awards

**Comment by Beeblerox** [comment]
- [ ] Cathay Capital reportedly [pours €50m into Shiro Games](https://www.gamesindustry.biz/cathay-capital-reportedly-pours-50m-into-shiro-games)

**Comment by Beeblerox** [comment]
- [ ] ["Shadows tiles"](https://twitter.com/merrak/status/1580074621348773888) in Rogue of Vallas

**Comment by Beeblerox** [comment]
- [ ] Wartales Major Update #2: [The Great Gosenberg](https://steamcommunity.com/games/1527950/announcements/detail/3556180117858574242)

**Comment by Beeblerox** [comment]
- [ ] 47rooks been playing with lower level [GLSL access via OpenFL](https://discord.com/channels/162395145352904705/162664383082790912/1028849428456546324)

**Comment by Beeblerox** [comment]
- [ ] [pixelimage](https://github.com/nanjizal/pixelimage) is a little library by [Nanjizal](https://twitter.com/Nanjizal_net/status/1580391148840833024) for pixel drawing currently only in Javascript target

**Comment by Beeblerox** [comment]
- [ ] [Basically A Walking Simulator](https://www.youtube.com/watch?v=L20oKvDI5Ag) (B.A.W.S.): DEMO OUT! video by [Spookin'_64](https://discord.com/channels/162395145352904705/1026956468261494794/1029495463478562876)

**Comment by Beeblerox** [comment]
- [ ] [Minecart trains](https://discord.com/channels/162395145352904705/162664383082790912/1029864097690435657) with mounted cannons/chests/whatever structures you want to put in them

**Comment by skial** [comment]
- [ ] `[open source]` [HaxePong `git`](https://github.com/N1ckn1ght/HaxePong) - A not-so-classic clone of Pong made in Heaps, Haxe.
