### ISSUE TITLE
Haxe Roundup 658

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1042]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by AlexHaxe** [comment]
- [ ] latest [starship v.1.12.0](https://starship.rs) (a customisable shell prompt) added support for showing current [Haxe version](https://starship.rs/config/#haxe) as part your prompt

**Comment by skial** [comment]
Tomorrows roundup will be the last one this year with the next being planned for the 5th January.

**Comment by skial** [comment]
- [ ] `[core]` Dynamic on abstract [issue](https://github.com/HaxeFoundation/haxe/issues/10881).

**Comment by skial** [comment]
- [ ] `[core]` Reification outside of `macro` expr [fixed](https://github.com/HaxeFoundation/haxe/issues/10883).

**Comment by skial** [comment]
- [ ] `[core]` User defines/metas: do not display Haxe help message [merged](https://github.com/HaxeFoundation/haxe/pull/10885).

**Comment by skial** [comment]
- [ ] libs
   - [minecraft-api `0.2.69-alpha`](https://lib.haxe.org/p/minecraft-api)
   - [dropecho.interop `0.4.7`](https://lib.haxe.org/p/dropecho.interop)
   - [reflaxe `1.0.3`](https://lib.haxe.org/p/reflaxe)
   - [IniFiction `0.1.0`](https://lib.haxe.org/p/IniFiction)
   - [dropecho.storygen `0.9.3`](https://lib.haxe.org/p/dropecho.storygen)
   - [dropecho/dungen `1.5.0`](https://lib.haxe.org/p/dropecho.dungen)

**Comment by skial** [comment]
- [ ] `[community]` Year end retrospective-- DQ2 Progress Report for November 2022 [article](https://www.fortressofdoors.com/year-end-retrospective-dq2-progress-report-for-november-2022/) by Lars Doucet.

**Comment by skial** [comment]
- [ ] `[community]` Chibi Ninja [Devlog `#3`](https://www.ohsat.com/post/chibi-ninja-shino-kun-devlog/chibi-ninja-devlog-3/) by Andrej Preradovic.

**Comment by skial** [comment]
- [ ] `[community]` Northgard: Cross of Vidar [release article](https://store.steampowered.com/news/app/466560/view/3620361554186868976).

**Comment by skial** [comment]
- [ ] `[community]` Minicology `0.8.8.5`: Darkness re-loaded, sounds and game feel [devlog](https://store.steampowered.com/news/app/1471700/view/3624865153728907982).

**Comment by skial** [comment]
- [ ] `[community]` Castlevania is back! Dead Cells: Return to Castlevania DLC [coming Q1 2023](https://store.steampowered.com/news/app/588650/view/3515651436944643473)!

**Comment by skial** [comment]
- [ ] `[video]` Rogue of Vallas Level 6-4 - Excavation [Playthrough](https://www.youtube.com/watch?v=1vTyFdxilf4&widget_referrer=haxe.io).

**Comment by skial** [comment]
- [ ] `[video]` Let's Play Bring It On! [Episode 03](https://www.youtube.com/watch?v=WmgF0j2CCag&widget_referrer=haxe.io) - Featuring Black Magix.

**Comment by skial** [comment]
- [ ] `[video]` Citadelic - Roguelite Strategy Game [Trailer](https://www.youtube.com/watch?v=LQBJdRrfr7k&widget_referrer=haxe.io) by Kirill Poletaev.

**Comment by skial** [comment]
- [ ] `[video]` How to make [a custom cursor](https://www.youtube.com/watch?v=_Niwk5zHUzU&widget_referrer=haxe.io) in Armory 3D.

**Comment by skial** [comment]
- [ ] `[open source]` [xmpp-action `git`](https://github.com/tong/xmpp-action) - Use XMPP in GitJub actions.

**Comment by Beeblerox** [comment]
- [ ] Two short twitter threads about improvements in HaxeFlixel 5:
    * Improved [collision in action](https://twitter.com/HaxeFlixel/status/1600841816106229761)
    * Improved [path finding](https://twitter.com/HaxeFlixel/status/1601306929934270465)

**Comment by Beeblerox** [comment]
- [ ] Ludovic Bas asked [ChatGPT to write some Haxe code](https://twitter.com/loudoweb/status/1601134097619091457) :)

**Comment by Beeblerox** [comment]
- [ ] Reading Aseprite pixel art [animations in Ceramic engine](https://twitter.com/jeremyfaivre/status/1601173901652160512) by Jérémy Faivre

**Comment by Beeblerox** [comment]
- [ ] New quick videos from [Chibi Ninja Shino-kun](https://store.steampowered.com/app/2175640/Chibi_Ninja_Shinokun_Treasure_of_Demon_Tower/): Treasure of Demon Tower:
    * You can not only jump on arrows, but also [use your hookshot on them](https://twitter.com/ohsat_games/status/1601639356078313472)!
    * [Working on](https://twitter.com/ohsat_games/status/1602371571213123587) a slightly prettier level select
    * Having a good tutorial and clear instructions is important for a game, [wouldn't you say?](https://twitter.com/ohsat_games/status/1602818919437406214)
    * [Platform goes up, platform goes down](https://twitter.com/ohsat_games/status/1603105091267039233)

**Comment by Beeblerox** [comment]
- [ ] [ninja_muffin99](https://twitter.com/ninja_muffin99/status/1601776820378271745) has moved the FNF github repo to FunkinCrew github org. And [a little headsup](https://twitter.com/ninja_muffin99/status/1601786081589854209) for FNF github / open source stuff

**Comment by Beeblerox** [comment]
> * [ ]  `[community]` Castlevania is back! Dead Cells: Return to Castlevania DLC [coming Q1 2023](https://store.steampowered.com/news/app/588650/view/3515651436944643473)!

- [ ] [the hardest part of the whole production process...](https://twitter.com/motiontwin/status/1601998201216811008) :D

**Comment by Beeblerox** [comment]
- [ ] Nanjizal has [fixed the PathElementShape](https://twitter.com/Nanjizal_net/status/1602260936206737410) in pixelimage library

**Comment by Beeblerox** [comment]
- [ ] [Building an online multiplayer browser game with Haxe and Colyseus](https://www.youtube.com/watch?v=5XaGzRH5Y7I) by Richard Oliver Bray

**Comment by Beeblerox** [comment]
- [ ] [Some prototype work](https://twitter.com/RobClemmonsJr/status/1602652612846927873) for Patches Of Adventure by Rob Clemmons Jr

**Comment by Beeblerox** [comment]
- [ ] https://haxe.social/ is a new (unofficial) akkoma instance I'm running especially for Haxe developers and projects.

**Comment by Beeblerox** [comment]
- [ ] Wartales: [co-op gameplay with the devs](https://www.twitch.tv/videos/1678864365) VOD

**Comment by Beeblerox** [comment]
- [ ] [Last weeks experiments](https://twitter.com/disktree/status/1603078679340658688) by Tong

**Comment by Beeblerox** [comment]
- [ ] 47rooks [added light casters](https://discord.com/channels/162395145352904705/162664383082790912/1052080796359475220) for their [OpenGL with OpenFL and Lime project](https://github.com/47rooks/virtual-rubiks-cube).

**Comment by Beeblerox** [comment]
- [ ] go2hx showcase: [passing go's std: strings](https://discord.com/channels/162395145352904705/1020578706743365632/1052400213215678564)

**Comment by Beeblerox** [comment]
- [ ] [ZwodahS](https://discord.com/channels/162395145352904705/1041380289169068072/1050295035960229948) has released [prototype of Card City Mayor](https://zwodahs.itch.io/card-city-mayor?secret=6lgGfvHFZN8C67QL7vT54koCltA)

**Comment by Beeblerox** [comment]
- [ ] [New GIF from Hitter](https://discord.com/channels/162395145352904705/1022291887505281025/1050482583475069068) by Naoya

**Comment by Beeblerox** [comment]
- [ ] Some info [about Reflaxe](https://discord.com/channels/162395145352904705/1052688097592225904/1052688097592225904) - Reflection Compiler for Haxe

**Comment by Beeblerox** [comment]
- [ ] sharpcdf is [messing around in Ceramic](https://discord.com/channels/162395145352904705/162664383082790912/1052778587675185203) and thinking about making a puzzle game

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` Make `_hx_std_process_kill` work everywhere [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1021).

**Comment by skial** [comment]
- [ ] `[core]` Information on Generated Variables and Optimisations for Improving Debugging [discussion](https://github.com/HaxeFoundation/haxe/issues/10888).

**Comment by skial** [comment]
- [ ] `[open source/armory]` `armqna` - Tensorflow based question+answer tool [discussion](https://github.com/armory3d/armory/discussions/2707).

**Comment by skial** [comment]
- [ ] `[open source]` [HardcoreLightly `git`](https://github.com/imfi-jz/HardcoreLightly) - A Minecraft Spigot plugin written in Haxe that makes players lose max health each time they die.
