### ISSUE TITLE
Haxe Roundup 659

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1045]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` `analyzer-user-var-fusion` directive seems to be ignored in nightly [issue](https://github.com/HaxeFoundation/haxe/issues/10908).

**Comment by skial** [comment]
- [ ] `[core]` `-D no-inline` breaks map literals in HashLink [issue](https://github.com/HaxeFoundation/haxe/issues/10912).

**Comment by skial** [comment]
- [ ] `[community]` New set of libraries: "Core Haxe" [thread](https://community.haxe.org/t/new-set-of-libraries-core-haxe/3816?u=skial).

**Comment by skial** [comment]
- [ ] `[core/ci]` Improved CI build times [merged](https://github.com/HaxeFoundation/haxe/pull/10892).

**Comment by skial** [comment]
- [ ] `[core/lua]` Respect lua-vanilla for Json.parse [merged](https://github.com/HaxeFoundation/haxe/pull/10915).

**Comment by skial** [comment]
- [ ] `[core/js]` UInt inconsistent result across targets [issue](https://github.com/HaxeFoundation/haxe/issues/10913).

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` Libuv Asys Implementation [draft pull request](https://github.com/HaxeFoundation/hxcpp/pull/1022).

**Comment by skial** [comment]
- [ ] `[core/lua]` Rest from Array doesn't work properly [issue](https://github.com/HaxeFoundation/haxe/issues/10909).

**Comment by skial** [comment]
- [ ] `[core]` Clean up field-level errors [merged](https://github.com/HaxeFoundation/haxe/pull/10896).

**Comment by skial** [comment]
- [ ] `[open source]` Haxe-to-GDScript version `0.1.0` has been [released](https://github.com/RobertBorghese/Haxe-to-GDScript/releases/tag/v0.1.0).

**Comment by skial** [comment]
- [ ] `[open source]` Reflaxe version `2.0.0` has been [released](https://github.com/RobertBorghese/reflaxe/releases/tag/v2.0.0). :star:

**Comment by skial** [comment]
- [ ] `[core/hashlink]` Easier build on M1 [pull request](https://github.com/HaxeFoundation/hashlink/pull/577).

**Comment by skial** [comment]
- [ ] `[open source/vector-math]` Workaround for nasty ternary closure codegen for min/max on Lua target [pull request](https://github.com/haxiomic/vector-math/pull/18).

**Comment by skial** [comment]
- [ ] `[open source/openfl]` Use HashLink to run Lime tools [draft pull request](https://github.com/openfl/lime/pull/1614).

**Comment by skial** [comment]
- [ ] `[core/lua]` Remove haxe-deps and directly reference dependencies; re-enable CI [merged](https://github.com/HaxeFoundation/haxe/pull/10916).

**Comment by skial** [comment]
- [ ] `[core/jvm]` Rest from Array doesn't work properly [issue](https://github.com/HaxeFoundation/haxe/issues/10906).

**Comment by skial** [comment]
- [ ] `[core/js]` Fix type names in debugger [pull request](https://github.com/HaxeFoundation/haxe/pull/10894). :star:

**Comment by skial** [comment]
- [ ] `[core/js]` `overload` and `@:require` cannot be put together [fixed](https://github.com/HaxeFoundation/haxe/issues/10890).

**Comment by skial** [comment]
- [ ] `[open source]` Haxe-checkstyle `2.8.4` has been [released](https://github.com/HaxeCheckstyle/haxe-checkstyle/releases/tag/v2.8.4).

**Comment by skial** [comment]
- [ ] libs
  - [checkstyle `2.8.4`](https://lib.haxe.org/p/checkstyle)
  - [torznab `0.1.0`](https://lib.haxe.org/p/torznab)
  - [haxework `2.0.0`](https://lib.haxe.org/p/haxework)
  - [HxShaders `5.3.0`](https://lib.haxe.org/p/HxShaders)
  - [box2d-xml-parser `0.1.1`](https://lib.haxe.org/p/box2d-xml-parser)
  - [fabula `0.8.0`](https://lib.haxe.org/p/fabula)
  - [kadabra-utils `0.3.0`](https://lib.haxe.org/p/kadabra-utils)
  - [hash `1.0.1`](https://lib.haxe.org/p/hash)
  - [pirhana `1.1.23`](https://lib.haxe.org/p/pirhana)
  - [ldtk-haxe-api `1.2.1-rc.1`](https://lib.haxe.org/p/ldtk-haxe-api)
  - [hxdefold `1.4.1`](https://lib.haxe.org/p/hxdefold)
  - [hxdiscord `0.0.2`](https://lib.haxe.org/p/hxdiscord)
  - [dropecho.testing `1.0.1`](https://lib.haxe.org/p/dropecho.testing)
  - [wasteofhaxe `0.1.0`](https://lib.haxe.org/p/wasteofhaxe)
  - [electron `22.0.0`](https://lib.haxe.org/p/electron)
  - [flxanimate `3.0.2`](https://lib.haxe.org/p/flxanimate)
  - [flixel `5.1.0`](https://lib.haxe.org/p/flixel)
  - [gdscript `0.1.1`](https://lib.haxe.org/p/gdscript)
  - [reflaxe `2.0.0`](https://lib.haxe.org/p/reflaxe)
  - [omdb `1.2.2`](https://lib.haxe.org/p/omdb)
  - [haxe-injection `3.0.1`](https://lib.haxe.org/p/haxe-injection)

**Comment by skial** [comment]
- [ ] `[community]` Debugging Hxcpp Programs with Sourcemaps [article](https://blog.aidanlee.uk/hxcppdbg-intro/) by Aidan Lee.

**Comment by skial** [comment]
- [ ] `[community]` Fraymakers Early Access [Arrives on January 18th](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3698608)!

**Comment by skial** [comment]
- [ ] `[community/devlog]` Energy Island Corp: [Major Update `1.1`](https://store.steampowered.com/news/app/1241710/view/3647384349427391359).

**Comment by skial** [comment]
- [ ] `[community/devlog]` Dune: Spice Wars - [December Dev Update](https://store.steampowered.com/news/app/1605220/view/5851895827516276925).

**Comment by skial** [comment]
- [ ] `[community]` Wartales: [Major Update `#3`](https://store.steampowered.com/news/app/1527950/view/3556180117863015569).

**Comment by skial** [comment]
- [ ] `[video]` Rogue of Vallas [Mineshaft Level](https://www.youtube.com/watch?v=WiTy1hxaC-0&widget_referrer=haxe.io).
- [ ] `[video]` Interview with a Developer [video](https://www.youtube.com/watch?v=RSTmAnviUmY&widget_referrer=haxe.io).

**Comment by skial** [comment]
- [ ] `[video]` Big things for Armory 3D in 2023 [video](https://www.youtube.com/watch?v=3rs1JTWYRn0&widget_referrer=haxe.io).

**Comment by skial** [comment]
- [ ] `[video]` Custom Graphics [in RPG Playground](https://www.youtube.com/watch?v=u3cyZCOGY94&widget_referrer=haxe.io).

**Comment by skial** [comment]
- [ ] `[video]` Gunman Clive [Joins Fraymakers](https://www.youtube.com/watch?v=hcrdQtIEpgs&widget_referrer=haxe.io)!

**Comment by skial** [comment]
- [ ] `[video]` Northgard | Cross of Vidar [Launch Trailer](https://www.youtube.com/watch?v=gEm8BftNS3s&widget_referrer=haxe.io).

**Comment by skial** [comment]
- [ ] `[video]` [Raycasting Explained](https://www.youtube.com/watch?v=8ymSPfgnY4Y&widget_referrer=haxe.io) in Armory 3D.
- [ ] `[video]` Using Tweens in Armory 3D [for smooth animations](https://www.youtube.com/watch?v=XHCyGScD4cM&widget_referrer=haxe.io).
- [ ] `[video]` Armory 3D December 2022 [release notes](https://www.youtube.com/watch?v=5sM6mY00eGs&widget_referrer=haxe.io).

**Comment by skial** [comment]
- [ ] `[open source]` [json-rpc `git`](https://github.com/core-haxe/json-rpc) - JSON RPC client supporting fully typed rest operations.
- [ ] `[open source]` [http `git`](https://github.com/core-haxe/http) - Flexible HTTP client supporting different HTTP providers.
- [ ] `[open source]` [rest `git`](https://github.com/core-haxe/rest) - Rest client supporting fully typed rest operations.
- [ ] `[open source]` [db-core `git`](https://github.com/core-haxe/db-core) - Pluggable database abstraction.
- [ ] `[open source]` [db-sqlite `git`](https://github.com/core-haxe/db-sqlite) - sqlite database plugin for db-core.
- [ ] `[open source]` [db-mysql `git`](https://github.com/core-haxe/db-mysql) - mysql database plugin for db-core.
- [ ] `[open source]` [sqlite3 `git`](https://github.com/core-haxe/sqlite3) - sqlite3 for all relevant Haxe targets.
- [ ] `[open source]` [mysql `git`](https://github.com/core-haxe/mysql) - mysql for all relevant Haxe targets.
- [ ] `[open source]` [queues-core `git`](https://github.com/core-haxe/queues-core) - Pluggable queue abstraction.
- [ ] `[open source]` [logging `git`](https://github.com/core-haxe/logging) - Flexible logging framework supporting various adaptors.
- [ ] `[open source]` [promises `git`](https://github.com/core-haxe/promises) - Promise lib _(typedef for thenshim currently)_.
- [ ] `[open source]` [haxe-nvim `git`](https://github.com/danielo515/haxe-nvim) - Configure NeoVim in Haxe!!! Lua externs for the neovim lua API.
- [ ] `[open source]` [hlwwise `git`](https://github.com/trethaller/hlwwise) - Basic Wwise bindings for Hasklink.
- [ ] `[open source]` [discordjs `git`](https://github.com/Jarrio/discordjs) - Haxe Externs for discord.js
- [ ] `[open source]` [TA-LIB-Haxe `git`](https://github.com/Frederisk/TA-LIB-Haxe) - Rewrite TA-LIB in Haxe.
- [ ] `[open source]` [love-hx `git`](https://github.com/SylviBlossom/love-hx) - A small template for creating Love2D games with Haxe.
- [ ] `[open source]` [sharperus `git`](https://github.com/nadako/sharperus) - Small experiment on converting Cerberus-X code to `C#`.
- [ ] `[open source]` [Haxetta-stone `git`](https://github.com/jobf/haxetta-stone) - One game, multiple frameworks.
- [ ] `[open source]` [Parallax `git`](https://github.com/rise-ig/Parallax) - Heaps Parallax Library.
- [ ] `[open source]` [Pacaea `git`](https://github.com/ActualMandM/Pacaea) - A file packer for a Switch rhythm game.
- [ ] `[open source]` [dinomight-editor `git`](https://github.com/snwhd/dinomight-editor).
- [ ] `[open source]` [hxcpp_asys `git`](https://github.com/Aidan63/hxcpp_asys).
- [ ] `[open source]` OpenFL and Haxe: Foundation ActionScript `3.0` Animation [repo](https://github.com/joshtynjala/foundation-animation-making-things-move-haxe-openfl) translated from Making Things Move by Keith Peters.

**Comment by skial** [comment]
- [ ] `[community]` ⛏️Cave Generator `2.0.0`: glade view [article](https://www.patreon.com/posts/76496723) by Oleg Dolya.

**Comment by skial** [comment]
- [ ] `[community]` ❄️Winter Wreaths [article](https://www.patreon.com/posts/winter-wreaths-76311436) by Oleg Dolya.

**Comment by skial** [comment]
- [ ] `[releases]` Lighthouses [generator](https://watabou.itch.io/lighthouses) for `#procjam` by [Oleg Dolya](https://twitter.com/watawatabou/status/1604493100671696897).

**Comment by skial** [comment]
- [ ] `[jobs/bounties]` FunkinBounties [`75$` - Haxe Fix HMM git](https://github.com/FunkinCrew/funkinBounties/issues/1).

**Comment by skial** [comment]
- [ ] `[closed source]` [Mine Blocks](https://twitter.com/Mine_Blocks/status/1609259732300353538) now has 10K skins!
