### ISSUE TITLE
Haxe Roundup 664

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1055]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by sebthom** [comment]
- [ ] Reusable workflows for GitHub Actions to easily build/test Haxe code against different Haxe versions and compiler targets. [haxe-reusable-workflows](https://github.com/vegardit/haxe-reusable-workflows/)

**Comment by skial** [comment]
- [ ] Check https://github.com/skial/haxe.io/pull/1054#issuecomment-1414086123

**Comment by skial** [comment]
- [ ] `[core]` Wrong fields order for `@:structInit` object literal completion [issue](https://github.com/HaxeFoundation/haxe/issues/10958).

**Comment by skial** [comment]
- [ ] `[core]` Rest vs optional arguments [issue](https://github.com/HaxeFoundation/haxe/issues/10955).

**Comment by skial** [comment]
- [ ] libs
   - [electron `23.0.0`](https://lib.haxe.org/p/electron)
   - [linc_wintoast `0.0.4`](https://lib.haxe.org/p/linc_wintoast)
   - [hxdiscord `0.2.5`](https://lib.haxe.org/p/hxdiscord)
   - [webstorage `4.0.3`](https://lib.haxe.org/p/webstorage)
   - [tokentree `1.2.6`](https://lib.haxe.org/p/tokentree)
   - [hldx `1.13.0`](https://lib.haxe.org/p/hldx)
   - [hlsdl `1.13.0`](https://lib.haxe.org/p/hlsdl)
   - [flx-jamkit `0.0.1`](https://lib.haxe.org/p/flx-jamkit)
   - [lcov `5.0.0`](https://lib.haxe.org/p/lcov)
   - [which `3.1.2`](https://lib.haxe.org/p/which)
   - [bootstrap_bundle `2.1.0`](https://lib.haxe.org/p/bootstrap_bundle)

**Comment by skial** [comment]
- [ ] `[community/devlog]` [Fraymakers EA Update](https://store.steampowered.com/news/app/1420350/view/3657521257917606101) `v0.5.3` - Palette Performance, Tap Jump, Quick Reload & more.

**Comment by Beeblerox** [comment]
- [ ] Everything new in february 2023 release of Armory 3D [video](https://www.youtube.com/watch?v=KrzHI_xYlMA)

**Comment by Beeblerox** [comment]
- [ ] [Perilous Shores 1.5.0](https://www.patreon.com/posts/78135972): area labels and conlang toponyms by [Oleg Dolya](https://twitter.com/watawatabou/status/1621302218375708676)

**Comment by Beeblerox** [comment]
- [ ] [WEEK OF 2023/01/27](https://funkincrew.github.io/funkBlog/blog/2023-02-03/): IN FUNKIN' WE TRUST by [ninja_muffin99](https://twitter.com/ninja_muffin99/status/1621709283627761667)

**Comment by Beeblerox** [comment]
- [ ] [Music playback and memory management in Citadelic](https://kircode.com/en/post/music-playback-and-memory-management-in-citadelic) by [Kirill Poletaev](https://twitter.com/kircode/status/1621814015084077057)

**Comment by Beeblerox** [comment]
- [ ] [zzox (tyler)](https://twitter.com/zzo__x/status/1623130649765855234) has released sinesurf on [itch](https://zzox.itch.io/sinesurf) and [Newgrounds](https://www.newgrounds.com/portal/view/873482)

**Comment by Beeblerox** [comment]
- [ ] This enemy from Chibi Ninja Shino-kun is [supposed to throw shuriken...](https://twitter.com/ohsat_games/status/1621955188574638080)

**Comment by Beeblerox** [comment]
- [ ] Rob Clemmons Jr thinks that Patches Of Adventure [basics are there](https://twitter.com/RobClemmonsJr/status/1622146685752283137)

**Comment by Beeblerox** [comment]
- [ ] [Some new systems in HaxeUI](https://twitter.com/IanHarrigan1982/status/1622650707345014788)

**Comment by Beeblerox** [comment]
- [ ] Renaine Kickstarter Update #42: [Six Years!](https://www.kickstarter.com/projects/585676804/renaine-a-game-about-overcoming-failure/posts/3726996)

**Comment by Beeblerox** [comment]
- [ ] [Michael Bickel](https://twitter.com/dazKind/status/1622735178522103810) is porting more and more bits of their old Godot 3 space-game project over to HxGodot and Godot Engine 4

**Comment by Beeblerox** [comment]
- [ ] [Nanjizal](https://twitter.com/Nanjizal_net/status/1622716259002449935) is experimenting with their PixelImage library

**Comment by Beeblerox** [comment]
- [ ] [Alex Johansson](https://twitter.com/alexvscoding/status/1621139055282126849) is looking for a part time/contractor role

**Comment by Beeblerox** [comment]
- [ ] [HxcodecPlus Dev Build : 001](https://twitter.com/Rapper_GF_Dev/status/1622510191030706178)

**Comment by Beeblerox** [comment]
- [ ] [Dicey Dungeons](https://store.playstation.com/en-gb/product/EP7425-PPSA05370_00-DICEYDUNGEONS000) for PS4 and PS5 is OUT NOW! via [Terry Cavanagh](https://twitter.com/terrycavanagh/status/1622551864465039360)

**Comment by Beeblerox** [comment]
- [ ] [CastleDBGUI](https://github.com/Shallowmallow/CastleDBGUI) is the adaptation of CastleDB. Works with HaxeUI and OpenFL

**Comment by Beeblerox** [comment]
- [ ] [UI Design at Lower Resolutions](https://bitdecaygames.itch.io/odd-verdure/devlog/486423/ui-design-at-lower-resolutions) Odd Verdure devlog

**Comment by Beeblerox** [comment]
- [ ] [The Root of the Problem](https://axolstudio.itch.io/the-root-of-the-problem) is the 2023 Global Game Jam entry by Axol Studio

**Comment by Beeblerox** [comment]
- [ ] [Casey Clyde](https://discord.com/channels/162395145352904705/1072046131984474142/1072046131984474142) is working on [Into the Necrovale](https://store.steampowered.com/app/1717090/Into_the_Necrovale/)

**Comment by Beeblerox** [comment]
- [ ] [ZwodahS](https://discord.com/channels/162395145352904705/1070564912469921906/1070564912469921906) is working on extended version of Crop Rotation

**Comment by Beeblerox** [comment]
- [ ] Dead Cells: Return to Castlevania DLC [is arriving 6th March](https://twitter.com/motiontwin/status/1623447320787296258) on PC & consoles

**Comment by skial** [comment]
- [ ] `[core]` Add test for Int/Int32 shift left operations with overflow [pull request](https://github.com/HaxeFoundation/haxe/pull/10962).

**Comment by skial** [comment]
- [ ] `[open source]` [yad `git`](https://github.com/GrowtopiaFli/yad) - Youtube Archive Downloader.

**Comment by skial** [comment]
- [ ] `[open source]` [Haxe-to-GCFreeCPP `git`](https://github.com/RobertBorghese/Haxe-to-GCFreeCPP) - An alternative C++ target for Haxe that generates dependent-less, GC-less C++17 code. :star:

**Comment by skial** [comment]
- [ ] `[releases]` [IriySoft](https://twitter.com/IriySoft/status/1622608375023382530) has ported Battalion Commander 2 to HTML5 with OpenFL.

**Comment by skial** [comment]
- [x] `[core/eval]` Add `-D eval-pretty-print` [pull request](https://github.com/HaxeFoundation/haxe/pull/10963).
