### ISSUE TITLE
Haxe Roundup 667

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1061]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [ ] optional description [link name](/link/to/item)

**Comment by Yanrishatum** [comment]
- [ ] Release of a [successor library](https://github.com/Yanrishatum/tiledhx) to old `format-tiled` in the form of `tiledhx` along with a [backstory article](https://github.com/Yanrishatum/tiledhx/blob/master/Backstory.md) of how both libraries came to be.

**Comment by skial** [comment]
- [ ] `[core/cppia]` Create cppia output folder if it doesn't exist [pull request](https://github.com/HaxeFoundation/haxe/pull/10991).

**Comment by skial** [comment]
- [ ] `[core/lua]` Speed up `StringTools.(starts|ends)With` on Lua [pull request](https://github.com/HaxeFoundation/haxe/pull/10983).

**Comment by skial** [comment]
- [ ] `[core/lua]` Exit code 0 in case of error [issue](https://github.com/HaxeFoundation/haxe/issues/10979).

**Comment by skial** [comment]
- [ ] `[open source/tink_sql]` `WIP` Initial SQL server support [pull request](https://github.com/haxetink/tink_sql/pull/152).

**Comment by skial** [comment]
- [ ] `[core/neko]` Add `boot -c` flag to nekotools help [pull request](https://github.com/HaxeFoundation/neko/pull/273).

**Comment by skial** [comment]
- [ ] `[open source]` Ceramic `0.19.0` has been [released](https://github.com/ceramic-engine/ceramic/releases/tag/v0.19.0).

**Comment by skial** [comment]
- [ ] `[core]` Extended EnumFlags [issue](https://github.com/HaxeFoundation/haxe/issues/10981).

**Comment by skial** [comment]
- [ ] libs
   - [haxelib `4.0.3`](https://lib.haxe.org/p/haxelib)
   - [intl `0.3.2`](https://lib.haxe.org/p/intl)
   - [SScript `1.9.9`](https://lib.haxe.org/p/SScript)
   - [tink_domspec `0.4.0`](https://lib.haxe.org/p/tink_domspec)
   - [hxdiscord `0.3.0`](https://lib.haxe.org/p/hxdiscord)
   - [tiledhx `1.0.0`](https://lib.haxe.org/p/tiledhx)
   - [haxe-doctest `3.2.1`](https://lib.haxe.org/p/haxe-doctest)
   - [lex `1.0.0`](https://lib.haxe.org/p/lex)

**Comment by skial** [comment]
- [ ] `[releases]` Citadelic Soundtrack is [now available](https://kircode.com/en/post/citadelic-soundtrack-is-now-available).

**Comment by skial** [comment]
- [ ] `[community/devlog]` Fraymakers EA [Update `v0.5.5`](https://store.steampowered.com/news/app/1420350/view/3683418857214512380) - Major Lost Input Fixes and More.

**Comment by skial** [comment]
- [ ] `[video]` Marika Versus the Wall Walker [video](https://www.youtube.com/watch?v=QTkW8SY7KyA&widget_referrer=haxe.io) from Rogue of Vallas.

**Comment by skial** [comment]
- [ ] `[video]` [Art Gallery](https://www.youtube.com/watch?v=QLWubcZvkNM&widget_referrer=haxe.io) & [ME Environment 1](https://www.youtube.com/watch?v=c_WjQSWa97A&widget_referrer=haxe.io) in Armory3D by Alexander Kleemann.

**Comment by skial** [comment]
- [ ] `[video]` Understanding Conditions in [Armory 3D](https://www.youtube.com/watch?v=KuoQqb76MnU&widget_referrer=haxe.io).
- [ ] `[video]` Using 1 player controller across many levels in [Armory 3D](https://www.youtube.com/watch?v=7lzT_IwGzgM&widget_referrer=haxe.io).

**Comment by Beeblerox** [comment]
- [ ] Quick videos from new WIP platformer game by Robert Alvarez:
    * [What if midair jumps made you smaller?](https://twitter.com/Rob1221dev/status/1628785704170844160)
    * [Bigger isn't always better](https://twitter.com/Rob1221dev/status/1630236318910300162)

**Comment by Beeblerox** [comment]
- [ ] New quick videos from [Renaine](https://store.steampowered.com/app/662340/Renaine/):
    * hey look I'm the programmer and I can hastily shove in whatever [placeholder art for this duo boss](https://twitter.com/squuuidly/status/1628786768547033091) battle I want ok?
    * [messy fight from an outtake](https://twitter.com/squuuidly/status/1629557990641508353)
    * Warning! [One of these gnomes is not like the others](https://twitter.com/squuuidly/status/1630608327599071233) 🔺🔺🔺
    * [ARE YOU READY TO CHALLENGE THE KING?](https://twitter.com/RenaineGame)

**Comment by Beeblerox** [comment]
- [ ] Dead Cells: Return to Castlevania DLC - [Final Teaser & Surprise Reveal](https://www.youtube.com/watch?v=CsAyUBexG78)

**Comment by Beeblerox** [comment]
- [ ] New quick videos from [Chibi Ninja Shino-kun](https://store.steampowered.com/app/2175640/Chibi_Ninja_Shinokun_Treasure_of_Demon_Tower/):
    * If stuff drops from above, [Shino-kun gets a little panicked...](https://twitter.com/ohsat_games/status/1629571594669391873) which is understandable, honestly. Look at the size of those things! 
    * Chibi Ninja Shino-kun doesn't have one, not two, but [THREE ledge wobble animations](https://twitter.com/ohsat_games/status/1629838516858363904). Why do you think the game is taking so long? I got priorities ¯\_(ツ)_/¯
    * If you kick a shield enemy standing on ice in Chibi Ninja Shino-kun, [he'll slide farther than he usually would...](https://twitter.com/ohsat_games/status/1630281034725040129) and he looks a bit unhappy about it. Might have something to do with that spike pit.
    * [The current state of Chibi Ninja Shino-kun](https://twitter.com/ohsat_games/status/1630580802797940736)
    * Even a master ninja like Shino-kun [can't wall-jump when the walls are covered in ice](https://twitter.com/ohsat_games/status/1631009035049750531). Who knew?

**Comment by Beeblerox** [comment]
- [ ] New quick videos from WIP Starfox remake game by SnkyGames:
    * [Blooper `#1`](https://twitter.com/SnkyGames/status/1629585123053035521)
    * [Blooper `#2`](https://twitter.com/SnkyGames/status/1629830055739154432)
    * Starfox update 🐸🐰🦅🦊, [new Camera 📹](https://twitter.com/SnkyGames/status/1629573331165773828)

**Comment by Beeblerox** [comment]
- [ ] 🏰[Medieval Fantasy City Generator 0.9.2](https://www.patreon.com/posts/medieval-fantasy-79147510): assorted new features and improvements by [Oleg Dolya](https://twitter.com/watawatabou/status/1629176036767285248)

**Comment by Beeblerox** [comment]
- [ ] Nanjizal is [struggling with edge smoothing for triangles](https://twitter.com/Nanjizal_net/status/1630888725411422208), but looking a better.

**Comment by Beeblerox** [comment]
- [ ] Thanks to the Haxe community (and its multilingual nature), [HaxeUI now has a better locale support](https://twitter.com/IanHarrigan1982/status/1629422273865170953)!

**Comment by Beeblerox** [comment]
- [ ] Michael Bickel: It's time to worry about compiling, [running and reloading Haxe as CPPIA scripts](https://twitter.com/dazKind/status/1629533927923744769).

**Comment by Beeblerox** [comment]
- [ ] Armory3D just got another release (v2023.03)! You can view the full release notes here: [https://armory3d.org/notes#2023.03](https://armory3d.org/notes#2023.03). via [RPaladin](https://twitter.com/RPaladin_01/status/1630960840466903040)

**Comment by Beeblerox** [comment]
- [ ] There was an update to haxelib. It is minor and just has some bug fixes but stability is cool! Run `haxelib --global install haxelib`. via [Aurel Bílý](https://discord.com/channels/162395145352904705/286485321925918721/1080121435814633482)

**Comment by Beeblerox** [comment]
- [ ] Ceramic is now able to [load tilemap objects from LDtk projects](https://discord.com/channels/162395145352904705/853414608747364352/1079427847388676196)

**Comment by Beeblerox** [comment]
- [ ] Cornell Daly is [getting around to actual core game mechanics](https://twitter.com/bojjenclon/status/1628879132862939137) for their engine's POC project

**Comment by Beeblerox** [comment]
- [ ] [Crop Rotation](https://zwodahs.itch.io/crop-rotation) [0.0.5] is live! With new mechanic : Crop Set. via [ZwodahS](https://discord.com/channels/162395145352904705/1070564912469921906/1079768301800005784)

**Comment by Beeblerox** [comment]
- [ ] [Blue](https://discord.com/channels/162395145352904705/1079482062148481165/1079482062148481165) is a free, multi-platform, compiled programming language made with and inspired by Haxe! Currently there are four supported language backends (C++, Groovy, Haxe, and Javascript), however the compiler has a Lua API that allows you to make your own language backends easily without meddling with the compiler's source code.
    * [Github](https://github.com/BlueLangDev/Blue) 
    * [WIP] [Documentation](https://bluelang.org/docs)
    * [Standard Library reference](https://bluelang.org/api-reference)

**Comment by Beeblerox** [comment]
- [ ] [Cherry On Top](https://drewbys-games.itch.io/cherry-on-top) is a cherry-throwing arcade microgame made by [Markl](https://discord.com/channels/162395145352904705/162664383082790912/1079620009120247878) for Nokia jam using HaxeFlixel

**Comment by Beeblerox** [comment]
- [ ] yoplala is [making a dictation app for Linux](https://discord.com/channels/162395145352904705/162664383082790912/1080516447962398780). It uses python target for now. Here is a [short video showing how it works](https://tempclip.com/vchFX1s2tyecDeQ/watch)

**Comment by Beeblerox** [comment]
- [ ] [Fish, Man](https://spinlandgames.itch.io/fish-man-prototype) is a score-chaser game with a  built in leaderboard by [tissproper](https://discord.com/channels/162395145352904705/162664383082790912/1080525708771741757)

**Comment by Beeblerox** [comment]
- [ ] Dead Cells Mobile - [Everyone is Here Vol.2 release trailer](https://www.youtube.com/watch?v=NWlMnkSNvqQ)
- [ ] Dead Cells Mobile - [Boss Rush Release trailer](https://www.youtube.com/watch?v=JerXZSza1qM)

**Comment by skial** [comment]
- [ ] `[community]` NeoVim config written entirely in Haxe _(using haxe-nvim)_ [milestone](https://community.haxe.org/t/neovim-config-written-entirely-in-haxe-using-haxe-nvim/3882?u=skial).

**Comment by skial** [comment]
- [ ] `[core/eval/lua]` `Reflect.hasField` on function reference throws exception [issue](https://github.com/HaxeFoundation/haxe/issues/10993).

**Comment by skial** [comment]
- [ ] `[core/php]` Vector + conditionals can break diagnostics [issue](https://github.com/HaxeFoundation/haxe/issues/10992).

**Comment by skial** [comment]
- [ ] `[community]` Creating a Launch Script with Haxe/Lime [article](https://www.elitemastereric.com/Launch-Script-Lime/) by EliteMasterEric.

**Comment by skial** [comment]
- [ ] `[open source]` [HaxeBSON `git]`(https://github.com/Cheemsandfriends/HaxeBSON) - BSON, short for Bin­ary [JSON](https:///json.org), is a bin­ary-en­coded seri­al­iz­a­tion of JSON-like doc­u­ments.

**Comment by skial** [comment]
- [ ] `[open source]` [iterMagic `git`](https://github.com/nanjizal/iterMagic) - Helpers for `IntIter`.

**Comment by skial** [comment]
- [ ] `[open source]` [haxvolt `git`](https://github.com/ben-forster/haxvolt) - Haxvolt is a Haxe library for building Revolt bots.

**Comment by skial** [comment]
- [ ] `[open source]` [Haxefrog `git`](https://github.com/Weathercold/Haxefrog) - Example Mindustry _(automation tower defense RTS)_ mod in Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [FixedPointNumber `git`](https://github.com/LeotomasMC/FixedPointNumber) - A Haxe library for fixed point numbers.

**Comment by Aurel300** [comment]
@Beeblerox I think I see this for the second time now, so just to clarify: `NotBilly` on the Haxe Discord is not me :) I am `Aurel300` there as well. I cannot take credit for the haxelib thing in this roundup, for example.

**Comment by Beeblerox** [comment]
@Aurel300 Sorry, my bad. Won't happen again
