### ISSUE TITLE
Haxe Roundup 671

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1071]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` MacroApi.type_expr vs diagnostics [merged](https://github.com/HaxeFoundation/haxe/pull/11048).

**Comment by skial** [comment]
- [ ] `[core]` More strict macro API for init vs not init macros [merged](https://github.com/HaxeFoundation/haxe/pull/11043).

**Comment by skial** [comment]
- [ ] `[core/nullsafety]` Null safety skips inline argument cast [issue](https://github.com/HaxeFoundation/haxe/issues/11045).

**Comment by skial** [comment]
- [ ] `[core]` Detect transitive casts [pull request](https://github.com/HaxeFoundation/haxe/pull/11041).

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` Migrate to PCRE2 [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1037).

**Comment by skial** [comment]
- [ ] `[core/eval]` Migrate to PCRE2 [merged](https://github.com/HaxeFoundation/haxe/pull/11032).

**Comment by skial** [comment]
- [ ] `[core/lua]` Use lrexlib-pcre2 for regular expressions [merged](https://github.com/HaxeFoundation/haxe/pull/11030).

**Comment by skial** [comment]
- [ ] `[core/hl]` Migrate to PCRE2 [merged](https://github.com/HaxeFoundation/hashlink/pull/515).

**Comment by skial** [comment]
- [ ] fix https://github.com/skial/haxe.io/issues/1072

**Comment by skial** [comment]
- [ ] `[core]` `@:using` typedef cascading signatures loop [fixed](https://github.com/HaxeFoundation/haxe/issues/10107).

**Comment by skial** [comment]
- [ ] `[core/lua]` Fix for https requests failing immediately and updating `_hx_bit` to work with lua `5.4` [merged](https://github.com/HaxeFoundation/haxe/pull/11052).

**Comment by skial** [comment]
- [ ] `[core/macro]` Add `TypeTools.validateTypeParams` [pull request](https://github.com/HaxeFoundation/haxe/pull/11053).

**Comment by skial** [comment]
- [ ] `[core/eval]` Floats being treated as Ints in interp mode [issue](https://github.com/HaxeFoundation/haxe/issues/10918).

**Comment by skial** [comment]
- [ ] `[core/jvm]` Functional interface support [merged](https://github.com/HaxeFoundation/haxe/pull/11019).

**Comment by skial** [comment]
- [ ] `[core]` Improve duplicate field range [merged](https://github.com/HaxeFoundation/haxe/pull/11042).

**Comment by skial** [comment]
- [ ] `[core/typer]` Add define to retain meta upon typing [merged](https://github.com/HaxeFoundation/haxe/pull/10973).

**Comment by Beeblerox** [comment]
- [ ] Poor Bunny! (made with Stencyl) by [Advent](https://twitter.com/AdventIslands/status/1639636343771807746) has been released on [Poki](https://poki.com/en/g/poor-bunny), [App Store](https://apps.apple.com/us/app/poor-bunny/id1642056967) and [Google Play](https://play.google.com/store/apps/details?id=com.adventureislands.poorbunny)

**Comment by Beeblerox** [comment]
- [ ] Renaine had [been on PAX East](https://twitter.com/RenaineGame/status/1638970105638842386) last weekend. There are many more photos on their twitter

**Comment by Beeblerox** [comment]
- [ ] Starfox update 🐸🐰🦅🦊, [it's a moai life](https://twitter.com/SnkyGames/status/1639697909930139648)

**Comment by Beeblerox** [comment]
- [ ] [Smooth camera follow in Armory 3D](https://www.youtube.com/watch?v=7Ayu9bwU2vU) video

**Comment by Beeblerox** [comment]
- [ ] 🏡[Village Generator 1.4.0](https://www.patreon.com/posts/village-1-4-0-80494491): village square and orchards by [Oleg Dolya](https://twitter.com/watawatabou/status/1639553825341145088)

**Comment by Beeblerox** [comment]
- [ ] [The City Streets update](https://twitter.com/AxolStudio/status/1639666703067136001) is coming soon for [Bring It On!](https://store.steampowered.com/app/2020460/Bring_It_On/) by Axol Studio

**Comment by Beeblerox** [comment]
- [ ] A crappy version of Doom can [technically run with the HaxeFlixel](https://twitter.com/indigoUan/status/1640827945785622529) framework

**Comment by Beeblerox** [comment]
- [ ] [Freestyle Engine Dev Build 006](https://twitter.com/Rapper_GF_Dev/status/1639908006056927233): Audio Reactive Elements now Work With Waveforms!!
- [ ] [Freestyle Dev Build 007](https://twitter.com/Rapper_GF_Dev/status/1640905720961835008): Assets can be loaded with Case-Insensitive names!!

**Comment by Beeblerox** [comment]
- [ ] New funkin blog - [WEEK OF 2023/03/27](https://funkin.me/blog/2023-03-30/): VITAMIN D EDITION

**Comment by Beeblerox** [comment]
- [ ] CLYDE is building out [the Prison area...](https://twitter.com/clydegamedev/status/1641286399679930370) for [Into the Necrovale](https://store.steampowered.com/app/1717090/Into_the_Necrovale/)

**Comment by Beeblerox** [comment]
- [ ] [A bunch of little floating Haxe logos?](https://twitter.com/EliteMasterEric/status/1640971954248138753) In my modded Minecraft world? It's more likely than you think. After some cleanup you'll see a release of PickHaxe 0.1.0-alpha

**Comment by Beeblerox** [comment]
- [ ] Level editor by ChargingTurnip is [going pretty well](https://discord.com/channels/162395145352904705/1081002322475360377/1090843493561270392)

**Comment by skial** [comment]
- [ ] `[events/upcoming]` The next Haxe Roundup _Roundup_ is scheduled for Sunday 9th April on the [Haxe Discord server](https://discord.com/events/162395145352904705/1089951493190328402).

**Comment by skial** [comment]
- [ ] `[core/lua]` Hide Lua String inlines [pull request](https://github.com/HaxeFoundation/haxe/pull/11057).

**Comment by skial** [comment]
- [ ] `[core/neko]` Fix issues with HaxeLib ndll behaviour [merged](https://github.com/HaxeFoundation/haxe/pull/11056).

**Comment by skial** [comment]
- [ ] libs
   - [hxdefold `1.4.4`](https://lib.haxe.org/p/hxdefold)
   - [dropecho.storygen `0.13.0`](https://lib.haxe.org/p/dropecho.storygen)
   - [intl `0.6.0`](https://lib.haxe.org/p/intl)
   - [hxlua `1.3.1`](https://lib.haxe.org/p/hxlua)
   - [haxe-nvim `1.0.0`](https://lib.haxe.org/p/haxe-nvim)
   - [mc2it_theme `4.0.1`](https://lib.haxe.org/p/mc2it_theme)
   - [SSIni `1.0.1`](https://lib.haxe.org/p/SSIni)
   - [hxgamejolt-api `1.0.3`](https://lib.haxe.org/p/hxgamejolt-api)
   - [CXXGraph `0.5.0`](https://lib.haxe.org/p/CXXGraph)
   - [comma `0.1.5`](https://lib.haxe.org/p/comma)
   - [dreamengine-cli `0.1.4`](https://lib.haxe.org/p/dreamengine-cli)
   - [electron `23.2.0`](https://lib.haxe.org/p/electron)

**Comment by skial** [comment]
- [ ] `[open source]` [daftlib-openfl `git`](https://github.com/ericlincn/daftlib-openfl) - A collection of commonly used utility classes and data structures.
