### ISSUE TITLE
Haxe Roundup 672

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1074]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by EliteMasterEric** [comment]
- [ ] New library release: [PickHaxe](https://github.com/EliteMasterEric/pickhaxe), a Minecraft modding framework (currently supports Fabric 1.19, with Forge coming soon).

**Comment by skial** [comment]
- [ ] `[core]` Similarly named typedefs in adjacent modules cause overlap [issue](https://github.com/HaxeFoundation/haxe/issues/11079).

**Comment by skial** [comment]
- [ ] `[core/null safety]` Null safety inline generic function [issue](https://github.com/HaxeFoundation/haxe/issues/11077).

**Comment by skial** [comment]
- [ ] `[core/null safety]` Fix null arg check [pull request](https://github.com/HaxeFoundation/haxe/pull/11076).

**Comment by skial** [comment]
- [ ] `[core`] Mono to Any cast error [issue](https://github.com/HaxeFoundation/haxe/issues/11068).

**Comment by skial** [comment]
- [ ] `[core]` Fix call stack positions [merged](https://github.com/HaxeFoundation/haxe/pull/11065).

**Comment by skial** [comment]
- [ ] `[core]` Switch with at least one field match accesses all the fields [issue](https://github.com/HaxeFoundation/haxe/issues/11062).

**Comment by skial** [comment]
- [ ] `[core/python]` Fix Python vector syntax issue [merged](https://github.com/HaxeFoundation/haxe/pull/11060).

**Comment by skial** [comment]
- [ ] `[core/js]` Generate class names when using `Type.typeof` on classes [pull request](https://github.com/HaxeFoundation/haxe/pull/11074).

**Comment by skial** [comment]
- [ ] `[events]` The HaxeUp event schedule at Shiro Games has been [released](https://community.haxe.org/t/april-haxeup-at-shiro-games/3909/6?u=skial).

**Comment by skial** [comment]
- [ ] libs
   - [bootstrap_bundle `2.1.2`](https://lib.haxe.org/p/bootstrap_bundle)
   - [SScript `2.0.0`](https://lib.haxe.org/p/SScript)
   - [deepnightLibs `1.0.76`](https://lib.haxe.org/p/deepnightLibs)
   - [PickHaxe `0.1.1`](https://lib.haxe.org/p/PickHaxe)
   - [haxe-concurrent `5.1.1`](https://lib.haxe.org/p/haxe-concurrent)
   - [flxgif `1.0.1`](https://lib.haxe.org/p/flxgif)
   - [hxdiscord `0.5.0`](https://lib.haxe.org/p/hxdiscord)
   - [extension-kizzyrpc `1.0.1`](https://lib.haxe.org/p/extension-kizzyrpc)
   - [extension-androidtools `1.8.1`](https://lib.haxe.org/p/extension-androidtools)
   - [hxgamejolt-api `1.0.4`](https://lib.haxe.org/p/hxgamejolt-api)
   - [hxlua `1.3.2`](https://lib.haxe.org/p/hxlua)
   - [starling `2.7.0`](https://lib.haxe.org/p/starling)
   - [tink_core `2.1.0`](https://lib.haxe.org/p/tink_core)

**Comment by skial** [comment]
- [ ] `[video]` How to Make Adding a Video to a HaxeFlixel Project Quick and Painless [video](https://www.youtube.com/watch?v=UU0HLO4oqvg) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] `[video]` Armory 3D project structure [video](https://www.youtube.com/watch?v=lA78BM90sFU).
- [ ] `[video]` Armory 3D April 2023 release [overview](https://www.youtube.com/watch?v=wcDROlOpMbA).
- [ ] `[video]` Node grouping is changing Armory 3D forever [video](https://www.youtube.com/watch?v=EJemk24yvMM).

**Comment by skial** [comment]
- [ ] `[open source]` [minecraft-book-paster `git`](https://github.com/Bloodninj/minecraft-book-paster) - Tool to help paste large pieces of text into Minecraft's book & quill item.

**Comment by skial** [comment]
- [ ] `[community/releases]` Defender's Quest 2 is [re-announced](https://twitter.com/larsiusprime/status/1643617785883377665). Lean more at [defendersquest2.com](https://www.defendersquest2.com/)!

**Comment by Beeblerox** [comment]
- [ ] Northgard [Spectator Mode: Open Beta](https://store.steampowered.com/news/app/466560/view/3690175524530408110)
- [ ] Wartales [Community Update `#6`](https://store.steampowered.com/news/app/1527950/view/3716073126075919653) Out now!

**Comment by Beeblerox** [comment]
- [ ] gepatto is [testing the Away3D Terrain Sample](https://twitter.com/gepatto/status/1641410116472676354) on a Raspberry Pi 4 at 640x480

**Comment by Beeblerox** [comment]
- [ ] New quick videos from [Renaine](https://store.steampowered.com/app/662340/Renaine/):
    * Chompy actually [goes after anyone that attacks you](https://twitter.com/squuuidly/status/1641457503463456770) - even ranged attacks (•﹏•)
    * [going up ⬆️](https://twitter.com/squuuidly/status/1641813469149249538)
    * Important Announcement on April 1st: Due to the popularity of Chompy as an assist and adorable pet, [we've upgraded their role to Main Character](https://twitter.com/RenaineGame/status/1642165460920594437)

**Comment by Beeblerox** [comment]
- [ ] Armory3D [v2023.04 release notes](https://armory3d.org/notes#2023.04)

**Comment by Beeblerox** [comment]
- [ ] [indigoUan](https://twitter.com/indigoUan/status/1643705005654810624) wrote a StepMania chart parser in Haxe

**Comment by Beeblerox** [comment]
- [ ] [More editor progress](https://discord.com/channels/162395145352904705/1081002322475360377/1092863610058973335) by ChargingTurnip

**Comment by Beeblerox** [comment]
- [ ] Kala is [working on Tien Len](https://twitter.com/kala_ixia/status/1641411625390592003), a Vietnamese card game

**Comment by Beeblerox** [comment]
- [ ] [The door is no longer needed](https://twitter.com/SyoPic/status/1643697198280892430) in Jitter Sandbox by Syo

**Comment by Beeblerox** [comment]
- [ ] [Real-time RIGID BODY editing](https://discord.com/channels/415681294446493696/436230004251164672/1092612131268067358) in Starfox remake by SnkyGames

**Comment by Beeblerox** [comment]
- [ ] Sébastien Benard has [added a quick switcher](https://discord.com/channels/761549092677353513/778168731036549130/1090908920538742836) to travel between existing worlds in LDtk

**Comment by Beeblerox** [comment]
- [ ] [Ando has announced](https://twitter.com/ohsat_games/status/1643692663395196929) that they are working on a new game Edge Monster Saga

**Comment by kLabz** [comment]
Hi!

We're releasing haxe 4.3.0 in like 5~6 hours at the beginning of HaxeUp, I don't know if you want to do anything special about it.
The release page on github is up (but kinda empty until the event) there https://github.com/HaxeFoundation/haxe/releases/tag/4.3.0

The release message is also ready:


Dear Community,

On behalf of the Haxe Foundation, we are proud to announce the official release of Haxe 4.3.0!

Here are the most notable features made into this release:

- Support defaults for type parameters (see [haxe-evolution proposal](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0013-default-type-parameters.md))
- Support abstract keyword to reference the abstract (see [haxe-evolution proposal](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0014-self-access-for-abstracts.md))
- Support static var at expression-level (see [haxe-evolution proposal](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0015-local-static-variables.md))
- Support ?. safe navigation operator (see [haxe-evolution proposal](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0017-null-safe-navigation-operator.md))
- Added ?? null coalescing operator (see [haxe-evolution proposal](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0016-null-coalescing-operator.md))
- Support number separators (see [haxe-evolution proposal](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0018-number-separators.md))
- Support numeric literal suffixes (see [haxe-evolution proposal](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0019-numeric-iteral-suffixes.md))
- Add -w compiler option to configure warnings
- Added new error reporting modes (see [pull request](https://github.com/HaxeFoundation/haxe/pull/10863))
- Support custom metadata and defines (see [pull request](https://github.com/HaxeFoundation/haxe/pull/10858))
- many other features (see changelog)

Haxe 4.3.0 also includes dozens of other additions, optimizations, improvements, and bugfixes.

Check out the changelog below for more information.

If you have any suggestions or run into any problems, absolutely [open an issue on GitHub](https://github.com/HaxeFoundation/haxe/issues).

Thanks to everyone involved!

**Comment by skial** [comment]
So many new features to dig through, I'm esp interested in the new macro features 🙏

I usually don't do anything special for a release or HaxeUp as I'm always unavailable when a HaxeUp is live, **BUT** today I'll be able to watch it live and was considering postponing the roundup to cover anything from the talks.

**Comment by skial** [comment]
- [ ] `[community]` Chibi Ninja Shino-kun: Treasure of Demon Tower ~ [How's the Game?](https://store.steampowered.com/news/app/2175640/view/3692429859529104654) by Ando.

**Comment by kLabz** [comment]
> So many new features to dig through, I'm esp interested in the new macro features 🙏
> 
> I usually don't do anything special for a release or HaxeUp as I'm always unavailable when a HaxeUp is live, **BUT** today I'll be able to watch it live and was considering postponing the roundup to cover anything from the talks.

hey that's great! nothing to worry about on our end then I guess :)
