### ISSUE TITLE
Haxe Roundup 674

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1078]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[events/upcoming]` The next Haxe Roundup _Roundup_ [event](https://discord.com/events/162395145352904705/1096198797362745355) over on discord is scheduled for Sunday 23rd April 18:30.

**Comment by skial** [comment]
- [ ] `[core/jvm]` Exception attribute is broken [fixed](https://github.com/HaxeFoundation/haxe/issues/11140).

**Comment by skial** [comment]
- [ ] `[core]` Support deprecation for defines [merged](https://github.com/HaxeFoundation/haxe/pull/11137).

**Comment by skial** [comment]
- [ ] `[core]` Rework error handling [merged](https://github.com/HaxeFoundation/haxe/pull/11136).

**Comment by skial** [comment]
- [ ] `[core/haxelib]` Define `lib.name` [for Haxe `v5`](https://github.com/HaxeFoundation/haxelib/issues/600).

**Comment by skial** [comment]
- [ ] `[core/feature request]` Default value expressions (default operator and/or literal) [request](https://github.com/HaxeFoundation/haxe/issues/11138).

**Comment by skial** [comment]
- [ ] `[core]` Exponential increase in generated code size due to array matching [issue](https://github.com/HaxeFoundation/haxe/issues/11145).

**Comment by skial** [comment]
- [ ] `[core]` Possible null coalescing operator priority error [fixed](https://github.com/HaxeFoundation/haxe/issues/11144).

**Comment by skial** [comment]
- [ ] `[core]` Namespace message reporting defines for `4.3` bugfix [pull request](https://github.com/HaxeFoundation/haxe/pull/11142).

**Comment by skial** [comment]
- [ ] `[core]` Rework extractors [pull request](https://github.com/HaxeFoundation/haxe/pull/11141).

**Comment by skial** [comment]
- [ ] `[core/macro]` Custom target [progress](https://github.com/HaxeFoundation/haxe/pull/11128#issuecomment-1508237137) with `Compiler.setPlatformConfiguration`.

**Comment by skial** [comment]
- [ ] `[video]` Supercharge Your Code with Haxe `4.3.0`'s Incredible New Features [video](https://www.youtube.com/watch?v=0J1NkBIzKdw) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] `[community]` A guide for Ceramic about [Scenes](https://ceramic-engine.com/guides/scenes/) by Jérémy Faivre.

**Comment by skial** [comment]
- [ ] `[core]` Typing order error with generic and specific import order [issue](https://github.com/HaxeFoundation/haxe/issues/11152).

**Comment by skial** [comment]
- [ ] `[core/cpp]` Generate Typed Functions [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11151). :star:

**Comment by skial** [comment]
- [ ] `[core/nullsafety]` Fix null-safety locals after if/while [pull request](https://github.com/HaxeFoundation/haxe/pull/11150).

**Comment by skial** [comment]
- [ ] `[video]` Learn the [Blue programming language](https://github.com/SteveStudios/Blue) - Introduction and Methods [video](https://www.youtube.com/watch?v=iwkKahtgO3w).

**Comment by skial** [comment]
- [ ] Consider using/adding some stats from https://ossinsight.io/analyze/HaxeFoundation/haxe#overview & https://ossinsight.io/collections/programming-language/

**Comment by skial** [comment]
- [ ] `[core]` Allow boolean operators in patterns [pull request](https://github.com/HaxeFoundation/haxe/pull/11157).

**Comment by skial** [comment]
- [ ] `[core]` Should default type parameters abide by imports? [issue](https://github.com/HaxeFoundation/haxe/issues/11161).

**Comment by skial** [comment]
- [ ] `[core]` Turn TSwitch into a record [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11160).

**Comment by skial** [comment]
- [ ] `[core/tests]` Compilation server vs `defineModule`/`defineType` [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11159). :star:

**Comment by skial** [comment]
- [ ] `[core/macro]` Add `TypeTools.toBaseType()` [pull request](https://github.com/HaxeFoundation/haxe/pull/11153).

**Comment by skial** [comment]
- [ ] libs
   - [deepnightLibs `1.0.77`](https://lib.haxe.org/p/deepnightLibs)
   - [intl `0.8.1`](https://lib.haxe.org/p/intl)
   - [hxdiscord_rpc `1.0.5`](https://lib.haxe.org/p/hxdiscord_rpc)
   - [hxwren `1.0.1`](https://lib.haxe.org/p/hxwren)
   - [pirhana `1.1.25`](https://lib.haxe.org/p/pirhana)
   - [hxlua `1.4.0`](https://lib.haxe.org/p/hxlua)
   - [vision `1.3.1`](https://lib.haxe.org/p/vision)
   - [free_mobile `1.2.0`](https://lib.haxe.org/p/free_mobile)
   - [jsasync `1.3.1`](https://lib.haxe.org/p/jsasync)

**Comment by skial** [comment]
- [ ] `[community/devlog]` Dead Cells [Update 34](https://store.steampowered.com/news/app/588650/view/6438500527887133181) - Clean Cut moves into beta.

**Comment by skial** [comment]
- [ ] `[community]` What's next [for Northgard?](https://store.steampowered.com/news/app/466560/view/3727331670931048997)

**Comment by skial** [comment]
- [ ] `[open source]` [sfxr-hx `git`](https://github.com/jobf/sfxr-hx) - Sfxr in pure Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [haxe-functional `git`](https://github.com/imfi-jz/haxe-functional) - Tools for writing Haxe code in the functional programming paradigm.

**Comment by Beeblerox** [comment]
- [ ] [Perilous Icons](https://www.patreon.com/posts/perilous-icons-81512739) new generator by [Oleg Dolya](https://twitter.com/watawatabou/status/1646919738226794510)

**Comment by Beeblerox** [comment]
- [ ] New quick video from Renaine - [you guys thought i was joking](https://twitter.com/squuuidly/status/1646520466180558848)

**Comment by Beeblerox** [comment]
- [ ] [A little sneak peek](https://twitter.com/DuneSpiceWars/status/1647969044748726275) at the upcoming tutorials menu from [Dune: Spice Wars](https://store.steampowered.com/app/1605220/Dune_Spice_Wars/)

**Comment by Beeblerox** [comment]
- [ ] New Starfox 🐸🐰🦅🦊 remake updates by SnkyGames:
    * [venom wall](https://twitter.com/SnkyGames/status/1646544360144502795)
    * [solved i-frames, electric guitar time!](https://twitter.com/SnkyGames/status/1646573330944741377)
    * [mesh deformation](https://twitter.com/SnkyGames/status/1646981728576077826)
    * [Arwing to Walker transform](https://twitter.com/SnkyGames/status/1648375912809873422)

**Comment by Beeblerox** [comment]
- [ ] Freestyle Engine Updates by [Rapper GF | Freestyle Dev](https://twitter.com/Rapper_GF_Dev):
    * Freestyle Engine [Dev Build : 008](https://twitter.com/Rapper_GF_Dev/status/1646428910710583296)! Videos are now playable as instrumental tracks
    * [The minimum specs for the engine](https://twitter.com/Rapper_GF_Dev/status/1647288817030684673) are an i3 core duo @ 2.1GHZ or equivalent

**Comment by Beeblerox** [comment]
> * [ ]  `[community]` A guide for Ceramic about [Scenes](https://ceramic-engine.com/guides/scenes/) and [Observables](https://ceramic-engine.com/guides/observables/) by Jérémy Faivre.

- [ ] and [State Machines](https://ceramic-engine.com/guides/state-machines/). via [Jérémy Faivre](https://twitter.com/jeremyfaivre/status/1647616880012587009)

**Comment by Beeblerox** [comment]
- [ ] [Game Career Seminar: Micro-Postmortems: 'Casual Birder', 'ValiDate', and 'Heck Deck'](https://www.gdcvault.com/play/1029111/Game-Career-Seminar-Micro-Postmortems) where [torcado](https://twitter.com/torcado/status/1647055891697393664) talked about Heck Deck's development and turned it into a pseudo-lecture on how to make interesting games :)

**Comment by Beeblerox** [comment]
- [ ] [Ceramic v1.1.1](https://github.com/ceramic-engine/ceramic/releases/tag/v1.1.1) minor release

**Comment by Beeblerox** [comment]
- [ ] A preview of [the virtual keyboard](https://twitter.com/bojjenclon/status/1647755065778745345) by Cornell Daly

**Comment by Beeblerox** [comment]
- [ ] m0rkeulv is trying to [bring some new life](https://discord.com/channels/162395145352904705/1096816414880440560/1096816414880440560) to the old haxe intelliJ plugin. [Try the latest Beta](https://github.com/HaxeFoundation/intellij-haxe/releases). 
Note: This plugin has not been worked on for the last 2.5 years or so, so support for the more resent Haxe features are still missing, but will hopefully be added in the not too distant future.

**Comment by Beeblerox** [comment]
- [ ] [Prexot](https://discord.com/channels/162395145352904705/1020075437080191096/1096817630628818945) submitted and published new version of [Rhythm Magus](https://www.newgrounds.com/portal/view/880921?updated=1681571789)

**Comment by Beeblerox** [comment]
- [ ] [Josh Tynjala](https://discord.com/channels/415681294446493696/436230004251164672/1096184519498924123) decided to start blogging about some of the new features for the next version of OpenFL. Here's [devlog #1: Weak event listeners](https://joshblog.net/2023/openfl-devlog-weak-event-listeners/)

**Comment by skial** [comment]
- [ ] `[core]` Rework module resolution [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11168).

**Comment by skial** [comment]
- [ ] `[open source]` [nme `6.3.26`](https://github.com/haxenme/nme/releases/tag/v6.3.26) has been released.

**Comment by skial** [comment]
- [ ] `[open source]` [reflaxe.CSharp `git`](https://github.com/RobertBorghese/reflaxe.CSharp) - A remake of the Haxe/C# target written entirely within Haxe using Reflaxe. :star2:
