### ISSUE TITLE
Haxe Roundup 675

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1080]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[community]` HaxeUI `v1.6` has been [released](https://community.haxeui.org/t/haxeui-v1-6-released/528?u=skial)! :fire:

**Comment by rpaladin** [comment]
Hi. Just a reminder to pin the latest tweet of yours on Twitter.  Currently, your pin is still on your before last tweet, not last tweet. 🙂

**Comment by skial** [comment]
@rpaladin done :+1:

**Comment by skial** [comment]
- [ ] `[core]` hl analyzer since version `1.12.0` analyzer `20x` slower [issue](https://github.com/HaxeFoundation/haxe/issues/11174).

**Comment by skial** [comment]
- [ ] `[core]` Recursive inline is not supported on enum abstract constructor [issue](https://github.com/HaxeFoundation/haxe/issues/11177).

**Comment by skial** [comment]
- [ ] `[core/cpp]` Double throw generated in cpp `Reflect.callMethod` [issue](https://github.com/HaxeFoundation/haxe/issues/11175).

**Comment by skial** [comment]
- [ ] `[core/macro]` Add `resolveContextType` [merged](https://github.com/HaxeFoundation/haxe/pull/11172/).

**Comment by skial** [comment]
- [ ] `[core]` Go to definition problem with final assign [issue](https://github.com/HaxeFoundation/haxe/issues/11173).

**Comment by 0b1kn00b** [comment]
- [ ] Variadic constructors in Haxe [article](https://ohmrun.hashnode.dev/variadic-constructors-in-haxe)

**Comment by skial** [comment]
- [ ] libs
   - [extension-androidtools `1.8.2`](https://lib.haxe.org/p/extension-androidtools)
   - [hxwren `1.1.0`](https://lib.haxe.org/p/hxwren)
   - [urals-storage `0.0.1`](https://lib.haxe.org/p/urals-storage)
   - [hx_webserver `0.0.2`](https://lib.haxe.org/p/hx_webserver)
   - [hxdefold `1.4.5`](https://lib.haxe.org/p/hxdefold)
   - [urals-widget-web `0.0.1`](https://lib.haxe.org/p/urals-widget-web)
   - [urals-view-web `0.0.1`](https://lib.haxe.org/p/urals-view-web)
   - [result-tools `0.0.1`](https://lib.haxe.org/p/result-tools)
   - [option-tools `0.0.2`](https://lib.haxe.org/p/option-tools)
   - [intl `0.9.1`](https://lib.haxe.org/p/intl)
   - [haxeui-pdcurses `1.6.0`](https://lib.haxe.org/p/haxeui-pdcurses)
   - [haxeui-heaps `1.6.0`](https://lib.haxe.org/p/haxeui-heaps)
   - [hxWidgets `1.11.0`](https://lib.haxe.org/p/hxWidgets)
   - [haxeui-winforms `1.6.0`](https://lib.haxe.org/p/haxeui-winforms)
   - [haxeui-pixijs `1.6.0`](https://lib.haxe.org/p/haxeui-pixijs)
   - [haxeui-openfl `1.6.0`](https://lib.haxe.org/p/haxeui-openfl)
   - [haxeui-nme `1.6.0`](https://lib.haxe.org/p/haxeui-nme)
   - [haxeui-kha `1.6.0`](https://lib.haxe.org/p/haxeui-kha)
   - [haxeui-flixel `1.6.0`](https://lib.haxe.org/p/haxeui-flixel)
   - [haxeui-hxwidgets `1.6.0`](https://lib.haxe.org/p/haxeui-hxwidgets)
   - [haxeui-html5 `1.6.0`](https://lib.haxe.org/p/haxeui-html5)
   - [haxeui-core `1.6.0`](https://lib.haxe.org/p/haxeui-core)
   - [glory `2.2.2`](https://lib.haxe.org/p/glory)
   - [flixel-window `1.1.5`](https://lib.haxe.org/p/flixel-window)
   - [hxnodejs-serialport `1.4.0`](https://lib.haxe.org/p/hxnodejs-serialport)

**Comment by skial** [comment]
- [ ] `[community]` OpenFL devlog: NativeWindow, Lime’s Haxe and C++ bridge, and improved cleanup [article](https://joshblog.net/2023/openfl-devlog-nativewindow-limes-haxe-and-c-bridge-and-improved-cleanup/) by Josh Tynjala.

**Comment by skial** [comment]
- [ ] `[community]` Triggering Haxe functions from within OpenFL TextField HTML links [article](https://www.confidant.ca/blog/2023/triggering-haxe-functions-from-within-openfl-textfield-html-links/) by Allan Dowdeswell.

**Comment by skial** [comment]
- [ ] `[community/devlog]` Fraymakers EA Update `0.5.9` - Optimization and Custom Content Error Detection [post](https://store.steampowered.com/news/app/1420350/view/3689053519328946312).

**Comment by skial** [comment]
- [ ] `[video]` Building a simple game in Armory 3D - Beginners tutorial [part 2](https://www.youtube.com/watch?v=TUC5g7xStHI).

**Comment by skial** [comment]
- [ ] `[open source]` [deepnightKISS `git`](https://github.com/jobf/deepnightKISS) - KISS approach generic 2D game base on Haxe Lime with peote-view graphics.

**Comment by skial** [comment]
- [ ] `[open source]` [glot `git`](https://github.com/ohmrun/glot) - Haxe AST without the positional parameters, should eventually be self describing.

**Comment by skial** [comment]
- [ ] `[open source]` [cs2hx `git`](https://github.com/RobertBorghese/cs2hx) - C# DLL to Haxe externs plus automatic Haxe compile-time definitions. :star:

**Comment by skial** [comment]
- [ ] `[open source]` [reflaxe.Wren `git`](https://github.com/davidbruce/reflaxe.Wren) - A Wren target for Haxe written with the Reflaxe library. :star:

**Comment by skial** [comment]
- [ ] `[releases]` Nuclear Blaze is coming to Switch, PS4 and XBox in [a few days](https://twitter.com/deepnightfr/status/1650455795845169152)!

**Comment by kLabz** [comment]
* [ ] `[open source]` [Haxe Manager `git`](https://github.com/kLabz/haxe-manager) - Manage Haxe compiler versions, now for linux and macOS

**Comment by Beeblerox** [comment]
- [ ] Dune: Spice Wars | [April Development Update](https://steamcommunity.com/games/1605220/announcements/detail/3648515960079013383)

**Comment by Beeblerox** [comment]
- [ ] 💀[Perilous Icons 1.1.0](https://www.patreon.com/posts/81804599) by [Oleg Dolya](https://twitter.com/watawatabou/status/1649134682510876674)

**Comment by Beeblerox** [comment]
- [ ] [Falling tower elevator effect](https://twitter.com/squuuidly/status/1651242144454123524) quick video from Renaine

**Comment by Beeblerox** [comment]
- [ ] New Starfox 🐸🐰🦅🦊 remake updates by SnkyGames:
    * Working on redoing the objects with precise hitbox generation. [Here's a moaiship liftoff](https://twitter.com/SnkyGames/status/1649785294793715719)
    * Physics can be a nightmare, I've been playing with the rigid bodies, when are they allowed to sleep? [Here we can see the pillar wobble](https://twitter.com/SnkyGames/status/1650564189595787275)
    * Added detection for the [mouse position in 3D space and retrieving the Normal vector](https://twitter.com/SnkyGames/status/1651181896838119425) of a given mesh in the scene

**Comment by Beeblerox** [comment]
- [ ] [Cooking](https://twitter.com/indigoUan/status/1649805178630033409) and [balles](https://twitter.com/indigoUan/status/1650808164873392133) by indigoUan

**Comment by Beeblerox** [comment]
- [ ] [Layouting](https://twitter.com/SyoPic/status/1649802978981806080) from Jitter Sandbox

**Comment by Beeblerox** [comment]
- [ ] Nuclear Blaze by [Deepnight Games](https://twitter.com/deepnightfr/status/1650455795845169152) is finally coming to Switch, PS4 and XBox on April 28th

**Comment by Beeblerox** [comment]
- [ ] Freestyle Engine Dev updates by Rapper GF | Freestyle Dev:
    * [Freestyle Engine Dev Build 009](https://twitter.com/Rapper_GF_Dev/status/1650761116480425984): Metadata for songs are yaml file structures which parse faster than json and are much easier to read and edit
    * [Freestyle Engine Dev Build](https://twitter.com/Rapper_GF_Dev/status/1650761665388896257): 0010 : Crash Handling! The engine will attempt to continue when encountering errors if multiple pop up the engine can become unstable

**Comment by Beeblerox** [comment]
- [ ] ZwodahS is [redoing some UI](https://discord.com/channels/162395145352904705/162664383082790912/1098599599754707105) for their game. And [UI is (mostly) hooked in](https://discord.com/channels/162395145352904705/162664383082790912/1099914234726469663)

**Comment by Beeblerox** [comment]
- [ ] [m0rkeulv](https://discord.com/channels/162395145352904705/1096816414880440560/1099748897724846160) made [the first beta 2023.1 release](https://github.com/HaxeFoundation/intellij-haxe/releases/tag/pre-release%2F202304231701) of Haxe IntelliJ plugin

**Comment by Beeblerox** [comment]
- [ ] The upcoming LDtk 1.3.0 features the Multi-Worlds option as a preview. [Full patchnotes](https://ldtk.io/release-notes/next/) and [upcoming JSON changes](https://ldtk.io/json/next/#overview)

**Comment by Beeblerox** [comment]
- [ ] [Armory 3D can be like Unreal engine](https://www.youtube.com/watch?v=du-CTKcZ7jU)

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` `__hxcpp_parse_int` now parses hex numbers with wrapping as before [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1053).

**Comment by skial** [comment]
- [ ] `[core]` `Void` as value error disappears on second compilation [issue](https://github.com/HaxeFoundation/haxe/issues/11184).

**Comment by skial** [comment]
- [ ] `[video]` Vallas Backrooms [video](https://www.youtube.com/watch?v=E_PswylUeoc) by Merrak.

**Comment by Beeblerox** [comment]
- [ ] LDtk, the free level editor [has reached version 1.3.0](https://twitter.com/deepnightfr/status/1651493471205638145)! New multi-worlds feature and countless quality of life upgrades everywhere 🎉 [Grab it for free](https://ldtk.io)
