### ISSUE TITLE
Haxe Roundup 676

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1082]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by deepnight** [comment]
- [ ] LDtk 1.3 released: multi-worlds, better auto-layers and lots of quality of life changes [changelog](https://ldtk.io/release-notes/)

**Comment by 0b1kn00b** [comment]
- [ ] Predictable constructors in Haxe as it is [article](https://ohmrun.hashnode.dev/more-on-constructors-in-haxe)

**Comment by skial** [comment]
- [ ] `[community]` Haxe `4.3.1` has been [released](https://github.com/HaxeFoundation/haxe/releases/tag/4.3.1)! Available on haxe.org to [download](https://haxe.org/download/version/4.3.1/). :star2:

**Comment by skial** [comment]
- [ ] `[core]` Allow non constant "inline" var init with `-D no-inline` [pull request](https://github.com/HaxeFoundation/haxe/pull/11192).

**Comment by skial** [comment]
- [ ] `[core]` Call typing vs. expected enums [issue](https://github.com/HaxeFoundation/haxe/issues/11187).

**Comment by skial** [comment]
- [ ] `[core/community?`] Hxcpp `4.3.7` has been [released](https://github.com/HaxeFoundation/hxcpp/releases/tag/v4.3.7).

**Comment by Aurel300** [comment]
- [ ] (LDJam 53) [Why Deliver Y?](https://aurel300.itch.io/why-deliver-y), a vaguely noir puzzle game

**Comment by skial** [comment]
- [ ] `[evolution]` Support the `throws` statement [proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/110).

**Comment by skial** [comment]
- [ ] `[LDJam 53]` [FedUp](https://community.haxe.org/t/ldjam-fedup-a-flying-delivery-game/3943?u=skial) - A Flying Delivery game by Jeff Ward.

**Comment by skial** [comment]
- [ ] `[core/macro]` Possible bug in `@:autoBuild` meta order [issue](https://github.com/HaxeFoundation/haxe/issues/11194).

**Comment by skial** [comment]
- [ ] `[core/eval]` local static var - Instance constructor not found: `haxe.ds._Map.Map_Impl_` [issue](https://github.com/HaxeFoundation/haxe/issues/11193).

**Comment by skial** [comment]
- [ ] `[LDJam 53]`  [Dressed Delivery](https://ldjam.com/events/ludum-dare/53/dressed-delivery) - Three women embark on a journey to find a place in life.

**Comment by skial** [comment]
- `[LD53]`
  - [ ] [Delivering Parcelman](https://zwodahs.itch.io/ld53-delivering-parcelman) - Your good friend Travelling Salesman has introduce you to a Parcel delivery job. Will you do your job well or will you get fired?
  - [ ] [Flipping Finches](https://aeveis.itch.io/flipping-finches) - You are a finch known as the flip master. You always flip when turning in the air. You need to deliver a parcel. Hopefully you can deliver it intact!
  - [ ] [Haul and Pray](https://ldjam.com/events/ludum-dare/53/haul-and-pray) - _“I am only accepted as long as I am useful. If I don’t earn my keep, if I don’t constantly prove my worth, I might as well just disappear. And wouldn’t that be better for everyone?”_

**Comment by skial** [comment]
- [ ] `[open source]` [haxe-engineio `git`](https://github.com/snwhd/haxe-engineio) - A Haxe Engine.io implementation.
- [ ] `[open source]` [haxe-socketio `git`](https://github.com/snwhd/haxe-socketio) - A Haxe Socket.io implementation.

**Comment by skial** [comment]
- [ ] `[core/macro]` `EFieldKind` messes with macro pattern matching [issue](https://github.com/HaxeFoundation/haxe/issues/11198).

**Comment by skial** [comment]
- libs
  - [flxgif `1.0.2`](https://lib.haxe.org/p/flxgif)
  - [tink_syntaxhub `0.6.1`](https://lib.haxe.org/p/tink_syntaxhub)
  - [colyseus-websocket `1.0.12`](https://lib.haxe.org/p/colyseus-websocket)
  - [haxelib `4.1.0`](https://lib.haxe.org/p/haxelib)
  - [urals-renderer-web-js `0.1.2`](https://lib.haxe.org/p/urals-renderer-web-js)
  - [urals-renderer-web `0.2.3`](https://lib.haxe.org/p/urals-renderer-web)
  - [neutralinojs `1.0.0`](https://lib.haxe.org/p/neutralinojs)
  - [tostring `0.2.0`](https://lib.haxe.org/p/tostring)
  - [haxe-nvim `1.1.1`](https://lib.haxe.org/p/haxe-nvim)
  - [res `0.1.1-alpha`](https://lib.haxe.org/p/res)
  - [nwjs `1.4.0`](https://lib.haxe.org/p/nwjs)
  - [hxwren `1.1.1`](https://lib.haxe.org/p/hxwren)
  - [hxlua `1.5.1`](https://lib.haxe.org/p/hxlua)
  - [minecraft-api `0.3.82-alpha`](https://lib.haxe.org/p/minecraft-api)
  - [hxdiscord_rpc `1.1.0`](https://lib.haxe.org/p/hxdiscord_rpc)
  - [TeaScript `1.0.0`](https://lib.haxe.org/p/TeaScript)
  - [urals-storage `0.3.1`](https://lib.haxe.org/p/urals-storage)
  - [urals-widget-web `0.1.1`](https://lib.haxe.org/p/urals-widget-web)
  - [urals-id-renderer `0.0.1`](https://lib.haxe.org/p/urals-id-renderer)
  - [parcl `0.1.1`](https://lib.haxe.org/p/parcl)
  - [bootstrap_bundle `2.1.3`](https://lib.haxe.org/p/bootstrap_bundle)

**Comment by skial** [comment]
- [ ] `[community/releases?]` Northgard - Trials of Odin Update [Out Now](https://store.steampowered.com/news/app/466560/view/3731837715792008791)!

**Comment by skial** [comment]
- [ ] `[community/releases]` Dead Cells - Our 34th Dead Cells update "Clean Cut" is [now live](https://store.steampowered.com/news/app/588650/view/3704816660869715038)!

**Comment by skial** [comment]
- [ ] `[community]` Official Haxe `4.3.1` [release announcement](https://community.haxe.org/t/haxe-4-3-1-released/3939?u=skial). :star:

**Comment by skial** [comment]
- [ ] `[video]` Reacting to GameFromScratch's thoughts on HaxeFlixel `5.0.0` [video](https://www.youtube.com/watch?v=5qHzABNZvE4) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] `[video]` No More Lost Progress: Save Games in RPG Playground [video](https://www.youtube.com/watch?v=3j3iSg6suDA).

**Comment by skial** [comment]
- [ ] `[video]` Northgard | Trials of Odin | Official [trailer](https://www.youtube.com/watch?v=tdQuJnRrVww).

**Comment by skial** [comment]
- [ ] `[open source]` [stx_parse_ini `git`](https://github.com/ohmrun/stx_parse_ini) - Ini file parser in stx_parse.

**Comment by skial** [comment]
- [ ] `[core/macro]` LSP/macro type reification: Defining 0-ary function as a type parameter with a reified return type messes up LSP outline [issue](https://github.com/HaxeFoundation/haxe/issues/11199).

**Comment by skial** [comment]
- [ ] `[open source]` LDtk [`1.3.1`](https://github.com/deepnight/ldtk/releases/tag/v1.3.1) and [`1.3.2`](https://github.com/deepnight/ldtk/releases/tag/v1.3.2) have been released.

**Comment by PeyTy** [comment]
676 roundups in a row. That's crazy! How you are this consistent?

**Comment by skial** [comment]
> 676 roundups in a row. That's crazy! How you are this consistent?

I _really_ don't have a clue :shrug:
