### ISSUE TITLE
Haxe Roundup 677

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1084]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[ld53]` [Bundle Beeline](https://squidly.itch.io/bundle-beeline)  - Deliver packages throughout Bundle’s shift to her valuable Daintree Delivery customers! But be careful, as the shift continues, expected delivery times will speed up! And don’t even think about dropping the merchandise!

**Comment by skial** [comment]
- [ ] `[ld53]` [Knotty Network](https://ldjam.com/events/ludum-dare/53/knotty-network) - The internet may just be a series of tubes, but someone has to make sure the tubes go to the right place! Spin and swap the pieces on the board to build connections from the messages at the bottom of the board to the recipients waiting at the top.

**Comment by skial** [comment]
- [ ] `[core]` No documentation / goto data with safe nav access [issue](https://github.com/HaxeFoundation/haxe/issues/11205).

**Comment by skial** [comment]
- [ ] `[core/ide]` False `This cast has no effect, but some of its sub-expressions` report [issue](https://github.com/HaxeFoundation/haxe/issues/11203).

**Comment by skial** [comment]
- [ ] `[core/interp]` `MainLoop.add` not repeating [issue](https://github.com/HaxeFoundation/haxe/issues/11202).

**Comment by skial** [comment]
- [ ] `[events/upcoming]` The next Haxe Roundup _Roundup_ [event](https://discord.com/events/162395145352904705/1104182147406909522) is scheduled for 14th May at 18:30 on Discord.

**Comment by skial** [comment]
- [ ] `[open source]` [linalg `git`](https://github.com/marinight/linalg-haxe) - A cozy linear algebra library for Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [self-vn-engine `git`](https://github.com/mitaka78/self-vn-engine) - A dialogue parser & a dialogue system with choices.

**Comment by skial** [comment]
- [ ] `[releases]` Bundle Beeline has gotten its offical post LD53 jam release onto [Newgrounds](https://www.newgrounds.com/portal/view/883682) by [Squidly](https://twitter.com/squuuidly/status/1656064637400412160).

**Comment by skial** [comment]
- [ ] `[core]` Matching on enum abstract around another enum gives `Incompatible pattern` error [fixed](https://github.com/HaxeFoundation/haxe/issues/11213).

**Comment by skial** [comment]
- [ ] `[core]` Multiple `#else` blocks allowed [issue](https://github.com/HaxeFoundation/haxe/issues/11208).

**Comment by skial** [comment]
- [ ] `[community]` Porting LD53 Game FedUp to Heaps from Pixijs [thoughts & questions](https://community.haxe.org/t/ldjam-fedup-a-flying-delivery-game/3943/2).

**Comment by skial** [comment]
- [ ] libs
   - [ldtk-haxe-api `1.3.3-rc.1`](https://lib.haxe.org/p/ldtk-haxe-api)
   - [newgrounds `2.0.2`](https://lib.haxe.org/p/newgrounds)
   - [tostring `0.2.2`](https://lib.haxe.org/p/tostring)
   - [flixel `5.3.1`](https://lib.haxe.org/p/flixel)
   - [haxe-sshclient `0.1.1`](https://lib.haxe.org/p/haxe-sshclient)
   - [haxe-files `4.0.3`](https://lib.haxe.org/p/haxe-files)
   - [haxe-concurrent `5.1.3`](https://lib.haxe.org/p/haxe-concurrent)
   - [haxe-strings `7.0.3`](https://lib.haxe.org/p/haxe-strings)
   - [linalg `0.0.2`](https://lib.haxe.org/p/linalg)
   - [haxe-doctest `3.2.2`](https://lib.haxe.org/p/haxe-doctest)
   - [mc2it_theme `4.0.2`](https://lib.haxe.org/p/mc2it_theme)
   - [pirhana `1.1.26`](https://lib.haxe.org/p/pirhana)
   - [bootstrap_bundle `2.1.4`](https://lib.haxe.org/p/bootstrap_bundle)
   - [colyseus `0.15.0`](https://lib.haxe.org/p/colyseus)

**Comment by skial** [comment]
- [ ] `[closed source/haxe discord]` [Tyler](https://discord.com/channels/162395145352904705/1081002322475360377/1105663799974973481) is working on a card based auto battler. :crossed_swords: :shield:

**Comment by skial** [comment]
- [ ] `[video]` A-Star Pathfinding Algorithm | Haxe Game Engine (Heaps) [video](https://www.youtube.com/watch?v=TP1xvGv1Gmc).

**Comment by skial** [comment]
- [ ] `[video]` Rogue of Vallas Conquered Lands Revision [video](https://www.youtube.com/watch?v=LCX1jUqms8U).

**Comment by skial** [comment]
- [ ] `[video]` _"My update videos are getting out of control"_ [video](https://www.youtube.com/watch?v=t_bi-u5R6zo) by Zanzlanz.

**Comment by skial** [comment]
- [ ] `[video]` Armory 3D update for May 2023 [video](https://www.youtube.com/watch?v=SyF2IW7wOgY).

**Comment by skial** [comment]
- [ ] `[open source]` [zui-theme-editor `git`](https://github.com/tong/zui-theme-editor).

**Comment by Beeblerox** [comment]
- [ ] Syo is [working on a new demo level](https://twitter.com/SyoPic/status/1654769621692547073) for Jitter Sandbox called "Signalman"

**Comment by Beeblerox** [comment]
- [ ] [A peek at early prototype](https://twitter.com/ohsat_games/status/1654993310690205696) for next game by Ando

**Comment by Beeblerox** [comment]
- [ ] Couple of quick videos from Starfox 🐸🐰🦅🦊 remake by SnkyGames:
    * [Fresh start on 10 Pro N](https://twitter.com/SnkyGames/status/1654433191208337409), all seems well!
    * [Updating objects](https://twitter.com/SnkyGames/status/1655978018018394113) to suit engine enhancements

**Comment by Beeblerox** [comment]
- [ ] [Ibalukhagh... er... Khamlir](https://twitter.com/watawatabou/status/1655581998587555843) by Oleg Dolya

**Comment by Beeblerox** [comment]
- [ ] New Haxe IntelliJ plugin [beta release](https://github.com/HaxeFoundation/intellij-haxe/releases/tag/pre-release%2F202305072104) by [m0rkeulv](https://discord.com/channels/162395145352904705/1096816414880440560/1104880085389029549): added support for parsing some of the newer Haxe 4.3 features, note that its only parser support, the semantic checks still needs to be updated

**Comment by Beeblerox** [comment]
- [ ] [rynite](https://discord.com/channels/162395145352904705/1104478704903663686/1104478704903663686) has started working on [learnopengl-haxelime](https://github.com/bwkam/learnopengl-haxelime)

**Comment by Beeblerox** [comment]
- [ ] [Procedural serum brewing system](https://discord.com/channels/162395145352904705/1021928209308205177/1104075302830882828) in Minicology by Isaac Denner

**Comment by Beeblerox** [comment]
- [ ] [LDtk 1.3.3 update](https://discord.com/channels/761549092677353513/761550416504684545/1105824523783245934):
    * Added custom UI icons for IntGrid layer values.
    * Added custom min/max size limits to entities when then are resizables.
    * If you change the "grid size" of a Layer or a Tileset, LDtk will now try to remap all existing data to this new grid size (if that's possible).
    * Added an option to allow/disallow tiles stacking in the Rules Assistant window.

**Comment by skial** [comment]
- [ ] `[open source]` [pml_xml `git`](https://github.com/ohmrun/pml_xml) - Pml <-> Xml transformations.

**Comment by skial** [comment]
- [ ] Remove proposal https://github.com/HaxeFoundation/haxe-evolution/pull/110
