### ISSUE TITLE
Haxe Roundup 678

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1086]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[community/devlog]` Reflaxe/C++ - CallStack - [Devlog `#1`](https://srd.deno.dev/blog/reflaxe-cpp/1/) by Robert.

**Comment by skial** [comment]
- [ ] `[closed source]` _"Remember that falling tower? Here it is coming out the other end..."_ from the latest [Renaine preview](https://twitter.com/squuuidly/status/1656678529780809728).

**Comment by skial** [comment]
- [ ] `[closed source/haxe discord]` [Bubble Boy](https://discord.com/channels/162395145352904705/162664383082790912/1107792804656197682) has ladders!

**Comment by skial** [comment]
- [ ] `[core]` Getting invalid "Potential typo detected" warning [issue](https://github.com/HaxeFoundation/haxe/issues/11219).

**Comment by skial** [comment]
- [ ] `[community]` Super simple soft-body physics [prototype](https://community.haxe.org/t/super-simple-soft-body-physics-prototype/3951?u=skial) by Jeff Ward.

**Comment by skial** [comment]
- [ ] `[core]` Broken completion in display test case [issue](https://github.com/HaxeFoundation/haxe/issues/11225).

**Comment by skial** [comment]
- [ ] `[core]` ReferenceError / Instance prototype not found [issue](https://github.com/HaxeFoundation/haxe/issues/11222).

**Comment by skial** [comment]
- [ ] `[core]` Bring back forced inline [merged](https://github.com/HaxeFoundation/haxe/pull/11217).

**Comment by skial** [comment]
- [ ] `[open source/haxe discord]` The Hashlink JIT can now print [Hello World](https://discord.com/channels/162395145352904705/162664383082790912/1107965696069087292) running on ARM.

**Comment by skial** [comment]
- [ ] `[evolution]` Support Typed metadata [proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/111).

**Comment by skial** [comment]
- [ ] libs
   - [dell `0.1.0`](https://lib.haxe.org/p/dell)
   - [typepacker `1.3.1`](https://lib.haxe.org/p/typepacker)
   - [phpoffice `0.3.1`](https://lib.haxe.org/p/phpoffice)
   - [hxwren `1.1.2`](https://lib.haxe.org/p/hxwren)
   - [hxlua `1.6.0`](https://lib.haxe.org/p/hxlua)
   - [hxdiscord_rpc `1.1.1`](https://lib.haxe.org/p/hxdiscord_rpc)
   - [graphql-server `0.2.3`](https://lib.haxe.org/p/graphql-server)
   - [colyseus `0.15.1`](https://lib.haxe.org/p/colyseus)
   - [hgsl `0.3.0`](https://lib.haxe.org/p/hgsl)
   - [ase `2.0.2`](https://lib.haxe.org/p/ase)

**Comment by skial** [comment]
- [ ] `[community]` Dead Cells: The Rogue-Lite Board Game [Kickstarter](https://www.kickstarter.com/projects/scorpionmasque/dead-cells-the-rogue-lite-board-game) is live!.

**Comment by Beeblerox** [comment]
- [ ] polybiusproxy [fixed textures](https://twitter.com/polyproxy/status/1657064895987187713) in their Haxe game engine - Endor

**Comment by Beeblerox** [comment]
- [ ] [Announcing Next Update](https://steamcommunity.com/games/2020460/announcements/detail/6247100012249556027) for Bring It On!: Catacombs! by [Axol Studio](https://twitter.com/AxolStudio/status/1657413848222121985)

**Comment by Beeblerox** [comment]
- [ ] Deepnight Games are [putting a lot of effort](https://twitter.com/deepnightfr/status/1657355565842984961) into elevating Tenjutsu to meet their own expectations

**Comment by Beeblerox** [comment]
- [ ] Team Fray! are [working on the next patch](https://twitter.com/FraymakersGame/status/1656484967189450752), including rebalanced characters, 95% of Octodad's sprites done + tons of other improvements

**Comment by Beeblerox** [comment]
- [ ] [Text and doors](https://twitter.com/gogoprog/status/1657833828440834050) from WIP game by Gauthier Billot
- [ ] What is the best way to learn an API? Writing Haxe externs of course! So [Gauthier Billot](https://twitter.com/gogoprog/status/1658771626056458241) created [externs for WebGPU](https://github.com/gogoprog/haxe-webgpu)

**Comment by Beeblerox** [comment]
- [ ] [Matthijs Kamstra](https://twitter.com/MatthijsKamstra/status/1658059789350387712) has updated [the haxesys repository](https://github.com/MatthijsKamstra/haxesys) with fresh examples

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source/haxe discord]` [Bubble Boy](https://discord.com/channels/162395145352904705/162664383082790912/1107792804656197682) has ladders!

- [ ] [Now you can also shoot bubbles up and down](https://twitter.com/ohsat_games/status/1658490405510615047)
- [ ] [Making progress with transitions and enemies!](https://twitter.com/ohsat_games/status/1658896498837405696)

**Comment by Beeblerox** [comment]
- [ ] [Shelja](https://twitter.com/indigoUan/status/1658557725972877331) by IndigoUan

**Comment by Beeblerox** [comment]
- [ ] Jérémy Faivre is [making progress](https://discord.com/channels/162395145352904705/1081002322475360377/1107054602060316783) in the lights+mirror system, which also [works with 2 lights as well](https://discord.com/channels/162395145352904705/1081002322475360377/1107054972115365898) (and with hot reload from LDtk)

**Comment by Beeblerox** [comment]
- [ ] [Vortex](https://discord.com/channels/162395145352904705/1108515973012672583/1108515973012672583) is working on [hxpy](https://github.com/Vortex2Oblivion/hxpy) which allows users to run python code from within a haxe application or from a file

**Comment by Beeblerox** [comment]
- [ ] [Portal-pushing platforms](https://twitter.com/Rob1221dev/status/1657022816779395072) by Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] [saharan](https://twitter.com/shr_id/status/1657019586804424704) has opened source for [Chill](https://oimo.io/works/chill/) simulation
- [ ] [saharan](https://twitter.com/shr_id/status/1656964332264226817) also has plan to update [HGSL](https://github.com/saharan/HGSL)

**Comment by skial** [comment]
- [ ] `[core]` `Syntax.code`: remove double curly braces escaping [pull request](https://github.com/HaxeFoundation/haxe/pull/11231).
