### ISSUE TITLE
Haxe Roundup 680

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1091]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` `??` precedence [issue](https://github.com/HaxeFoundation/haxe/issues/11239).

**Comment by skial** [comment]
- [ ] `[core]` Abstract `@:op(a == b)` not working on Haxe `4.3` [issue](https://github.com/HaxeFoundation/haxe/issues/11240).

**Comment by skial** [comment]
- [ ] libs
   - [sasl `0.1.0`](https://lib.haxe.org/p/sasl)
   - [neutralinojs `1.1.0`](https://lib.haxe.org/p/neutralinojs)
   - [jans `0.2.0`](https://lib.haxe.org/p/jans)
   - [omdb `1.2.4`](https://lib.haxe.org/p/omdb)
   - [SScript `3.0.0`](https://lib.haxe.org/p/SScript)
   - [cxx2hx `1.0.1`](https://lib.haxe.org/p/cxx2hx)
   - [hx_webserver `0.0.3`](https://lib.haxe.org/p/hx_webserver)
   - [tweenxcore `1.1.0`](https://lib.haxe.org/p/tweenxcore)

**Comment by skial** [comment]
- [ ] `[community]` Kid Bubblegum [devlog `#2`](https://www.ohsat.com/post/kid-bubblegum-devlog/kid-bubblegum-devlog-2/).

**Comment by skial** [comment]
- [ ] `[closed source]` [Jurien Meerlo](https://twitter.com/codescapade/status/1663293414723530752) has _"added gravity activated moving walls. Need to work on the procgen placement logic a bit. They can spawn in not ideal places at the moment."_

**Comment by skial** [comment]
- [ ] `[closed source]` [SRDude](https://twitter.com/SumRndmDde/status/1662868695318769666) presents _"to you the first(?) Gameboy Advance game created in Haxe."_

**Comment by Beeblerox** [comment]
- [ ] New quick videos from [Renaine](https://store.steampowered.com/app/662340/Renaine/):
    * [Call and response](https://twitter.com/RenaineGame/status/1661767746298818563)
    * [testing out some stuff](https://twitter.com/squuuidly/status/1663215174386425857)
    * [I think I may have missed the wall](https://twitter.com/squuuidly/status/1663568887634444288)

**Comment by Beeblerox** [comment]
- [ ] LDtk – [Level Designer Toolkit in 2023LDtk](https://gamefromscratch.com/ldtk-level-designer-toolkit-in-2023/) by [Game From Scratch](https://twitter.com/gamefromscratch/status/1662107411597885443)

**Comment by Beeblerox** [comment]
- [ ] Return Portal, [Robert Alvarez](https://twitter.com/Rob1221dev/status/1663564269189840896) newest puzzle platformer, is now [playable on Poki](https://poki.com/en/g/return-portal)

**Comment by Beeblerox** [comment]
- [ ] The recreation/port of "Dojo of Death" to HaxeFlixel is nearing completion! [George Harpwood](https://twitter.com/GeorgeHarpwood/status/1663849521552424960) is currently adding the final touches

**Comment by Beeblerox** [comment]
- [ ] [Pacing and balance](https://twitter.com/clydegamedev/status/1663345972121079809) can really transform something from a bunch of systems into a real game. By Clyde for [Into the Necrovale](https://store.steampowered.com/app/1717090/Into_the_Necrovale/)

**Comment by Beeblerox** [comment]
- [ ] Something tells Lars Doucet that [this little psycopath](https://twitter.com/larsiusprime/status/1663629496245710854) is going to become a fan favorite character in Defenders Quest 2

**Comment by Beeblerox** [comment]
- [ ] [Jérémy Faivre](https://twitter.com/jeremyfaivre/status/1663144615183097857) has resumed work on their small jam game from January about harvesting light with mirrors.

**Comment by Beeblerox** [comment]
- [ ] Oleg Dolya [hoped this would look like fir trees...](https://twitter.com/watawatabou/status/1663924004862808067)

**Comment by Beeblerox** [comment]
- [ ] [CUBIC DRIFTER](https://the-untoaster-rebelion.repl.co/pages/originals/cubicdrifter.html) by [! MichaelTheBirthdayRatz](https://discord.com/channels/162395145352904705/1112410251262705704/1112410251262705704)

**Comment by Beeblerox** [comment]
- [ ] IntelliJ Haxe Plugin [1.4.0 Beta build 13](https://github.com/HaxeFoundation/intellij-haxe/releases/tag/pre-release%2F202305280045) (d3d685f5) by [m0rkeulv](https://discord.com/channels/162395145352904705/1096816414880440560/1112705436131541092)

**Comment by Beeblerox** [comment]
- [ ] [ZwodahS](https://discord.com/channels/162395145352904705/1070564912469921906/1112411280725245973) has updated [Crop Rotation](https://zwodahs.itch.io/crop-rotation)

**Comment by Beeblerox** [comment]
- [ ] [stickFlixel](https://www.newgrounds.com/projects/games/4747890/preview/filetype/2) by [Dusky](https://discord.com/channels/162395145352904705/162664383082790912/1111888143264792616)

**Comment by skial** [comment]
- [ ] `[open source]` OpenFL `9.2.2` has been [released](https://github.com/openfl/openfl/releases/tag/9.2.2).
- [ ] `[open source]` Lime `8.0.2` has been [released](https://github.com/openfl/lime/releases/tag/8.0.2).

**Comment by skial** [comment]
- [ ] `[closed source/haxe discord]` [Idenner](https://discord.com/channels/162395145352904705/1021928209308205177/1113547356076519426) has _"been trying to incorporate a bit more procedural animation into my enemies"_ in Minicology.
