### ISSUE TITLE
Haxe Roundup 686

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1103]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[events/upcoming]` The next weeklong [HaxeJam 2023: Summer Jam](https://itch.io/jam/haxejam-2023-summer-jam) is scheduled to start on August 6th by [Logo](https://fosstodon.org/@logo/110669456878920488). :tada:

**Comment by skial** [comment]
- [ ] `[core/jvm]` Resources containing a dash are escaped [fixed](https://github.com/HaxeFoundation/haxe/issues/11275).

**Comment by skial** [comment]
- [ ] `[open source]` Haxe Toolkit `1.4.5` has been [released](https://community.haxe.org/t/haxe-toolkit-support-1-4-0-released-supports-intellij-2023/3983/3?u=skial).

**Comment by skial** [comment]
- [ ] `[core]` Account for sub-types in `ComplexTypeTools.toComplex()` [merged](https://github.com/HaxeFoundation/haxe/pull/11273).

**Comment by skial** [comment]
- [ ] `[core]` Prepare for ocaml5 [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11272).

**Comment by skial** [comment]
- [ ] `[core]` Callback arg type is transformed to Mono with overloads [issue](https://github.com/HaxeFoundation/haxe/issues/11274).

**Comment by skial** [comment]
- [ ] libs
   - [PickHaxe `0.3.0`](https://lib.haxe.org/p/PickHaxe)
   - [mc2it_theme `5.1.1`](https://lib.haxe.org/p/mc2it_theme)
   - [dropecho.ai `1.0.0`](https://lib.haxe.org/p/dropecho.ai)
   - [dropecho.testing `1.1.4`](https://lib.haxe.org/p/dropecho.testing)
   - [dropecho.lib_example `0.10.0`](https://lib.haxe.org/p/dropecho.lib_example)
   - [hxdiscord `0.5.1`](https://lib.haxe.org/p/hxdiscord)

**Comment by skial** [comment]
- [ ] `[releases]` Dune Spice Wars [Patch Notes](https://store.steampowered.com/news/app/1605220/view/3669919470524650644) for `07/07/2023`.

**Comment by skial** [comment]
- [ ] `[open source]` [geometrize-haxe-cli `git`](https://github.com/ErikGaDev/geometrize-haxe-cli) - CLI version of the haxe package [Geometrize Haxe](https://github.com/Tw1ddle/geometrize-haxe) based on the [Geometrize Lib Example](https://github.com/Tw1ddle/geometrize-lib-example).

**Comment by skial** [comment]
- [ ] `[open source]` [stx_lense `git`](https://github.com/ohmrun/stx_lense) - Implementation of bidirectional tree transforms over the PML datastructure.

**Comment by skial** [comment]
- [ ] `[open source]` [spm `git`](https://github.com/SymmetricalOS/spm) - A simple package manager for Linux.

**Comment by skial** [comment]
- [ ] `[closed source]` [Cornell Daly](https://twitter.com/bojjenclon/status/1678554239889469443) _"shows off how the basic crafting system will work"_ in their upcoming game made with Kha.

**Comment by skial** [comment]
- [ ] `[release?]` Decomposing mini-game by [Yutori](https://twitter.com/_yutoring/status/1677988448140136453).

**Comment by skial** [comment]
- [ ] `[closed source]` [Paradeus](https://twitter.com/ParadeusGame/status/1677346746165497856) adds drag and drop animations to their `WIP` indie game.

**Comment by skial** [comment]
- [ ] `[community]` ☠️Perilous Shores `1.6.0` [article](https://www.patreon.com/posts/85733421): archipelagoes, adding and removing towns by [Oleg Dolya](https://twitter.com/watawatabou/status/1677399158687146008).

**Comment by Beeblerox** [comment]
- [ ] short video from [Kid Bubblegum](https://store.steampowered.com/app/2441500/Kid_Bubblegum):
    * [Boat Ride](https://www.youtube.com/shorts/g3b6C0ymiVU) 
    * [Weeeee](https://www.youtube.com/shorts/EFeSuwhFTyY)

**Comment by Beeblerox** [comment]
- [ ] Do you have a small 2D game idea that you want to make into a reality but don't have the programming skills to pull it off? You can [HIRE Tim I Hely](https://twitter.com/SeiferTim/status/1678522112699514884): A highly experienced HaxeFlixel developer!

**Comment by Beeblerox** [comment]
- [ ] When you thought your 2d lighting finally worked as expected, but notice there is [one single situation where it doesn’t](https://twitter.com/jeremyfaivre/status/1677337070463864834). by Jérémy Faivre

**Comment by Beeblerox** [comment]
- [ ] [Dark Clues](https://watabou.itch.io/dark-clues) by [Oleg Dolya](https://twitter.com/watawatabou/status/1679084074827218945) is an attempt to make a roguelike game in 7 days for [7DRL CHALLENGE](https://itch.io/jam/7drl-challenge-2022). Here is some info [about this game](https://watabou.itch.io/dark-clues/devlog/391024/about-this-game)

**Comment by Beeblerox** [comment]
- [ ] Sugar Coding Tips #1 [DYNAMIC FUNCTIONS AND UPDATES](https://twitter.com/sugarcoatedOwO/status/1678894210072600579)

**Comment by Beeblerox** [comment]
- [ ] Damilare Akinlaja is [implementing the Hashlink bytecode interpreter](https://twitter.com/FourEyedWiz/status/1677656310655905792) byte by byte...

**Comment by Beeblerox** [comment]
- [ ] [Defeating enemies and salvage](https://twitter.com/joelgervasi/status/1677785141215744001) the SCRAPS OF LIGHT, these can be used later to create new skills and upgrades

**Comment by Beeblerox** [comment]
- [ ] You can download a [preview build](https://ldtk.io/versions/) of LDtk 1.3.4 right below. via [Sébastien Benard](https://discord.com/channels/761549092677353513/761550416504684545/1126795033094410240). [Changelog](https://ldtk.io/release-notes/next/ )

**Comment by Beeblerox** [comment]
- [ ] New [gamedev blog post](https://loudoweb.fr/texture-atlas/) in french about texture atlases by [Ludovic Bas](https://twitter.com/loudoweb/status/1676901236929437696). Ludovic put some tests made with OpenFL in a big table with data of POT/NPOT textures, ATF compression texture + GZIP and with a slight comparison with Unity.

**Comment by Beeblerox** [comment]
- [ ] [sup0088](https://discord.com/channels/162395145352904705/162664383082790912/1127335376009314335) finished their first haxeflixel game for the gmtk game jam - [Survive The Human!](https://sabe09.itch.io/survive-the-human)

**Comment by Beeblerox** [comment]
- [ ] reesod implemented Bevel Filters in FlxAnimate! Here's the [filter in action](https://discord.com/channels/162395145352904705/162664383082790912/1128150440131964979)

**Comment by Beeblerox** [comment]
- [ ] [Vadym Diachenko](https://discord.com/channels/162395145352904705/1121417972238536855/1121417972238536855) aka YellowAfterlife presented [a cleaner-looking C# generator](https://github.com/YAL-Haxe/sillysharp)
