### ISSUE TITLE
Haxe Roundup 688

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1107]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[open source/genes]` Support custom enum discriminator [merged](https://github.com/benmerckx/genes/pull/70).

**Comment by skial** [comment]
- [ ] `[core]`  No hover/definition for overload call [issue](https://github.com/HaxeFoundation/haxe/issues/11285).

**Comment by skial** [comment]
- [ ] `[core]`  Named inline functions get a single implementation for different classes if assigned to an object [issue](https://github.com/HaxeFoundation/haxe/issues/11283).

**Comment by skial** [comment]
- [ ] libs
   - [sfs2x-api-haxe `0.0.1`](https://lib.haxe.org/p/sfs2x-api-haxe)
   - [SScript `3.0.2`](https://lib.haxe.org/p/SScript)
   - [genes `0.4.9`](https://lib.haxe.org/p/genes)
   - [MinecraftClient `0.0.1`](https://lib.haxe.org/p/MinecraftClient)

**Comment by skial** [comment]
- [ ] `[community/devlog]` Character 5 Reveal + Fraymakers at Super Smash Con and PAX West!! - July 2023 [Progress Update](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3867123).

**Comment by skial** [comment]
- [ ] `[releases]` Dead Cells: Return to Castlevania Soundtrack [available now](https://store.steampowered.com/news/app/588650/view/3641773965991289345) on Steam!

**Comment by skial** [comment]
- [ ] `[community/devlog]` Minicology `0.10.7` [patch notes](https://store.steampowered.com/news/app/1471700/view/3642899865907088510) - Refinery live in overworld, melee buffs & crashfixes.

**Comment by skial** [comment]
- [ ] `[open source]` [esb-bundle-sqlite `git`](https://github.com/core-haxe/esb-bundle-sqlite)
- [ ] `[open source]` [esb-bundle-xlsx `git`](https://github.com/core-haxe/esb-bundle-xlsx)
- [ ] `[open source]` [esb-bundle-deepl `git`](https://github.com/core-haxe/esb-bundle-deepl)
- [ ] `[open source]` [esb-bundle-chatgpt `git`](https://github.com/core-haxe/esb-bundle-chatgpt)

**Comment by skial** [comment]
- [ ] `[open source]` [heappo `git`](https://github.com/NeverHeaps/heappo) - Graphical User Interface Framework.

**Comment by skial** [comment]
- [ ] `[open source]` [why-search-syntax `git`](https://github.com/why-haxe/why-search-syntax/tree/master)

**Comment by skial** [comment]
- [ ] `[open source]` [kick-connector `git`](https://github.com/logo4poop/kick-connector) - Replaces Kick Chat with one that also bridges Twitch.

**Comment by skial** [comment]
- [ ] `[events/upcoming]` The next Haxe Roundup _**Roundup**_ [Discord event](https://discord.com/events/162395145352904705/1132753746150035486) is scheduled for August 6th.

**Comment by Beeblerox** [comment]
- [ ] [Clones copy your inputs](https://twitter.com/Rob1221dev/status/1682045243145981952), not your position. By Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] [Movement is a game mechanic](https://twitter.com/SyoPic/status/1682131729270689794) in Jitter Sandbox

**Comment by Beeblerox** [comment]
- [ ] 🔑[House Plan Generator](https://www.patreon.com/posts/86436420) by [Oleg Dolya](https://twitter.com/watawatabou/status/1682396620724269060)

**Comment by Beeblerox** [comment]
- [ ] New quick videos from Kid Bubblegum by Ando:
    * [Kick butt and chew bubblegum](https://twitter.com/ohsat_games/status/1682453377106563088)
    * Bubblegum will [let you climb anything](https://twitter.com/ohsat_games/status/1682819487416954881)
    * [Blow bubbles](https://twitter.com/ohsat_games/status/1683538407660634138)

**Comment by Beeblerox** [comment]
- [ ] [ChatGPT spittin FACTS](https://twitter.com/HaxeFlixel/status/1682461760429719552) (except for the part about tint, lol)

**Comment by Beeblerox** [comment]
- [ ] [Tim’s Tips `#1`: Texture Packing Sprites](https://axolstudio.com/articles/2023-07-23-tims-tips-1-texture-packing-sprites/) by [Tim I Hely](https://twitter.com/SeiferTim/status/1683227060926283778)

**Comment by Beeblerox** [comment]
- [ ] New GIFs from Tenjutsu by Sébastien Benard:
    * [A kungfu-roguelite](https://twitter.com/deepnightfr/status/1682675863245017089) that plays just like in a Jackie Chan or John Wick movie
    * [Working on a rogue-fu game](https://twitter.com/deepnightfr/status/1682789814163087361)

**Comment by Beeblerox** [comment]
- [ ] [Explore with multiple perspectives](https://twitter.com/joelgervasi/status/1682762471117934593) in Scraps of Light

**Comment by Beeblerox** [comment]
- [ ] [Run a command via a Shell](https://twitter.com/cedxbelin/status/1683528801462960141): Java vs Haxe (but this could also apply to NodeJS or PHP).

**Comment by Beeblerox** [comment]
- [ ] [new jump animation](https://twitter.com/SomeRanDev/status/1684308971174199298) by SomeRanDev

**Comment by Beeblerox** [comment]
- [ ] [A cozy little library area](https://twitter.com/clydegamedev/status/1684360317386752000) in [Into the Necrovale](https://store.steampowered.com/app/1717090/Into_the_Necrovale/)

**Comment by Beeblerox** [comment]
- [ ] [Yeoman generator for Heaps](https://github.com/nevergarden/generator-heaps) by [Nevergarden](https://discord.com/channels/162395145352904705/1133561981589278761/1133561981589278761)

**Comment by Beeblerox** [comment]
- [ ] ddmills [added a destruction system](https://discord.com/channels/162395145352904705/1021250535405404170/1133397187427061871) in Wild West Roguelike, so you can blow stuff up

**Comment by Beeblerox** [comment]
- [ ] [HaxeAL Soft](https://github.com/YanniZ06/HaxeAL-Soft/tree/main) - Native C++ Bindings for OpenAL Soft 1.23.1 by [YanniZ06](https://discord.com/channels/162395145352904705/1133094294144684163/1133094294144684163)

**Comment by Beeblerox** [comment]
- [ ] [BGP: Kitchen Infestation](https://heroofdermwood.itch.io/bgp-kitchen-infestation) by [E. Zachary Knight](https://discord.com/channels/162395145352904705/162664383082790912/1133520966258004129)

**Comment by skial** [comment]
- [ ] `[open source]` HXCPP Generate Typed Functions [update](https://github.com/HaxeFoundation/haxe/pull/11151#issuecomment-1652145767). _"C++ version down from 17 to 11, the Haxe repo tests pass with cpp and cppia and the hxcpp repo tests seem fine as well."_

**Comment by skial** [comment]
- [ ] `[community]` Animating Sprites in An Infested Kitchen [article](https://ezknight.net/2023/07/25/animating-sprites-in-an-infested-kitchen/) by E. Zachary Knight.

**Comment by skial** [comment]
- [ ] `[open source]` [porcelain `git`](https://github.com/FableMakerEngine/porcelain) - A set of helper classes and core game mechanics used by Fable Maker developed using Ceramic game engine.
