### ISSUE TITLE
Haxe Roundup 689

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1109]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` `HXCPP_GC_MOVING` CFFI crash [issue](https://github.com/HaxeFoundation/hxcpp/issues/1061)

**Comment by skial** [comment]
- [ ] `[core]`  Double `Null<T>` wrapping when inferring nullable type [issue](https://github.com/HaxeFoundation/haxe/issues/11286).

**Comment by skial** [comment]
- [ ] `[core/feature request]` `@:structInit` meta callback argument [issue](https://github.com/HaxeFoundation/haxe/issues/11287).

**Comment by skial** [comment]
- [ ] `[community]` Getting cursor position in console [question](https://community.haxe.org/t/getting-cursor-position-in-console/3997?u=skial).

**Comment by skial** [comment]
- [ ] libs
   - [corountine `2.0.2`](https://lib.haxe.org/p/coroutine)
   - [yield `3.2.1`](https://lib.haxe.org/p/yield)
   - [HaxeGJClient `3.0.0`](https://lib.haxe.org/p/HaxeGJClient)
   - [comma `0.1.6`](https://lib.haxe.org/p/comma)
   - [hmm `3.1.0`](https://lib.haxe.org/p/hmm)
   - [SScript `4.0.1`](https://lib.haxe.org/p/SScript)

**Comment by skial** [comment]
- [ ] `[community/devlog]` Bring It On! `0.11` - The Volcano Update is live [article](https://axolstudio.itch.io/bring-it-on/devlog/566548/v011-the-volcano-update-is-live-now)!

**Comment by skial** [comment]
- [ ] `[video]` Bring It On! [Early Access Trailer 2](https://www.youtube.com/watch?v=hcLQz10Cm1c).

**Comment by skial** [comment]
- [ ] `[open source]` [xing `git`](https://github.com/nevergarden/xing) - Hashlink Web Framework.

**Comment by skial** [comment]
- [ ] `[releases]` [Odd Verdure](https://www.newgrounds.com/portal/view/893426) by MondayHopscotch is available to play now on Newgrounds.

**Comment by skial** [comment]
- [ ] `[core/ammer]` Ammer rewrite based on `ammer-core` has been [merged](https://github.com/Aurel300/ammer/pull/53).

**Comment by Beeblerox** [comment]
- [ ] [test text](https://twitter.com/squuuidly/status/1686900636783157248) lookin great in [Renaine](https://store.steampowered.com/app/662340/Renaine/)

**Comment by Beeblerox** [comment]
- [ ] [WEEK OF 2023/08/01](https://funkin.me/blog/2023-08-01/): The Funkin' CREW in Toronto! post by [ninja_muffin99](https://twitter.com/ninja_muffin99/status/1686415535204978703)

**Comment by Beeblerox** [comment]
- [ ] New GIFs from Jitter Sandbox by Syo:
    * If you look closely, you can see [an astronaut who decided to breathe fresh air](https://twitter.com/SyoPic/status/1685001107964100616) at the last moment
    * At the base, [everyone is busy with something](https://twitter.com/SyoPic/status/1686770081332703233). It seems that they just walk and fly

**Comment by Beeblerox** [comment]
- [ ] New quick videos from Kid Bubblegum by Ando:
    * Kid Bubblegum can play bubble-billiards to [get across large gaps!](https://twitter.com/ohsat_games/status/1684991327132381186)
    * Steep walls? [No problem for Kid Bubblegum](https://twitter.com/ohsat_games/status/1685351300890779648)
    * [Bubblegum can be pretty useful(https://twitter.com/ohsat_games/status/1686081283254845441), huh?

**Comment by Beeblerox** [comment]
- [ ] [Advent](https://twitter.com/AdventIslands/status/1685297891366064128) is working on their next game - [Animal Arena](https://simpanen.carbonmade.com/animal-arena), wacky arena battle game for 1-4 players, featuring cute animals and simple one button controls. Stomp opponents and earn points to unlock more playable animals!

**Comment by Beeblerox** [comment]
- [ ] 🔑[House Plan Generator 1.1.0](https://www.patreon.com/posts/86852618): regular staircases and basements by [Oleg Dolya](https://twitter.com/watawatabou/status/1685374932019040257)

**Comment by Beeblerox** [comment]
- [ ] [Fishbunjin sprite status](https://twitter.com/FraymakersGame/status/1685443105477308416): 65% complete!!

**Comment by Beeblerox** [comment]
- [ ] A sneak peek at the [new Title Screen](https://twitter.com/Rapper_GF_Dev/status/1685541506394775552) for FreestyleEngine

**Comment by Beeblerox** [comment]
- [ ] [Michael Bickel](https://discord.com/channels/162395145352904705/1059447388047159399/1135280277707563058) is exploring how to build & integrate cpp externs directly with hxgodot

**Comment by Beeblerox** [comment]
- [ ] [SirBluberry](https://discord.com/channels/162395145352904705/1136207722178682951/1136207722178682951) is working on Nine Nighty Nightmares

**Comment by Beeblerox** [comment]
- [ ] [MichaelTheBirthdayRatz](https://discord.com/channels/162395145352904705/1101679621369499768/1101679621369499768) is working on [BEAT IT UP!!!!!!](https://forums.tigsource.com/index.php?topic=74526.0)

**Comment by Beeblerox** [comment]
- [ ] [Release 1.4.10](https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.10) of IntelliJ Haxe plugin

**Comment by Beeblerox** [comment]
- [ ] [MAJigsaw](https://discord.com/channels/162395145352904705/162664383082790912/1134897444069589095) is working on a undertale engine using HaxeFlixel and some another libraries

**Comment by Beeblerox** [comment]
- [ ] [New GIF and screenshots](https://discord.com/channels/162395145352904705/1043224047581929542/1134400705197789245) from Tenjutsu+ by Sébastien Benard

**Comment by Beeblerox** [comment]
- [ ] [George Harpwood](https://twitter.com/harpwood_studio/status/1686303087093305344) added a ton of new features in my Aseprite script which is generating animation code for the HaxeFlixel based on timeline's tags data

**Comment by Beeblerox** [comment]
- [ ] When considering extending an abstract type with a class, realised you can [use the abstract type inside it's class](https://try.haxe.org/#9cFa6257) by [Nanjizal](https://twitter.com/Nanjizal_net/status/1686345533797863425)

**Comment by skial** [comment]
- [ ] `[open source]` [hx-crowdcontrol `git`](https://github.com/AxolStudio/hx-crowdcontrol) - A Haxe library for Crowd Control.

**Comment by Beeblerox** [comment]
- [ ] [State of Ohsat `#26`](https://172068.seu2.cleverreach.com/m/14634685/546938-e1f27faf73ef9dc77a030bc3e9fe17e492d924959ff128a1dc575687cf00da3eb267a62987655e76f63522508e327a88):Back from Vacation
