### ISSUE TITLE
Haxe Roundup 693

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1117]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] Double check for pinned items before moving/deleting sections.

**Comment by skial** [comment]
- [ ] `[core/feature request]` Default constructors [question](https://github.com/HaxeFoundation/haxe/issues/11309)?

**Comment by skial** [comment]
- [ ] `[core]` `sys.FileStat.ctime` is not accurate on Linux/macOS [issue](https://github.com/HaxeFoundation/hashlink/issues/619).

**Comment by skial** [comment]
- [ ] libs
   - [hxsdl `0.1.2`](https://lib.haxe.org/p/hxsdl)
   - [hxal `1.0.1`](https://lib.haxe.org/p/hxal)
   - [hxdr_wav `0.1.0`](https://lib.haxe.org/p/hxdr_wav)
   - [hxstb_vorbis `0.1.0`](https://lib.haxe.org/p/hxstb_vorbis)
   - [dropecho.ds `1.7.0`](https://lib.haxe.org/p/dropecho.ds)
   - [mc2it_theme `5.4.2`](https://lib.haxe.org/p/mc2it_theme)

**Comment by skial** [comment]
- [ ] `[devlog]` Bring It On! `0.11.5` [Released](https://axolstudio.itch.io/bring-it-on/devlog/588300/v0115-rekeased)!

**Comment by skial** [comment]
- [ ] `[devlog]` Dune: Spice Wars - Early Access [Recap](https://store.steampowered.com/news/app/1605220/view/3645156108237934025).

**Comment by skial** [comment]
- [ ] `[open source]` [xml2object `git`](https://github.com/core-haxe/xml2object) -  Type safe XML (de)serializer.

**Comment by skial** [comment]
- [ ] `[releases]` [Gogoprog](https://twitter.com/gogoprog/status/1701682317918343181) `#js13k` entry made with Haxe is call Minipuyo.

**Comment by skial** [comment]
- [ ] `[community]` Armory3D `2023.09` has been [released](https://armory3d.org/notes#2023.09)! via [RPaladin](https://twitter.com/RPaladin_01/status/1698418897597382965).

**Comment by skial** [comment]
Once again, this issue will be postponed till next week.

**Comment by skial** [comment]
- [ ] `[open source]` [couchdb.hx `git`](https://github.com/cedx/couchdb.hx) - An Apache CouchDB client for Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [reflaxe_javasources `git`](https://github.com/EliteMasterEric/reflaxe_javasources) - A compiler that compiles Haxe code into javasources.

**Comment by skial** [comment]
- [ ] `[closed source]` Your chance of being attacked by a gnome at any given time in [Renaine](https://twitter.com/RenaineGame/status/1701992382865252733) are low... but not zero.

**Comment by skial** [comment]
- [ ] `[core]` Map abstract breaks compilation server DCE [issue](https://github.com/HaxeFoundation/haxe/issues/11311).

**Comment by skial** [comment]
- [ ] `[core/server]` Add support for ipv6 addresses for --wait/--connect [merged](https://github.com/HaxeFoundation/haxe/pull/11310).

**Comment by skial** [comment]
- [ ] `[community]` Haxe `4.3.2` has been [uploaded](https://github.com/HaxeFoundation/haxe/issues/10676#issuecomment-1726308146) to the PPA by Andy Li.

**Comment by skial** [comment]
- [ ] `[core]`  CLI `Sys.getChar` doesn't work on OSX [issue](https://github.com/HaxeFoundation/haxe/issues/11312).

**Comment by skial** [comment]
- [ ] `[devlog]` Wartales is [available now](https://store.steampowered.com/news/app/1527950/view/6611902998202165497) on Nintendo Switch!

**Comment by skial** [comment]
- [ ] `[devlog]` Dune: Spice Wars `1.0` is [available now](https://store.steampowered.com/news/app/1605220/view/7034115464048776058)!

**Comment by skial** [comment]
- [ ] `[devlog]` Dead Cells Update 35 [patch notes](https://store.steampowered.com/news/app/588650/view/6611902998201551260).

**Comment by skial** [comment]
- [ ] `[videos]` Processing Textures in ArmorLab [video](https://www.youtube.com/watch?v=j2M0xGH6_WY).

**Comment by skial** [comment]
- [ ] `[videos]` Dune: Spice Wars `1.0` [trailer](https://www.youtube.com/watch?v=5UhWFRFPSW0).

**Comment by skial** [comment]
- [ ] `[videos]` Wartales Nintendo Switch Launch [Trailer](https://www.youtube.com/watch?v=a6s50tfKqpo).

**Comment by skial** [comment]
- [ ] `[open source]` [ColorMatrixHx `git`](https://github.com/ConfidantCommunications/ColorMatrixHx) - Utility to manipulate a ColorMatrix for use in a ColorMatrixFilter in Flash or OpenFL.

**Comment by skial** [comment]
- [ ] `[closed source]` After two weeks of messing with shaders in Haxe/Kha, [Cornell Daly](https://twitter.com/bojjenclon/status/1703546478231171259) finally has a lighting solution they are pleased with.

**Comment by skial** [comment]
- [ ] `[closed source]` [Renaine](https://twitter.com/RenaineGame/status/1704165451931205983) Bonk! :bird:

**Comment by skial** [comment]
- [ ] `[closed source]` [Fraymakers](https://twitter.com/FraymakersGame/status/1703490204752031876) hard at work finishing Fishbunjin's sprites!

**Comment by skial** [comment]
- [ ] `[closed source]` A mid combo crouch attack is perfect for keeping your enemy stun-locked in [Renaine](https://twitter.com/RenaineGame/status/1703430861218029622)!

**Comment by skial** [comment]
- [ ] `[community]` 🏡Village Generator `1.5.2`: improved rivers and bridges [article](https://www.patreon.com/posts/village-1-5-2-89314043) by [Oleg Dolya](https://twitter.com/watawatabou/status/1702998471987359823).

**Comment by skial** [comment]
- [ ] `[closed source]` Lineria is made of many areas, that are all diverse and full of life in [Renaine](https://twitter.com/RenaineGame/status/1702718165183271266)!

**Comment by skial** [comment]
- [ ] `[open source]` [epikowa_cli `git`](https://github.com/epikowa/epikowa_cli) - Cli command line parser.

**Comment by skial** [comment]
- [ ] `[releases/haxe discord]` A _fun lil drawing app made in HaxeFlixel_ by [White Ninja](https://discord.com/channels/162395145352904705/162664383082790912/1152973472084000778).

**Comment by skial** [comment]
- [ ] `[events/upcoming]` The next Haxe Roundup _Roundup_ Discord [event](https://discord.com/events/162395145352904705/1150148331926990909) is scheduled for Saturday 30th September 18:30.

**Comment by Beeblerox** [comment]
- [ ] [Texturing a cowboy](https://twitter.com/armory3d/status/1700166952818217430) in ArmorPaint 0.9
- [ ] [Extracting PBR maps](https://twitter.com/armory3d/status/1702073828598313101) from a photo in ArmorLab

**Comment by Beeblerox** [comment]
- [ ] Couple of quick video from [Animal Arena](https://simpanen.carbonmade.com/animal-arena) by Jussi Simpanen:
    * The Desert stage features [quicksand that slows down anyone](https://twitter.com/AdventIslands/status/1700602506970071159) who steps in it. Jump to get out!
    * [Testing a button](https://twitter.com/AdventIslands/status/1703000127172985264) to let you pick a random animal from the ones you've unlocked instead of choosing one from a list.

**Comment by Beeblerox** [comment]
- [ ] [ArmorPaint 0.9 has been shipped](https://80.lv/articles/armorpaint-0-9-released/). Check Out a New Version of This Open-Source 3D Texturing Tool

**Comment by Beeblerox** [comment]
- [ ] The aliens seem to have put out [digital wanted posters](https://twitter.com/ohsat_games/status/1703010621967442160) for Kid Bubblegum... probably for good reason

**Comment by Beeblerox** [comment]
- [ ] Couple more GIFs from Renaine:
    * Sometimes you just need [a nice reading break](https://twitter.com/RenaineGame/status/1702346969258283303) 📚
    * [Cool knights don't look at explosions](https://twitter.com/RenaineGame/status/1704524064805519843) 😎

**Comment by Beeblerox** [comment]
- [ ] [Spitko](https://discord.com/channels/162395145352904705/501408700142059520/1151336379398225930) has made [CerastesTemplate](https://github.com/nspitko/CerastesTemplate) available. They don't recommend anyone use it, but it could be a good starting point for your own stuff. [An example](https://discord.com/channels/162395145352904705/501408700142059520/1151389385770676286) of what you can do with it

**Comment by Beeblerox** [comment]
- [ ] [Crop Rotation](https://store.steampowered.com/app/2348090/Crop_Rotation/) has launched.
- [ ] 9 months + of daily grind. Always fun to [look back at my notes](https://twitter.com/ZwodahS/status/1702184449113477493) to see how much the game evolve. Will probably write a post mortem at some point.

**Comment by Beeblerox** [comment]
- [ ] New GIFs from [Into the Necrovale](https://store.steampowered.com/app/1717090/Into_the_Necrovale/) by Casey Clyde:
    * [New player and enemies in action](https://twitter.com/clydegamedev/status/1703275104556536066)
    * [Crystal staff power move](https://twitter.com/clydegamedev/status/1703889735956283646). Ice master
    * [Bear hugs for all the skeletons](https://twitter.com/clydegamedev/status/1704197612306583989)

**Comment by Beeblerox** [comment]
- [ ] [HxGodot & Steam Audio, first steps](https://www.youtube.com/watch?v=7qmpf1F9kUQ) by [Michael Bickel](https://discord.com/channels/162395145352904705/1059447388047159399/1151622623604768869)

**Comment by Beeblerox** [comment]
- [ ] Prexot is [almost done with Chapter 1](https://discord.com/channels/162395145352904705/1020075437080191096/1153760567228641361) of [Rhythm Magus](https://goldenpigames.itch.io/rhythm-magus)

**Comment by Beeblerox** [comment]
- [ ] [Godot Manager](https://git.team-prism.rocks/FryingPan/godot-manager) is a tool to manage Godot versions on Linux. Made with Haxe

**Comment by Beeblerox** [comment]
- [ ] [semmi](https://discord.com/channels/162395145352904705/162664383082790912/1152734792278880326) wrote [a little function-plotter](http://www.maitag.de/semmi/armory3d/mathTerm/html5/)

**Comment by Beeblerox** [comment]
- [ ] [HeapsIONewGameTemplate](https://github.com/Sup0088/HeapsIONewGameTemplate) is just a basic heaps.io template by [Sabe aka sup0088](https://discord.com/channels/162395145352904705/162664383082790912/1152751106653437952)

**Comment by Beeblerox** [comment]
- [ ] [eggu](https://discord.com/channels/162395145352904705/162664383082790912/1153880217778126860) has made a game for history class about the Boston tea party.

**Comment by Beeblerox** [comment]
- [ ] Joshua Tynjala posted a [few screenshots of Feathers UI for OpenFL](https://discord.com/channels/415681294446493696/436230004251164672/1154095747743092816) compiled to SWF and running on Ruffle instead of Flash Player. And screenshots of [NyanCat and PiratePig OpenFL](https://discord.com/channels/415681294446493696/436230004251164672/1154102985283084319) samples running in Ruffle

**Comment by Beeblerox** [comment]
- [ ] Andrei Apanasik is [checking out Haxe](https://twitter.com/Suvitruf/status/1702590310457508159) as an option to port a plugin for their company's product [Balancy](https://balancy.co/). And [trying to use ChatGPT for it](https://twitter.com/Suvitruf/status/1702591171015401921)

**Comment by skial** [comment]
- [ ] `[community]` Releasing an OpenFL project on MacOS - code signing and notarization [guide](https://community.openfl.org/t/releasing-an-openfl-project-on-macos-code-signing-and-notarization/13794?u=skial.bainn).

**Comment by skial** [comment]
- [ ] `[core]` Remove hard references from `if_features` [pull request](https://github.com/HaxeFoundation/haxe/pull/11315).
