### ISSUE TITLE
Haxe Roundup 697

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1126]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by 0b1kn00b** [comment]
- [ ] Library for passing data between macro time and runtime [bake](https://lib.haxe.org/p/bake/) by [0b1kn00b](https://github.com/ohmrun/)

**Comment by skial** [comment]
- [ ] `[core/jvm]` Field annotations not exported correctly with `RententionPolicy.RUNTIME` [issue](https://github.com/HaxeFoundation/haxe/issues/11370).

**Comment by skial** [comment]
- [ ] `[core]` `Contex.parseInlineString` ignore extra code [fixed](https://github.com/HaxeFoundation/haxe/issues/11368).

**Comment by skial** [comment]
- [ ] `[core/jvm]` Compiler failure when attempting to relocate `haxe.root.Array` [issue](https://github.com/HaxeFoundation/haxe/issues/11361).

**Comment by skial** [comment]
- [ ] `[core]` `extern overload`'s cause enum identifier resolution to fail [issue](https://github.com/HaxeFoundation/haxe/issues/11372).

**Comment by skial** [comment]
- [ ] `[core/php]` Wrong `addbytes` for BytesBuffer [issue](https://github.com/HaxeFoundation/haxe/issues/11369).

**Comment by skial** [comment]
- [ ] `[core]` RH switch with only null case causes stack overflow in the compiler [fixed](https://github.com/HaxeFoundation/haxe/issues/11366).

**Comment by skial** [comment]
- [ ] `[core]` Some preprocessor cleanup [merged](https://github.com/HaxeFoundation/haxe/pull/11365).

**Comment by skial** [comment]
- [ ] `[core]` Typedef vs `@:generic` [issue](https://github.com/HaxeFoundation/haxe/issues/11367).

**Comment by skial** [comment]
- [ ] `[core]` Improve inline constructor handling of `if`, `try` and `while` expressions [merged](https://github.com/HaxeFoundation/haxe/pull/11356).

**Comment by skial** [comment]
- [ ] `[core/eval]` Make `Context.definedValue` return `Null<String>` and document `Context.resolvePath` exception [merged](https://github.com/HaxeFoundation/haxe/pull/11363).

**Comment by skial** [comment]
- [ ] `[community]` OpenFL `9.3.2` and Lime `8.1.1` have been [released](https://community.openfl.org/t/openfl-9-3-2-and-lime-8-1-1-release/13827?u=skial.bainn).

**Comment by skial** [comment]
- [ ] `[core]` Instance builder cleanup [pull request](https://github.com/HaxeFoundation/haxe/pull/11376).

**Comment by skial** [comment]
- [ ] `[core]` Safe navigation is invalid for assigning variables [issue](https://github.com/HaxeFoundation/haxe/issues/11379).

**Comment by skial** [comment]
- [ ] `[core/hlc]` HL/C compilation fails with Visual Studio when Haxe field is named restrict, _restrict, or __restrict [issue](https://github.com/HaxeFoundation/haxe/issues/11378).

**Comment by skial** [comment]
- [ ] `[core]` Respect imports on `@:build` [merged](https://github.com/HaxeFoundation/haxe/pull/11373).

**Comment by skial** [comment]
- [ ] `[core]` Don't exception-wrap every macro API function [pull request](https://github.com/HaxeFoundation/haxe/pull/11374).

**Comment by skial** [comment]
- [ ] `[libs]`
  - [hxyarn `0.1.12`](https://lib.haxe.org/p/hxyarn)
  - [nwjs `1.4.1`](https://lib.haxe.org/p/nwjs)
  - [couchdb `0.2.0`](https://lib.haxe.org/p/couchdb)
  - [PickHaxe `0.4.1`](https://lib.haxe.org/p/PickHaxe)
  - [tink_macro `1.0.3`](https://lib.haxe.org/p/tink_macro)
  - [flixel `5.5.0`](https://lib.haxe.org/p/flixel)
  - [openfl `9.3.2`](https://lib.haxe.org/p/openfl)
  - [lime `8.1.1`](https://lib.haxe.org/p/lime)
  - [typed-json `0.0.2`](https://lib.haxe.org/p/typed-json)
  - [macro-type-decoder `0.0.2`](https://lib.haxe.org/p/macro-type-decoder)
  - [SScript `7.7.0`](https://lib.haxe.org/p/SScript)
  - [hxsdl `0.1.9`](https://lib.haxe.org/p/hxsdl)
  - [godot-api-generator `1.2.1`](https://lib.haxe.org/p/godot-api-generator)
  - [3LLua `0.0.618-alpha`](https://lib.haxe.org/p/3LLua)
  - [torchsfunctions `0.3.1`](https://lib.haxe.org/p/torchsfunctions)
  - [proxsys `0.1.1`](https://lib.haxe.org/p/proxsys)
  - [parasol `0.0.6`](https://lib.haxe.org/p/parasol)
  - [flixel-demos `3.1.0`](https://lib.haxe.org/p/flixel-demos)
  - [deepnightLibs `1.0.79`](https://lib.haxe.org/p/deepnightLibs)
  - [docklix `0.1.0`](https://lib.haxe.org/p/docklix)
  - [godot-extension-api-typings `1.0.2`](https://lib.haxe.org/p/godot-extension-api-typings)
  - [commUnit `0.1.0`](https://lib.haxe.org/p/commUnit)

**Comment by skial** [comment]
- [ ] `[devlog]` 💪 Ultra Fishbunjin 3000 OUT NOW!! + The Watcher Details - November 2023 [Progress Update](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3902799) from Fraymakers.

**Comment by skial** [comment]
- [ ] `[devlog]` Go! Go! Pogogirl Is Coming to Mega Drive! [article](https://www.ohsat.com/post/go-go-pogogirl-coming-to-md/) by Andrej Preradovic.

**Comment by skial** [comment]
- [ ] `[devlog]` Join the Northgard beta-test team for a new multiplayer system [post](https://store.steampowered.com/news/app/466560/view/3781394975952663989).

**Comment by skial** [comment]
- [ ] `[video]` Big Armory 3D update for November 2023 [video](https://www.youtube.com/watch?v=RrqS2W_ELMY).

**Comment by skial** [comment]
- [ ] `[video]` Make a Top Down player controller in Armory 3D [video](https://www.youtube.com/watch?v=2FqaivpZIkE).
- [ ] `[video]` Groupe chat networking in Armory 3D [video](https://www.youtube.com/watch?v=7WpPh2uJOJY).

**Comment by skial** [comment]
- [ ] `[open source]` [hx-http-server `git`](https://github.com/rainyt/hx-http-server) - Haxe HXCPP target httpserver.

**Comment by skial** [comment]
- [ ] `[open source]` [fuel-lang `git`](https://github.com/mneuroth/fuel-lang-haxe) - A port of the fuel language to the Haxe language.

**Comment by skial** [comment]
- [ ] `[open source]` [centauri-game-engine `git`](https://github.com/Falagard/centauri-game-engine) - The Centauri Game Engine uses BabylonHx as its rendering engine & adds pathfinding, artificial intelligence systems, entity component systems.

**Comment by skial** [comment]
- [ ] `[open source]` [haxe-shade `git`](https://github.com/EliteMasterEric/haxe-shade) - A utility library to relocate packages in Haxe projects.

**Comment by skial** [comment]
- [ ] `[core]` `@:structInit` hover does not have doc comments [issue](https://github.com/vshaxe/vshaxe/issues/613).

**Comment by skial** [comment]
- [ ] `[open source]` [Michael Bickle](https://twitter.com/dazKind/status/1724567517283098726) previews further work on HxGodot with a complex test-scene using Haxe externs and proven Haxe libs.
- [ ] `[video]` HxGodot & Steam Audio, Occlusion & Reflections `#2` [video](https://www.youtube.com/watch?v=YMzrG5o-yfw).

**Comment by skial** [comment]
- [ ] `[closed source?]` [SomeRanDev](https://twitter.com/SomeRanDev/status/1722443204220358902) has added a Haxe compliation button to Godot.

**Comment by skial** [comment]
- [ ] `[open source]` [haxix `git`](https://github.com/MadMcCrow/haxix) - nix flake to build Haxe/heaps.io projects.

**Comment by Beeblerox** [comment]
- [ ] Animal Arena by [Advent](https://twitter.com/AdventIslands/status/1722534935779520718) is now available on [App Store](https://apps.apple.com/us/app/animal-arena-4-player-battle/id6453332216) and [Google Play](https://play.google.com/store/apps/details?id=com.adventureislands.animalarena)
- [ ] And they are [working on some new content](https://twitter.com/AdventIslands/status/1724529291793219685) for Animal Arena

**Comment by Beeblerox** [comment]
- [ ] [Cave Generator 2.1.0](https://www.patreon.com/posts/92512693): assorted new features by [Oleg Dolya](https://twitter.com/watawatabou/status/1722256508208230824)

**Comment by Beeblerox** [comment]
- [ ] Kid Bubblegum [Emergency Patch and Wall of Text](https://ohsat-andrej.itch.io/kid-bubblegum/devlog/633596/emergency-patch-and-wall-of-text)

**Comment by Beeblerox** [comment]
> * [ ]  `[video]` Make a Top Down player controller in Armory 3D [video](https://www.youtube.com/watch?v=2FqaivpZIkE).
> * [ ]  `[video]` Groupe chat networking in Armory 3D [video](https://www.youtube.com/watch?v=7WpPh2uJOJY).

- [ ] Make moving platforms in Armory 3D [short video](https://www.youtube.com/shorts/PqOORDKFuZk).

**Comment by Beeblerox** [comment]
- [ ] [Axol Studio](https://twitter.com/AxolStudio/status/1723523420577570981) updated the Bring It On! website with a [FAQ section](https://bringiton.axolstudio.com/#FAQ)

**Comment by Beeblerox** [comment]
- [ ] [racing minigame idea](https://twitter.com/zzo__x/status/1721176108563849352) by zzox (tyler)

**Comment by Beeblerox** [comment]
- [ ] Before they play their roles for you, we learn to [play airsoft together](https://twitter.com/SyoPic/status/1721859461310988602) by Syo

**Comment by Beeblerox** [comment]
- [ ] New HaxeFlixel demo [just dropped](https://twitter.com/HaxeFlixel/status/1721919085917646881), showcasing [new FlxAsepriteUtil helpers](https://haxeflixel.com/demos/FlxAsepriteUtil/)

**Comment by Beeblerox** [comment]
- [ ] [A side effect of the camera](https://twitter.com/squuuidly/status/1724910689293091139) in Renaine now locking on npcs as they talk to you is it ALSO follows them while they panic run back and forth aimlessly

**Comment by Beeblerox** [comment]
- [ ] ChargingTurnip is making [Sweepminer](https://discord.com/channels/162395145352904705/1172403835386462248/1172403835386462248) - What if Minesweeper was a rogue-lite platformer

**Comment by Beeblerox** [comment]
- [ ] EyeDaleHim is working on [FNaF Series Recreation](https://discord.com/channels/162395145352904705/1172565073655496754/1172565073655496754)

**Comment by Beeblerox** [comment]
- [ ] [More sprite stacking](https://discord.com/channels/162395145352904705/165234904815239168/1174423822838013984) shenanigans by WIll Blanton

**Comment by Beeblerox** [comment]
- [ ] [Haxe-GodotBindingsGenerator](https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator) by [SomeRanDev](https://discord.com/channels/162395145352904705/1052688097592225904/1170122984741154906)

**Comment by Beeblerox** [comment]
- [ ] [short gameplay clip](https://discord.com/channels/162395145352904705/1140615400770519122/1170194273782726676) from Power Line Rider

**Comment by Beeblerox** [comment]
- [ ] PickHaxe, the Minecraft modding framework for Haxe, has been making a lot of progress in its tooling lately. [Here's a demonstration](https://discord.com/channels/162395145352904705/162664383082790912/1172379825382625361) that goes from an empty workspace to a sample mod working in-game in less than 2 minutes

**Comment by skial** [comment]
- [ ] `[core/haxelib]` Misleading instructions [issue](https://github.com/HaxeFoundation/haxelib/issues/616).
- [ ] `[core/haxelib]` SQL query leak [issue](https://github.com/HaxeFoundation/haxelib/issues/615).
