### ISSUE TITLE
Haxe Roundup 698

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1128]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` Unclosed monomorphs in function signature [issue](https://github.com/HaxeFoundation/haxe/issues/11381).

**Comment by skial** [comment]
- [ ] `[core/display]` Remove legacy diagnostics [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11413).

**Comment by skial** [comment]
- [ ] `[core/display]` Diagnostics as json rpc [merged](https://github.com/HaxeFoundation/haxe/pull/11412).

**Comment by skial** [comment]
- [ ] `[core]` Override and default types [issue](https://github.com/HaxeFoundation/haxe/issues/11410).

**Comment by skial** [comment]
- [ ] `[core/hl/c]` Fix reserved keywords [merged](https://github.com/HaxeFoundation/haxe/pull/11408).

**Comment by skial** [comment]
- [ ] `[core]` Add support for `--undefine foo` to remove define [merged](https://github.com/HaxeFoundation/haxe/pull/11400).

**Comment by skial** [comment]
- [ ] `[core/hl]` Hashlink null comparison [issue](https://github.com/HaxeFoundation/haxe/issues/11416).

**Comment by skial** [comment]
- [ ] `[hashlink]` Add hlc stack trace to Linux/Mac [merged](https://github.com/HaxeFoundation/hashlink/pull/634).

**Comment by skial** [comment]
- [ ] `[core]` Add MFromMacroInMacro constraint and check it when iterating/matching [pull request](https://github.com/HaxeFoundation/haxe/pull/11406).

**Comment by skial** [comment]
- [ ] `[core]` Track actual path position for `path.Path<Params>` [merged](https://github.com/HaxeFoundation/haxe/pull/11405).

**Comment by skial** [comment]
- [ ] `[core]` Use available terminal columns instead of hardcoded 80 columns [merged](https://github.com/HaxeFoundation/haxe/pull/11404).

**Comment by skial** [comment]
- [ ] `[core]` Inline constructors vs. Void (continued) [issue](https://github.com/HaxeFoundation/haxe/issues/11396).

**Comment by skial** [comment]
- [ ] `[core]` Void expressions in value places... in non-value places [fixed](https://github.com/HaxeFoundation/haxe/issues/11391).

**Comment by skial** [comment]
- [ ] `[core]` Expected type conflation in binop handler [fixed](https://github.com/HaxeFoundation/haxe/issues/11392).

**Comment by skial** [comment]
- [ ] `[core]` Duplicate parameter name [issue](https://github.com/HaxeFoundation/haxe/issues/11417).

**Comment by skial** [comment]
- [ ] `[core/jvm]` Jvm annotation rework [merged](https://github.com/HaxeFoundation/haxe/pull/11398).

**Comment by skial** [comment]
- [ ] `[core]` Metadata attached to nothing [issue](https://github.com/HaxeFoundation/haxe/issues/11389).

**Comment by skial** [comment]
- [ ] `[core]` Remove magicTypes.ml [merged](https://github.com/HaxeFoundation/haxe/pull/11387).

**Comment by skial** [comment]
- [ ] `[community]` Haxe `4.3.3` has been [released](https://community.haxe.org/t/haxe-4-3-3-released/4083?u=skial)!
   - > This is a bugfix release. It is available along with the changelog at [https://haxe.org/download/version/4.3.3](https://haxe.org/download/version/4.3.3)

**Comment by skial** [comment]
- [ ] `[core]` Module field regression [fixed](https://github.com/HaxeFoundation/haxe/issues/11385).

**Comment by skial** [comment]
- [ ] `[evolution]` Typed metadata [update](https://github.com/HaxeFoundation/haxe-evolution/pull/111#issuecomment-1820332348).

**Comment by skial** [comment]
- [ ] libs
   - [sha `0.0.1`](https://lib.haxe.org/p/sha)
   - [godot-extension-api-typings `1.1.0`](https://lib.haxe.org/p/godot-extension-api-typings)
   - [parasol `0.0.8`](https://lib.haxe.org/p/parasol)
   - [hx-http-server `0.0.4`](https://lib.haxe.org/p/hx-http-server)
   - [openfl-glsl `0.2.0`](https://lib.haxe.org/p/openfl-glsl)
   - [SScript `8.1.6`](https://lib.haxe.org/p/SScript)
   - [hxstb_vorbis `0.1.3`](https://lib.haxe.org/p/hxstb_vorbis)
   - [hxal `1.0.2`](https://lib.haxe.org/p/hxal)
   - [hxsdl `0.2.0`](https://lib.haxe.org/p/hxsdl)
   - [hxpy `1.0.0`](https://lib.haxe.org/p/hxpy)
   - [electron `27.1.0`](https://lib.haxe.org/p/electron)
   - [bootstrap_bundle `2.3.2`](https://lib.haxe.org/p/bootstrap_bundle)
   - [godot-api-generator `1.3.1`](https://lib.haxe.org/p/godot-api-generator)
   - [hgsl `0.4.0`](https://lib.haxe.org/p/hgsl)
   - [hxcpp-release `4.3.15`](https://lib.haxe.org/p/hxcpp-release)
   - [typed-json `0.0.3`](https://lib.haxe.org/p/typed-json)
   - [macro-type-decoder `0.0.3`](https://lib.haxe.org/p/macro-type-decoder)
   - [couchdb `0.2.1`](https://lib.haxe.org/p/couchdb)

**Comment by skial** [comment]
- [ ] `[devlog]` Dune: Spice Wars - Community Update `#1` [Out Now](https://store.steampowered.com/news/app/1605220/view/3899616281688406678)!

**Comment by skial** [comment]
- [ ] `[devlog]` Northgard: Enter the clan of the Owl! [article](https://store.steampowered.com/news/app/466560/view/3815173246080519077).

**Comment by skial** [comment]
- [ ] `[devlog]` Bring It On! `0.13` Corruption [Update](https://axolstudio.itch.io/bring-it-on/devlog/641781/v013-corruption) is now available!

**Comment by skial** [comment]
- [ ] `[open source]` [openfl-seawater-shader `git`](https://github.com/rainyt/openfl-seawater-shader) - It uses shaders to achieve basic seawater effects, such as shadows and waves.

**Comment by skial** [comment]
- [ ] `[open source]` [SimpleLocation `git`](https://github.com/Joalor64GH/SimpleLocalization) - My own localization system made from scratch!

**Comment by skial** [comment]
- [ ] `[open source]` [HaxeRustIntegration `git`](https://github.com/AltronMaxX/HaxeRustIntegration) - Usage of Rust native library in Haxe, an experiment aimed at studying the execution of code.

**Comment by skial** [comment]
- [ ] `[open source]` [DyslecixWords `git`](https://github.com/drflamemontgomery/DyslexicWords) - An application aimed at Dyslexics to support writing and reading text.

**Comment by skial** [comment]
- [ ] `[open source]` [HaxeDoxInjector `git`](https://github.com/EliteMasterEric/HaxeDoxInjector) - A library which provides a macro to inject documentation into Haxe classes from JSON data.

**Comment by skial** [comment]
- [ ] `[open source]` Some additions to HaxeUI animation tools to allow animating parts of your user interface with ease! by [Ian Harrigan](https://twitter.com/IanHarrigan1982/status/1725450112913002899).

**Comment by skial** [comment]
- [ ] `[events]` Haxe Roundup _Roundup_ Discord [Event](https://discord.gg/jCCuesf9?event=1177406451287871500) scheduled for Sunday 3rd December 18:30.

**Comment by Beeblerox** [comment]
- [ ] [Dune: Spice Wars](https://twitter.com/DuneSpiceWars/status/1729807879094350174) is now [available on Xbox Series X/S](https://www.xbox.com/en-US/games/store/dune-spice-wars/9n46jzzngs3p)

**Comment by Beeblerox** [comment]
- [ ] When even the fox [going through infinite glitched forms](https://twitter.com/squuuidly/status/1725643234745921607) refuses to talk to you

**Comment by Beeblerox** [comment]
- [ ] [Running into some tiny roadblocks](https://twitter.com/OneAndOnlyEGGU/status/1726825854565789885) quick videos from WIP game by eggu

**Comment by Beeblerox** [comment]
- [ ] Animal Arena [by Advent](https://twitter.com/AdventIslands/status/1726611731714351332) is now globally [launched on Poki
](https://poki.com/en/g/animal-arena)

**Comment by Beeblerox** [comment]
- [ ] ☠️[Perilous Shores 1.6.1](https://www.patreon.com/posts/93672952): tributaries by [Oleg Dolya](https://twitter.com/watawatabou/status/1729512612965015607)

**Comment by Beeblerox** [comment]
- [ ] Create a path to the exit in [Arrow Pathway](https://poki.com/en/g/arrow-pathway) by [Robert Alvarez](https://twitter.com/Rob1221dev/status/1729528691842060682)

**Comment by Beeblerox** [comment]
- [ ] In Leapin Lads by Cory Martin you [can play as pizza](https://twitter.com/CoryAlexMartin/status/1729947466919809423)

**Comment by Beeblerox** [comment]
- [ ] Ceramic [Release v1.3.2](https://github.com/ceramic-engine/ceramic/releases/tag/v1.3.2)

**Comment by Beeblerox** [comment]
- [ ] [Antriel](https://discord.com/channels/162395145352904705/1178330673833050172/1178330673833050172) began work on [Fantasy Sphere Mini](https://mini.fantasysphere.games/) - a new, planned to be tiny, RPG

**Comment by Beeblerox** [comment]
- [ ] [Little update](https://discord.com/channels/162395145352904705/1022291887505281025/1176531829885517877) on Hitter by naoya

**Comment by Beeblerox** [comment]
- [ ] EyeDaleHim made some spaghetti code for [full screen and gameplay resetting](https://discord.com/channels/162395145352904705/1172565073655496754/1175168496452255744) for FNaF Series Recreation

**Comment by skial** [comment]
- [ ] `[core/hl/c]`  Compilation fails with C compilers when Haxe field name matches C `#define` [issue](https://github.com/HaxeFoundation/haxe/issues/11419).
