### ISSUE TITLE
Haxe Roundup 699 🎄

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1130]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` Discrepancy in null-coalescing operator [issue](https://github.com/HaxeFoundation/haxe/issues/11425).

**Comment by skial** [comment]
- [ ] `[core]` Type operator `lhs` against expected type [pull request](https://github.com/HaxeFoundation/haxe/pull/11428).

**Comment by skial** [comment]
- [ ] `[core]` No completion because of wrong type errors [fixed](https://github.com/HaxeFoundation/haxe/issues/11422).

**Comment by skial** [comment]
- [ ] `[core/js]` Wrong auto-generated constructor for a child class with rest args in constructor [issue](https://github.com/HaxeFoundation/haxe/issues/11426).

**Comment by skial** [comment]
- [ ] `[core]` HxOverrides undefined or missing members unless `--dce` set to `no` [fixed](https://github.com/HaxeFoundation/haxe/issues/11427),

**Comment by skial** [comment]
- [ ] `[core/js]` Add externs for the Web Share API [merged](https://github.com/HaxeFoundation/haxe/pull/11423).

**Comment by skial** [comment]
- [ ] `[core/js]` Add externs for the Screen Wake Lock API [merged](https://github.com/HaxeFoundation/haxe/pull/11421).

**Comment by skial** [comment]
- [ ] `[hashlink]` Added compute shader api [merged](https://github.com/HaxeFoundation/hashlink/pull/638).

**Comment by skial** [comment]
- [ ] `[community]` HXCPP cross compilation MacOS to Linux [tutorial](https://community.haxe.org/t/hxcpp-cross-compilation-macos-to-linux/4104?u=skial).

**Comment by skial** [comment]
- [ ] `[ocamlhaxe]` Update repo path, lib version & readme [merged](https://github.com/HaxeFoundation/ocamhaxe/pull/8).

**Comment by skial** [comment]
- [ ] `[heaps]` Working compute shaders in DX12 [merged](https://github.com/HeapsIO/heaps/pull/1182).

**Comment by skial** [comment]
- [ ] libs
   - [heapsJsonTiled `0.0.14`](https://lib.haxe.org/p/heapsJsonTiled)
   - [haxeda-test `1.1.0`](https://lib.haxe.org/p/haxeda-test)
   - [HxWebView `0.0.1`](https://lib.haxe.org/p/HxWebView)
   - [flixel-text-input `1.1.0`](https://lib.haxe.org/p/flixel-text-input)
   - [extension-androidtools `1.8.4`](https://lib.haxe.org/p/extension-androidtools)
   - [electron `28.0.0`](https://lib.haxe.org/p/electron)
   - [hxnativefiledialog `1.0.0`](https://lib.haxe.org/p/hxnativefiledialog)
   - [hxsdl `0.2.1`](https://lib.haxe.org/p/hxsdl)
   - [HaxeAL-Soft `1.0.0`](https://lib.haxe.org/p/HaxeAL-Soft)
   - [typed-json `0.0.4`](https://lib.haxe.org/p/typed-json)
   - [godot-api-generator `1.5.1`](https://lib.haxe.org/p/godot-api-generator)

**Comment by skial** [comment]
- [ ] `[devlog]` Minicology - Charting a Course for the Next Phase [article](https://store.steampowered.com/news/app/1471700/view/3907498939957293865).

**Comment by skial** [comment]
- [ ] `[community]` [Brace yourselves](https://store.steampowered.com/news/app/588650/view/3899617640604482263), something NEW is coming from MotionTwin!

**Comment by skial** [comment]
- [ ] `[devlog]` Wartales - Pirates of Belerion: Lords of the Sea [announcement](https://store.steampowered.com/news/app/1527950/view/3899617640602126457).

**Comment by skial** [comment]
- [ ] `[devlog]` Northgard - Clan of the Owl is [out now!](https://store.steampowered.com/news/app/466560/view/3893986782156282989)
  - _Plus the Winter Update, The Winter festival & more!_

**Comment by skial** [comment]
- [ ] `[devlog]` Fraymakers Update `0.6.2` - [The Emote Update](https://store.steampowered.com/news/app/1420350/view/3884980308706426127)!

**Comment by skial** [comment]
- [ ] `[video]` December release notes for Armory3D [video](https://www.youtube.com/watch?v=3bM4YVgjkE8).

**Comment by Beeblerox** [comment]
- [ ] [LEVEL DEVIL](https://poki.com/en/g/level-devil) is a platformer that will make you curse my name then ask for more. by [Unept](https://twitter.com/Unept/status/1730620211228004510)

**Comment by Beeblerox** [comment]
- [ ] New GIFs from Renaine:
    * [gif capture glitches](https://twitter.com/squuuidly/status/1730696931930710323) make it look like bullwhip bones is just standing there while aine does unspeakable things to that poor bird
    * rule #1 of gif capture: [never get hit](https://twitter.com/squuuidly/status/1730985173901008920)
    * [Crossin' the chasm](https://twitter.com/squuuidly/status/1731732629618036780), made this level all the way back and I don't remember it being so... precarious
    * [use bubbledash geysers](https://twitter.com/RenaineGame/status/1732079725395276184) to burst through the danger :O
    * this [ancient desert tower is so vertical](https://twitter.com/squuuidly/status/1732811603999863230) it needs this gif to be in 4:3 
    * watch out for [spears from the Merspear](https://twitter.com/squuuidly/status/1733158494272893368)!
    * [this mammoth be like](https://twitter.com/squuuidly/status/1733292628282880426) "hey screw you buddy" *glitchily shuffles away*

**Comment by Beeblerox** [comment]
- [ ] New quick videos from Starfox remake by SnkyGames:
    * [Starfox 2 Arwing to SF1](https://twitter.com/SnkyGames/status/1731002789663232187) via real-time mesh deform 🐸
    * I've started on the [Arwing to Walker transform](https://twitter.com/SnkyGames/status/1733614046354555225) via mesh deformation. I feel the reaper coming for me as I do 3D animations via code not modelling. 🐸
    * Progress with the starfox [arwing to walker transform](https://twitter.com/SnkyGames/status/1734281399622897986)

**Comment by Beeblerox** [comment]
- [ ] [zzox (tyler)](https://twitter.com/zzo__x/status/1730996663697686747) made a grid-based real-time roguelike for a jam. You can [play it on itch.io](https://zzox.itch.io/depths)

**Comment by Beeblerox** [comment]
- [ ] Everyone loves Money! Everyone loves jumping in Fish Mouths and [getting spat out into lots of Money](https://twitter.com/CoryAlexMartin/status/1730997284173762938) in Leapin Lads by Cory Martin

**Comment by Beeblerox** [comment]
> * [ ]  `[video]` December release notes for Armory3D [video](https://www.youtube.com/watch?v=3bM4YVgjkE8).

- [ ] And [December - 2023](https://armory3d.org/notes#2023.12-title) release notes itself

**Comment by Beeblerox** [comment]
- [ ] [1.2 Update](https://store.steampowered.com/news/app/2348090/view/3904120607127340071) for Crop Rotation by [ZwodahS](https://twitter.com/ZwodahS/status/1731506432405872814)

**Comment by Beeblerox** [comment]
- [ ] [loop-de-loop](https://twitter.com/SomeRanDev/status/1733633084338155611) by SomeRanDev

**Comment by Beeblerox** [comment]
- [ ] 🍺[Tiny Pubs](https://www.patreon.com/posts/tiny-pubs-94469350) by [Oleg Dolya](https://twitter.com/watawatabou/status/1734223271179039146)

**Comment by Beeblerox** [comment]
- [ ] Wami been [working on a small project](https://discord.com/channels/162395145352904705/1081002322475360377/1179951352806375545) in Godot using Reflaxe's gdscript export. Also this project is [on github](https://github.com/UmnganeWami/Random-Haxe-Godot-First-Person-Game)

**Comment by Beeblerox** [comment]
- [ ] [Vasco](https://discord.com/channels/162395145352904705/1045089472204779531/1184308856550072410) has officially released the web version of G-Switch 4, made with HaxeFlixel:
    * [Trailer](https://www.youtube.com/watch?v=S1OXcqtHK50)
    * [The game itself](https://seriusgames.com/g-switch-4.html)

**Comment by Beeblerox** [comment]
- [ ] [I ported FNaF to HaxeFlixel](https://www.youtube.com/watch?v=MhuauBcz444) video by [EyeDaleHim](https://discord.com/channels/162395145352904705/1172565073655496754/1179771840709795850)

**Comment by Beeblerox** [comment]
- [ ] ChargingTurnip [got around to making a file select](https://discord.com/channels/162395145352904705/1172403835386462248/1183630413772632157) for Sweepminer

**Comment by Beeblerox** [comment]
- [ ] [Asset pipeline diagram](https://discord.com/channels/162395145352904705/1178330673833050172/1180481431005306900) for Fantasy Sphere Mini by Peter Achberger

**Comment by Beeblerox** [comment]
- [ ] !SIG7Ivan/Alory is [remaking the Wii Menu](https://discord.com/channels/162395145352904705/1182083476506296371/1182083476506296371) in HaxeFlixel.

**Comment by Beeblerox** [comment]
- [ ] Star is [working on FlxTextInput](https://discord.com/channels/162395145352904705/1180906804499206217/1180906804499206217) - Improved text input for HaxeFlixel

**Comment by Beeblerox** [comment]
- [ ] [YanniZ06](https://discord.com/channels/162395145352904705/1180982568452104253/1180982568452104253) is working on [ZAudio Backend](https://github.com/YanniZ06/z-audio-backend/tree/main) - An audio backend for Haxe using the HaxeAL-Soft Library

**Comment by Beeblerox** [comment]
- [ ] Chroma Go library is [soon coming to Haxe](https://discord.com/channels/162395145352904705/1020578706743365632/1179816783167901736)!

**Comment by Beeblerox** [comment]
- [ ] [Octaclone](https://discord.com/channels/162395145352904705/1180578838460235866/1180578838460235866) released [Preon demo](https://octaclone.itch.io/preon), made with HaxeFlixel

**Comment by Beeblerox** [comment]
- [ ] [Map screen](https://discord.com/channels/162395145352904705/1022291887505281025/1180327074758668298) from Hitter by naoya

**Comment by Beeblerox** [comment]
- [ ] [Travis](https://discord.com/channels/162395145352904705/162664383082790912/1182355275110432768) is doing a little somethin’ somethin’ in HaxeFlixel for the Big Mode Game Jam.

**Comment by Beeblerox** [comment]
- [ ] [Quick & dirty inversion shader](https://discord.com/channels/162395145352904705/162664383082790912/1182811902007586947) for a 'subspace warp'/damage evasion effect in Minicology

**Comment by Beeblerox** [comment]
- [ ] [A sneak-peek](https://discord.com/channels/761549092677353513/761550416504684545/1180179289950400552) of an upcoming change in LDtk 1.5: Biomes!

**Comment by skial** [comment]
- [ ] `[core/haxelib]` Move password hashing to server side [pull request](https://github.com/HaxeFoundation/haxelib/pull/617).

**Comment by skial** [comment]
- [ ] `[open source]` [globalpkg `git`](https://github.com/sidgames5/globalpkg) - Install packages from all packaging formats.

**Comment by skial** [comment]
- [ ] `[closed source]` [DCACLab's](https://twitter.com/DCACLab/status/1735012724558409824) the online circuit simulator tool have unveiled their latest feature, which offers time-domain plotting for both current & voltage!

**Comment by skial** [comment]
- [ ] `[closed source]` Try not to flip out, the Watcher's sprites are `54%` complete, by [Fraymakers](https://twitter.com/FraymakersGame/status/1733648497889693801).

**Comment by skial** [comment]
- [ ] `[closed source]` [Fraymakers](https://twitter.com/FraymakersGame/status/1732198676490342803) show a peek behind the scenes to how they create their high resolution pixel animations.

**Comment by skial** [comment]
- [ ] `[events/upcoming]` The next Discord [Haxe Roundup _Roundup_](https://discord.com/events/162395145352904705/1181007423373312140) event is scheduled for Sunday 17th Decemeber 18:30.

**Comment by skial** [comment]
- [ ] `[open source]` [haxeget `git`](https://github.com/l0go/haxeget/) - The easier way to install and manage Haxe compiler versions.

**Comment by skial** [comment]
- [ ] `[open source]` The Haxe plugin for IntelliJ, [`1.4.20`](https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.20) has been released!
