### ISSUE TITLE
Haxe Roundup 700 🤯

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1132]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` Typedef vs. GADT [fixed](https://github.com/HaxeFoundation/haxe/issues/11446).
- [ ] `[core/cpp]` Enum Type Checking [merged](https://github.com/HaxeFoundation/haxe/pull/11444).
- [ ] `[core/messageReporting]` Add config to use absolute positions [merged](https://github.com/HaxeFoundation/haxe/pull/11439).
- [ ] `[core/macro/draft]` MacroApi cleanup for Haxe 5 [pull request](https://github.com/HaxeFoundation/haxe/pull/11433).
- [ ] `[core`] Analyzer infinite loop with recursive enum values [fixed](https://github.com/HaxeFoundation/haxe/issues/11429).

**Comment by skial** [comment]
- [ ] `[core]` Aidan Lee updates us with his progress on the Async IO API - [part 1](https://github.com/HaxeFoundation/haxe/pull/9111#issuecomment-1867806093) - [part 2](https://github.com/HaxeFoundation/haxe/pull/9111#issuecomment-1867901322).

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` Do not add host architecture if an arm architecture is set [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1079).
- [ ] `[core]` Internal type parameter changes [merged](https://github.com/HaxeFoundation/haxe/pull/11436).

**Comment by skial** [comment]
- [ ] `[core]` Update hxcpp defines [merged](https://github.com/HaxeFoundation/haxe/pull/11455).
- [ ] `[core/lua]` Allow generating sourcemaps for Lua in the same format as JS [merged](https://github.com/HaxeFoundation/haxe/pull/11454).
- [ ] `[core/lua]` Fix bug in genlua causing significant slowdown in all loops [merged](https://github.com/HaxeFoundation/haxe/pull/11453), improving loop perf by 30% in limited testing.
- [ ] `[core]` Internal dependency cleanup 2023 [merged](https://github.com/HaxeFoundation/haxe/pull/11451).
- [ ] `[core]` Add @:message.follow [pull request](https://github.com/HaxeFoundation/haxe/pull/11448).

**Comment by m0rkeulv** [comment]
- [ ] `[community]` The Haxe plugin for IntelliJ, [1.4.21](https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.21) has been released!

**Comment by skial** [comment]
- [ ] `[core]` Add generator-specific ocntext [pull request](https://github.com/HaxeFoundation/haxe/pull/11471).

**Comment by skial** [comment]
- [ ] `[community]` 4 Years of `go2hx` [post](https://community.haxe.org/t/go2hx-work-in-progress/2821/14?u=skial). :star:

**Comment by skial** [comment]
- [ ] `[core/ocamhaxe]` Move towards OCaml 5 [issue](https://github.com/HaxeFoundation/ocamhaxe/issues/9).
- [ ] `[core]` A story of `cf_expr_unoptimiszed` vs `hxb` [issue](https://github.com/HaxeFoundation/haxe/issues/11460).
- [ ] `[core]` HashLink `1.4` has been [released](https://github.com/HaxeFoundation/hashlink/releases/tag/1.14).
- [ ] `[core/js]` Wrong calculation for Int64 (ushr/add) methods [issue](https://github.com/HaxeFoundation/haxe/issues/11475).
- [ ] `[core]` Missing field generation regression [issue](https://github.com/HaxeFoundation/haxe/issues/11472).
- [ ] `[core]`  Avoid creating TAnons from object declarations if we have an expected type [pull request](https://github.com/HaxeFoundation/haxe/pull/11474).
- [ ] `[core/hxcpp]` GC Pinning [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1085).
- [ ] `[core/hashlink]` `try catch` set bug [issue](https://github.com/HaxeFoundation/haxe/issues/11466).
- [ ] `[core]` Bucket typer delays [pull request](https://github.com/HaxeFoundation/haxe/pull/11465).
- [ ] `[core/hxcpp`] Remove Haxe 3 code [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1083).

---
- [ ] `[evolution]` Addition syntax for safe navigation [issue](https://github.com/HaxeFoundation/haxe-evolution/issues/114).

---
- [ ]  `[open source]` DomKit `1.0` has been [released](https://github.com/HeapsIO/domkit/releases/tag/1.0).
- [ ]  `[open source]` Heaps `2.0` has been [released](https://github.com/HeapsIO/heaps/releases/tag/2.0).

**Comment by skial** [comment]
- [ ] libs
  - [HxDiscordGateway `git`](https://lib.haxe.org/p/HxDiscordGateway)
  - [hxsdl_ttf `0.1.0`](https://lib.haxe.org/p/hxsdl_ttf)
  - [hxsdl_image `0.1.0`](https://lib.haxe.org/p/hxsdl_image)
  - [haxework `2.1.0`](https://lib.haxe.org/p/haxework)
  - [tink_domspec `0.5.2`](https://lib.haxe.org/p/tink_domspec)
  - [hxdr_mp3 `0.1.0`](https://lib.haxe.org/p/hxdr_mp3)
  - [hxglad `0.1.0`](https://lib.haxe.org/p/hxglad)
  - [HaxeGJClient `5.0.0`](https://lib.haxe.org/p/HaxeGJClient)
  - [neutralinojs `2.0.0`](https://lib.haxe.org/p/neutralinojs)
  - [openfl-spine `1.8.8`](https://lib.haxe.org/p/openfl-spine)
  - [zygameui `14.0.19`](https://lib.haxe.org/p/zygameui)
  - [hx-astcenc `1.0.0`](https://lib.haxe.org/p/hx-astcenc)
  - [epicqr `0.9.2`](https://lib.haxe.org/p/epicqr)
  - [json_http `1.0.0`](https://lib.haxe.org/p/json_http)
  - [hx-chatgpt `0.0.2`](https://lib.haxe.org/p/hx-chatgpt)
  - [HxWebView `0.0.3`](https://lib.haxe.org/p/HxWebView)
  - [bootstrap_bundle `3.0.1`](https://lib.haxe.org/p/bootstrap_bundle)
  - [hxvlc `1.1.0`](https://lib.haxe.org/p/hxvlc)
  - [hlsdl `1.14.0`](https://lib.haxe.org/p/hlsdl)
  - [hxdx `1.14.0`](https://lib.haxe.org/p/hldx)
  - [domkit `0.3.0`](https://lib.haxe.org/p/domkit)
  - [heaps `2.0.0`](https://lib.haxe.org/p/heaps)
  - [format 3.7.0`](https://lib.haxe.org/p/format)
  - [HaxeAL-Soft `1.0.1`](https://lib.haxe.org/p/HaxeAL-Soft)
  - [yukonio `1.0.0`](https://lib.haxe.org/p/yukonio)
  - [godot-extension-api-typings `1.1.1`](https://lib.haxe.org/p/godot-extension-api-typings)
  - [polybool `1.0.1`](https://lib.haxe.org/p/polybool)
  - [flixel-text-input `2.0.1`](https://lib.haxe.org/p/flixel-text-input)
  - [mc2it_theme `6.2.3`](https://lib.haxe.org/p/mc2it_theme)
  - [hxpotpack `1.0.3`](https://lib.haxe.org/p/hxpotpack)
  - [coroutine `2.0.3`](https://lib.haxe.org/p/coroutine)
  - [yield `3.2.2`](https://lib.haxe.org/p/yield)
  - [test-adapter `2.0.6`](https://lib.haxe.org/p/test-adapter)
  - [hscript-iris `1.0.2`](https://lib.haxe.org/p/hscript-iris)

**Comment by skial** [comment]
- [ ] `[devlog]` Fraymakers Development Update - January 2024 (plus 2023 Recap!) [article](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3997231).

**Comment by skial** [comment]
- [ ] `[core/macro]` `@:native` vs two macros [issue](https://github.com/HaxeFoundation/haxe/issues/11481).
- [ ] `[core/hxcpp]` Generate typed functions performance [update](https://github.com/HaxeFoundation/haxe/pull/11151#issuecomment-1881635825) from Aidan Lee.
- [ ] `[core/hxb]` HXB finishing line [todo list](https://github.com/HaxeFoundation/haxe/issues/11479).

**Comment by skial** [comment]
- [ ] `[open source]` https://github.com/skial/haxe.io/issues/1133

**Comment by skial** [comment]
- [ ] `[devlog]` Dune: Spice Wars - Community Update `#2` [Out Now](https://store.steampowered.com/news/app/1605220/view/3880477976866234295)!
  - > Changes to Conquest, UI/UX improvements & more! 
- [ ] `[devlog]` Wartales Patch Notes for [`15/12/2023`](https://store.steampowered.com/news/app/1527950/view/3904122044546906569), [`19/12/23`](https://store.steampowered.com/news/app/1527950/view/3904122044561154931), [`20/12/23`](https://store.steampowered.com/news/app/1527950/view/3877100912014175784), [`21/12/23`](https://store.steampowered.com/news/app/1527950/view/3877100912017745927) and [`04/01/24`](https://store.steampowered.com/news/app/1527950/view/3877100912064216503).
- [ ] `[devlog]` Northgard Patch Notes for [`21/12/23`](https://store.steampowered.com/news/app/466560/view/3886108111275512235).
- [ ] `[devlog]` Minicology Interstellar Intermission: [Catch Us in 2024](https://store.steampowered.com/news/app/1471700/view/3878226811923584191)!
- [ ] `[devlog]` Fraymakers [`0.6.3`](https://store.steampowered.com/news/app/1420350/view/3904122509789956883) and [`0.6.4`](https://store.steampowered.com/news/app/1420350/view/3904122509843799428) updates.
  - > Input Eating Bug Fix + Fishbunjin Spinning Piledriver!
- [ ] `[devlog]` Chibi Ninja Shino-kun: Treasure of Demon Tower [`1.0.2`](https://store.steampowered.com/news/app/2175640/view/3871471412549872805) update is out!
---

- [ ] `[releases]` Wartales: Pirates of Belerion - [Out Now](https://store.steampowered.com/news/app/1527950/view/3866967177986466449)!
- [ ] `[releases]` Bring It On! [Tundra](https://axolstudio.itch.io/bring-it-on/devlog/661769/v0141-tundra) `0.14.1` has been released!
  - > The 7th and second-to-last level for Bring It On! has been released!

**Comment by skial** [comment]
- [ ] `[video]` Scavenger Hunt in 2D Minecraft! (Mine Blocks `1.31`) [video](https://www.youtube.com/watch?v=fnR7djDnkyo).
- [ ] `[video]` Wartales, Pirates of Belerion | [Release Trailer](https://www.youtube.com/watch?v=zPtyRzit46Q).
- [ ] `[video]` Armory3d Community Channel - [I'm leaving](https://www.youtube.com/watch?v=T725r1FpWuE) video.
- [ ] `[video]` Making TicTacToe Game Using Armory3d Part 1 Grid Setup [video](https://www.youtube.com/watch?v=ohRRkBWGmSE).
- [ ] `[video]` Making TicTacToe Game Using Armory3d Part 2 RayCaster [video](https://www.youtube.com/watch?v=Dg9XpOwTGHs).
- [ ] `[video]` Armory3d Lesson 01 - Numbers and Operators [video](https://www.youtube.com/watch?v=uIKkWNSYE0o).
- [ ] `[video]` Armory3d Lesson 02 - Variables [video](https://www.youtube.com/watch?v=LCf2_7oCccg).
- [ ] `[video]` Armory3d Lesson 03 - Strings [video](https://www.youtube.com/watch?v=7Z_1l8nzAfk).
- [ ] `[video]` Armory3d Lesson 04 - Boolean [video](https://www.youtube.com/watch?v=inHZcnikPrU).
- [ ] `[video]` Short Armory3d gameplay [demo](https://www.youtube.com/watch?v=j6DILyuwja8).
- [ ] `[video]` Go! Go! PogoGirl running on Mega Drive [video](https://www.youtube.com/watch?v=MPY87WWdDCE).

**Comment by skial** [comment]
- [ ] `[open source]` [rewrite `git`](https://github.com/fourst4r/rewrite) - Small script that rewrites Haxe expressions with primitive pattern matching (inspired by gofmt).
- [ ] `[open source]` [spiel-server `git`](https://github.com/sidgames5/spiel-server) - A simple server for Spiel Messenger written in Haxe.
- [ ] `[open source]` [HxDiscordGateway `git`](https://github.com/SanicBTW/HxDiscordGateway) - Library to communicate with the Discord Gateway through WebSockets.
- [ ] `[open source]` [pbkdf2-haxe `git`](https://github.com/j-jzk/pbkdf2-haxe) - Haxe implementation of the PBKDF2 Algorithm for password hashing (library resurrection).
- [ ] `[open source]` [jsonhttphx `git`](https://github.com/dragsbruh/jsonhttphx) - Perform JSON-oriented HTTP tasks on all native (sys) platforms.
- [ ] `[open source]` [hlos `git`](https://github.com/ncannasse/hlos) - A toy operating system for HashLink VM.
- [ ] `[open source]` [air3 `git`](https://github.com/ninjamuffin99/air3) - Externs for Adobe AIR3, ported to Haxe 4.

**Comment by skial** [comment]
- [ ] `[community]` Armory3D `2024.01` [Release Notes](https://armory3d.org/notes#2024.01) via [RPaladin](https://twitter.com/RPaladin_01/status/1742653784881537029).
- [ ] `[community]` [Leo Bergman](https://twitter.com/leo_bergman/status/1743713001713098819) has posted threads about Haxe [Compilation Times](https://twitter.com/leo_bergman/status/1743713954038181912) and [Support for being declarative](https://twitter.com/leo_bergman/status/1744320305344979435) over on Twitter.

---

- [ ] `[open source]` HxGodot [finally deals](https://twitter.com/dazKind/status/1740200994607419532) properly with GC & RefCounted. HxGodot also now supports documentation generation based on official GodotEngine docs with adjustedHaxe types by [Michael Bickel](https://twitter.com/dazKind/status/1740581622393762280).
- [ ] `[open source]` [SomeRanDev](https://twitter.com/SomeRanDev/status/1735814049034567829) previews _"the hookshot ability takes a bit of skill to combo with the wall-run "_ in a Haxe Godot demo.

---

- [ ] `[releases?]` [DCACLab](https://twitter.com/DCACLab/status/1739569076551233911) just launched a new analysis type: DC Sweep. Unleash its potential and elevate your analysis experience.
- [ ] `[releases]` [Gogoprog](https://twitter.com/gogoprog/status/1736493233331425633) updated Mariah Carnage [https://gogoprog.itch.io/mariah-carnage](https://gogoprog.itch.io/mariah-carnage) with a visual feedback when the player is hit! Have fun!

---

- [ ] `[closed source]` Renaine GIFS!
  - Cute lil bird [walking back and forth](https://twitter.com/squuuidly/status/1737149290647040168) all Egyptian like ok?
  - Aeri's are speri's [with hats](https://twitter.com/squuuidly/status/1737532328962896209).
  - In Lower Factoria things... are not [going so good](https://twitter.com/RenaineGame/status/1737871298012037420).
  - Help they are [struggling](https://twitter.com/squuuidly/status/1738023581462757558)
  - These [almost-perfectly looping gnomes](https://twitter.com/RenaineGame/status/1738235448810500496) have no idea their whole tileset is gonna be replaced in a few days, anyone gonna tell them?
  - I updated [Holiday Chompy](https://twitter.com/squuuidly/status/1738597080418120012) to the most recent sprite sheet so they're free to festively chomp once again.
  - Someone left [all these presents](https://twitter.com/RenaineGame/status/1738967780861596077) for Chompy, any guesses to what's inside?
  - He's just a lil guy, [look at em' go](https://twitter.com/squuuidly/status/1739853481760985164).
  - Personally im offended that you'd [rather break physics](https://twitter.com/squuuidly/status/1740561498550985187) and sink into the floor than look at me.
  - [_Speedy Speedy_](https://twitter.com/RenaineGame/status/1744394782913568872) 💨🫧.

**Comment by skial** [comment]
- [ ] `[closed source]` Thieves stole your armor? **Shotgun Time**! via [Clyde](https://twitter.com/clydegamedev/status/1735091982438129722).
- [ ] `[closed source/hx discord]` A [small demo](https://discord.com/channels/162395145352904705/162664383082790912/1185979196560900146) of a digital circuit simulation app and a demo of [multiplexer builds](https://discord.com/channels/162395145352904705/162664383082790912/1187787862280786011) in Logimimic.
- [ ] `[closed source/hx discord]` Trying to add a cartwheeling monkey to Power Line Rider by [travis_battles](https://discord.com/channels/162395145352904705/162664383082790912/1192511273146007604).

---

- [ ] `[open source/hx discord]` With contributions from `@AltronMaxX`, [`haxeget`](https://discord.com/channels/162395145352904705/1185591971071406253/1185712931883724860) now has Windows support and supports nightly builds!
- [ ] `[open source]` [epikowa_mocky `git`](https://github.com/epikowa/epikowa_mocky) - A Haxe 4/5 mocking library.

---

- [ ] `[events/upcoming]` The next [Haxe Roundup _Roundup_](https://discord.com/events/162395145352904705/1193650994295361598) over on the Haxe Discord server is scheduled for Sunday 21st January 18:30.

---

- [ ] `[community]` 🍺Tiny Pubs `1.0.1` [article](https://www.patreon.com/posts/tiny-pubs-1-0-1-94721098) by [Oleg Dolya](https://twitter.com/watawatabou/status/1735776329985872352).
- [ ] `[community]` Avdanced features available in HashLink `1.14` [documentation](https://github.com/HaxeFoundation/hashlink/wiki/Advanced-features) via [Nicolas Cannasse](https://twitter.com/ncannasse/status/1743366255942222296).
- [ ] `[community/hx discord]` NotBilly New Year's Haxe Discord [message](https://discord.com/channels/162395145352904705/286485321925918721/1191170117443260416).

---

- [ ] `[looking for work/community?]` [Robert Konrad](https://twitter.com/robdangerous/status/1737832856523817359) might be available as a freelancer from this May, to work on console ports or performance work.

---

- [ ] `[videos]` Power Line Rider [Trailer](https://www.youtube.com/watch?v=GETz5NUSaDk).

**Comment by skial** [comment]
- [ ] `[core]` Remove some global state [merged](https://github.com/HaxeFoundation/haxe/pull/11483).
- [ ] `[core]` Don't create a class field for every enum field [merged](https://github.com/HaxeFoundation/haxe/pull/11452).
- [ ] `[core]` Add server/resetCache and use it in the server tests [pull request](https://github.com/HaxeFoundation/haxe/pull/11482).
---
- [ ] `[community]` Text to speech [question](https://community.haxe.org/t/text-to-speech/4133?u=skial).
---
- [ ] `[open source]` LDtk `1.5.0` has been [released](https://github.com/deepnight/ldtk/releases/tag/v1.5.0).
