### ISSUE TITLE
Haxe Roundup 702

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1137]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by m0rkeulv** [comment]
- [ ] `[community]` IntelliJ IDEA Haxe plugin version [1.4.25](https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.25) has been released

**Comment by skial** [comment]
Let me add that to the 701 issue im about to publish.

**Comment by skial** [comment]
- [ ] `[core/jvm]` `Reflect.callMethod` problem related to... I don't know [issue](https://github.com/HaxeFoundation/haxe/issues/11531).
- [ ] `[core/jvm]` Assign dynamic method only if it's null [merged](https://github.com/HaxeFoundation/haxe/pull/11530).
- [ ] `[core]` Hxb writer config [merged](https://github.com/HaxeFoundation/haxe/pull/11507).
- [ ] `[core]` Exhaustiveness checks thrown off by enum abstract with only null value [issue](https://github.com/HaxeFoundation/haxe/issues/11521).
- [ ] `[core]` Viability of hxb based custom backends? [discussion](https://github.com/HaxeFoundation/haxe/issues/11523).
- [ ] `[core]` Always allow local function type parameters [pull request](https://github.com/HaxeFoundation/haxe/pull/11520).
- [ ] `[core]` Class type parameter in static var [fixed](https://github.com/HaxeFoundation/haxe/issues/11528).
- [ ] `[core]` Populate cache from last context rather than hxb [discussion](https://github.com/HaxeFoundation/haxe/issues/11519).
- [ ] `[core]` Inline constructor of abstracts [fixed](https://github.com/HaxeFoundation/haxe/issues/11526).
- [ ] `[core]` Set --run args only when we're actually running [merged](https://github.com/HaxeFoundation/haxe/pull/11524).
- [ ] `[core/hxb]` Implement shared string pools [pull request](https://github.com/HaxeFoundation/haxe/pull/11511).

**Comment by skial** [comment]
- [ ] `[core]` Split up typer context [pull request](https://github.com/HaxeFoundation/haxe/pull/11534).
- [ ] `[core]` `@:structInit` on forwarded abstracts breaks when using `@:from` another structInit type [issue](https://github.com/HaxeFoundation/haxe/issues/11535).

**Comment by skial** [comment]
- [ ] `[core]` Remove C# and Java targets [merged](https://github.com/HaxeFoundation/haxe/pull/11551).
- [ ] `[core]` Typedefs are not enums [pull request](https://github.com/HaxeFoundation/haxe/pull/11550).
- [ ] `[core]` Typer cleanup continued [merged](https://github.com/HaxeFoundation/haxe/pull/11548).
- [ ] `[core/jvm]` Rework functional interface unification [pull request](https://github.com/HaxeFoundation/haxe/pull/11544).
- [ ] `[core]` Make `ctx.pass` immutable [merged](https://github.com/HaxeFoundation/haxe/pull/11538).
- [ ] `[core]` Skip abstract impl classes when applying `addGlobalMetadata` [merged](https://github.com/HaxeFoundation/haxe/pull/11546).
- [ ] `[core]` Remove 32bit Windows builds [pull request](https://github.com/HaxeFoundation/haxe/pull/11541).
- [ ] `[core]` Delete `Reflect.deleteField` [discussion](https://github.com/HaxeFoundation/haxe/issues/11543).
- [ ] `[core/haxe.org]` Add nightlies page [merged](https://github.com/HaxeFoundation/haxe.org/pull/470).
- [ ] `[core]` Simplify type parameter typing [merged](https://github.com/HaxeFoundation/haxe/pull/11537).
- [ ] `[core/macro]` Remove some API from `haxe.marcro.Compiler` [merged](https://github.com/HaxeFoundation/haxe/pull/11540).
---
- [ ] `[evolution]` Add Type based enums [proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/115).

**Comment by skial** [comment]
- [ ] `[core]` Allow `@:using` with Class and Enum [pull request](https://github.com/HaxeFoundation/haxe/pull/11553).

**Comment by skial** [comment]
- [ ] `[core]` Only allow `Void` in return types [pull request](https://github.com/HaxeFoundation/haxe/pull/11558).
- [ ] `[core]` Default type parameters vs constraints [issue](https://github.com/HaxeFoundation/haxe/issues/11556).
- [ ] `[core]` Coroutine experiments but without the TFun change [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11554).
---
- [ ] `[community]` Enums and `@:rtti` [community question](https://community.haxe.org/t/enums-and-rtti/4168?u=skial).
- [ ] `[community]` OpenFL devlog: HashLink/C compilation [article](https://joshblog.net/2024/openfl-devlog-hashlink-c-compilation/) by Josh Tynjala.
---
- [ ] `[devlogs]` Minicology [Auto-saws and Auto-harvesters](https://store.steampowered.com/news/app/1471700/view/4044863966191032639), Mimic Eels, [Mysterious Artifacts, Crashfixes](https://store.steampowered.com/news/app/1471700/view/4044863966180642406), [Fire Eels](https://store.steampowered.com/news/app/1471700/view/4044863802195310475) and [Pink zone POI](https://store.steampowered.com/news/app/1471700/view/3987442273063687840) updates.
- [ ] Northgard in 2024 [article](https://store.steampowered.com/news/app/466560/view/3961546575204461525).
- [ ] Fraymakers Frame 1 Random Desync [devlog](https://store.steampowered.com/news/app/1420350/view/3976183273972887814).
---
- libs
   - [hxluajit `1.0.0`](https://lib.haxe.org/p/hxluajit)
   - [SScript `10.0.618-beta`](https://lib.haxe.org/p/SScript)
   - [flixel `5.6.0`](https://lib.haxe.org/p/flixel)
   - [hxWebP `0.1.1`](https://lib.haxe.org/p/hxWebP)
   - [modifaxe.json `1.0.0`](https://lib.haxe.org/p/modifaxe.json)
   - [proxsys `0.2.1`](https://lib.haxe.org/p/proxsys)
   - [hxdr_mp3 `0.1.2`](https://lib.haxe.org/p/hxdr_mp3)
   - [hxdr_wav `0.1.2`](https://lib.haxe.org/p/hxdr_wav)
   - [pony `1.9.8`](https://lib.haxe.org/p/pony)
   - [codegen `1.7.1`](https://lib.haxe.org/p/codegen)
   - [injector `1.1.0`](https://lib.haxe.org/p/injector)
   - [classic-for `0.4.0`](https://lib.haxe.org/p/classic-for)
   - [torchsfunctions `0.3.2`](https://lib.haxe.org/p/torchsfunctions)
   - [input2action `0.7.1`](https://lib.haxe.org/p/input2action)
   - [wquery `1.0.0`](https://lib.haxe.org/p/wquery)
   - [mongomod `1.0.5`](https://lib.haxe.org/p/mongomod)
   - [codemirror `1.1.2`](https://lib.haxe.org/p/codemirror)
   - [bootstrap `1.0.7`](https://lib.haxe.org/p/bootstrap)
   - [serializator `1.0.2`](https://lib.haxe.org/p/serializator)
   - [yuidoc2haxe `1.5.6`](https://lib.haxe.org/p/yuidoc2haxe)
   - [xpcom `1.4.1`](https://lib.haxe.org/p/xpcom)
   - [winapi `1.0.2`](https://lib.haxe.org/p/winapi)
   - [websocket `2.0.3`](https://lib.haxe.org/p/websocket)
   - [unicode `1.4.1`](https://lib.haxe.org/p/unicode)
   - [undoqueue `1.0.2`](https://lib.haxe.org/p/undoqueue)
   - [tweenjs `1.0.3`](https://lib.haxe.org/p/tweenjs)
   - [threejs `91.0.1`](https://lib.haxe.org/p/threejs)
   - [stdlib `2.2.3`](https://lib.haxe.org/p/stdlib)
   - [soundjs `0.6.3`](https://lib.haxe.org/p/soundjs)
   - [session `1.2.3`](https://lib.haxe.org/p/session)
   - [requirejs `1.0.1`](https://lib.haxe.org/p/requirejs)
   - [refactor `4.3.0`](https://lib.haxe.org/p/refactor)
   - [profiler `1.0.7`](https://lib.haxe.org/p/profiler)
   - [preloadjs `0.6.3`](https://lib.haxe.org/p/preloadjs)
   - [phpnatives `3.2.1`](https://lib.haxe.org/p/phpnatives)
   - [orm `2.1.1`](https://lib.haxe.org/p/orm)
   - [ndllfinder `1.1.2`](https://lib.haxe.org/p/ndllfinder)
   - [haxescript `1.0.3`](https://lib.haxe.org/p/haxescript)
   - [ImageMagick `1.6.5`](https://lib.haxe.org/p/ImageMagick)
   - [jsprop `2.1.1`](https://lib.haxe.org/p/jsprop)
   - [jsonmod `1.1.1`](https://lib.haxe.org/p/jsonmod)
   - [jslibs `1.2.2`](https://lib.haxe.org/p/jslibs)
   - [jsfl `1.2.5`](https://lib.haxe.org/p/jsfl)
   - [jquery `1.5.3`](https://lib.haxe.org/p/jquery)
   - [hxnodejs-rgbquant `1.1.3`](https://lib.haxe.org/p/hxnodejs-rgbquant)
   - [HtmlParser `3.3.3`](https://lib.haxe.org/p/HtmlParser)
   - [hant `3.7.3`](https://lib.haxe.org/p/hant)
   - [fontjs `1.0.3`](https://lib.haxe.org/p/fontjs)
   - [fcgi `1.1.4`](https://lib.haxe.org/p/fcgi)

**Comment by Beeblerox** [comment]
- [ ] Characters in Fantasy Sphere by Peter Achberger can [hide behind trees](https://twitter.com/PeterAchberger/status/1750906055528210665) now

**Comment by Beeblerox** [comment]
- [ ] [Into the Necrovale](https://store.steampowered.com/app/1717090/Into_the_Necrovale/) is live! via [Clyde](https://twitter.com/clydegamedev/status/1750981397672837547)

**Comment by Beeblerox** [comment]
- [ ] New quick videos from Jitter Game by Syo:
    * [Experiments with multi-layered music](https://twitter.com/SyoPic/status/1751197922719346955), mood changes 
    * I can't wait to show you the full demo, but it's still [a work in progress](https://twitter.com/SyoPic/status/1753746420715192489). Hopefully it will be playable this month.
    * [1 minute to go](https://twitter.com/SyoPic/status/1753901101651239401)

**Comment by Beeblerox** [comment]
- [ ] New devlogs from [Oleg Dolya](https://twitter.com/watawatabou):
    * 🔑[Dwellings 1.3.1](https://www.patreon.com/posts/97493516): small improvements and experiments
    * ☠️[Perilous Shores 1.6.3](https://www.patreon.com/posts/perilous-shores-98030728): improved forests

**Comment by Beeblerox** [comment]
- [ ] [Ship of Fools](https://sertradough.itch.io/ship-of-fools) made in 48 hourse for the 2024 Global Game Jam

**Comment by Beeblerox** [comment]
- [ ] [Addlemoth Dev Update](https://mauve.itch.io/addlemoth/devlog/673255/addlemoth-dev-update-january-2024): January 2024 by [mauve](https://twitter.com/mauvecow/status/1752472377911648356)
- [ ] Here is also [screenshots of 3 new stages](https://twitter.com/mauvecow/status/1754383767723196482) for Addlemoth made on stream

**Comment by Beeblerox** [comment]
- [ ] New GIFs and screenshot from [Renaine](https://store.steampowered.com/app/662340/Renaine/):
    * [but it will be with a lil...](https://twitter.com/squuuidly/status/1752496661597667829)
    * [the oddly named puffcop](https://twitter.com/RenaineGame/status/1752741770243240133) is a variant of the puffdrop that patrols left and right before dropping down on you
    * [wip bathysphere](https://twitter.com/squuuidly/status/1753188540588925338), ignore the second aine sinking in the ground looking confused as her front facing doppelganger is inside

**Comment by Beeblerox** [comment]
- [ ] [Things are going great](https://twitter.com/deepnightfr/status/1753513734411280430) with Tenjutsu Project by Deepnight Games

**Comment by Beeblerox** [comment]
- [ ] [Does this look familiar?](https://twitter.com/gogoprog/status/1754062008893272419) by Gauthier Billot

**Comment by Beeblerox** [comment]
- [ ] [textbox should be accurate](https://discord.com/channels/162395145352904705/1190890266450743297/1201903808352100422) in Undertale Purple by EyeDaleHim

**Comment by Beeblerox** [comment]
- [ ] [Heaps Editor](https://github.com/nayata/editor) by [Nayata](https://discord.com/channels/162395145352904705/1203833500319358976/1203833500319358976)

**Comment by Beeblerox** [comment]
- [ ] Prexot made [made a trailer](https://discord.com/channels/162395145352904705/1020075437080191096/1200319798828081202) for their [Rhythm Magus](https://goldenpigames.itch.io/rhythm-magus) game

**Comment by Beeblerox** [comment]
- [ ] [Learn Haxe with HaxeFlixel](https://www.youtube.com/playlist?list=PLLrBJXzcw-ddqs3tf31Qj-eN67WwR-uQa) video series by [the other mako](https://discord.com/channels/162395145352904705/162664383082790912/1200389486253707325)

**Comment by Beeblerox** [comment]
- [ ] [canabalt-hf](https://github.com/ninjamuffin99/canabalt-hf) - a HaxeFlixel port of CANABALT, by Adam 'Atomic' Saltsman, ported by Cameron 'ninjamuffin99' Taylor

**Comment by Beeblerox** [comment]
- [ ] [Josh Tynjala](https://discord.com/channels/415681294446493696/436230004251164672/1202040184716402688) added the [Working with the file system](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/) chapter to the OpenFL Developer's Guide

**Comment by skial** [comment]
- [ ] `[core]` Add empty enum as `haxe.Unit` [pull request](https://github.com/HaxeFoundation/haxe/pull/11563).
---
- [ ] `[open source]` [kit.file `git`](https://github.com/wartman/kit.file) - File tools for Haxe.
- [ ] `[open source]` [editor `git`](https://github.com/nayata/editor) - Minimal 2D edutir written in Haxe Heaps.
- [ ] `[open source]` [hltml `git`](https://github.com/ncannasse/hltml) - HL Partial HTML emulation in Domkit.
---
- [ ] `[events/upcoming]` The next Discord [Haxe Roundup _Roundup_](https://discord.com/events/162395145352904705/1204062012662095882) event is this Sunday 11th at 18:30.
---
- [ ] `[releases]` [Ship of Fools](https://sertradough.itch.io/ship-of-fools) made in 48 hours for 2024 Global Game Jam.
---
- [ ] `[video]` Ship of Fools [trailer](https://www.youtube.com/watch?v=KJ0bR7irtHU).
- [ ] `[video]` Armory3D Lesson 25 Environment Animation [video](https://www.youtube.com/watch?v=s407-Y85OSw).

**Comment by skial** [comment]
- [ ] keep  #1138 content for another issue.
