### ISSUE TITLE
Haxe Roundup 703

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1140]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core/hxb]` Add OFD and OBD chunks [merged](https://github.com/HaxeFoundation/haxe/pull/11564).

**Comment by skial** [comment]
- [ ] `[core]` Coroutine updates and example transofrmation [comments](https://github.com/HaxeFoundation/haxe/pull/11554#issuecomment-1943185518).
- [ ] `[core]` Expceptions refactor [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11574).
- [ ] `[core]` Null coalescing `bind` does nothing [issue](https://github.com/HaxeFoundation/haxe/issues/11571).

**Comment by skial** [comment]
- [ ] `[core]` Enum abstract not checked [issue](https://github.com/HaxeFoundation/haxe/issues/11577).

**Comment by skial** [comment]
- [ ] `[hxcpp]` Fix Android for large builds [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1091).
- [ ] `[core]` The latest [comments and discussions](https://github.com/HaxeFoundation/haxe/pull/11554#issuecomment-1946165294) on developing coroutines.
- [ ] `[core/bugfix]` Haxe `4.3.4` [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11583).
- [ ] `[hl]` hlopt rework try-catch control flow [pull request](https://github.com/HaxeFoundation/haxe/pull/11581).
- [ ] `[core/macro]` Build order vs inheritance [merged](https://github.com/HaxeFoundation/haxe/pull/11582).
---
- [ ] `[community]` Right Tools for iOS and Android App Development [thread](https://community.haxe.org/t/haxe-right-tools-for-ios-and-android-app-development/4179?u=skial)

**Comment by skial** [comment]
- [ ] `[core]` Unify help messages handling [merged](https://github.com/HaxeFoundation/haxe/pull/11584).
- [ ] `[core]` Pretty errors as default message reporting [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11587).
- [ ] `[core]` Null safety hole with array access [issue](https://github.com/HaxeFoundation/haxe/issues/11585).
- [ ] `[core]` `@:structInit` ambiguity when `@:from` between abstract forwarded types [issue](https://github.com/HaxeFoundation/haxe/issues/11586).
---
- [ ] `[community]` A super-late update on Dead Cells [article](https://store.steampowered.com/news/app/588650/view/4020094639145168178).
- [ ] `[community]` Regarding Dead Cells termination [article](https://deepnight.net/blog/regarding-dead-cells-termination/) by Sébastien Benard.
- [ ] `[community]` Dune: Spice Wars has been [awarded](https://store.steampowered.com/news/app/1605220/view/6923791230069832958) Strategy / Simulation Game of the Year.
---
- [ ] `[devlog]` Bring It On! [`0.14.6`](https://store.steampowered.com/news/app/2020460/view/4018968739248830283) and [`0.14.7`](https://store.steampowered.com/news/app/2020460/view/6697485348307987751) updates.
---
- libs
   - [jsprop `2.2.0`](https://lib.haxe.org/p/jsprop)
   - [HxWebView `0.0.5`](https://lib.haxe.org/p/HxWebView)
   - [hxvlc `1.3.0`](https://lib.haxe.org/p/hxvlc)
   - [easeljs `3.0.1`](https://lib.haxe.org/p/easeljs)
   - [threejs-addons `161.0.2`](https://lib.haxe.org/p/threejs-addons)
   - [threejs `161.0.2`](https://lib.haxe.org/p/threejs)
   - [stdlib `3.1.1`](https://lib.haxe.org/p/stdlib)
   - [hxnodejs-re-htmlparser `3.4.0`](https://lib.haxe.org/p/hxnodejs-re-htmlparser)
   - [yuidoc2haxe `1.5.7`](https://lib.haxe.org/p/yuidoc2haxe)
   - [tweenjs `2.0.0`](https://lib.haxe.org/p/tweenjs)
   - [soundjs `1.0.0`](https://lib.haxe.org/p/soundjs)
   - [refactor `4.4.1`](https://lib.haxe.org/p/refactor)
   - [preloadjs `1.0.0`](https://lib.haxe.org/p/preloadjs)
   - [fonthx `0.0.8`](https://lib.haxe.org/p/fonthx)
   - [SScript `10.1.618`](https://lib.haxe.org/p/SScript)
   - [hxnodejs-wquery `1.1.1`](https://lib.haxe.org/p/hxnodejs-wquery)
   - [hant `3.8.0`](https://lib.haxe.org/p/hant)
   - [wquery `1.1.1`](https://lib.haxe.org/p/wquery)
   - [undoqueue `1.1.0`](https://lib.haxe.org/p/undoqueue)
   - [datatools `2.0.0`](https://lib.haxe.org/p/datatools)
   - [codegen `2.1.0`](https://lib.haxe.org/p/codegen)
   - [test-adapter `2.0.7`](https://lib.haxe.org/p/test-adapter)
   - [HxWebView `0.0.4`](https://lib.haxe.org/p/HxWebView)
   - [formatter `1.16.0`](https://lib.haxe.org/p/formatter)
   - [flixel `5.6.2`](https://lib.haxe.org/p/flixel)
   - [tokentree `1.2.11`](https://lib.haxe.org/p/tokentree)

**Comment by Beeblerox** [comment]
- [ ] Freestyle Engine Dev Build : 0021 : [Introducing - Freestyle Mod Files](https://twitter.com/Rapper_GF_Dev/status/1756715406486626437) (.fsm) A WIP feature that should make adding mods as easy as drag n dropping

**Comment by Beeblerox** [comment]
- [ ] Giving the [HaxeFlixel tutorial a facelift](https://twitter.com/HaxeFlixel/status/1758255705511915748) with some help from Kenney
's amazing assets

**Comment by Beeblerox** [comment]
- [ ] 🏰[Medieval Fantasy City Generator 0.10.1](https://www.patreon.com/posts/98918904) by [Oleg Dolya](https://twitter.com/watawatabou/status/1760339650382594325)

**Comment by Beeblerox** [comment]
- [ ] ✨ Fraymakers is [coming to PAX East(https://twitter.com/FraymakersGame/status/1758995731216753015) ✨on March 21st-24th

**Comment by Beeblerox** [comment]
- [ ] It's 2024! [What's up with Ceramic?](https://ceramic-engine.com/blog/ceramic-2024/)

**Comment by Beeblerox** [comment]
- [ ] Move and jump in 4 directions in [Sides of Gravity](https://poki.com/en/g/sides-of-gravity), a new puzzle platformer by [Robert Alvarez](https://twitter.com/Rob1221dev/status/1760001038159876125)

**Comment by Beeblerox** [comment]
- [ ] [NotBilly](https://discord.com/channels/162395145352904705/1209142804819869736/1209142804819869736) is working on [HaxeUI Ceramic backend](https://github.com/Jarrio/haxeui-ceramic)

**Comment by Beeblerox** [comment]
- [ ] [Electr0Gunner](https://discord.com/channels/162395145352904705/1209220244854415440/1209220244854415440) is working [on a fork](https://github.com/Electr0Gunner/PlantsVSZombiesHaxeEngine/tree/main) of Cheese-Curd's Pvz Haxe Edition

**Comment by Beeblerox** [comment]
- [ ] [Discord GameSDK](https://github.com/ahika462/discord_game_sdk) for Haxe (C++ targets). There are [plans to make](https://discord.com/channels/162395145352904705/1207566473392816168/1207566473392816168) C, C# and maybe JS targets

**Comment by Beeblerox** [comment]
- [ ] [Xerox](https://github.com/Ethan-makes-music/Xerox) by [Axuko](https://discord.com/channels/162395145352904705/1205442860749553674/1205442860749553674)

**Comment by Beeblerox** [comment]
- [ ] [TheMysticSword](https://discord.com/channels/162395145352904705/162664383082790912/1205984777698672670) published a v0.1 of [Mechanism That Brings Disaster](https://themysticsword.itch.io/mechanism-that-brings-disaster) game
- [ ] Mechanism That Brings Disaster - [v0.1 Gameplay Preview](https://www.youtube.com/watch?v=HSjHZHg3gu8)

**Comment by Beeblerox** [comment]
- [ ] Michael Bickel is fiddling with one of their HxGodot Projects: Rewriting chaotic spaghetti code FPS controller [using statecharts](https://discord.com/channels/162395145352904705/162664383082790912/1207633603710820413) and realtime debug visualization. It's a therapeutic experience 😛

**Comment by Beeblerox** [comment]
- [ ] [BASTON is back on track!](https://twitter.com/TxoriCom/status/1749467546934239254) thread

**Comment by skial** [comment]
- [ ] `[community]` IntelliJ IDEA Haxe plugin version [`1.4.43`](https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.43) has been released.
