### ISSUE TITLE
Haxe Roundup 705

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1144]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by EyeDaleHim** [comment]
- [ ] Undertale Purple Announcement [Teaser](https://youtu.be/rjlOHruXsBA)

**Comment by skial** [comment]
- [ ] `[open source]` Lime `8.1.2` has been [released](https://github.com/openfl/lime/releases/tag/8.1.2).
- [ ] `[open source]` OpenFL `9.3.3` has been [released](https://github.com/openfl/openfl/releases/tag/9.3.3).
- [ ] `[open source]` Haxe-strings `7.0.4` has been [released](https://github.com/vegardit/haxe-strings/releases/tag/v7.0.4).
---
- [ ] `[evolution]` Add Auto Closing [proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/119).
- [ ] `[evolution]` Add additional mathematical constants and functions [discussion](https://github.com/HaxeFoundation/haxe-evolution/pull/117).
---
- [ ] `[core]` Iterable arg is not inlineable [issue](https://github.com/HaxeFoundation/haxe/issues/11602).
- [ ] `[core]` Fix cast error if `Std.string` fails [pull request](https://github.com/HaxeFoundation/haxe/pull/11607).
- [ ] `[core]` Getter + incrememnt `haxe.Int64` variable compile error [issue](https://github.com/HaxeFoundation/haxe/issues/11605).
- [ ] `[core/hxcs]` Adding dotnet core support to hxcs [pull request](https://github.com/HaxeFoundation/hxcs/pull/53).
- [ ] `[core/hl]` Fixed hxbutes compare [pull request](https://github.com/HaxeFoundation/haxe/pull/11610).
- [ ] `[core]` Only write default Connection header to HTTP requests if needed [merged](https://github.com/HaxeFoundation/haxe/pull/11604).
- [ ] `[core/hashlink]` HL/C CArray code generation has unnecessary cast for known types [issue](https://github.com/HaxeFoundation/haxe/issues/11611).
- [ ] `[core]` Add `-D fail-fast` [pull request](https://github.com/HaxeFoundation/haxe/pull/11609).
---
- [ ] `[community]` ☠️Perilous Shores `1.6.4`: improved islands and peninsulas [article](https://www.patreon.com/posts/perilous-shores-99908396).
- [ ] `[community]` 🏰Medieval Fantasy City Generator `0.10.2`: alleys view [article](https://www.patreon.com/posts/medieval-fantasy-100431269).

**Comment by skial** [comment]
- [ ] libs
   - [haxe-strings `7.0.4`](https://lib.haxe.org/p/haxe-strings)
   - [neataptic-js `0.0.2`](https://lib.haxe.org/p/neataptic-js)
   - [SScript `17.0.618`](https://lib.haxe.org/p/SScript)
   - [proxsys `0.3.0`](https://lib.haxe.org/p/proxsys)
   - [flixel-ui `2.6.0`](https://lib.haxe.org/p/flixel-ui)
   - [stdlib `3.1.3`](https://lib.haxe.org/p/stdlib)
   - [easeljs `3.0.3`](https://lib.haxe.org/p/easeljs)
   - [datatools `2.0.1`](https://lib.haxe.org/p/datatools)
   - [codegen `2.1.2`](https://lib.haxe.org/p/codegen)
   - [omggif `0.9.0`](https://lib.haxe.org/p/omggif)
   - [electron `29.1.4`](https://lib.haxe.org/p/electron)
   - [markdown-openfl-textfield `1.0.3`](https://lib.haxe.org/p/markdown-openfl-textfield)
   - [amfio `1.0.2`](https://lib.haxe.org/p/amfio)
   - [openfl `9.3.3`](https://lib.haxe.org/p/openfl)
   - [lime `8.1.2`](https://lib.haxe.org/p/lime)
   - [haxeium `1.1.1`](https://lib.haxe.org/p/haxeium)
   - [hxAwsSdk `0.0.5`](https://lib.haxe.org/p/hxAwsSdk)
   - [awslambda-hl `0.0.3`](https://lib.haxe.org/p/awslambda-hl)
   - [hxbun `0.0.2`](https://lib.haxe.org/p/hxbun)
   - [flixel-addons `3.2.2`](https://lib.haxe.org/p/flixel-addons)
   - [hxcpp-debug `1.2.4`](https://lib.haxe.org/p/hxcpp-debug)
   - [HaxeAL-Soft `1.1.0`](https://lib.haxe.org/p/HaxeAL-Soft)
---
- [ ] `[community]` Week of `2024/03/12`: the funkblog with factorio references... [article](https://funkin.me/blog/2024-03-12/).

**Comment by skial** [comment]
- [ ] `[community]` Minicology E-Corp Intergalactic Almanac: Shape Your Own Planets [article](https://store.steampowered.com/news/app/1471700/view/7353887524194745791).
- [ ] `[community]` Fraymakers EA Update `v0.6.8` - Training Mode Overhaul, Replay Options, and Optimization [article](https://store.steampowered.com/news/app/1420350/view/4141694364920308627).
- [ ] `[community]` Rivals and Allies Out Now for [Northgard](https://store.steampowered.com/news/app/466560/view/4101161968274202265)!
- [ ] `[community]` Heros of [Dune Out Now](https://store.steampowered.com/news/app/1605220/view/4154078631372669175)!
---
- [ ] `[devlog]` Dune: Spice Wars [`13/03/24`](https://store.steampowered.com/news/app/1605220/view/4129310099714269768) patch notes.
- [ ] `[devlog]` Wartales [`13/03/24`](https://store.steampowered.com/news/app/1527950/view/4116925200739190493) patch notes.
- [ ] `[devlog]` Northgard [`11/03/24`] [hotfix](https://store.steampowered.com/news/app/466560/view/4101161968292119171) and Rival and Allies [`07/03/24`](https://store.steampowered.com/news/app/466560/view/4101161968277711324) patch notes.
---
- [ ] `[releases]` Dune: Spice Wars HouseVernius of Ix [available now](https://store.steampowered.com/news/app/1605220/view/4154078631372415882)!
- [ ] `[releases]` Northgard Steam Spring Sale has [started](https://store.steampowered.com/news/app/466560/view/5967904736247614611)!
--- 
- [ ] `[core/hl]` Rework `Null<Int/Float/Bool>` comparison for spec/alloc [pull request](https://github.com/HaxeFoundation/haxe/pull/11612).

**Comment by skial** [comment]
- [ ] `[core]` `Reflect.hasField` returns false on property getters on the JavaScript target [issue](https://github.com/HaxeFoundation/haxe/issues/11613).
---
- [ ] `[video]` Dune: Spice Wars | House Vernius of Ix [trailer](https://www.youtube.com/watch?v=Ch09cT3HG1M).
- [ ] `[video]` Armory3d Timer [tutorial](https://www.youtube.com/watch?v=4LG3q8OYlzw).
- [ ] `[video]` Armory3d Functions [part 1](https://www.youtube.com/watch?v=UVL_eh2VjAs) and [part 2](https://www.youtube.com/watch?v=w_EijNlMFK0).

**Comment by AlexHaxe** [comment]
- [ ] `[community]` Step up your testing game with UI tests  [article](https://community.haxe.org/t/step-up-your-testing-game-with-ui-tests/4204)

**Comment by skial** [comment]
- [ ] `[core/server]` Add define to see what modules trigger most invalidation [draft pull request](https://github.com/HaxeFoundation/haxe/pull/11616).
- [ ] `[core/hashlink]` Fix `UI8` assign on Linux [pull request](https://github.com/HaxeFoundation/hashlink/pull/665).
- [ ] `[core/macro]` Remove `CompilationServer.setModuleCheckPolicy` [pull request](https://github.com/HaxeFoundation/haxe/pull/11615).
---
- [ ] `[open source]` NME `6.3.54` has been [released](https://github.com/haxenme/nme/releases/tag/v6.3.54).
---
- [ ] `[community]` OpenFL `9.3.3` and Lime `8.1.2` releases [announcement post](https://community.openfl.org/t/openfl-9-3-3-and-lime-8-1-2-release/13902?u=skial.bainn).
- [ ] `[upcoming/event]` The next Haxe Roundup _Roundup_ Discord [event](https://discord.com/events/162395145352904705/1219013893867962473) is scheduled for the 14th April 19:30.

**Comment by EyeDaleHim** [comment]
- [ ] Friday Night Funkin' [Erect Mode Sampler](https://youtu.be/bkBjhkpOcUM) by Funkin' Crew

**Comment by skial** [comment]
- [ ] `[core/hashlink]` Check for Vulkan or Metal request and don't force OpenGL [pull request](https://github.com/HaxeFoundation/hashlink/pull/666).

**Comment by skial** [comment]
- [ ] `[open source]` [haxe-threading-example `git`](https://github.com/47rooks/haxe-threading-examples) - Haxe Threading examples.
