### ISSUE TITLE
Haxe Roundup 706

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1146]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by EyeDaleHim** [comment]
- [ ] The HaxeFlixel website received a new section [on the main page](https://github.com/HaxeFlixel/haxeflixel.com/pull/257) plus some minor tweaks.

**Comment by EyeDaleHim** [comment]
- [ ] The Undertale Purple team has released [three new soundtracks](https://www.youtube.com/playlist?list=PLwul-9oMpDXqNrSGzN3AQeGdcfbSnurvI) as sneak peeks.

**Comment by skial** [comment]
- [ ] `[evolution/discussion]` Cast Specification [discussion](https://github.com/HaxeFoundation/haxe-evolution/issues/120).
---
- [ ] `[community]` IntelliJ IDEA Haxe Plugin [version 1.4.47](https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.47) has been released.
- [ ] `[community]` The latest async io update from Aidan on [Object Lifetimes](https://github.com/HaxeFoundation/haxe/pull/9111#issuecomment-2028892207).
- [ ] `[community]` Given only a reference to a method, can I get the instance the method belongs to in Haxe? [question & answer](https://community.haxe.org/t/given-only-a-reference-to-a-method-can-i-get-the-instance-the-method-belongs-to-in-haxe/4205?u=skial).
- [ ] `[community]` Minicology: E-Corp Intergalactic Almanac: The Nano-Tool [article](https://store.steampowered.com/news/app/1471700/view/4110170432154781712).
---
- [ ] `[devlog]` Wartales Roadmap Update for [`21/03/24`](https://store.steampowered.com/news/app/1527950/view/4113548131862199218).
- [ ] `[devlog]` Dune: Spice Wars patch notes for [`02/04/24`](https://store.steampowered.com/news/app/1605220/view/4177725061518027039).
- [ ] `[devlog]` Northgard patch notes for [`26/03/24`](https://store.steampowered.com/news/app/466560/view/4147325129091965584), plus, Claws & Jaws preview - [Wild Foes](https://store.steampowered.com/news/app/466560/view/4147325129091159809).
- [ ] `[devlog]` Bring It On! [`0.14.16`](https://axolstudio.itch.io/bring-it-on/devlog/701911/v01416-bug-fixes-and-improvements-galore) bugs fixes and improvements galore!
---
- [ ] `[core]` Delay macro build order change with `-D haxe-next` [pull request](https://github.com/HaxeFoundation/haxe/pull/11622).
- [ ] `[core/hxb]` Detect need for local context in nested anons [merged](https://github.com/HaxeFoundation/haxe/pull/11617).
- [ ] `[core]` Catch missing standard library in init macros [merged](https://github.com/HaxeFoundation/haxe/pull/11621).
- [ ] `[core/hashlink]` `Single` and `hl.F32` function args for `callMethod` stack issue [fixed](https://github.com/HaxeFoundation/hashlink/issues/670).
- [ ] `[core]` Fix `@:generic` with multiple calls [merged](https://github.com/HaxeFoundation/haxe/pull/11619).
- [ ] `[core/hxcpp]` Abstract wrapping extern cannot find the extern [issue](https://github.com/HaxeFoundation/hxcpp/issues/1099).
---
- [ ] `[open source]` haxe-strings `7.0.5` has been [released](https://github.com/vegardit/haxe-strings/releases/tag/v7.0.5).
---
- [ ] libs
   - [gmodhaxe `0.3.0`](https://lib.haxe.org/p/gmodhaxe)
   - [hxAwsSdk `0.0.7`](https://lib.haxe.org/p/hxAwsSdk)
   - [haxe-github `1.1.3`](https://lib.haxe.org/p/haxe-github)
   - [haxe-strings `7.0.5`](https://lib.haxe.org/p/haxe-strings)
   - [hxWebP `0.4.0`](https://lib.haxe.org/p/hxWebP)
   - [hxbun `0.1.0`](https://lib.haxe.org/p/hxbun)
   - [SScript `17.2.618`](https://lib.haxe.org/p/SScript)
   - [hxchart `0.0.1`](https://lib.haxe.org/p/hxchart)
   - [Emitter `0.9.0`](https://lib.haxe.org/p/Emitter)
   - [redistHelper `0.7.6`](https://lib.haxe.org/p/redistHelper)
   - [thrift `0.20.0`](https://lib.haxe.org/p/thrift)

**Comment by skial** [comment]
- [ ] `[video]` Armory3D Tutorial 30 Game Over [video](https://www.youtube.com/watch?v=bYy2jyI_7J4).
---
- [ ] `[open source]` [Copper-MC `git`](https://github.com/TheUnderName/Copper-MC) - Minecraft bedrock edition server written in Haxe.
- [ ] `[open source]` [Haxe-UnRAR `git`](https://github.com/Snirozu/Haxe-UnRAR) - Haxe C++ native externs for UnRAR.
- [ ] `[open source]` [blok.router `git`](https://github.com/blok-ui/blok.router) - Simple routing for Blok.
- [ ] `[open source]` [jbuff `git`](https://github.com/onehundredfeet/jbuff) - JSON w/Buffer File Format.
- [ ] `[open source]` [Emitter `git`](https://github.com/Dimensionscape/Emitter) - A tiny, fast, and lightweight signal emitter for Haxe.
---
- [ ] `[open source/haxe discord]` DazKind shows off [hot-reloading](https://discord.com/channels/162395145352904705/565569107701923852/1224797174576058530) a HaxeUI project.
- [ ] `[open source/haxe discord]` Ian Harrigan showcases [Glint Analytics](https://discord.com/channels/162395145352904705/162664383082790912/1220349992150241342), a crypto data analytics visualization platform in closed beta, fully built in HaxeUI.
---
- [ ] `[closed source/haxe discord]` Travis is still messing around with in the game colours of [Power Line Rider](https://discord.com/channels/162395145352904705/162664383082790912/1220417223773126727). Plus a preview of the [new colour scheme](https://discord.com/channels/162395145352904705/162664383082790912/1222932877218545727) for all three regions.
---
- [ ] `[releases/haxe discord]` Slameron has released [Diced Up!](https://discord.com/channels/162395145352904705/162664383082790912/1223318011382075453), a shooter where you get new perks and unlock new weapons as floors progress, available on [Newgrounds](https://www.newgrounds.com/portal/view/923658).
- [ ] `[releases/haxe discord]` Zwodahs has released [Kadoko](https://zwodahs.itch.io/kadoko), a short deduction game, sudoku + poker.

**Comment by skial** [comment]
- [ ] `[core]` Apply `@:using` after build macros [merged](https://github.com/HaxeFoundation/haxe/pull/11625).
- [ ] `[core]` Missing type parameter infor when return type inferred from interface [issue](https://github.com/HaxeFoundation/haxe/issues/11624).
---
- [ ] `[open source]` [Michael Bickel](https://twitter.com/dazKind/status/1774451702864777546) has been _"messing with some secret Haxe engine work"_, creating a live coding prototype mixing bgfx and nanovg with cppia.
---
- [ ] `[closed source]` Cremini movement glitch o shmoovement tech? in [Renaine](https://twitter.com/squuuidly/status/1775380898906599574).
- [ ] `[closed source]` [Geokureli](https://twitter.com/Geokureli/status/1774947281877278741) has ported their old game, Gassy Rick Astley to HaxeFlixel for its 10 year anniversay! Play it now on [Newgrounds](https://www.newgrounds.com/portal/view/636783).
