### ISSUE TITLE
Haxe Roundup 713

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1160]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by SabeDoesThings** [comment]
- [ ] A new simple, less bloated, Haxe game framework. by SabeDoesThings called [Haxion](https://github.com/SabeDoesThings/Haxion)

**Comment by skial** [comment]
- [ ] `[core]` `[4.3.5]` Backport Json RPC diagnostics [pull request](https://github.com/HaxeFoundation/haxe/pull/11707).
- [ ] `[core]` Null-coalescing operator cast before test against null issue [fixed](https://github.com/HaxeFoundation/haxe/issues/11706).
- [ ] `[core/hashlink]` Unexpected implicit cast to `Int`, from `abstract(Null<Int>)` [issue](https://github.com/HaxeFoundation/hashlink/issues/696).
- [ ] `[core/hxcpp]` `HXCPP_CXX_STANDARD` define [issue](https://github.com/HaxeFoundation/hxcpp/issues/1124).
- [ ] `[core/hxcpp]` CI - Updated version handling [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1123).
- [ ] `[core/neko]` Pre-release of neko [`2.4.0-rc`](https://github.com/HaxeFoundation/neko/releases/tag/v2-4-0-rc).
---
- [ ] `[community]` ⛏️Cave/Glade Generator is now a part of Procgen Arcana [article](https://www.patreon.com/posts/106975409) by Oleg Dolya.
- [ ] `[community]` Avoid serving legacy JavaScript to modern browsers [thread](https://community.haxe.org/t/avoid-serving-legacy-javascript-to-modern-browsers/4279?u=skial).
---
- [ ] `[devlog]` Fraymakers Update `v0.6.13` - Engine Upgrade [Release](https://store.steampowered.com/news/app/1420350/view/4252042698957549708).
- [ ] `[devlog]` Tightrope Theatre `1.0.5` Rebalancing [Update](https://store.steampowered.com/news/app/1891140/view/4239657799983204379).
- [ ] `[devlog]` Northgard patch notes for [`04/07/24`](https://store.steampowered.com/news/app/466560/view/4263301698038937501).
- [ ] `[devlog]` Printersim Achievements Bug Fix [post](https://store.steampowered.com/news/app/1665200/view/4243035499720342394).
---
- [ ] `libs`
   - [hxopenai_api `git`](https://lib.haxe.org/p/hxopenai_api)
   - [hxpkg `1.1.0`](https://lib.haxe.org/p/hxpkg)
   - [haxework `2.1.1`](https://lib.haxe.org/p/haxework)
   - [extension-androidtools `2.1.0`](https://lib.haxe.org/p/extension-androidtools)
   - [hxvlc `1.7.1`](https://lib.haxe.org/p/hxvlc)
   - [hxdiscord_gamesdk `0.1.0`](https://lib.haxe.org/p/hxdiscord_gamesdk)
   - [hxluagit `1.0.2`](https://lib.haxe.org/p/hxluajit)
   - [hxArchipelago `0.9.0`](https://lib.haxe.org/p/hxArchipelago)
   - [freeCategories `1.0.1`](https://lib.haxe.org/p/freeCategories)
   - [hxScry `0.0.1-beta`](https://lib.haxe.org/p/hxScry)
   - [polybool `1.1.0`](https://lib.haxe.org/p/polybool)
   - [colyseus-websocket `1.0.14`](https://lib.haxe.org/p/colyseus-websocket)

**Comment by SabeDoesThings** [comment]
Could you maybe put my new project on there? https://discordapp.com/channels/162395145352904705/1260060068544647199

**Comment by skial** [comment]
- [ ] `[events/upcoming]` The next Haxe Roundup _Roundup_ Discord event is scheduled for [July 21st at 18:45](https://discord.gg/dQNTDKWk?event=1259603222088253502).
---
- [ ] `[open source/haxe discord]` Sabe is working on a [first person shooter](https://discord.com/channels/162395145352904705/1260060068544647199) inspired by Wolfenstein 3D, written in Heaps.io [Haxenstein `git`](https://github.com/SabeDoesThings/Haxenstein).
- [ ] `[open source/haxe discord]` [Jeremy Fa](https://discord.com/channels/162395145352904705/162664383082790912/1258922375139954800) has a _"game prototype working on the retroid pocket 4. Gamepad support on Android will be enabled in the next Ceramic release"_.
---
- [ ] `[open source]` [UZG `git`](https://github.com/AdamAlNajar/uzg) - A game about shooting zombies written in Heaps.io and Haxe.
- [ ] `[open source]` [modvania `git`](https://github.com/kiss-lang/modvania) - Component-oriented, moddable metroidvania engine in HaxeFlixel.
- [ ] `[open source]` [hxopenai_api `git`](https://github.com/MAJigsaw77/hxopenai_api) - Haxe bindings for OpenAI API.
- [ ] `[open source]` [space-chaos `git`](https://github.com/montibbalt/space-chaos) - Porting an old Flash game of mine to HTML5.
- [ ] `[open source]` [HaxeSandbox `git`](https://github.com/l0go/HaxeSandbox) - Use podman to run untrusted Haxe code in a read-only container.
---
- [ ] `[video]` The Haxe Roundup _Roundup_ Archive [Episode 5](https://www.youtube.com/watch?v=mi3T-tvPCAQ)
- [ ] `[video]` The latest Asteroids Armory3D series video updates:
   - [Rocks Life](https://www.youtube.com/watch?v=ganyrQe1MCI)
   - [Small Rocks](https://www.youtube.com/watch?v=K8Vf3RMdR2k)
   - [BG Animation](https://www.youtube.com/watch?v=6jOk_lLEHmQ)
   - [Wrap Effect](https://www.youtube.com/watch?v=W2byXm3q6P0)
---
- [ ] `[closed source/haxe discord]` [Jeremy Fa](https://discord.com/channels/162395145352904705/162664383082790912/1260561671295074417) _"switched to a circular shape for the magnetic impulsion that turns mirrors"_
- [ ] `[closed source/haxe discord]` [MKI](https://discord.com/channels/162395145352904705/162664383082790912/1260542913444712558) has written a _"simple graph calculator in Haxe as a simple demo for their `WIP` UI framework"_ call KumoUI. Find out more over on the [projects Discord page](https://discord.com/channels/162395145352904705/1256279332515741807).

**Comment by skial** [comment]
Thank you @SabeDoesThings for contributing. Anything Haxe related in whatever state is more than welcome to be included. It looks like you're making good progress with Haxenstein  :+1:.
