### ISSUE TITLE
Haxe Roundup 714

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1162]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by kLabz** [comment]
* [ ] Haxe 4.3.5 [released](https://haxe.org/download/version/4.3.5/)

**Comment by EliteMasterEric** [comment]
- [ ] A JSONPath evaluator for Haxe, now released on haxelib: [jsonpath](https://lib.haxe.org/p/jsonpath/)

**Comment by skial** [comment]
- [ ] `[core]` Use whole import position when storing subtype import resolution data [merged](https://github.com/HaxeFoundation/haxe/pull/11732).
- [ ] `[core/hl]` Fix interface override function resolution [merged](https://github.com/HaxeFoundation/haxe/pull/11723).
- [ ] `[core/hlc]` Use uint64 instead of uint64_t for shift cast [merged](https://github.com/HaxeFoundation/haxe/pull/11721).
- [ ] `[core/neko]` Neko `2.4.0` has been [released](https://github.com/HaxeFoundation/neko/releases/tag/v2-4-0).
- [ ] `[core]` Local static in inlined function gets optimized away with analyzer [fixed](https://github.com/HaxeFoundation/haxe/issues/11725).
- [ ] `[core]` Switch `Abstract<Null<Int>>` generation differ from `Null<Int>` [fixed](https://github.com/HaxeFoundation/haxe/issues/11715),
- [ ] `[core/hxcpp]` HXCPP `4.3.49` has been [released](https://github.com/HaxeFoundation/hxcpp/releases/tag/v4.3.49).
- [ ] `[core/hxcpp]`  Struct<NativeEnum, EnumHandler> does not work in switch expression [issue](https://github.com/HaxeFoundation/hxcpp/issues/1131).
---
- [ ] `[opensource]` OpenFL `9.3.4` has been [released](https://github.com/openfl/openfl/releases/tag/9.3.4).
- [ ] `[opensource]` Lime `8.1.3` has been [released](https://github.com/openfl/lime/releases/tag/8.1.3).
---
- [ ] `[community]` Haxe `4.3.5` announcement [post](https://community.haxe.org/t/haxe-4-3-5-released/4293?u=skial).
- [ ] `[community]` Haxe IntelliJ plugin `1.5.6` has been [released](https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.5.6).
- [ ] `[community]` [TilBuci](https://community.openfl.org/t/tilbuci-a-free-interactive-content-creator-with-openfl/13966?u=skial.bainn), a free interactive content creator made with OpenFL.
- [ ] `[community]` Hxcpp: Ways to retain objects outside of Haxe? [question & answers](https://community.haxe.org/t/hxcpp-ways-to-retain-objects-outside-of-haxe/4294?u=skial).
---
- [ ] `[evo]` Add Defer keyword [proposal](https://github.com/DawDavis/haxe-evolution/blob/defer/proposals/0000-defer.md).

**Comment by skial** [comment]
- [ ] libs
   - [openfl `9.3.4`](https://lib.haxe.org/p/openfl)
   - [lime `8.1.3`](https://lib.haxe.org/p/lime)
   - [neon `0.0.5`](https://lib.haxe.org/p/neon)
   - [HaxeGJClient `6.1.2`](https://lib.haxe.org/p/HaxeGJClient)
   - [hxpkg `1.2.0`](https://lib.haxe.org/p/hxpkg)
   - [torchsfunction `0.6.0`](https://lib.haxe.org/p/torchsfunctions)
   - [jsonpath `1.0.0`](https://lib.haxe.org/p/jsonpath)
   - [hx-delaunator `1.0.1`](https://lib.haxe.org/p/hx-delaunator)
   - [siteHX `1.2.0`](https://lib.haxe.org/p/siteHX)
---
- [ ] `[devlogs]` Wartales Roadmap Update [`17/07/2024`](https://store.steampowered.com/news/app/1527950/view/4365760492630422412).
- [ ] `[devlogs]` Northgard patch note for [`18/07/2024`](https://store.steampowered.com/news/app/466560/view/4375893591785939433).
---
- [ ] `[video]` The latest Asteroids Armory3D video - [Player Collision](https://www.youtube.com/watch?v=vrXtNMfNsYs).
---
- [ ] `[open source]` [entities2 `git`](https://github.com/core-haxe/entities2)
- [ ] `[open source]` [KumoUI `git`](https://github.com/mikaib/kumoui) - KumoUI: Immediate-mode platform-agnostic UI library. 
- [ ] `[open source]` [tagg `git`](https://github.com/Teslotik/tagg) - Textures and graffiti generator based on layer stacking.
---
- [ ] `[community]` Bring It On! Full Release Date has been [announced](https://store.steampowered.com/news/app/2020460/view/4335361829048618741)!
- [ ] `[community]` Renaine: [Enter the Dojo](https://www.kickstarter.com/projects/585676804/renaine-a-game-about-overcoming-failure/posts/3908950) article.
---
- [ ] The latest GIFs from Renaine:
   - These Spero raiders had a glitch where they could jump midair so... now it's official, [complete with fx](https://x.com/squuuidly/status/1815804061280584146).
   - New auto-tracking GIFs! It auto creates pixel [perfect GIFs like this](https://x.com/squuuidly/status/1813972323453792430) right from the game itself!
   - Come on [let her up](https://x.com/RenaineGame/status/1813703928930091264) ._.
   - Really cool combo posted without [context](https://x.com/RenaineGame/status/1812903087297769589).

**Comment by skial** [comment]
- [ ] `[upcoming/events]` The next Haxe Roundup _Roundup_ [discord event](https://discord.gg/ettAhfjP?event=1264662535156793465) is scheduled for Sunday 4th August 18:45.

**Comment by skial** [comment]
Thank you @kLabz and @EliteMasterEric for contributing to this issue. :+1:
