### ISSUE TITLE
Haxe Roundup 715

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1164]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by EliteMasterEric** [comment]
- [ ] A JSONPatch evaluator for Haxe, now released on haxelib: [jsonpath](https://lib.haxe.org/p/jsonpatch/)

NOTE: This is a different library from the one I posted last roundup! JSONPath is for pointing to specific locations in a JSON object in a robust way, while JSONPatch allows for detailing a list of operations to mutate a JSON object.

**Comment by leonvn** [comment]
Following up that this Job Listing has been closed and can be removed from future Roundups. Thanks for listing it for us!

Clockwork Acorn is [looking for an experienced](https://community.haxe.org/t/paid-work-looking-for-experienced-haxe-w-openfl-developer-to-finish-porting-our-game-to-mobile-fully-remote/4240?u=skial) Haxe developer to port their game Jetstream to iOS and Android.

**Comment by skial** [comment]
- [ ] `[community]` New HaxeUI [component explorer](https://community.haxeui.org/t/new-haxeui-component-explorer/624?u=skial) by Ian Harrigan! `[Haxe community announcement](https://community.haxe.org/t/new-haxeui-component-explorer/4298?u=skial). :star:
- [ ] `[community]` Features UI `1.3` - Drag and drop, Collapsible component, dispose() method and tons of bugs fixed [article](https://feathersui.com/blog/2024/08/01/feathers-ui-version-1-3-haxe-openfl-release-announcement/) by Josh Tynjala.
---
- [ ] `[open source]` polymod `1.8.0` has been [released](https://github.com/larsiusprime/polymod/releases/tag/v1.8.0).
---
- [ ] `[core]` Haxe `4.3.6` has been [released](https://github.com/HaxeFoundation/haxe/releases/tag/4.3.6).
- [ ] `[core/haxelib]` Added ANSI colouring to `haxelib help` command [pull request](https://github.com/HaxeFoundation/haxelib/pull/637).
- [ ] `[core/haxelib]` Display current repository path when using `haxelib list` [pull request](https://github.com/HaxeFoundation/haxelib/pull/634).
- [ ] `[core/hashlink]` Fix TestInt64 [merged](https://github.com/HaxeFoundation/haxe/pull/11742).
- [ ] `[core/hxcpp]` Expose mbedtls xml config for external use [merged](https://github.com/HaxeFoundation/hxcpp/pull/1133).
- [ ] `[core/jvm]` Fix `--java out -D jvm` deprecation warning [merged](https://github.com/HaxeFoundation/haxe/pull/11739).
- [ ] `[core/js]` Call stack missing type names on JS in Chrome [issue](https://github.com/HaxeFoundation/haxe/issues/11735).
- [ ] `[core/hxcpp]` Null check interfaces [merged](https://github.com/HaxeFoundation/haxe/pull/11743).
- [ ] `[core/diagnostics]` Do not define `display` for json rpc diagnostics [merged](https://github.com/HaxeFoundation/haxe/pull/11746).
- [ ] `[core/hxcpp]` WinCrypt and Friends SSL implementation `draft` [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1135).

**Comment by AlexHaxe** [comment]
- [ ] vshaxe 2.32.0 has been [released](https://marketplace.visualstudio.com/items?itemName=nadako.vshaxe). includes support for new Json RPC diagnostics introduced in Haxe 4.3.5 and recent nightlies.


also there is a typo in your previous post: it's "Feathers UI" not "Features UI"

**Comment by skial** [comment]
- [ ] `[events/upcoming]` The next Haxe Roundup _Roundup_ [Discord event](https://discord.gg/wh2r8ABs?event=1269722098268508254) is scheduled for Sunday August 18th 18:45.
- [ ] `[community]` Haxe `4.3.6` has been [officially released](https://community.haxe.org/t/haxe-4-3-6-released/4309?u=skial).
- [ ] `[community]` The Watcher OUT NOW!! + Character 7 Update & Fraymakers at PAX West - July 2024 [Progress Update](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/4162483).
- [ ] `[community]` Ohsat Games [Update 2024](https://www.ohsat.com/post/update-2024/).
---
- [ ] `[devlog]` Dune: Spice Wars [`06/08/24`](https://store.steampowered.com/news/app/1605220/view/4344369662311372499) patch notes.
- [ ] `[devlog]` Dune: Spice Wars [Community Update `#3`](https://store.steampowered.com/news/app/1605220/view/4344369662289739605) is out now.
---
- [ ] `[video]` [Rooftop Ambush](https://www.youtube.com/watch?v=wU8f5GNqCRU) Scene from Level 4-2 "Cyralai" of Idosra.
- [ ] `[video]` OpenFL [Monthly Roundup `#1`](https://www.youtube.com/watch?v=aG9CACwYnxc) by Chris Speciale. :star:
- [ ] `[video]` Haxe Roundup _Roundup_ Archive [Episode 6](https://www.youtube.com/watch?v=gW2U9GSZhzg).
- [ ] `[video]` The Watcher from Slay the Spire [now in Fraymakers](https://www.youtube.com/watch?v=LLyl-7NAd-Q)!
- [ ] The latest Asteroids Armory3D videos:
   - [Player VFX](https://www.youtube.com/watch?v=IEpamSVv_0c).
   - [Test Score](https://www.youtube.com/watch?v=7U1OkD6K5lw).
---
- [ ] libs
  - [hxpkg `1.2.3`](https://lib.haxe.org/p/hxpkg)
  - [moonchart `0.2.0`](https://lib.haxe.org/p/moonchart)
  - [snake-server `1.2.0`](https://lib.haxe.org/p/snake-server)
  - [parallaxlt `0.0.5`](https://lib.haxe.org/p/parallaxlt)
  - [hxluajit `1.0.3`](https://lib.haxe.org/p/hxluajit)
  - [extension-androidtools `2.1.1`](https://lib.haxe.org/p/extension-androidtools)
  - [hxvlc `1.8.0`](https://lib.haxe.org/p/hxvlc)
  - [tokentree `1.2.13`](https://lib.haxe.org/p/tokentree)
  - [feathersui `1.3.0`](https://lib.haxe.org/p/feathersui)
  - [highlighter `0.7.0`](https://lib.haxe.org/p/highlighter)
  - [markdown `1.1.3`](https://lib.haxe.org/p/markdown)
  - [hx-promise-thenable `0.0.1`](https://lib.haxe.org/p/hx-promise-thenable)
  - [polymod `1.8.0`](https://lib.haxe.org/p/polymod)
  - [jsonpatch `1.0.0`](https://lib.haxe.org/p/jsonpatch)
  - [im-exporter-builder `1.0.1`](https://lib.haxe.org/p/im-exporter-builder)
  - [haxe-extension-tools `1.0.1`](https://lib.haxe.org/p/haxe-extension-tools)
---
- [ ] `[closed source/discord]` Jeremy Fa has added character [ladder climbing animation](https://discord.com/channels/162395145352904705/162664383082790912/1266750036532793345).
- [ ] `[closed source/discord]` Ddmills is reworking damage xp kickers [animation](https://discord.com/channels/162395145352904705/162664383082790912/1266890657620819968).
- [ ] `[closed source/discord]` GenKit: Create dangerously efficient bindings [announcement post](https://discord.com/channels/162395145352904705/1268509269104525352).
---
- [ ] `[open source/discord]` Rock Paper Scissors [demo](https://discord.com/channels/162395145352904705/162664383082790912/1268345356769427457) written in [FlowScript `git`](https://github.com/HaxelDev/FlowScript), a programming language coded in Haxe.

**Comment by skial** [comment]
- [ ] `[video]` Gepatto is [having fun](https://mastodon.social/@gepatto@fosstodon.org/112910895400364170) with Away3D Haxe on a RaspberryPi 5 and a micro:bit.

**Comment by skial** [comment]
Thank you @EliteMasterEric, @AlexHaxe and @leonvn for contributing. :+1: It's always appreciated.
