### ISSUE TITLE
Haxe Roundup 718

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#1170]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core/cpp]` Add Tracy profiler extern to `std` [pull request](https://github.com/HaxeFoundation/haxe/pull/11772).
- [ ] `[core/hxcpp]` Add support for Tracy profiler [pull request](https://github.com/HaxeFoundation/hxcpp/pull/1153).
- [ ] `[core/php]` Add externs for some POSIX functions [merged](https://github.com/HaxeFoundation/haxe/pull/11769).
- [ ] `[core/tests]` Enable hlc tests on Windows and Mac [pull request](https://github.com/HaxeFoundation/haxe/pull/11768).
- [ ] `[core]` Consider `toString` static extension in string coercion [issue](https://github.com/HaxeFoundation/haxe/issues/11767).
- [ ] `[core]` Non-Issue: How to get Haxe compiling and running on FreeBSD [issue](https://github.com/HaxeFoundation/haxe/issues/11764).
- [ ] `[core/cpp]` Absolute paths with `absolute-path` [merged](https://github.com/HaxeFoundation/haxe/pull/11763).
- [ ] `[core]` Inconsistent interface type inference for getters/setters [issue](https://github.com/HaxeFoundation/haxe/issues/11774).
- [ ] `[core/cppia]` Generate scriptable functions for overriden functions [merged](https://github.com/HaxeFoundation/haxe/pull/11773).
---
- [ ] `[community]` 🔑Dwellings `1.3.2`: permalinks and multi-floor export [article](https://www.patreon.com/posts/111909860) by Oleg Dolya.
---
- [ ] `[devlog]` Bring It On! [`1.0.9`](https://store.steampowered.com/news/app/2020460/view/6423910781604424989) and [`1.0.10`](https://store.steampowered.com/news/app/2020460/view/6423910781604812162) patch notes.
- [ ] `[devlog]` Northgard Beta patch notes for [week 3](https://store.steampowered.com/news/app/466560/view/4610085845253522312).
---
- [ ] libs
   - [hxWindowsColorMode `0.1.0`](https://lib.haxe.org/p/hxWindowColorMode)
   - [moxiesfunctions `0.1.0`](https://lib.haxe.org/p/moxiesfunctions)
   - [rulescript `0.1.1`](https://lib.haxe.org/p/rulescript)
   - [hxdiscord_rpc `1.2.4`](https://lib.haxe.org/p/hxdiscord_rpc)
   - [sl-windows-api `1.0.0`](https://lib.haxe.org/p/sl-windows-api)
   - [which `3.5.0`](https://lib.haxe.org/p/which)
   - [xa3.csv `0.2.0`](https://lib.haxe.org/p/xa3.csv)
   - [hscript-iris `1.1.0`](https://lib.haxe.org/p/hscript-iris)
   - [neutranlinojs `3.0.0`](https://lib.haxe.org/p/neutralinojs)
   - [akismet `3.0.0`](https://lib.haxe.org/p/akismet)

**Comment by skial** [comment]
- [ ] `[upcoming/events]` The next Haxe Discord Haxe Roundup _Roundup_ [event](https://discord.gg/ZNhKeMHv?event=1284987001237672018) is scheduled for Sunday 29th September at 19:00.
- [ ] `[community/haxe dsicord]` Join Chris and others in the Haxe community entry in the [Ludum Dare 56 Collab](https://discord.com/channels/162395145352904705/1282493664068767825/1282493664068767825) channel.
---
- [ ] `[closed source/haxe discord]` [Jeremy Fa](https://discord.com/channels/162395145352904705/162664383082790912/1282354105808851106) has done _"work on ladder animations in their game "_ made with Ceramic.
- [ ] `[closed source/haxe dsicord]` [Travis](https://discord.com/channels/162395145352904705/162664383082790912/1282691290315886704) shows monkey cartwheel action!

**Comment by EliteMasterEric** [comment]
- [] Friday Night Funkin' has released a new update, featuring a new playable character with all new remixes! [Play on Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [] Friday Night Funkin' has published the source code for its latest update! Check it out on [GitHub](https://github.com/FunkinCrew/Funkin)

**Comment by skial** [comment]
- [x] `[open source]` [haxebt `git`](https://github.com/Antriel/haxebt) - Behavior trees lib for Haxe.
- [x] `[open source]` [hxgitapi `git`](https://github.com/yophlox/hxgitapi) - A HaxeLib to interact with the GitHub API. 
- [x] `[open source]` [jume `git`](https://github.com/Jume-Labs/jume) - 2D Web Game Engine written in Haxe.
- [x] `[open source]` [haxe-sql-parser `git`](https://github.com/c-g-dev/haxe-sql-parser) - SQL lexer/parser for Haxe core.
- [x] `[open source]` [hxserial_api `git`](https://github.com/MAJigsaw77/hxserial_api) - Haxe/Hxcpp `@:native` integration for managing serial connections and devices. 
- [x] `[open source]` [hxbutt `git`](https://github.com/nebulazorua/hxbutt) - Buttplug.IO support for the Haxe language.
