### ISSUE TITLE
Haxe Roundup 362

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#286]
To add to the roundup todo list, use the following markdown format.
```
- [ ] optional description [link name](/link/to/item) by [Persons Name](link/to/person)
```

**Comment by IBwWG** [comment]
- [ ] New HaxeFlixel-based [Willy and Mathilda's Houseboat Adventure Game devlog](https://forums.tigsource.com/index.php?topic=55540.0) by [KJB of IBwWG](https://twitter.com/wastheWordGame)

**Comment by skial** [comment]
- [ ] videos
 - [ ] [Kha tutorial 19](https://twitter.com/lewislepton/status/725025242574389251) - timers.
 - [ ] [DC/AC Virtual Labs](https://twitter.com/hopewise/status/726122998818869248) Auto connection wires.
 - [ ] [FOSDEM 2016 Haxe talk](https://twitter.com/blackmag_c/status/726737511238766592) video released.

- [ ] news
 - [ ] [Hello Lua!](http://haxe.org/blog/hello-lua)
 - [ ] [Blender and Kha introduction](https://twitter.com/luboslenco/status/725705080683548672)
 - [ ] [Separable Subsurface Scattering in Kha](https://twitter.com/luboslenco/status/726785703615418369)
 - [ ] [Kha turtle](https://github.com/Disar/KhaTurtle)
 - [ ] [Announcing Clothsoul](https://twitter.com/carpetwurm/status/726135587619524608) on TIGForum.
 - [ ] [TiVo acquired by _patent giant_ Rovi for $1.1 billion](http://www.engadget.com/2016/04/29/rovi-tivo-acquisition-agreement/)
 - [ ] [C style enum behaviour with macros](https://twitter.com/YellowAfterlife/status/726637531836628992)

- [ ] lib releases
 - [ ] [buddy `1.4.1`](http://lib.haxe.org/p/buddy)
 - [ ] [akifox-asynchttp `0.4.3`](http://lib.haxe.org/p/akifox-asynchttp)
 - [ ] [haxe-react-addons `git`](https://github.com/tokomlabs/haxe-react-addons)
 - [ ] [duell `4.9.1`](http://lib.haxe.org/p/duell)
 - [ ] [haxpression `2.0.0`](http://lib.haxe.org/p/haxpression)
 - [ ] [tink_url `0.0.4`](http://lib.haxe.org/p/tink_url)
 - [ ] [haxedci `0.14.0`](http://lib.haxe.org/p/haxedci)
 - [ ] [farcek `1.4.0`](http://lib.haxe.org/p/farcek)
 - [ ] [tink_clone `0.1.0`](http://lib.haxe.org/p/tink_clone)
 - [ ] [tink_validation `0.1.0`](http://lib.haxe.org/p/tink_validation)
 - [ ] [hxInfate `0.2.4`](http://lib.haxe.org/p/hxInflate)
 - [ ] [dataclass `0.16.0`](http://lib.haxe.org/p/dataclass)
 - [ ] [robotlegs `0.3.2`](http://lib.haxe.org/p/robotlegs)

- [ ] previews
 - [ ] [Buttons go haywire](https://twitter.com/ingenoire/status/724997708445003776) in Hegemone Pass.
 - [ ] [Locked gates! Hurry!](https://twitter.com/ingenoire/status/725014922682355712) in Hegemone Pass.
 - [ ] [Conveyor Belts](https://twitter.com/ingenoire/status/725692425872756736) in Hegemone Pass.
 - [ ] [Air Bubbles](https://twitter.com/ingenoire/status/726404853711441922) in Hegemone Pass.
 - [ ] [Pixel ninja, pirate, wizard, knight, ...](https://twitter.com/_eons/status/725080019006033921) HaxeFlixel game.
 - [ ] [Creature running in Haxe](https://twitter.com/KestrelmMoon/status/725119517676998657) and [HaxeFlixel](https://twitter.com/KestrelmMoon/status/725431657604374528)
 - [ ] [Sakura, new levels and features](https://twitter.com/fierysquirrel/status/725353832939552768), [progress](https://twitter.com/fierysquirrel/status/725593021668970496), [new level](https://twitter.com/fierysquirrel/status/726383543568326656)
 - [ ] [NPC's](https://twitter.com/87meansSuhail/status/725369064101699585), HaxeFlixel
 - [ ] [Hard shadow prototype in kha](https://twitter.com/the_august_late/status/725682194312617989)
 - [ ] [Multi process webserver](https://twitter.com/fponticelli/status/725688075951599616) built with Abe, NodeJS and Cluster.
 - [ ] [Success with pivot tiles](https://twitter.com/Triplefox/status/726309619530878976) in Kha.
 - [ ] [Swept under the rug](https://twitter.com/carpetwurm/status/726889582239748097) in Clothsoul.

- [ ] jobs, bounties
 - [ ] [LiveJasmin](http://new.livejasmin.com/en/job_offer), bonus [comic](https://twitter.com/francisbourre/status/725326537873088513)

**Comment by skial** [comment]
- [ ] core updates
 - [ ] [Add `--wait` stdio](https://github.com/HaxeFoundation/haxe/pull/5188) pr.
 - [ ] [Haxe Lua logo](https://github.com/HaxeFoundation/haxe.org/issues/194) pr.
 - [ ] [Moving to OCaml 4](https://github.com/HaxeFoundation/haxe/issues/5174).
 - [ ] [Type guard](https://github.com/HaxeFoundation/haxe/issues/5167) discussion.
 - [ ] [Handle `macro :$tp<Int>`](https://github.com/HaxeFoundation/haxe/issues/5162).
