### ISSUE TITLE
Haxe Roundup 366

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#311]
To add to the roundup todo list, use the following markdown format.
```
- [ ] optional description [link name](/link/to/item) by [Persons Name](link/to/person)
```

**Comment by DleanJeans** [comment]
Doing backflips on a [square planet](https://twitter.com/DleanJeans/status/743804609437700098) by [Dlean Jeans](https://twitter.com/DleanJeans)

**Comment by IBwWG** [comment]
previews/demos

- [ ] [First render of the new Under the Spell of Shiny Shimmering Sunbeam Sparkles mechanic](https://twitter.com/wastheWordGame/status/743146566425395200) in Willy and Mathilda's Houseboat Adventure: The Game by [IBwWG](https://twitter.com/wastheWordGame)
- [ ] [Didn't picture how it would all fit](https://twitter.com/wastheWordGame/status/743154481899122689) in Willy and Mathilda's Houseboat Adventure: The Game by [IBwWG](https://twitter.com/wastheWordGame)
- [ ] [Mathilda approves](https://twitter.com/wastheWordGame/status/743182276784119809) in Willy and Mathilda's Houseboat Adventure: The Game by [IBwWG](https://twitter.com/wastheWordGame)
- [ ] [Who learned me to spell?](https://twitter.com/wastheWordGame/status/743450482899828736) in Willy and Mathilda's Houseboat Adventure: The Game by [IBwWG](https://twitter.com/wastheWordGame)
- [ ] [Done in four hard-coded difficulties...](https://twitter.com/wastheWordGame/status/743477243503058946) in Willy and Mathilda's Houseboat Adventure: The Game by [IBwWG](https://twitter.com/wastheWordGame)

community updates

- [ ] More general-audience updates at HaxeFlixel-based [Willy and Mathilda's Houseboat Adventure: The Game devlog](https://forums.tigsource.com/index.php?topic=55540.0) by [IBwWG](https://twitter.com/wastheWordGame)

app & game releases

- [ ] Early paid preview of HaxeFlixel-based Willy and Mathilda's Houseboat Adventure: The Game on [itch.io](https://ibwwg.itch.io/mathildagame) by [IBwWG](https://twitter.com/wastheWordGame)

**Comment by fzzr-** [comment]
Library releases

- [ ] [signal](http://lib.haxe.org/p/signal) by [Alex 'fzzr' Koz.](https://github.com/fzzr-)
- [ ] [bindings](http://lib.haxe.org/p/bindings) by [Alex 'fzzr' Koz.](https://github.com/fzzr-)

Some funny cool thinks

- [ ] [Haxe Operators](https://duckduckgo.com/?q=Haxe%20ops%20cheat%20sheet&ia=cheatsheet) by [Alex 'fzzr' Koz.](https://github.com/fzzr-)
- [ ] [Neko Standard Library](https://duckduckgo.com/?q=Neko%20STD%20cheat%20sheet&ia=cheatsheet) by [Alex 'fzzr' Koz.](https://github.com/fzzr-)
- [ ] [Neko Operators](https://duckduckgo.com/?q=Neko%20operators%20cheatsheet&ia=cheatsheet) by [Alex 'fzzr' Koz.](https://github.com/fzzr-)
- [ ] [Neko CLI](https://duckduckgo.com/?q=Neko%20CLI%20cheat%20sheet&ia=cheatsheet) by [Alex 'fzzr' Koz.](https://github.com/fzzr-)
- [ ] [Neko Builtins](https://duckduckgo.com/?q=Neko%20Builtins%20cheat%20sheet&ia=cheatsheet) by [Alex 'fzzr' Koz.](https://github.com/fzzr-)

**Comment by skial** [comment]
News, community updates, etc
- [ ] Indevelopment try haxe allows you to choose your haxe version - [tweet](https://twitter.com/jdbaudi/status/744584299702272000) & now has a bunch of popular haxelibs available - [tweet](https://twitter.com/jdbaudi/status/747476725240635393)
- [ ] Slickrock.io now open sourced - [tweet](https://twitter.com/nico_m__/status/745053576825712642)
- [ ] Dan Korostelev's thoughts on Haxe's future - [tweet](https://twitter.com/nadako/status/745282027667226624)

Jobs
- [ ] Haxe engineer for game project - [link](https://groups.google.com/d/msg/haxelang/bc9KLpJiyoE/klFZBxSABQAJ)

Videos
- [ ] Kha Tutorial EP33 - Buttons - [tweet](https://twitter.com/lewislepton/status/747746402869075968)
- [ ] Kha Tutorial EP34 - Bouncing Ball - [tweet](https://twitter.com/lewislepton/status/748471277762011136)

Community
- [ ] HaxeTink libraries now have a gitter channel - [tweet](https://twitter.com/kevinresol/status/746693603586539520)
- [ ] OpenHaxe now has a gitter channel - [tweet](https://twitter.com/PeyTyPeyTy/status/744352182997225472)
- [ ] C# support coming to OpenFL / Lime - [issue](https://github.com/openfl/lime/issues/763)

Dev updates
- [ ] Snake Island - A New Start - [tweet](https://twitter.com/AndHalfAFish/status/744938972741173248)
- [ ] Derhier Elementar 2 - [tweet](http://forum.haxeflixel.com/topic/66/derhier-elementar-2-multiplayer-minigame-madness)

Game releases
- [ ] Interactive Conways Game of Life made with Haxe and ThreeJS - [tweet](https://twitter.com/Sam_Twidale/status/744984981760516096)
- [ ] Captain Stago on itch.io with source available - [tweet](https://twitter.com/AntonUklein/status/745800687947132929)
- [ ] Kryce available for Windows from itch.io made with luxe engine - [tweet](https://twitter.com/keymaster_/status/747493375822204928)

Library releases
- [ ] [waud `0.5.4`](http://lib.haxe.org/p/waud)
- [ ] [puremvc-pipes `1.3.0`](http://lib.haxe.org/p/puremvc-pipes)
- [ ] [puremvc-standard `1.3.0`](http://lib.haxe.org/p/puremvc-standard)
- [ ] [puremvc-multicore `1.4.0`](http://lib.haxe.org/p/puremvc-multicore)
- [ ] [puremvc-statemachine-standard `1.3.0`](http://lib.haxe.org/p/puremvc-statemachine-standard)
- [ ] [puremvc-statemachine-multicore `1.3.0`](http://lib.haxe.org/p/puremvc-statemachine-multicore)
- [ ] [starling `0.5.7`](http://lib.haxe.org/p/starling)
- [ ] [moon-core `1.0.0`](http://lib.haxe.org/p/moon-core)
- [ ] [dataclass `0.21.1`](http://lib.haxe.org/p/dataclass)
- [ ] [haxe-doctext `0.3.2`](http://lib.haxe.org/p/haxe-doctest)
- [ ] [abstracts-core `0.1.1`](http://lib.haxe.org/p/abstracts-core)
- [ ] [ithril `1.1.0`](http://lib.haxe.org/p/ithril)
- [ ] [haxe-strings `1.2.0`](http://lib.haxe.org/p/haxe-strings)
- [ ] [jquery-uipages `0.0.1`](http://lib.haxe.org/p/jquery-uipages)
- [ ] [hxslam `0.1.1`](http://lib.haxe.org/p/hxslam)
- [ ] [raven `0.3.0`](http://lib.haxe.org/p/raven)
- [ ] [tink_await `0.1.4`](http://lib.haxe.org/p/tink_await)
- [ ] [haxelow `0.7.1`](http://lib.haxe.org/p/haxelow)
- [ ] [signal `0.9.9`](http://lib.haxe.org/p/signal) - see previous comment
- [ ] [bindings `0.9.2`](http://lib.haxe.org/p/bindings) - see previous comment
- [ ] [luce `0.8.1`](http://lib.haxe.org/p/luce)
- [ ] [glory `1.2.0`](http://lib.haxe.org/p/glory)
- [ ] [rexit `1.0.2`](http://lib.haxe.org/p/rexit)
- [ ] [promhx-unit-test `2.0.1`](http://lib.haxe.org/p/promhx-unit-test)

Tutorials
- [ ] Kha arcade game clone - Speed Race - [tweet](https://twitter.com/dstrekelj/status/744538425282465792)

Previews, Demos
- [ ] Doing Backflips in HaxeFlixel with Nape - [tweet](https://twitter.com/DleanJeans/status/743804609437700098)
- [ ] Indiedev HaxeFlixel progress - [tweet](https://twitter.com/carpetwurm/status/743964336025182208)
- [ ] Wave, path and stage views made with HaxeFlixel - [tweet](https://twitter.com/oelsons/status/744462916280254464)
- [ ] Kha is going multilingual - [tweet](https://twitter.com/robdangerous/status/744946015246127105)
- [ ] Kha based Unity API, my first Cube - [tweet](https://twitter.com/Hexvalues/status/745025196998930432)
- [ ] Subpixel morphological antialiasing and reflection filtering in Kha - [tweet](https://twitter.com/luboslenco/status/745170225742520321)
- [ ] Sakura Cherry Blossoms in OpenFL - [tweet](https://twitter.com/fierysquirrel/status/745420320606085120)
- [ ] Sakura Cherry Blossom levels - [tweet](https://twitter.com/fierysquirrel/status/746906656248758272)
- [ ] Sakura improvements - [tweet](https://twitter.com/fierysquirrel/status/748343849055989761)
- [ ] Flambe particle physics in Kha using Nape - [tweet](https://twitter.com/Meltingtallow/status/745523368598724608)
- [ ] Swarm Alpha gameplay on Android made with HaxeFlixel - [tweet](https://twitter.com/LigerGroup/status/746823471389417474)
- [ ] Paper Airplane made with HaxeFlixel - [tweet](https://twitter.com/Desttinghim/status/746830977352273920)
- [ ] Hegemone Pass - AI needs some work... - [tweet](https://twitter.com/ingenoire/status/747731131248807937)
- [ ] Taking a break from coding... - [tweet](https://twitter.com/keymaster_/status/748178819425665024)
- [ ] Animate the pattern - [tweet](https://twitter.com/keymaster_/status/748467346205999104)

Core updates
- [ ] haxe.org now supports https - [issue](https://github.com/HaxeFoundation/haxe.org/issues/177#issuecomment-229398256)
- [ ] Add inital working Dockerfile - [commit](https://github.com/HaxeFoundation/haxe.org/compare/8be46aed4875...e452fadfa782)
- [ ] Haxe XML is slow, why? - [issue](https://github.com/HaxeFoundation/haxe/issues/5423)

**Comment by skial** [comment]
Thanks @DleanJeans, @IBwWG and @fzzr-  for this week's links!
