### ISSUE TITLE
Haxe Roundup 367

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#321]
To add to the roundup todo list, use the following markdown format.
```
- [ ] optional description [link name](/link/to/item) by [Persons Name](link/to/person)
```

**Comment by kevinresol** [comment]
- [ ] [Heroku Buildpack for Haxe](https://github.com/kevinresol/heroku-buildpack-haxe) by [kevinresol](https://github.com/kevinresol)
- [ ] [Haxe Docker Image](https://github.com/kevinresol/docker-haxe) by [kevinresol](https://github.com/kevinresol)

Both of them ship with Haxe `3.3.0-rc.1` and Neko `2.1.0`

**Comment by lj222kj** [comment]
- [ ] SVG to Bitmapdata [VectorAsset](http://lib.haxe.org/p/vectorasset/) by [Linus Jakobsson](https://twitter.com/nloj_)

**Comment by skial** [comment]
- [ ] community news
 - [ ] The HaxeFlixel Indiegogo fundraiser - [tweet](https://twitter.com/larsiusprime/status/757964223183892480) - _currently at `157%` funded_ - [How We Paid Our Open Source Taxes](http://www.fortressofdoors.com/how-we-paid-our-open-source-taxes/)
 - [ ] Register to playtest Sakura - [tweet](https://twitter.com/fierysquirrel/status/754491676844883968)
 - [ ] Interview with Kevin Field, head dev of Willy and Mathilda's Houseboat Adventure - [tweet](https://twitter.com/TheOrangeBison/status/753482953196462080)
 - [ ] Kryce development devlog - [tweet](https://twitter.com/keymaster_/status/756138768386564097)
 - [ ] Is Haxe for you? - [tweet](https://twitter.com/nadako/status/756297286767013888) - [reddit](https://www.reddit.com/r/programming/comments/4u0vt9/is_haxe_for_you/)
 - [ ] HaxeFlixel turns 5 - [tweet](https://twitter.com/HaxeFlixel/status/757228549359149056) - [cake](https://twitter.com/ingenoire/status/757255997249449984)
 - [ ] Component filtering BLAZING fast with macros - [tweet](https://twitter.com/tommislav/status/758775424818307073)
 - [ ] Hegemone Pass dev log # 1 - [tweet](https://twitter.com/ingenoire/status/758980902080831495)

- [ ] community help
 - [ ] Generating super call with arguments in Haxe macro - [stackoverflow](https://stackoverflow.com/questions/38426637/haxe-generating-super-call-with-arguments)
 - [ ] Getting the number of constructor arguments - [stackoverflow](https://stackoverflow.com/questions/38427169/getting-number-of-arguments-accepted-by-class-constructor)
 - [ ] Adding a new key to object with variable - [stackoverflow](https://stackoverflow.com/questions/38574508/haxe-add-new-key-to-object-with-variable)

- [ ] talks
 - [ ] Dan talking about Haxe at NevosoftRu recording - [tweet](https://twitter.com/nadako/status/755707173871742976) - [slides](http://slides.com/nadako/nevosoft_haxe_talk#/)
 - [ ] 10 favorite Haxe features talk [slides](https://twitter.com/francisbourre/status/758848201801687040)

- [ ] videos
 - [ ] Kha tutorial ep38 - [Setup FFMPEG](https://twitter.com/lewislepton/status/756160431031451648)
 - [ ] Kha tutorial ep39 - [Video](https://twitter.com/lewislepton/status/756268508447641601)

- [ ] demos, previews
 - [ ] Jumping Sakura - [tweet](https://twitter.com/fierysquirrel/status/754648056419672065)
 - [ ] Hectit hegdehogs in Sakura - [tweet](https://twitter.com/fierysquirrel/status/755022339071279104)
 - [ ] hexMachina `0.5.0` isomorphic nodejs & neko apps - [tweet](https://twitter.com/francisbourre/status/755364962676117504)
 - [ ] Hegemone Pass tutorial - [tweet](https://twitter.com/ingenoire/status/755405748822237184)
 - [ ] Procedurally generating a corridor - [tweet](https://twitter.com/dazKind/status/755489503599624192)
 - [ ] Procedurally generating ship interiors experiment - [tweet](https://twitter.com/dazKind/status/756148571888578561)
 - [ ] Procedurally generating ship interiors completed - [tweet](https://twitter.com/dazKind/status/756291941466124288)
 - [ ] First test of internal structure of ships - [tweet](https://twitter.com/dazKind/status/757359024778149888)
 - [ ] Space filling a space ship - [tweet](https://twitter.com/dazKind/status/758604838766870528)
 - [ ] Look at things _scroll_ using luxe engine - [tweet](https://twitter.com/nico_m__/status/755609285166403585)
 - [ ] Procedurally generating markov chain word ballpool - [tweet](https://twitter.com/Sam_Twidale/status/756230840821092352)
 - [ ] Profile all the shaders! - [tweet](https://twitter.com/luboslenco/status/756759014793482241)
 - [ ] Preview of the upcoming Armory trailer - [tweet](https://twitter.com/luboslenco/status/757922852578426880)
 - [ ] Things are getting together - [tweet](https://twitter.com/EdoardoLopes/status/756897563480092672)
 - [ ] A Wicked Curse title screen - [tweet](https://twitter.com/ericmbernier/status/758844176817455104)
 - [ ] A Wicked Curse Big Bad Wolf Boss fight - [tweet](https://twitter.com/ericmbernier/status/759432483058257920)
 - [ ] Glorch has been greenlit on Steam - [tweet](https://twitter.com/wg_phancock/status/759460061752139776)

- [ ] game releases
 - [ ] Word Search created with HaxeFlixel available from Amazon - [tweet](https://twitter.com/FouedLat/status/756140359667843072)
 - [ ] WordMix created with HaxeFlixel featured on Amazon - [tweet](https://twitter.com/FouedLat/status/757147498381279232)
 - [ ] Volcano Escape created with HaxeFlixel available from itch.io - [tweet](https://twitter.com/madnotdead/status/757342363694075904)
 - [ ] Paperguy created with HaxeFlixel available from itch.io - [tweet](https://twitter.com/simonparzer/status/757335082587811840)

- [ ] library releases
 - [ ] [waud `0.6.7`](http://lib.haxe.org/p/waud)
 - [ ] [haxe-doctest `1.0.1`](http://lib.haxe.org/p/haxe-doctest)
 - [ ] [jstack `0.1.0`](http://lib.haxe.org/p/jstack/)
 - [ ] [hexMachina `0.5.0`](https://twitter.com/francisbourre/status/755361012077985792)
 - [ ] [buddy `2.5.2`](http://lib.haxe.org/p/buddy)
 - [ ] [dataclass `0.21.3`](http://lib.haxe.org/p/dataclass)
 - [ ] [utest `1.5.0`](http://lib.haxe.org/p/utest)
 - [ ] [lime `3.0.3`](http://lib.haxe.org/p/lime)
 - [ ] [openfl `4.0.3`](http://lib.haxe.org/p/openfl)
 - [ ] [swf `2.2.3`](http://lib.haxe.org/p/swf)
 - [ ] [hxInflate `0.3.0`](http://lib.haxe.org/p/hxinflate)
 - [ ] [exceljs `0.14.0`](http://lib.haxe.org/p/exceljs-hx)
 - [ ] [hxslam `0.3.0`](http://lib.haxe.org/p/hxslam)
 - [ ] [codegen `1.3.1`](http://lib.haxe.org/p/codegen)
 - [ ] [codemirror `1.1.0`](http://lib.haxe.org/p/codemirror)
 - [ ] [hant `3.6.2`](http://lib.haxe.org/p/hant)
 - [ ] [jsfl `1.2.4`](http://lib.haxe.org/p/jsfl)
 - [ ] [refactor `3.4.1`](http://lib.haxe.org/p/refactor)
 - [ ] [stdlib `2.1.4`](http://lib.haxe.org/p/stdlib)
 - [ ] [xpcom `1.3.3`](http://lib.haxe.org/p/xpcom)
 - [ ] [HaQuery `6.7.3`](http://lib.haxe.org/p/haquery)
 - [ ] [stx_chunk `0.0.6`](http://lib.haxe.org/p/stx_chunk)
 - [ ] [moon-ai `0.1.0`](http://lib.haxe.org/p/moon-ai) :star2: 
 - [ ] [extension-android-immersive `1.0.2`](http://lib.haxe.org/p/extension-android-immersive)
 - [ ] [hxmake `0.0.1`](http://lib.haxe.org/p/hxmake)
 - [ ] [hxease `1.0.0`](http://lib.haxe.org/p/hxease)
 - [ ] [nanotest `1.0.1`](http://lib.haxe.org/p/nanotest)
 - [ ] [haxe-ws `0.1.0`](http://lib.haxe.org/p/haxe-ws)
 - [ ] [luce `0.8.4`](http://lib.haxe.org/p/luce)
 - [ ] [aws-sdk-neko `0.1.0`](http://lib.haxe.org/p/aws-sdk-neko) :star2: 
 - [ ] [knockout.hx `3.3.1`](http://lib.haxe.org/p/knockout.hx)
 - [ ] [HaggleVNE `1.0.0`](http://lib.haxe.org/p/HagglerVNE)
 - [ ] [geojson `0.9.5`](http://lib.haxe.org/p/geojson)
 - [ ] [libsetup `git`](https://github.com/Yanrishatum/CherrySoup/tree/master/libsetup)
 - [ ] [haxeui-nme `git`](https://github.com/haxeui/haxeui-nme) :star2: 
 - [ ] [haxeui-kha `git`](https://github.com/haxeui/haxeui-kha) :star2: 
 - [ ] [haxeui-luxe `git`](https://github.com/haxeui/haxeui-luxe) :star2: 
 - [ ] [haxeui-hxwidgets `git`](https://github.com/haxeui/haxeui-hxwidgets) :star2: 
 - [ ] [haxeui-openfl `git`](https://github.com/haxeui/haxeui-openfl) :star2: 
 - [ ] [haxeui-flame `git`](https://github.com/haxeui/haxeui-flambe) :star2: 
 - [ ] [haxeui-pixijs `git`](https://github.com/haxeui/haxeui-pixijs) :star2: 
 - [ ] [haxeui-html5 `git`](https://github.com/haxeui/haxeui-html5) :star2: 

- [ ] ide updates
 - [ ] vaxe adds python2/3 support - [github issue](https://github.com/jdonaldson/vaxe/issues/94)

**Comment by skial** [comment]
- [ ] community news
 - [ ] [Python Tutorials](https://steemit.com/@kkaos)

- [ ] code snippets, insights
 - [ ] Override standard types via macros - [git comment](https://github.com/HaxeFoundation/hxnodejs/issues/42#issuecomment-233547042)

- [ ] core news
 - [ ] [Improve `StringBug.add` to increase performance](https://github.com/HaxeFoundation/haxe/issues/5440)
 - [ ] [DCE adjustments for Lua](https://github.com/HaxeFoundation/haxe/pull/5479) - pr merged
 - [ ] [HaxeLib now powered by AWS CloudFront](https://github.com/HaxeFoundation/haxelib/issues/33#issuecomment-233066414)

- [ ] job offers
 - [ ] [Gamesys London Job](https://groups.google.com/d/msg/haxelang/Ivfibl0TWMI/9syYc08IAgAJ)
 - [ ] [Haxe opportunity in London](https://groups.google.com/d/msg/haxelang/vI24XJbQiFg/MA3s759xBgAJ)

**Comment by skial** [comment]
- [ ] Haxe proposals
 - [ ] [Add `Any.hx` type](https://github.com/HaxeFoundation/haxe-evolution/pull/1)

**Comment by skial** [comment]
- [ ] Core updates
 - [ ] as3hx gets a recent surge of fixes and improvements by @SlavaRa - [commit list](https://github.com/HaxeFoundation/as3hx/commits/master?author=SlavaRa)
 - [ ] The `Any.hx` type has been added to Haxe, available from a nightly build - [commit](https://github.com/HaxeFoundation/haxe/commit/f72909dabe251b0fc15b00f53c3a009191ab4818) - [issue](https://github.com/HaxeFoundation/haxe/issues/5322)

**Comment by skial** [comment]
- [ ] Community
 - [ ] [Building 42 games within a year](https://twitter.com/mknol/status/760750801660866560)

- [ ] demos, previews
 - [ ] Shape ship procedurally generating internal structure - [tweet](https://twitter.com/dazKind/status/761515890106048512)
 - [ ] A Wicked Curse whale dungeon - [tweet](https://twitter.com/ericmbernier/status/761938095855931393)
 - [ ] Hegemone Pass website launch - [tweet](https://twitter.com/ingenoire/status/762008374733115396)
 - [ ] N°7 preview and devlog - [tweet](https://twitter.com/EdoardoLopes/status/762019442557616129)

- [ ] library releases
 - [ ] [google-apps-script `git`](https://github.com/tong/google-apps-script) :star2: - [in use](https://github.com/tong/google-apps-script/pull/1#issuecomment-237342301)
 - [ ] [chrome-app `52.0.0`](http://lib.haxe.org/p/chrome-app/)
 - [ ] [chrome-extension `52.0.1`](http://lib.haxe.org/p/chrome-extension)
 - [ ] [raymp `1.0.1`](http://lib.haxe.org/p/raymp)
 - [ ] [away3d `1.3.2`](http://lib.haxe.org/p/away3d)
 - [ ] [monsoon `0.3.0`](http://lib.haxe.org/p/monsoon)
 - [ ] [path2ereg `0.1.0`](http://lib.haxe.org/p/path2ereg)
 - [ ] [jquery-uipages `0.0.5`](http://lib.haxe.org/p/jquery-uipages)
 - [ ] [tink_await `0.1.6`](http://lib.haxe.org/p/tink_await)
 - [ ] [flixel `4.1.1`](http://lib.haxe.org/p/flixel)
 - [ ] [as3hx `1.0.3`](http://lib.haxe.org/p/as3hx)
 - [ ] [airconsole `1.0.0`](http://lib.haxe.org/p/AirConsole)
 - [ ] [signal `1.0.2`](http://lib.haxe.org/p/signal)
 - [ ] [khage `0.0.4`](http://lib.haxe.org/p/khage)
 - [ ] [samecodes-chartboost `1.0.5`](http://lib.haxe.org/p/samcodes-chartboost)
 - [ ] [pixijs `3.1.3`](http://lib.haxe.org/p/pixijs)
