### ISSUE TITLE
Haxe Roundup 368

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#325]
To add to the roundup todo list, use the following markdown format.
```
- [ ] optional description [link name](/link/to/item) by [Persons Name](link/to/person)
```

**Comment by IBwWG** [comment]
- [ ] Mini Ludum Dare entry (HTML5/Flash, made with HaxeFlixel) [Anticolonias](http://ludumdare.com/compo/minild-69/?action=preview&uid=67231) by [KJB of IBwWG](https://twitter.com/wastheWordGame)

**Comment by IBwWG** [comment]
Also what about https://github.com/stuartcaunt/xt3d ?  It doesn't seem this was ever covered on haxe.io but it's been around a year and is still actively developed, if unfinished.  Last release was 16 days ago.

**Comment by skial** [comment]
Absolutely, I don't remember ever coming across it before.

**Comment by accidentalrebel** [comment]
- [ ] Haxe import library for Emacs released called [Emacs Haxe Imports](https://github.com/accidentalrebel/emacs-haxe-imports) by [AccidentalRebel](https://twitter.com/accidentalrebel)

**Comment by skial** [comment]
- [ ] core compiler
 - [ ] Brand new Php generator being worked on - [commits](https://github.com/RealyUniqueName/haxe/commits/php7?author=RealyUniqueName) :star2: 
 - [ ] as3hx still improving - [repo](https://github.com/HaxeFoundation/as3hx)

- [ ] demos, previews
 - [ ] Listview implemented in wxWidgets and coming to HaxeUI soon! - [tweet](https://twitter.com/IanHarrigan1982/status/765947555364663296)
 - [ ] Spaceship decks, hall ways and lifts auto generated - [tweet](https://twitter.com/dazKind/status/765673853574152200)

- [ ] community updates
 - [ ] Lewis Lepton, Kha tutorial series creator, outline future plans on Patreon - [tweet](https://twitter.com/lewislepton/status/765861257920536576)
 - [ ] HaxeFlixel fundraiser gets extra goodies! - [tweet](https://twitter.com/leongotgame/status/765679819409457152)
 - [ ] Help shape the rewrite of the php compiler target - [tweet](https://twitter.com/RealyUniqueName/status/764468459698814976)
 - [ ] DC/AC virtual labs full wave rectifier walk through - [tweet](https://twitter.com/hopewise/status/763969755984171010)
 - [ ] Northgard trailer - [tweet](https://twitter.com/ncannasse/status/762997545215856640)
 - [ ] HaxeFlixel fundraiser nearly at `$7K`, 219% of total. - [tweet](https://twitter.com/larsiusprime/status/765652135857954816) - [kongregate buys gold sponsership](https://twitter.com/larsiusprime/status/763763980548485120)
 - [ ] Kha stereo rendering - [tweet](https://twitter.com/luboslenco/status/763418296398049280)

- [ ] jobs
 - [ ] London based Haxe developer position working on social games - [tweet](https://twitter.com/JamesBiniti8/status/763020549706637313)

- [ ] talks and slides
 - [ ] Slides from Eugenes RedGameDev Haxe talk - [tweet](https://twitter.com/nitrobin/status/766171293297377280)

- [ ] videos
 - [ ] Kha tutorial ep41 - project sound - [tweet](https://twitter.com/lewislepton/status/763015718304645120)
 - [ ] Kha tutorial ep42 - install kha2d - [tweet](https://twitter.com/lewislepton/status/765503501451595776)

- [ ] code snippets
 - [ ] Haxe macro get expected identifier name - [tweet](https://twitter.com/skial/status/765833416021516288)
 - [ ] Parametrized abstract externs - [tweet](https://twitter.com/nadako/status/765325317879791617) :star2: 
 - [ ] Handle javascript events with haxe 3.3.0 abstracts - [tweet](https://twitter.com/sa_su_ke/status/765190489037561856) :star2: 
 - [ ] Haxe macro to get abstract `@:enum` values - [gist](https://gist.github.com/skial/592a9c1e58ff701e186de19fae31e946)
 - [ ] Functional threading with macros - [tweet](https://twitter.com/sa_su_ke/status/763678726483742720)

- [ ] libs
 - [ ] [odd `git`](https://twitter.com/dstrekelj/status/764491704963653633)

**Comment by skial** [comment]
- [ ] community updates
 - [ ] `linc_steam_api` still in the works - [progress update](https://github.com/snowkit/linc/issues/8#issuecomment-240942604)
 - [ ] `Harfang 1.0.0`, a haxe web framework, has been released - [thread](https://groups.google.com/d/msg/haxelang/d3v5qpD4OcU/12bq4PTWAgAJ) 
 - [ ] Dox, the haxe documentation lib, has been updated - [thread](https://groups.google.com/d/msg/haxelang/23ELJ_W29Bo/ZSSRnFkUAgAJ)
 - [ ] UFront-orm updates - [pr](https://github.com/ufront/ufront-orm/pull/28)
 - [ ] hidden haxe compiler ability - [thread](https://groups.google.com/d/msg/haxelang/zSa8G7Yhx88/X5BsIxXoBwAJ)

- [ ] core updates
 - [ ] cook book wanted articles list - [issue](https://github.com/HaxeFoundation/code-cookbook/issues/49)
 - [ ] ipv6 support needed - [issue](https://github.com/HaxeFoundation/haxe/issues/3122#issuecomment-236357856)
- [ ] Proper utf-8 code point encoding _possibly_ coming to the compiler - [issue](https://github.com/HaxeFoundation/haxe/issues/5163#issuecomment-240806895)
- [ ] Better windows compiler building support - [issue](https://github.com/HaxeFoundation/haxe/issues/5174#issuecomment-240809143)

**Comment by skial** [comment]
- [ ] previews, demos
 - [ ] Sakura enemies - [tweet](https://twitter.com/fierysquirrel/status/766296208801280000)

- [ ] videos
 - [ ] Kha tutorial ep43 - kha2d animation - [tweet](https://twitter.com/lewislepton/status/766228254411939840)

- [ ] lib releases
 - [ ] [waud `0.7.0`](http://lib.haxe.org/p/waud)
 - [ ] [openfl-atlas `1.0.0`](http://lib.haxe.org/p/openfl-atlas)
 - [ ] [rexit `1.0.5`](http://lib.haxe.org/p/rexit)
 - [ ] [harfang `1.0.0`](http://lib.haxe.org/p/Harfang) :star2: 
 - [ ] [parsihx `0.2.0`](http://lib.haxe.org/p/parsihax) :star2: 
 - [ ] [ecx `0.0.3`](http://lib.haxe.org/p/ecx)
