### ISSUE TITLE
Haxe Roundups 382

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#386]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item) by [Persons Name](link/to/person)
```

**Comment by Aurel300** [comment]
- lib release
   - [ ] [plustd](https://github.com/Aurel300/plustd)
 - LDJAM 38 game
   - [ ] [Planet of Babel](ludum.thenet.sk/ld38)

**Comment by kevansevans** [comment]
- Game Release [openLR](https://github.com/kevansevans/openLR)

**Comment by boorik** [comment]
-  [ ] LDJAM 38 game :  [Aquarium king election](https://ldjam.com/events/ludum-dare/38/aquarium-king-election) by [Vincent Blanchet](https://twitter.com/deadponycorn)

**Comment by skial** [comment]
- news
  - [ ] Haxe nightlies gets **short lambdas _(arrow functions)_** - https://github.com/HaxeFoundation/haxe/pull/6209
  - [ ] Building a collision engine Part 1

- lib releases
  - [ ] [dragonbones `5.0.0`](http://lib.haxe.org/p/dragonbones)
  - [ ] [haxpression `2.0.2`](http://lib.haxe.org/p/haxpression) :star2: 
  - [ ] [js-virtual-dom `0.5.5`](http://lib.haxe.org/p/js-virtual-dom)
  - [ ] [tink_core `1.13.0`](http://lib.haxe.org/p/tink_core)
  - [ ] [http-status `1.2.1`](http://lib.haxe.org/p/http-status)
  - [ ] [texturepacker `0.0.9`](http://lib.haxe.org/p/texturePacker)
  - [ ] [lunar `0.1.0`](http://lib.haxe.org/p/lunar)
  - [ ] [pixijs `4.5.0`](http://lib.haxe.org/p/pixijs)
  - [ ] [nme-toolkit `6.1.0`](http://lib.haxe.org/p/nme-toolkit)
  - [ ] [dodrugs `1.0.0-beta.1`](http://lib.haxe.org/p/dodrugs)
  - [ ] [tink_state `0.5.0`](http://lib.haxe.org/p/tink_state)
  - [ ] [priori `0.7.1`](http://lib.haxe.org/p/priori)
  - [ ] [priori-bootstrap `0.1.1`](http://lib.haxe.org/p/priori-bootstrap)
  - [ ] [PixiGAFPlayer `git`](https://github.com/mathieuanthoine/PixiGAFPlayer) :star2: 

- app releases
  - [ ] Fake Text Mode Snake released onto itch.io - https://twitter.com/Uhfgood/status/859156698501701634

- tutorials
  - [ ] HaxeFlixel Sprite Animation - https://twitter.com/gamefromscratch/status/857647225438175233
  - [ ] HaxeFlixel Sound and Music - https://twitter.com/gamefromscratch/status/857265012213252097 :book: 

- demos
  - [ ] Speedbot preview - https://twitter.com/kircode/status/858745831196897280
  - [ ] Who hasnt played ~Soccer~ Football against a trashcan - https://twitter.com/austineastDev/status/858559851819126785
  - [ ] Running bear or flying goblin - https://twitter.com/egor69ok/status/858070015974813697
  - [ ] Procedurally generated medieval villages - https://twitter.com/watawatabou/status/857137330729213954 :star2: 

- patreons
  - [ ] https://twitter.com/mayakwd/status/858962091864203266

**Comment by skial** [comment]
- libs
  - [ ] [justTriangles `git`](https://github.com/nanjizal/justTriangles) :star2: 

- news
  - [ ] Dodrugs announcement - https://groups.google.com/d/msg/haxelang/2M7AdIbbVFQ/sBL8a_JfAQAJ

- evolution proposals
  - [ ] Allow context specific keywords - https://github.com/HaxeFoundation/haxe-evolution/issues/22

- core
  - [ ] Haxe lexer now encoding aware - https://github.com/HaxeFoundation/haxe/issues/5163#event-1064096720
  - [ ] Allow `@:op(A in B)` - https://github.com/HaxeFoundation/haxe/issues/6224

- [ ] eval - https://github.com/Simn/haxe/commits/eval

**Comment by nanjizal** [comment]
justTriangles is still quite experimental, not sure it's suitable yet for list of libraries, it's still very much evolving, but I guess it's there now, perhaps add '( experimental )' to it's entry?  The demos will currently not compile as it has changed since they were created, but can update them easily.

**Comment by skial** [comment]
@nanjizal The library was marked with and links to the `git` repo, imo, this should be enough for people to understand the library maybe in active development. Maybe the the section title should be _lib updates_ instead of _lib releases_...

**Comment by nanjizal** [comment]
@skial one aspect of the roundups that currently troubles me is the "Previews Demos & Snippets" section, I would like to see any "opensource" code promoted separately from just links to games people are working on or unreleased code, as more and more people are providing cool demos without any source access, but obviously it's important to promote the stuff people can explore higher, quite happy for closed stuff and game releases to go to the bottom of the post.
At the moment I feel the sections are muddled between areas of code that I can look at explore and contribute towards, and stuff the is purely inspirational or coming soon, essentially advertising/promotional.  Unless there is a section clearly marked for open exploration that most haxe users will look at above just previews for games, it does not motivate users to share open work as much and we are seeing the preview section containing less and less code to look at.  I guess there needs to be more open demos but still separation would be ideal.

Opensource Explore

Previews

But otherwise keep up great work this is a brilliant project your creating.

**Comment by skial** [comment]
Thanks @nanjizal the separation point is a good one :smile: . I could split the _previews_ section up, maybe adding subheadings to be a little clearer.

Most of the promotional/advertising stuff is in the previews and app releases section, which you know. If I come across an article promoting the preview or app release I'll probably add it to the news section, normally because the news section is light on content. 

I would like to have a section that lists projects/repos that are specifically looking for help, but this would require me spending more time keeping an eye on lots of repos. At the moment I'm not going to spend any more time on the roundups than I already do. 

I'm all for promoting open source work when it's being promoted by the dev, a great example is Ian Harrigan's HaxeUI project and Lubos Lenco's Armory project. But both of these, _at the stage they are at now_, fall into the same category as games, they are visual, which is easier to show progress. Imo anyway.

And yes the preview section has seen less and less code being shared, there is a good chance I'm missing it, but if I do, people are pretty quick to point it out to me, usually.
