### ISSUE TITLE
Haxe Roundup 400

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#432]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```

**Comment by Matan** [comment]
- [ ] Cross-platform filesystem lib [ki-filesystem] (https://lib.haxe.org/p/ki-filesystem)

**Comment by skial** [comment]
- haxesummit
  - [ ] Haxe Summit 2017 Party Report - [article](http://haxe.org/blog/haxe-summit-2017-party-report/)
  - [ ] Haxe Summit 2017 Links - [doc](https://docs.google.com/document/d/1RLheR9FIUCRtV174DJsb8lYpEpUw6bUnGKq8LjW3Bws/edit#)

- articles, news, etc
  - [ ] Haxe `3.4.3` has been released - [tweet](https://twitter.com/haxe_org/status/907686319794659328)
  - [ ] Haxe `4.0.0-preview.1` has been released - [tweet](https://twitter.com/disktree/status/907634368461643777)
  - [ ] Reverse arc length parameterization [example](https://twitter.com/matrefeytontias/status/910618129503571975)
  - [ ] Developers start your engines: The race to transition your game off Flash has officially begun - [article](https://twitter.com/haxe_org/status/910218413703880704)
  - [ ] The Haxe Foundation and Docler Holding become strategic partners - [tweet](https://twitter.com/DoclerHoldingLU/status/908260238402445312)
  - [ ] 10 Year Anniversary! Haxe, HXCPP and NME - [article](http://gamehaxe.com/2017/09/11/10-year-anniversary/)
  - [ ] Kha has PS4, Xbox One and Nintendo Switch backends - [tweet](https://twitter.com/luboslenco/status/909746131000791040)

- lib releases
  - [heaps `1.0.0`](http://lib.haxe.org/p/heaps) :star2: 
  - [hxcpp `3.4.188`](http://lib.haxe.org/p/hxcpp) :star2: 
  - [winrpi `1.0.0`](http://lib.haxe.org/p/winrpi) :star2: 
  - [hxmlinstall `0.0.5`](http://lib.haxe.org/p/hxmlinstall)
  - [jwt `1.3.0`](http://lib.haxe.org/p/jwt)
  - [gotocore-hx `1.0.0`](http://lib.haxe.org/p/gotocore-hx)
  - [gotocore-hx-nodejs `0.0.1`](http://lib.haxe.org/p/gotocore-hx-nodejs)
  - [pixijs `4.5.5`](http://lib.haxe.org/p/pixijs)
  - [jstack `2.3.5`](http://lib.haxe.org/p/jstack)
  - [zlender `git`](https://github.com/AdrianV/zlender) :star2:
  - [waud `0.9.13`](http://lib.haxe.org/p/waud)
  - [modular `0.5.0`](http://lib.haxe.org/p/modular) :star2: 
  - [haxe-loader `0.2.1`](http://lib.haxe.org/p/haxe-loader)
  - [haxe-doctest `1.1.0`](http://lib.haxe.org/p/haxe-doctest)
  - [openfl `6.1.2`](http://lib.haxe.org/p/openfl)
  - [lime `5.5.0`](http://lib.haxe.org/p/lime)
  - [as3hx `1.0.5`](http://lib.haxe.org/p/as3hx)
  - [starling `1.8.11`](http://lib.haxe.org/p/starling)
  - [away3d `5.0.4`](http://lib.haxe.org/p/away3d)
  - [away3d-samples `5.0.2`](http://lib.haxe.org/p/away3d-samples)
  - [svg `1.1.2`](http://lib.haxe.org/p/svg)
  - [tnative `1.2.1`](http://lib.haxe.org/p/tnative)
  - [hexmachina `0.29.2`](http://lib.haxe.org/p/hexmachina/)
  - [tink_typecrawler `0.5.2`](http://lib.haxe.org/p/tink_typecrawler)
  - [tink_macro `0.14.2`](http://lib.haxe.org/p/tink_macro)
  - [tink_anon `0.1.3`](http://lib.haxe.org/p/tink_anon)
  - [js-virtual-dom `0.9.1`](http://lib.haxe.org/p/js-virtual-dom)
  - [coconut.vdom `0.4.2`](http://lib.haxe.org/p/coconut.vdom)
  - [nme `6.0.58`](http://lib.haxe.org/p/nme)
  - [Console.hx `0.2.3`](http://lib.haxe.org/p/Console.hx)
  - [yield `1.1.0`](http://lib.haxe.org/p/yield)
  - [flixel-demos `2.4.2`](http://lib.haxe.org/p/flixel-demos)
  - [promhx-unit-test `2.2.0`](http://lib.haxe.org/p/promhx-unit-test)
  - [byteConvert `1.0.3`](http://lib.haxe.org/p/byteConvert)

- code examples
  - [ ] Set git dependency directly in hxml - [tweet](https://twitter.com/mknol/status/909876589223084033)

- os demos
  - [ ] Global illumination from a little Armory game - [tweet](https://twitter.com/luboslenco/status/910142952877576194)
  - [ ] OpenLR is getting a HTML5 version thanks to OpenFL - [tweet](https://twitter.com/kbeevans/status/909330865552998400)
  - [ ] Procedurally generated cities - [tweet](https://twitter.com/watawatabou/status/908343320140812288)

- cs demos
  - [ ] Relay switch in action built with Circuit Simulator - [tweet](https://twitter.com/hopewise/status/909663889041879040)
  - [ ] _Like mamma said, you gotta go fast_ - [tweet](https://twitter.com/austinweast/status/907841530504892417)

- videos
  - Kha tutorial - EP70 - Volume Control - [tweet](https://twitter.com/lewislepton/status/908234443223166976)

**Comment by Aurel300** [comment]
- games
  - https://twitter.com/AurelDev/status/910837145304215554 - rgbwiz, a OneHourGameJam entry

**Comment by skial** [comment]
- news
  - [ ] HashLink `1.2` has been released - [tag](https://github.com/HaxeFoundation/hashlink/releases/tag/1.2), _with partial LibUV support_

- videos
  - [ ] Kha tutorial - EP71 - Depth - [youtube](https://www.youtube.com/watch?v=W5kfC13H-RY)

- framework
  - [ ] Hololens support for Kha - [pr](https://github.com/Kode/Kore/pull/214)

- core 
  - [ ] `final` keyword debate? - [issues](https://github.com/HaxeFoundation/haxe/issues/6584)
  - [ ] Unification error messages - [issue](https://github.com/HaxeFoundation/haxe/issues/6597)
  - [ ] Remove `haxe.unit` - [pr](https://github.com/HaxeFoundation/haxe/pull/6600)
  - [ ] Add the `final` keyword - [pr](https://github.com/HaxeFoundation/haxe/pull/6596)
  - [ ] Implement language independent source maps - [issue](https://github.com/HaxeFoundation/haxe/issues/6591)
  - [ ] Target configuration from command line - [issue](https://github.com/HaxeFoundation/haxe/issues/6582)

**Comment by skial** [comment]
- frameworks
  - [ ] Fix joystick mappings, optimizations with retrocompatibility - [pr](https://github.com/haxenme/nme/pull/503)

- core
  - [ ] Super flatten JS output - [issue](https://github.com/HaxeFoundation/haxe/issues/6602)
  - [ ] Example of how to use custom ocaml coded generators with the compiler - [comment](https://github.com/HaxeFoundation/haxe/issues/6582#issuecomment-331189031)

**Comment by skial** [comment]
- frameworks
  - [ ] Threaded cached for HXCPP speedup by `33%` - [pr](https://github.com/HaxeFoundation/hxcpp/pull/640)
