### ISSUE TITLE
Haxe Roundup 405

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#443]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```

**Comment by Beeblerox** [comment]
- [ ] TetraSoft LLC. (Saint-Petersburg, Russia) is looking for ActionScript/Flex developer who wish to learn Haxe/TypeScript languages - [job description](http://www.flasher.ru/forum/showthread.php?t=214635)

**Comment by skial** [comment]
- haxe summit 2017
  - [ ] Videos are being uploaded - [channel](https://www.youtube.com/channel/UCGTson1aVohkJnbrqpNBXqg)

- articles
  - [ ] [Hanging on Balloons in Speer](https://twitter.com/ohsat_games/status/922987099975974913)
  - [ ] Game series tutorial update - [tweet](https://twitter.com/lewislepton/status/921458331369312256)

- os demos

- cs demos
  - [ ] :ru: Racing game preview - [tweet](https://twitter.com/ryzzed/status/922953032689692677)
  - [ ] Four player split screen - [tweet](https://twitter.com/aidanleegames/status/922945258505363456)
  - [ ] Kaizen HaxeUI app gets a facelift - [tweet](https://twitter.com/IanHarrigan1982/status/922780255877783552) :star2: 

- libs
  - [ ] [openfl `6.3.0`](http://lib.haxe.org/p/openfl)
  - [ ] [lime `5.8.0`](http://lib.haxe.org/p/lime)
  - [ ] [as3hx `1.0.6`](http://lib.haxe.org/p/as3hx)
  - [ ] [sortablejs.npm `0.0.3-alpha`](http://lib.haxe.org/p/sortablejs.npm)
  - [ ] [hxsocketio `0.1.0`](http://lib.haxe.org/p/hxsocketio)
  - [ ] [hxmake `0.1.8`](http://lib.haxe.org/p/hxmake)
  - [ ] [texturePacker `0.0.10`](http://lib.haxe.org/p/texturePacker)
  - [ ] [tink_json `0.6.3`](http://lib.haxe.org/p/tink_json) :star2: 

- app releases
  - [ ] Halloween Party released on the [Play Store](https://twitter.com/SehicGonzo/status/922436628395823104) created with OpenFL
  - [ ] [Tetristhing](https://twitter.com/AurelDev/status/921871557777149953) created for `#onehourgamejam`
  - [ ] Play KhappyBalt - [tweet](https://twitter.com/lewislepton/status/921787708535726080)
  - [ ] Old School Test Drive has been release on the [Play Store and App store](https://twitter.com/AdderitGames/status/921273028666945537)

**Comment by skial** [comment]
- jobs
  - [ ] Haxe/OpenFL Game Developer - Forge of Empires or Elvenar https://github.com/skial/haxe.io/issues/444

**Comment by skial** [comment]
- evolutions
  - [ ] Global using at declaration site - [issue](https://github.com/HaxeFoundation/haxe-evolution/issues/35)

- core
  - [ ] Allow `var ?x:T` - [issue](https://github.com/HaxeFoundation/haxe/issues/6707)
  - [ ] Hashlink `1.3` - [tag](https://github.com/HaxeFoundation/hashlink/releases/tag/1.3)

**Comment by skial** [comment]
- core
  - [ ] rework exception handling - [pull request](https://github.com/HaxeFoundation/haxe/pull/6713)

- framework updates
  - [ ] Haxepunk misc updates - [pull request](https://github.com/HaxePunk/HaxePunk/pull/518)

- libs
  - [ ] [no-vdom `0.1.0`](http://lib.haxe.org/p/no-vdom) :star2: 
  - [ ] [plumob `git`](https://github.com/Aurel300/plumob) :star2:
