### ISSUE TITLE
Haxe Roundup 422

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#484]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- news, articles
  - [ ] HashLink `1.5` upcoming release - [tag](https://github.com/HaxeFoundation/hashlink/releases/tag/1.5)
  - [ ] Checkout Haxe.org's new video section - [videos](https://haxe.org/videos/)
  - [ ] Haxe.org now has its own merchandise - [shop](https://haxe.org/foundation/shop/#!/)
  - [ ] Particle talk and future framework plans - [article](https://lewislepton.com/blog/2018/03/05/particles-&-framework-plans/)

- vids
  - [ ] Kha tutorial - EP080 - Center Position - [youtube](https://www.youtube.com/watch?v=9IqXJZq4pyw)
  - [ ] Kha tutorial - EP081 - Delete Array Entity - [twitter](https://t.co/9HBrXREaOX)

- events & talks
  - [ ] CreativeMagic will be giving a talk about indie/freelance gamedev on Haxe + OpenFL - [thread](https://community.haxe.org/t/event-game-dev-event-in-tokyo/512/1)

- ~~os previews, demos~~

- cs previews, demos
  - [ ] TouretteQuest protoype targeting HTML5 with HaxeFlixel for `7DRL` in-progress - [tweet](https://twitter.com/larsiusprime/status/971266306761723904)
  - [ ] Isometric projection in HaxeFlixel - [tweet](https://twitter.com/JoeCreates/status/969633683962519552)

- lib releases
  - [ ] [haxicord `0.2.2`](http://lib.haxe.org/p/Haxicord)
  - [ ] [geojson `0.9.7`](http://lib.haxe.org/p/geojson)
  - [ ] [annyang_lib `0.0.1`](http://lib.haxe.org/p/annyang_lib)
  - [ ] [protobux `1.0.0`](http://lib.haxe.org/p/protobux)
  - [ ] [enzyme `0.5.1`](http://lib.haxe.org/p/enzyme)
  - [ ] [event-types `0.2.1`](http://lib.haxe.org/p/event-types)
  - [ ] [tink_hxx `0.15.2`](http://lib.haxe.org/p/tink_hxx)
  - [ ] [tink_state `0.6.2`](http://lib.haxe.org/p/tink_state)
  - [ ] [hxbit `1.4.0`](http://lib.haxe.org/p/hxbit)
  - [ ] [haxegon `0.12.1`](http://lib.haxe.org/p/haxegon)

- lib updates
  - [ ] [ts2hx](https://github.com/ncannasse/ts2hx) can convert `.d.ts` to `.hx` - [comment](https://github.com/HaxeFoundation/haxe/issues/6546#issuecomment-369977111)
  - [ ] webidl now tracks position information, allowing IDE goto definitions - [pull request](https://github.com/ncannasse/webidl/pull/4)
  - [ ] tink_sql adds `tink.sql.Query`, a fully type safe? SQL query implementation? - [pull request](https://github.com/haxetink/tink_sql/pull/61)
  - [ ] Haxe modular `0.10.2` released with detailed size report and visualisations - [thread](https://twitter.com/elsassph/status/969548430849830914)

- core changes
  - [ ] Discussion about missing `Socket` and `Sys` tests - [thread](https://github.com/HaxeFoundation/haxe/issues/6889)
  - [ ] Add support for `toString` metadata - [pull request](https://github.com/HaxeFoundation/haxe/pull/6894) - [example](https://github.com/HaxeFoundation/haxe/issues/6841#issuecomment-371237157)
  - [ ] Haxe compiler will use OCaml native `SHA1` implementation - [pull request](https://github.com/HaxeFoundation/haxe/pull/6890)

**Comment by skial** [comment]
- os previews, demos
  - [ ] [Trilateral](https://github.com/nanjizal/Trilateral) now does curved corners - [tweet](https://twitter.com/Nanjizal_net/status/970772604071088129)

- cs previews, demos
  - [ ] Swanky new health meters in kitty coliseum built with HaxePunk - [tweet](https://twitter.com/mousemobgames/status/971059368501248000)


- articles
  - [ ] Collision Boxes & Interaction - [article](https://lewislepton.com/blog/2018/03/02/collision-boxes-&-interaction/)
