### ISSUE TITLE
Haxe Roundup 435

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#514]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by codingthat** [comment]
- [ ] [Haxe: Cross-platform Development's Best-kept Secret](https://www.toptal.com/cross-platform/haxe-language-cross-platform) published on the Toptal Engineering Blog

**Comment by skial** [comment]
- news, articles
  - [ ] Haxe `4.0.0-preview..4` has been released! - [tweet](https://twitter.com/haxe_org/status/1006630901462261760)
  - [ ] HashLink `1.6` has been released - [tweet](https://twitter.com/ncannasse/status/1006663958605058048)
  - [ ] The HaxeLib website has had several improvements released - [tweet](https://twitter.com/haxe_org/status/1006632619906355200)
  - [ ] The Haxe VSCode `2.0.0` extension has been released - [tweet](https://twitter.com/haxe_org/status/1006634249217363969)
  - [ ] Forge of Empires has enabled their HTML5 build, made with OpenFL - [tweet](https://twitter.com/nadako/status/1006879345770713088)

- videos
  - [ ] Haxe `4.0.0-preview.4` overview - [tweet](https://twitter.com/gamefromscratch/status/1006607830621700096)
  - [ ] Armory3D Engine Series - Getting Started - [tweet](https://twitter.com/gamefromscratch/status/1006552645501407233)
  - [ ] Kha Tutorial - EP084 - Random Range - [tweet](https://twitter.com/lewislepton/status/1006503173127856128)
  - [ ] Kha Tutorial - EP083 - LERP - [tweet](https://twitter.com/lewislepton/status/1004736345762418688)

- libs
  - [ ] [hexmachina `1.0.0-alpha.3`](http://lib.haxe.org/p/hexmachina)
  - [ ] [hlsdl `1.6.0`](http://lib.haxe.org/p/hlsdl)
  - [ ] [hldx `1.6.0`](http://lib.haxe.org/p/hldx)
  - [ ] [argan `0.9.2`](http://lib.haxe.org/p/argan)
  - [ ] [flex `4.4.2`](http://lib.haxe.org/p/flixel) - _Haxe `4.0.0-preview.4` compatible_ - [tweet](https://twitter.com/HaxeFlixel/status/1006569948720848896)
  - [ ] [hxbit `1.4.1`](http://lib.haxe.org/p/hxbit)
  - [ ] [commonbox `0.1.1`](http://lib.haxe.org/p/commonbox)
  - [ ] [tink_await `0.4.0`](http://lib.haxe.org/p/tink_await)
  - [ ] [yield `1.2.0`](http://lib.haxe.org/p/yield)
  - [ ] [vscode `1.24.0`](http://lib.haxe.org/p/vscode)
  - [ ] [nice `1.3.0`](http://lib.haxe.org/p/Nice)
  - [ ] [tokentree `1.0.0`](http://lib.haxe.org/p/tokentree)
  - [ ] [hre `0.1.4`](http://lib.haxe.org/p/hre)

- events
  - [ ] Nicolas Cannasse will be speaking at Game Camp France 18/19 June - [tweet](https://twitter.com/haxelang/status/1005102817621635072)

- os previews
  - [ ] Generating anonymous functions with the Haxe VSCode extension - [tweet](https://twitter.com/Gama11_/status/1005424364685324288)
  - [ ] Generating override signatures with the Haxe VSCode extension - [tweet](https://twitter.com/Gama11_/status/1004828180266536960)

**Comment by skial** [comment]
- news
  - [ ] Armory3D is out and free! - [thread](http://forums.armory3d.org/t/armory-0-4-is-out-and-free/1109)
  - [ ] OpenFL has official support for the Nintendo Switch and its free, once approved - [tweet](https://twitter.com/larsiusprime/status/1006942902885416960)

- videos
  - [ ] Armory3D Engine Series - Scripting Basics - [tweet](https://twitter.com/gamefromscratch/status/1006959005590159360)

- frameworks
  - [ ] [Lime] Alternatives to OpenAL - [issue](https://github.com/openfl/lime/issues/1201)
  - [ ] [Modular] Use Cherow for parsing instead of Acorn.js - [pull request](https://github.com/elsassph/haxe-modular/pull/81)

- core
  - [ ] Express function purity in type system - [issue](https://github.com/HaxeFoundation/haxe/issues/7181)
  - [ ] [js] Enum as objects cleanup - [issue](https://github.com/HaxeFoundation/haxe/issues/7165)
  - [ ] Inline cleanup - [merged](https://github.com/HaxeFoundation/haxe/pull/7155)
