### ISSUE TITLE
Haxe Roundup 448

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#542]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [ ] optional description [link name](/link/to/item)

**Comment by tbrosman** [comment]
More shameless self-promotion:

- [ ] Starscend (built on OpenFL and Haxe) has been released for Android! Store page: https://play.google.com/store/apps/details?id=com.vacuumtubegames.starscend Official Facebook page: https://www.facebook.com/VacuumTubeGames/

(@skial Not sure if you want to list both of those; it's up to you!)

Fun fact: we started in Haxe 2. In 2013. I feel like a Haxe dinosaur.

**Comment by AtomicPair** [comment]
- [ ] _Teach Monster Games, Ltd._ is looking for a Freelance Game Developer to work with them long-term to improve their core technologies based on Haxe and other languages/tools: [WeWorkRemotely posting](https://weworkremotely.com/remote-jobs/teach-monster-games-ltd-freelance-game-developer) or [Original posting](https://www.teachyourmonstertoread.com/jobs)

**Comment by skial** [comment]
- jobs
  - [ ] Front-end Haxe dev - Binkies 3D - [thread](https://community.haxe.org/t/job-front-end-haxe-developer-binkies-3d-the-hague-netherlands/1095/1)

- libs
  - [ ] [deep_equal `0.3.1`](https://lib.haxe.org/p/deep_equal)
  - [ ] [tink_state `0.9.0`](https://lib.haxe.org/p/tink_state)
  - [ ] [hexmodulardsl `1.0.0-alpha.5`](https://lib.haxe.org/p/hexmodulardsl)
  - [ ] [hexmachina `1.0.0-alpha.5`](https://lib.haxe.org/p/hexmachina)
  - [ ] [heaps `1.3.0`](https://lib.haxe.org/p/heaps)
  - [ ] [coroutine `1.0.3`](https://lib.haxe.org/p/coroutine)
  - [ ] [utest `1.8.4`](https://lib.haxe.org/p/utest)
  - [ ] [nova `0.0.2`](https://lib.haxe.org/p/nova)
  - [ ] [tink_io `0.6.0`](https://lib.haxe.org/p/tink_io)
  - [ ] [tink_streams `0.3.1`](https://lib.haxe.org/p/tink_streams)
  - [ ] [yield `1.3.3`](https://lib.haxe.org/p/yield)

- news, articles 
  - [ ] Renaine Kickstarter Update `#21` - [tweet](https://twitter.com/OctosoftUS/status/1042225240435126272)
  - [ ] Unicode in Haxe 4 - [tweet](https://twitter.com/haxe_org/status/1041658513511145473)
  - [ ] ArtsTech engine dev log - [thread](https://community.haxe.org/t/artstech-engine-development-log/1069)
  - [ ] More Rosetta Code, Neko and DNS - [thread](https://community.haxe.org/t/more-rosetta-code-neko-and-dns/1086/1)

- cs demos, previews
  - [ ] Its possible to make dynamic lights with Haxe & HaxeFlixel - [tweet](https://twitter.com/DeadWorldHeroes/status/1041997921015787523)
  - [ ] Bat dodge - [tweet](https://twitter.com/_arnulfo/status/1041039073559732224)

- os demos, previews
  - [ ] Atomic Modding + Scripting with HScript demo for Polymod - [tweet](https://twitter.com/larsiusprime/status/1040839613156405249)
  - [ ] Scholae, a student project, is an example of using Haxe, ReactJS, Redux and UIKit - [tweet](https://twitter.com/grebenshikov_n/status/1040415029634457600)

- core
  - [ ] Remove `TypedArray` pollyfills [pull request](https://github.com/HaxeFoundation/html-externs/pull/10)
  - [ ] Allow enums to be used as default args [pull request](https://github.com/HaxeFoundation/haxe/pull/7439)
  - [ ] `macro new` _possibly_ coming to Haxe [issue comment](https://github.com/HaxeFoundation/haxe/issues/5292#issuecomment-422274266)
  - [ ] Allow `[]` for empty `Map` types [added](https://github.com/HaxeFoundation/haxe/issues/7426#event-1849071836).

**Comment by Beeblerox** [comment]
- [ ] New twin-stick shooter template is available for [Armory](https://twitter.com/luboslenco/status/1040615626350493697)

**Comment by Beeblerox** [comment]
- [ ] [CastleDB integration example for Kha](https://github.com/Beeblerox/Kha-CastleDB)

**Comment by Beeblerox** [comment]
- [ ] New online Haxe event called HaxeUp Sessions is announced by [Josefiene Pertosa](https://twitter.com/Fiene_P/status/1042019000174211072). It will be at 13th of October. There will be talks from Simon Krajewski, Robert Konrad, Dan Korostelev, Aleksandr Kuzmenko, Juraj Kirchheim and possibly Nicolas Cannasse.
