### ISSUE TITLE
Haxe Roundup 491

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#646]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by Aurel300** [comment]
- [ ] [`ammer`](https://github.com/Aurel300/ammer) - unified native extensions for Haxe

**Comment by Beeblerox** [comment]
- [ ] Mino Games (Montreal, Canada) [is hiring haxe developers](https://github.com/skial/haxe.io/issues/649) (just in case if you missed this new issue)

**Comment by Beeblerox** [comment]
- [ ] New tunes for Dicey Dungeons (the game will come out next week!) by Chipzel:
* [last nights work = happy feet](https://twitter.com/chipzel/status/1156892633475817478)
* [*flails arms around wildly*](https://twitter.com/chipzel/status/1159044489387958272)
* [boop boop boop de boop boop de boop de boop boop](https://twitter.com/chipzel/status/1159096086549663746)

**Comment by Beeblerox** [comment]
- [ ] And some news and pics from Terry Cavanagh about Dicey Dungeons:
* [A 6x6 grid of every major bug and rough edge left in Dicey Dungeons](https://twitter.com/terrycavanagh/status/1157730844116770820)
* [What's changed since the last alpha?](http://distractionware.com/blog/2019/08/7-whats-changed-since-last-time/)

**Comment by Beeblerox** [comment]
- [ ] [Upcoming Armorpaint ray-tracing update now in testing phase](https://twitter.com/luboslenco/status/1156938069125341186)

**Comment by Beeblerox** [comment]
- [ ] New screenshots from WIP racing game by Ed Ryzhov:
* [Road forks](https://twitter.com/ryzzed/status/1157035011729756162)
* [Extruded grass and fencing](https://twitter.com/ryzzed/status/1157448844180885505)

**Comment by Beeblerox** [comment]
- [ ] [Andy Li](https://twitter.com/andy_li/status/1157204483736125440) has worked on 64-bit Windows haxelib builds. Here is [temp link](https://www.twitch.tv/videos/461414523) for stream recording.

**Comment by Beeblerox** [comment]
- [ ] New Video: [SciAnts Evolved Gameplay Trailer [BETA]](https://www.youtube.com/watch?v=qL4VQfGBy_w)

**Comment by Beeblerox** [comment]
- [ ] SciAnts Evolved demo had been [presented at First Friday](https://twitter.com/AxolStudio/status/1157441104440156160)

**Comment by Beeblerox** [comment]
- [ ] You can play with Tank Doodles by [Oleg Dolya](https://twitter.com/watawatabou/status/1158512105647202318) at [itch.io](https://watabou.itch.io/tank-doodles) and read more about it [on patreon](https://www.patreon.com/posts/28936612).

**Comment by Beeblerox** [comment]
- [ ] [Tamar Curry](https://twitter.com/tamarcurry/status/1157369507691675648) has opened [bug bounty](https://github.com/streiffus/OpenFLTextPerformance) for improving TextField performance in OpenFL. Here is also [related issue in OpenFL repo](https://github.com/openfl/openfl/issues/2229)

**Comment by Beeblerox** [comment]
- [ ] [Weekend side project](https://twitter.com/joshtynjala/status/1158076762170859521) by Josh Tynjala: karaoke MP3+G player in Haxe and OpenFL.

**Comment by Beeblerox** [comment]
- [ ] [Oneshot](https://cocosar07.itch.io/oneshot) is a game made with HaxeFlixel for the [GMTK Game Jam 2019](https://itch.io/jam/gmtk-2019) in 48 hours by [cocosar07](https://twitter.com/cocosar07)

**Comment by Beeblerox** [comment]
- [ ] New video by [Luke Selman](https://twitter.com/PMBusinessInt): [Build a Website from Scratch with Haxe Day #12 - Starting on Dynamic News Loading](https://www.youtube.com/watch?v=nBb4LuVAUwU)

**Comment by Beeblerox** [comment]
- [ ] Sister Abigail from Darksburg has [changed a lot during development](https://imgur.com/a/3cFwmHC)!

**Comment by Beeblerox** [comment]
- [ ] Total Party Kill by [Jussi Simpanen](https://twitter.com/AdventIslands/status/1158734094571909121) has been downloaded over half a million times with 417k downloads on iOS and 154k on Android. And it has been selected as [Indie Game of the Month on Google Play](https://play.google.com/store/apps/editorial_collection/promotion_topic_b000054_games_indie_corner_tp?hl=en_US)!

**Comment by Beeblerox** [comment]
- [ ] [Random world interactions](https://twitter.com/SUPERCuteAlien/status/1158826401748979713) in SUPER Cute Alien

**Comment by Beeblerox** [comment]
- [ ] [Multiple hitboxes in HaxeFlixel](https://twitter.com/hello_lightbulb/status/1159116791211266049) by Hello Lightbulb

**Comment by Beeblerox** [comment]
- [ ] [Black hole + flailing civilians = particle magic](https://twitter.com/alexvscoding/status/1159032574527889408) in BREAK N TAKE by Alex Johansson

**Comment by Beeblerox** [comment]
- [ ] New video by Lewis Lepton: [Shader tutorial series - Episode 033 - Noise image](https://www.youtube.com/watch?v=8GaZsg8vJUw)

**Comment by Beeblerox** [comment]
- [ ] [Hello! From: HaxePunk and me](https://dev.to/xanozoid/hello-from-haxepunk-and-me-4h9k) an article about future of HaxePunk

**Comment by Beeblerox** [comment]
- [ ] [HaxeShare](https://github.com/persevere-and-motivate/HaxeShare) is a Haxe web framework that provides page generation, routing, form building, and client and server code generation.

**Comment by skial** [comment]
- [ ] `ammer` announcement comment from [Lars Bounties](https://github.com/larsiusprime/larsBounties/issues/2#issuecomment-517962948).

**Comment by skial** [comment]
- [ ] core
  - Handle recursive abstracts on typing a forwarded field [merged](https://github.com/HaxeFoundation/haxe/pull/8609).

**Comment by skial** [comment]
- [ ] libs
  - [console.hx `0.2.5`](https://lib.haxe.org/p/Console.hx)
  - [hxWidgets `1.0.8`](https://lib.haxe.org/p/hxWidgets)
  - [electron `6.0.1`](https://lib.haxe.org/p/electron)
  - [mini-mighty-engine `1.4.0-alpha`](https://lib.haxe.org/p/mini-mighty-engine)
  - [mme-tools-library `1.2.1`](https://lib.haxe.org/p/mme-tools-library)
  - [air4haxe `1.0.0`](https://lib.haxe.org/p/air4haxe)
  - [nova `0.3.9`](https://lib.haxe.org/p/nova)
  - [mithril `2.0.0`](https://lib.haxe.org/p/mithril)
  - [extype `2.0.0-rc.4`](https://lib.haxe.org/p/extype)
  - [haxe-concurrent `2.1.3`](https://lib.haxe.org/p/haxe-concurrent)
  - [notifier `1.0.7`](https://lib.haxe.org/p/notifier)
  - [thenshim `0.1.0`](https://lib.haxe.org/p/thenshim)
  - [nosey `0.1.0`](https://lib.haxe.org/p/nosey)

**Comment by skial** [comment]
- [ ] Using Haxe for a parsing library in JavaScript, Typescript, C# and CPP - [reddit](https://www.reddit.com/r/haxe/comments/cmp2mj/using_haxe_for_parsing_library/).
