### ISSUE TITLE
Haxe Roundup 506

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#693]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by codingthat** [comment]
- [ ] A [Haxe review focusing on Haxe 4](https://www.toptal.com/haxe/haxe-review-haxe-4-strengths) on the [Toptal Engineering Blog](https://www.toptal.com/developers/blog)

**Comment by skial** [comment]
- [ ] REMOVE https://github.com/skial/haxe.io/issues/694 ⚠⚠⚠

**Comment by skial** [comment]
- [ ] libs
  - [webgl_fluid_simulation `1.0.1`](https://lib.haxe.org/p/webgl_fluid_simulation)
  - [notifier `1.1.9`](https://lib.haxe.org/p/notifier)
  - [p2p `0.1.24`](https://lib.haxe.org/p/p2p)
  - [signals `1.2.6`](https://lib.haxe.org/p/signals)
  - [haxeui-core `1.0.7`](https://lib.haxe.org/p/haxeui-core)
  - [Nice `3.3.1`](https://lib.haxe.org/p/Nice)
  - [hxnodejs-sqlite3 `0.1.1`](https://lib.haxe.org/p/hxnodejs-sqlite3)
  - [fuse `0.0.44`](https://lib.haxe.org/p/fuse)
  - [sbComponents `0.0.5`](https://lib.haxe.org/p/sbComponents)
  - [haxeui-kha `1.0.3`](https://lib.haxe.org/p/haxeui-kha)
  - [hxWidgets `1.3.0`](https://lib.haxe.org/p/hxWidgets)
  - [DomWires `1.0.0-alpha.6`](https://lib.haxe.org/p/DomWires)
  - [transition `1.0.6`](https://lib.haxe.org/p/transition)
  - [utils `1.0.7`](https://lib.haxe.org/p/utils)
  - [hxPhidgetRfid `0.3.0`](https://lib.haxe.org/p/hxPhidgetRfid)
  - [Rice2D `2019.11.17`](https://lib.haxe.org/p/Rice2D)
  - [bindx2 `2.7.0`](https://lib.haxe.org/p/bindx2)

**Comment by skial** [comment]
- [ ] Pattern `[WIP]` [creative code](https://twitter.com/MatthijsKamstra/status/1196898773575835650) by [Matthijs Kamstra](https://twitter.com/MatthijsKamstra)

**Comment by skial** [comment]
- [ ] Richard Oliver Bray has [written](https://twitter.com/Ceiga/status/1196727027447017472) about building a native windows project in HaxeFlixel/OpenFL

**Comment by skial** [comment]
- [ ] A little update and polish on the Sonar Smash [title screen](https://twitter.com/fedellen/status/1196562072789831680) by fedellen.

**Comment by skial** [comment]
- [ ] Tick, tick, boooom! Ben Simms latest game preview going down the [fireworks & space](https://twitter.com/zerosimms/status/1196518824838860801) theme.

**Comment by skial** [comment]
- [ ] The open source Haxe powered OGMO 2D level editor has just been released `v3.1`. Check out the GameFromStratch [article](https://twitter.com/gamefromscratch/status/1196480955772493825).

**Comment by skial** [comment]
- [ ] More [drone swarm experiments](https://twitter.com/dazKind/status/1196382860015546368), this time its dynamic formation with built-in collision avoidance using Haxe by Michael Bickel.

**Comment by skial** [comment]
- [ ] Francois Barbut has released his Haxe and Php "Haxe 4, le Typescript de PHP ?" [slides](https://twitter.com/bablukid/status/1196364259510407168).

**Comment by skial** [comment]
- [ ] Will Blanton has [released](https://twitter.com/x01010111/status/1195459826635169795) the third version of the OGMO Editor made with Haxe and available from itch.io.

**Comment by skial** [comment]
- [ ] Alex Johansson has released some [preview footage](https://twitter.com/alexvscoding/status/1195804157317435392) of the bishop in action in his latest game being made with Stencyl.

**Comment by skial** [comment]
- [ ] Can you make a jump and run in one hour? Yes you can! Check out [Element Hunter](https://twitter.com/Laguna_999/status/1195692269627723776), a `#1hgj` indie game by Dr. Laguna.

**Comment by skial** [comment]
- [ ] [Wave system](https://twitter.com/caribouloche/status/1195663802286706688) added to Caribou's game being made in Heaps.

**Comment by skial** [comment]
- [ ] [Haxe used](https://twitter.com/ncannasse/status/1195423811354726401) in the [latest](https://twitter.com/Fiene_P/status/1195396913660608512) Pokemon Sword and Shield games.

**Comment by Beeblerox** [comment]
- [ ] Renegade Racing by [Paul Gene Thompson](https://twitter.com/paulgene) is now live on the [App Store](https://apps.apple.com/app/apple-store/id1355912318) and [Google Play](https://play.google.com/store/apps/details?id=com.notdoppler.renegaderacing). via [Not Doppler](https://twitter.com/notdoppler/status/1194900832925282305)

**Comment by Beeblerox** [comment]
- [ ] [The first devlog of Antlers](https://caribouloche.itch.io/antlers/devlog/109469/healers-heal-devlog-1), the multiplayer online ARPG by [Caribou](https://twitter.com/caribouloche/status/1194949819820904450)

**Comment by Beeblerox** [comment]
> 
> 
>     * [ ]  [Haxe used](https://twitter.com/ncannasse/status/1195423811354726401) in the [latest](https://twitter.com/Fiene_P/status/1195396913660608512) Pokemon Sword and Shield games.

- [ ] [Some more details](http://terurou.hateblo.jp/entry/2019/11/16/220840) about it in Japanese

**Comment by Beeblerox** [comment]
- [ ] [Collecting Power](https://www.fortressofdoors.com/defenders-quest-2-progress-november-2019/) - Defender's Quest 2 Progress: November 2019 by [Lars Doucet](https://twitter.com/larsiusprime/status/1197192666431266816)

**Comment by Beeblerox** [comment]
- [ ] An update to the Haxe Linux packages: most distributions got 4.0.2 now. ppa:haxe/releases was updated. There is still ppa:haxe/haxe3.4 if you don't wanna upgrade yet. Thank to [Andy Li](https://twitter.com/andy_li/status/1195348166385831936)!

**Comment by Beeblerox** [comment]
- [ ] [1: Launch Day?](http://distractionware.com/blog/2019/11/1-launch-day/) - a blog post by [Terry Cavanagh](https://twitter.com/terrycavanagh/status/1195428904229572608) from which you will know about Dicey Dungeon's launch, future plans, and the planned Switch and Mobile ports!

**Comment by Beeblerox** [comment]
- [ ] A few GIFs from "Scales: A Pangolin Story" by Hello LightBulb:
* [New pangolin animation](https://twitter.com/hello_lightbulb/status/1195432963091128324)
* [Hand crafted animation for our mother pangolin](https://twitter.com/hello_lightbulb/status/1196792942511448064)
* [A basic level selection screen](https://twitter.com/hello_lightbulb/status/1197187901085429761)

**Comment by Beeblerox** [comment]
- [ ] [Double Kick Heroes coming to Xbox Games Pass](https://invisioncommunity.co.uk/double-kick-heroes-coming-to-xbox-games-pass/)

**Comment by Beeblerox** [comment]
> 
> 
>     * [ ]  Tick, tick, boooom! Ben Simms latest game preview going down the [fireworks & space](https://twitter.com/zerosimms/status/1196518824838860801) theme.

And some more quick videos from this WIP game:
* [a new 'puzzle' mode](https://twitter.com/zerosimms/status/1195079445230628874)
* [journey, unlock and rating system](https://twitter.com/zerosimms/status/1195804023263318017)
* [Bowie just loves to eat the stars!](https://twitter.com/zerosimms/status/1197214598568521728)

**Comment by Beeblerox** [comment]
- [ ] [exploring a 'cabinet of curiosities'](https://twitter.com/e1sif/status/1195862038343540737) in [ArachnoPunk](https://e1sif.itch.io/arachnopunk) by Benny Heller

**Comment by Beeblerox** [comment]
- [ ] Couple of new GIFs from Croaking Hill by 1Speed studio:
* [playing around with particles](https://twitter.com/1speed2gamedev/status/1196095489323798528)
* [moar particles](https://twitter.com/1speed2gamedev/status/1196095817788067840)

**Comment by Beeblerox** [comment]
- [ ] [Devlog #3: Marketing Victories](https://www.pixelpajamastudios.com/blog/devlog-3-marketing-victories) by [fedellen](https://twitter.com/fedellen/status/1196496442296295425)

**Comment by Beeblerox** [comment]
- [ ] [heaps-ios](https://github.com/thejustinwalsh/heaps-ios/issues/2) is looking for maintainer

**Comment by Beeblerox** [comment]
- [ ] [Gifted class teaching their teacher](https://twitter.com/eileen_jenkin/status/1195502674051059712) how to play the video games they created with Stencyl

**Comment by Beeblerox** [comment]
- [ ] [Feathers UI Devlog](https://www.kickstarter.com/projects/feathersui/feathers-ui-cross-platform-components-for-haxe-and-openfl/posts/2683719): Collection filtering/sorting, TabBar, Callout, ComboBox, and layouts with percent sizing

**Comment by Beeblerox** [comment]
- [ ] A little improvement on the ["Level Select" menu](https://twitter.com/7thVariety/status/1197175093690032129) of "Treasure Measure"

**Comment by Beeblerox** [comment]
- [ ] [Hatching in 1PDG](https://www.patreon.com/posts/hatching-in-1pdg-31716880) by [Oleg Dolya](https://twitter.com/watawatabou/status/1197194111171940352)

**Comment by Beeblerox** [comment]
- [ ] And OgmoEditor needs your help:
* [Add .ogmo File Association](https://github.com/Ogmo-Editor-3/OgmoEditor3-CE/issues/44)
* [Setup Native Application Menu](https://github.com/Ogmo-Editor-3/OgmoEditor3-CE/issues/17)
* [Add in auto updating builds](https://github.com/Ogmo-Editor-3/OgmoEditor3-CE/issues/4)

**Comment by Beeblerox** [comment]
- [ ] New repo by David Klein - [kha-coconut.ui-template](https://github.com/sh-dave/kha-coconut.ui-template) (kha + haxeui + coconut.ui)

**Comment by Beeblerox** [comment]
- [ ] [Floyds Puzzle](https://github.com/mio-edition/floyds-puzzle) is a shape match puzzle game for kids available [at Google Play](https://play.google.com/store/apps/details?id=de.mioedition.floydspuzzle&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1)

**Comment by Beeblerox** [comment]
- [ ] From Haxe Discord: [thanks, haxeflixel particles](https://media.discordapp.net/attachments/162664383082790912/646024797733781504/sk-0.gif) by arnulfo

**Comment by Beeblerox** [comment]
- [ ] [OGMO Editor 3 Flixel integration using zerolib-flixel](https://gist.github.com/01010111/ad017dbdd453e8f2d85b273b59ca861e) by Will Blanton

**Comment by Beeblerox** [comment]
> 
> 
>     * [ ]  A little update and polish on the Sonar Smash [title screen](https://twitter.com/fedellen/status/1196562072789831680) by fedellen.

and [toying around with ideas for tutorial](https://twitter.com/fedellen/status/1197229038143778818)

**Comment by Beeblerox** [comment]
- [ ] [A lot of crabs](https://twitter.com/CoryAlexMartin/status/1197251709694808065) in Leapin Lads by Cory Martin

**Comment by skial** [comment]
- [ ] core
  - `StringTools.endsWith` unicode issue on Haxe 4 CPP target [issue](https://github.com/HaxeFoundation/haxe/issues/8980)
