### ISSUE TITLE
Haxe Roundup 519

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#723]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] Refactor `TyperDotPath` [merged](https://github.com/HaxeFoundation/haxe/pull/9191).

**Comment by skial** [comment]
- [ ] Fix error position for duplicate type declarations [merged](https://github.com/HaxeFoundation/haxe/pull/9188).

**Comment by skial** [comment]
- [ ] `[dce]` Abstract `to AnonStruct` makes underlying type keep unused fields [issue](https://github.com/HaxeFoundation/haxe/issues/9185)

**Comment by skial** [comment]
- [ ] `[hxcpp]` Replace usage of `gettimeofday` in HXCPP standard library [issue](https://github.com/HaxeFoundation/hxcpp/issues/887).

**Comment by skial** [comment]
- [ ] `[events]` EU Haxe Summit 2020 - Website now live! [thread](https://community.haxe.org/t/eu-haxe-summit-2020-website-live-tickets-available/2289/1).

**Comment by skial** [comment]
- [ ] [Aidan Lee](https://twitter.com/aidanleegames/status/1234600909356834817) has finished rewriting their IMGUI bindings for Haxe, now generated from cimgui definitions.

**Comment by skial** [comment]
- [ ] `[jvm]` Generate `interface-per-typedef`, bringing `class-to-anon` benchmark from `5M` to `120M` samples, [merged](https://github.com/HaxeFoundation/haxe/pull/9195).

**Comment by skial** [comment]
- [ ] libs
  - [HxDoom `0.0.3-alpha`](https://lib.haxe.org/p/HxDoom/)
  - [genes `0.1.0`](https://lib.haxe.org/p/genes/)
  - [datetime `3.1.2`](https://lib.haxe.org/p/datetime/)
  - [mithril `2.2.0`](https://lib.haxe.org/p/mithril/)
  - [animate-cc-openfl `0.0.1`](https://lib.haxe.org/p/animate-cc-openfl/)
  - [haxeui-core `1.0.25`](https://lib.haxe.org/p/haxeui-core/)
  - [haxeui-openfl `1.0.7`](https://lib.haxe.org/p/haxeui-openfl/)
  - [haxeui-kha `1.0.5`](https://lib.haxe.org/p/haxeui-kha/)
  - [haxeui-hxwidgets `1.0.8`](https://lib.haxe.org/p/haxeui-hxwidgets/)
  - [haxeui-html5 `1.0.6`](https://lib.haxe.org/p/haxeui-html5/)
  - [colyseus `0.12.5`](https://lib.haxe.org/p/colyseus/)
  - [pony `1.1.3`](https://lib.haxe.org/p/pony/)
  - [tracker `0.1.1`](https://lib.haxe.org/p/tracker/)
  - [notifier `1.1.18`](https://lib.haxe.org/p/notifier/)
  - [p2p `0.1.30`](https://lib.haxe.org/p/p2p/)
  - [dataclass `2.0.1`](https://lib.haxe.org/p/dataclass/)
  - [sneaker `0.1.2`](https://lib.haxe.org/p/sneaker/)
  - [OpenFL-Animate-Atlas-Player `1.9.1`](https://lib.haxe.org/p/OpenFl-Animate-Atlas-Player/)
  - [react-swipeable `1.0.0`](https://lib.haxe.org/p/react-swipeable/)
  - [escript `0.4.0`](https://lib.haxe.org/p/escript/)
  - [astar `0.2.3`](https://lib.haxe.org/p/astar/)

**Comment by skial** [comment]
- [ ] OpenFL 9 [Development Update](https://community.openfl.org/t/development-update-openfl-9/12347)

**Comment by skial** [comment]
- [ ] [Ian Harrigan](https://twitter.com/IanHarrigan1982/status/1234595858433347584)'s HaxeUI component explorer has been update with alot of new examples!

**Comment by skial** [comment]
- [ ] [Syo](https://twitter.com/SyoPic/status/1234198136815587328) Heaps powered game jittersandbox shows off MMCS - Mouse Movement Control System, the future of space mechanics.

**Comment by skial** [comment]
- [ ] [Robert Alvarez](https://twitter.com/Rob1221dev/status/1234180034052722689) has released HP Atk Def, his newest puzzle game now available from itch.io, made with Stencyl.

**Comment by Beeblerox** [comment]
- [ ] [Bouncing ⚽ Ball](https://www.kongregate.com/games/AdityaChaudhary/bouncing-ball) by [Aditya Chaudhary](https://twitter.com/AdityaGameDev/status/1232996241635569668) is out on 
Kongregate

**Comment by Beeblerox** [comment]
- [ ] New GIFs and screenshots from his WIP Stencyl game called [StarBurst](https://starburstgame.netlify.com/):

    - [new tutorial](https://twitter.com/zerosimms/status/1233016522097823744) to explain the rules
    - One of my worst fears! [floating out in space!](https://twitter.com/zerosimms/status/1233811142587318273)
    - Couldn't resist! [The Tesla car](https://twitter.com/zerosimms/status/1233818046881574912) , doing its thing

**Comment by Beeblerox** [comment]
- [ ] [Alex Johansson](https://twitter.com/alexvscoding/status/1233050105558818817) is working on PARcentage. A game about putting with percentages

**Comment by Beeblerox** [comment]
> * [ ]  `[events]` EU Haxe Summit 2020 - Website now live! [thread](https://community.haxe.org/t/eu-haxe-summit-2020-website-live-tickets-available/2289/1).

- [ ] And don't forget about ["EU Haxe Summit 2020 Announcement"](https://haxe.org/blog/eu-haxe-summit-2020/) blog post! (i know that there is link in the forum thread, but in my opinion it is better to add it in the roundup itself)

**Comment by Beeblerox** [comment]
- [ ] [Shout 10.000 times 7*7](https://www.instagram.com/p/B9HXSwDHe6q/?igshid=2dg0p8lieirb) by [Matthijs Kamstra](https://twitter.com/MatthijsKamstra)

**Comment by Beeblerox** [comment]
- [ ] Robert Alvarez is already [prototyping his next game](https://twitter.com/Rob1221dev/status/1233767979457896448) which will be a sliding puzzle game with sticky blocks

**Comment by Beeblerox** [comment]
- [ ] Here are a few photos from PAX East 2020, where Octosoft team showed Renaine:
    - [Renaine](https://twitter.com/thirdrateminion/status/1233439731607855105) is here once more, and a lil chompy is there, too!
    - [Praise Chompy](https://twitter.com/WyldfireNYC/status/1233846083090092034)
    - Thank you so much to Indie MEGABOOTH and Intel for the incredibly massive screen they loaned us! [Made our booth look INCREDIBLE this year!](https://twitter.com/OctosoftUS/status/1234582069914763273)
    - There are many other photos from the expo at the [Octosoft twitter account]((https://twitter.com/OctosoftUS))

**Comment by Beeblerox** [comment]
- [ ] A couple of screenshots from WIP turn based puzzle game by mauve:
    - [Freshening up the menus](https://twitter.com/mauvecow/status/1233987611951157248). A little bit of flair adds a lot.
    - [I feel like I've been wandering for hours](https://twitter.com/mauvecow/status/1234340032506236928)

**Comment by Beeblerox** [comment]
- [ ] [Armor Paint - Working with Materials | Beginner #3](https://youtu.be/-23fvmQ76yM) by [ArmoryBlender](https://twitter.com/ArmoryBlender/status/1234182540644278274)

**Comment by Beeblerox** [comment]
- [ ] Kaelan Evans has split his Haxe Doom port into two projects: [HxDoom](https://lib.haxe.org/p/HxDoom/) is now a haxelib (adaption of id Tech 1 which does not come with rendering or IO) and [Citrus Doom](https://github.com/kevansevans/CitrusDoom) is a Doom port built on Haxe, using Lime and HxDoom

**Comment by Beeblerox** [comment]
- [ ] [Laser Lightning Bugs in the Spotlight](https://www.fortressofdoors.com/laser-lightning-bugs-in-the-spotlight-defenders-quest-2-progress-for-february-2020/): Defender's Quest 2 Progress for February 2020 by [Lars Doucet](https://twitter.com/larsiusprime/status/1235261512593428482)

**Comment by Beeblerox** [comment]
- [ ] [Haxe + numba sample](https://gist.github.com/profelis/1a152882cb888b5e581f98a747105455) by Dima Granetchi

**Comment by Beeblerox** [comment]
- [ ] [happy wednesday](https://twitter.com/fedellen/status/1235290990946250762) quick video by fedellen
