### ISSUE TITLE
Haxe Roundup 520

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#725]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by BlackGoku36** [comment]
There is now roundups from Armory3D community: [Armory Digest - March 2020](https://forums.armory3d.org/t/armory-digest-march-2020/3943)

**Comment by skial** [comment]
- [ ] `[jvm]` Implement typed functions [merged](https://github.com/HaxeFoundation/haxe/pull/9208) with before & after [bench](https://github.com/HaxeFoundation/haxe/pull/9208#issuecomment-595862831).

**Comment by skial** [comment]
- [ ] `[macro/extern]` `macro` functions in `extern`'s default to `private` [issue](https://github.com/HaxeFoundation/haxe/issues/9209).

**Comment by skial** [comment]
- [ ] `[showcase]` Ammer and Anvil: Haxe Native Extension Toolkit - [community thread](https://community.haxe.org/t/ammer-and-anvil-haxe-native-extension-toolkit/2298/1).

**Comment by skial** [comment]
- [ ] Immediately bound constructor closures create redundant functions [issue](https://github.com/HaxeFoundation/haxe/issues/9227).

**Comment by skial** [comment]
- [ ] libs
  - [OpenFL-Animate-Atlas-Player `1.9.2`](https://lib.haxe.org/p/OpenFl-Animate-Atlas-Player/)
  - [tink_hxx `0.23.0`](https://lib.haxe.org/p/tink_hxx/)
  - [tink_anon `0.5.0`](https://lib.haxe.org/p/tink_anon/)
  - [tink_domspec `0.2.0`](https://lib.haxe.org/p/tink_domspec/)
  - [coconut.data `0.10.0`](https://lib.haxe.org/p/coconut.data/)
  - [tink_macro `0.19.0`](https://lib.haxe.org/p/tink_macro/)
  - [datetime `3.1.3`](https://lib.haxe.org/p/datetime/)
  - [p2p `0.1.39`](https://lib.haxe.org/p/p2p/)
  - [vscode-debugadapter `1.39.0`](https://lib.haxe.org/p/vscode-debugadapter/)
  - [ripper `0.1.0`](https://lib.haxe.org/p/ripper/)
  - [sneaker `0.3.0`](https://lib.haxe.org/p/sneaker/)
  - [hxid3 `1.0.0`](https://lib.haxe.org/p/hxid3/)
  - [fuzzaldrin `0.1.1`](https://lib.haxe.org/p/fuzzaldrin/)
  - [vscode `1.43.0`](https://lib.haxe.org/p/vscode/)
  - [deepnightLibs `0.0.34`](https://lib.haxe.org/p/deepnightLibs/)
  - [no-vdom `0.5.0`](https://lib.haxe.org/p/no-vdom/)
  - [csss `0.6.0`](https://lib.haxe.org/p/csss/)
  - [reaxe `1.0.4`](https://lib.haxe.org/p/reaxe/)
  - [pony `1.2.2`](https://lib.haxe.org/p/pony/)
  - [electron `8.1.0`](https://lib.haxe.org/p/electron/)

**Comment by skial** [comment]
- [ ] Sébastien Bénard has [written](https://twitter.com/deepnightfr/status/1237490730937057282) a complete guide to getting started making games using Haxe and the Heaps engine, the same tech used for DeadCells.

**Comment by skial** [comment]
- [ ] [Hello Lightbulb](https://twitter.com/hello_lightbulb/status/1237299534155395072) have been busy making a game for `#AustisticaPlayJam` which is now live on [itchio](https://hellolightbulb.itch.io/maisy-and-kevin)!

**Comment by skial** [comment]
- [ ] A quick video playthrough of [Ben Simms](https://twitter.com/zerosimms/status/1236759762957668354) game Star Burst, featuring all the latest changes! Made with Stencyl.

**Comment by skial** [comment]
- [ ] [Footage](https://twitter.com/PixelPajamas/status/1236365765336580097) from the Sonar Smash android beta using Explosive Shot to its finest! Coming April 8th on iOS, Android, PC and Mac!

**Comment by skial** [comment]
- [ ] [Oleg Dolya](https://twitter.com/watawatabou/status/1236267554332696576) has submitted Book Hunter in the last minutes of `#7DRL` made with Haxe and OpenFL, available on itchio.

**Comment by skial** [comment]
- [ ] _"Just flip it, easily, quick and stupid simple"_ [Matthijs Kamstra](https://twitter.com/MatthijsKamstra/status/1236218089261486080) using mirrored animation for a quick good looking animation.

**Comment by skial** [comment]
- [ ] [Alex Johansson](https://twitter.com/alexvscoding/status/1236093954208251904) showcases his snazzy pickup with a sonar pulse animation, which shoots out a ring of bullets when collected. Made with Stencyl.

**Comment by Beeblerox** [comment]
> * [ ]  [Alex Johansson](https://twitter.com/alexvscoding/status/1236093954208251904) showcases his snazzy pickup with a sonar pulse animation, which shoots out a ring of bullets when collected. Made with Stencyl.

I believe it will be called [The Belt](https://twitter.com/alexvscoding/status/1235592645512052736)

**Comment by Beeblerox** [comment]
- [ ] And Alex Johanson has made [his own spin on 2048](https://twitter.com/alexvscoding/status/1237666975842799616) where you’re cleaning files up on an old computer’s desktop

**Comment by Beeblerox** [comment]
- [ ] [ArmorPaint launches on Android](https://twitter.com/luboslenco/status/1235623146163748864) - development builds are up, with support for pen pressure, touch, keyboard, mouse and mirroring to big screen. iPadOS will follow!

**Comment by Beeblerox** [comment]
- [ ] Couple of GIFs / videos from WIP Stencyl game by Robert Alvarez:
    - [Made some test levels](https://twitter.com/Rob1221dev/status/1235663937514786816) and improved the background
    - [Some blocks don't combine](https://twitter.com/Rob1221dev/status/1236689972129927168) with others and just get in the way.

**Comment by Beeblerox** [comment]
- [ ] Couple of new GIFs from Heck Deck by torcado:
    - [a progress shot of the next boss](https://twitter.com/torcado/status/1235808924529377280)
    - [it's got turrets too.....](https://twitter.com/torcado/status/1236522141861859338)

**Comment by Beeblerox** [comment]
> * [ ]  _"Just flip it, easily, quick and stupid simple"_ [Matthijs Kamstra](https://twitter.com/MatthijsKamstra/status/1236218089261486080) using mirrored animation for a quick good looking animation.

- [ ] And [another animation](https://www.instagram.com/p/B9d_KB5nEXm/?igshid=17821unk75y63) “just mirrored” combined with character animation!

**Comment by Beeblerox** [comment]
- [ ] [Moving along the path](https://twitter.com/SyoPic/status/1236342527252463616) in JitterSandbox by Syo

**Comment by Beeblerox** [comment]
- [ ] Guys from Stencyl are [planning to do a Stencyl Jam](https://twitter.com/Stencyl/status/1236335803577573378) in a couple of weeks from now

**Comment by Beeblerox** [comment]
- [ ] WIP pstage select screen](https://twitter.com/mauvecow/status/1237264925598208000) from turn based puzzle game by mauve

**Comment by Beeblerox** [comment]
- [ ] [U-Ge! by Funplox](https://twitter.com/funplox/status/1236592252744388608) is now being submitted to AppStore and GooglePlay

**Comment by Beeblerox** [comment]
- [ ] [Gregory Seed](https://twitter.com/gregorysreed/status/1236826766242701320) is actively working on a DLC for his puzzle free game [Little Square Things](https://store.steampowered.com/app/945490/Little_Square_Things/)

**Comment by Beeblerox** [comment]
- [ ] [Rogue Mage by Ben Simms](https://twitter.com/zerosimms/status/1236968247183978498) has gone live on KaiOS app store! The game is made with Stencyl

**Comment by Beeblerox** [comment]
- [ ] Devlog #18 by [fedellen](https://twitter.com/fedellen/status/1237221568700391425): [Holographic dolphins](https://www.pixelpajamastudios.com/blog/devlog-18-holographic-dolphins)

**Comment by Beeblerox** [comment]
- [ ] Dead Cells [won the first Pegase](https://twitter.com/Playdigious/status/1237105900646785024) of the ceremony which is the reward for the Best Mobile Game!

**Comment by Beeblerox** [comment]
- [ ] [Introducing the Darksburg Leaderboard](https://twitter.com/Darksburg/status/1237392773994516483)

**Comment by Beeblerox** [comment]
- [ ] [Luyren Stencyl Tutorial Series #2: RPG Elements](https://www.youtube.com/watch?v=O-fmaYXjOBY&feature=youtu.be) by [Vítor Eduardo](https://twitter.com/LuyrenStencyl/status/1237822759465598977)

**Comment by Beeblerox** [comment]
- [ ] [SyncTube](https://github.com/RblSb/SyncTube) is a synchronized video viewing with chat and other features

**Comment by Beeblerox** [comment]
- [ ] [nme-enhance](https://github.com/haxenme/nme-enhance) - Interface to the enhance.co mobile extensions by Hugh Sanderson

**Comment by Beeblerox** [comment]
- [ ] Haxe Open Database Connectivity Native Extension: [HxDBC](https://github.com/piboistudios/hxdbc) is a native-extension library for the ammer FFI/stub code generator.

**Comment by Beeblerox** [comment]
- [ ] Gioele Bencivenga is making [his first ever game](https://github.com/Gioele-Bencivenga/FlixelGame) (with HaxeFlixel) for a school project

**Comment by Beeblerox** [comment]
- [ ] danausApollo from Haxe discord has released [Chat Cafe](https://www.newgrounds.com/portal/view/749814) game made with HaxeFlixel

**Comment by skial** [comment]
- [ ] `[cs/java/jvm]` Clean up `-main` handling [merged](https://github.com/HaxeFoundation/haxe/pull/9230).
