### ISSUE TITLE
Haxe Roundup 521

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#727]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] Min/Max number limits [pull request](https://github.com/HaxeFoundation/haxe/pull/9240).

**Comment by skial** [comment]
- [ ] Boolean binop reconstruction vs `return` [issue](https://github.com/HaxeFoundation/haxe/issues/9249).

**Comment by skial** [comment]
- [ ] Add `haxe.Constraints.NotVoid` [merged](https://github.com/HaxeFoundation/haxe/pull/8357).

**Comment by skial** [comment]
- [ ] Do not generate redundant final return for `return voidExpr` [closed](https://github.com/HaxeFoundation/haxe/issues/6420).

**Comment by skial** [comment]
- [ ] Cross-target exception handling [merged](https://github.com/HaxeFoundation/haxe/pull/9124)! :star2:

**Comment by skial** [comment]
- [ ] Remove redundant `continue` [closed](https://github.com/HaxeFoundation/haxe/issues/8952).

**Comment by skial** [comment]
- [ ] libs
  - [pony `1.2.5`](https://lib.haxe.org/p/pony/)
  - [mtasa-types `0.0.2`](https://lib.haxe.org/p/mtasa-types/)
  - [DomWires `1.0.0-alpha.11`](https://lib.haxe.org/p/DomWires/)
  - [extype `2.1.0`](https://lib.haxe.org/p/extype/)
  - [AnonStruct `0.2.0`](https://lib.haxe.org/p/AnonStruct/)
  - [banker `0.1.1`](https://lib.haxe.org/p/banker/)
  - [ripper `0.2.1`](https://lib.haxe.org/p/ripper/)
  - [sneaker `0.6.0`](https://lib.haxe.org/p/sneaker/)
  - [bind `0.4.5`](https://lib.haxe.org/p/bind/)

**Comment by skial** [comment]
- [ ] Alex Johnansson has been working on PARcentage, made with Stencyl:
   + added a fast [forward button](https://twitter.com/alexvscoding/status/1240051720752857088).
   + added a staggered [spawn animation](https://twitter.com/alexvscoding/status/1240083668640595970).

**Comment by skial** [comment]
- [ ] [Josh's](https://twitter.com/J0SHArt/status/1240035090257907713) game, Scrapworks, made with HaxeFlixel, now has menus which are now full functional.

**Comment by skial** [comment]
- [ ] [Alex Johansson](https://twitter.com/alexvscoding/status/1239974814460153863) has written a big write-up for Morse on tigsource, a strategy morse code game, made with Stencyl.

**Comment by skial** [comment]
- [ ] [PixelPajamaStudios](https://twitter.com/PixelPajamas/status/1239958954530295809) has additional footage of Sonar Smash Beta featuring great usage of the Bubble Shield and more!

**Comment by skial** [comment]
- [ ] [Shellrider](https://twitter.com/shellrider_game/status/1239635919721955328) has released A lot of Apples, a game made with HaxeFlixel, for the `quarantine` jam.

**Comment by skial** [comment]
- [ ] [Nanjizal](https://twitter.com/Nanjizal_net/status/1239362475130322946) has created a Covid19 cases map for the UK.

**Comment by skial** [comment]
- [ ] [Tong](https://twitter.com/disktree/status/1239205001009995776) has released [hlserialport `git`](https://github.com/tong/hlserialport)

**Comment by skial** [comment]
- [ ] [Michael Bickel](https://twitter.com/dazKind/status/1239161849846861824) presents his new startup: An autonomous toilet paper delivery service called `FlyWipe`. 🛸🧻

**Comment by skial** [comment]
- [ ] [Nick Grebenshikov](https://twitter.com/grebenshikov_n/status/1239017326655287296) has released Domino Solitaire, a little game created with OpenFL and JiveUI for iOS and Android.

**Comment by skial** [comment]
- [ ] [Osaka Red LLC](https://twitter.com/osakared/status/1238153091461132288) are cancelling this years HaxeUp due to Covid-19.

**Comment by Beeblerox** [comment]
- [ ] [this isn't goodbye. but I will see you around](https://www.youtube.com/watch?v=zsDp016VHMI&feature=emb_logo) by Lewis Lepton. Let's wish him luck with his future projects

**Comment by Beeblerox** [comment]
- [ ] Couple posts by [Oleg Dolya](https://twitter.com/watawatabou):
    - [Book Hunter and plans for the rest of March](https://www.patreon.com/posts/34822131)
    - [Towers in Procgen Mansion](https://www.patreon.com/posts/35009607)

**Comment by Beeblerox** [comment]
- [ ] The idea from a couple of weeks back [is taking shape](https://twitter.com/LuyrenStencyl/status/1239331601135423488). By Luyren

**Comment by Beeblerox** [comment]
- [ ] [These doors open](https://twitter.com/Rob1221dev/status/1238500314937950208) only when a certain number of blocks are connected. From WIP Stencyl game by Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] You can [pre-register](https://play.google.com/store/apps/details?id=com.greed.lst) for Little Square Things by [Gregory Sreed](https://twitter.com/gregorysreed/status/1238670422499045376) on the Google Play store

**Comment by Beeblerox** [comment]
- [ ] This week Ben Simms wanted to [make everything thing a bit more lively](https://twitter.com/zerosimms/status/1238859971019902978) in Star Burst

**Comment by Beeblerox** [comment]
- [ ] [Playing around](https://twitter.com/torcado/status/1238889179825618944) with a mechanic in Heck Deck that automatically slows time when you get close to a lethal card

**Comment by Beeblerox** [comment]
- [ ] [Andrej](https://twitter.com/ohsat_games/status/1239182588566294529) is [Making a Pogo Platformer](https://www.ohsat.com/post/pogo-platformer/)

**Comment by Beeblerox** [comment]
- [ ] Vulkan has ray tracing acceleration API now. And [Lubos Lenco](https://twitter.com/luboslenco/status/1239957279698493441) might throw some related pull-requests for Kha. Plus soon there will be accelerated ray-tracing in ArmorPaint

**Comment by Beeblerox** [comment]
- [ ] Renegade Racing by [Paul Gene Thompson](https://twitter.com/PaulGene/status/1240076778217013249) was "Game Of The Day" in 133 countries on iOS.  And it reached number 1 sports game in 31 countries on iPhone and 44 countries on iPad!

**Comment by Beeblerox** [comment]
- [ ]  Dicey Dungeons is [coming to Nintendo Switch](https://twitter.com/terrycavanagh/status/1240237782494142465). Thanks to [Ruari O'Sullivan](https://twitter.com/randomnine), who joined Dicey Dungeons' team and helped to port the game! Here is game's [Nintendo store page](https://www.nintendo.com/games/detail/dicey-dungeons-switch/)

**Comment by Beeblerox** [comment]
- [ ] Otherones from Haxe Discord serves has made a HaxeFlixel game called [Sheep Savior](https://www.kongregate.com/games/axp4/sheep-savior) for their course on game design

**Comment by Beeblerox** [comment]
- [ ] [Super MineSweeper II TURBO](https://ottob.it/super-minesweeper-2-turbo/) is made with love and HaxeFlixel as a test from zero to market by filipp8 from Haxe Discord server

**Comment by Beeblerox** [comment]
- [ ] What if tetris pieces had souls? [Havana24](https://twitter.com/hav24/status/1240347908072972289) is working on something new...

**Comment by Beeblerox** [comment]
> * [ ]  Alex Johansson has been working on PARcentage, made with Stencyl:
>   
>   * added a fast [forward button](https://twitter.com/alexvscoding/status/1240051720752857088).
>   * added a staggered [spawn animation](https://twitter.com/alexvscoding/status/1240083668640595970).

- [ ] [And a bunch of progress](https://twitter.com/alexvscoding/status/1240358833320583170)

**Comment by Beeblerox** [comment]
- [ ] [Stencyl Jam #19](https://twitter.com/Stencyl/status/1240400427524534277)! March 27th - April 6th. You can [sign up](https://itch.io/jam/stencyl-jam-19) at Stencyl website

**Comment by Beeblerox** [comment]
- [ ] [wBrain](https://tools.wbrain.me/) - Tools for Teams - Experimental tools for agile and remote teams. Made with Haxe and NodeJS. via [Felipe Peternella](https://twitter.com/felipevex/status/1240358238660497408)
