### ISSUE TITLE
Haxe Roundup 523

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#732]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] HashLink `1.1` has been [released](https://twitter.com/ncannasse/status/1244605603894394880)! Includes native CPU profiler and much more!

**Comment by skial** [comment]
- [ ] `[Draft]` Implements Rest arguments as an abstract over target natives [pull request](https://github.com/HaxeFoundation/haxe/pull/9274).

**Comment by skial** [comment]
- [ ] `[tink_http]` Rework AWS Lambda container [merged](https://github.com/haxetink/tink_http/pull/114).

**Comment by skial** [comment]
- [ ] `[js]` Local `var` renaming regression [issue](https://github.com/HaxeFoundation/haxe/issues/9281).

**Comment by skial** [comment]
- [ ] `[js]` Use `let` for ES6 mode [pull request](https://github.com/HaxeFoundation/haxe/pull/9280).

**Comment by skial** [comment]
- [ ] libs
  - [hxfsm `2.0.1`](https://lib.haxe.org/p/hxfsm/)
  - [callfunc `1.0.1`](https://lib.haxe.org/p/callfunc/)
  - [llama `1.0.0`](https://lib.haxe.org/p/llama/)
  - [vscode-json-rpc `1.0.0`](https://lib.haxe.org/p/vscode-json-rpc/)
  - [hxcpp-debug-server `1.2.4`](https://lib.haxe.org/p/hxcpp-debug-server/)
  - [banker `0.3.0`](https://lib.haxe.org/p/banker/)
  - [ripper `0.2.3`](https://lib.haxe.org/p/ripper/)
  - [sneaker `0.8.0`](https://lib.haxe.org/p/sneaker/)
  - [sbComponents `0.0.8`](https://lib.haxe.org/p/sbComponents/)
  - [flixel-templates `2.6.4`](https://lib.haxe.org/p/flixel-templates/)
  - [flixel-demos `2.7.2`](https://lib.haxe.org/p/flixel-demos/)
  - [glory `2.0.4`](https://lib.haxe.org/p/glory/)
  - [dox `1.4.0`](https://lib.haxe.org/p/dox/)
  - [react-portal `1.1.0`](https://lib.haxe.org/p/react-portal/)
  - [thenshim `1.0.0`](https://lib.haxe.org/p/thenshim/)

**Comment by skial** [comment]
- [ ] Contribute a couple of words about Haxe for an article [reddit](https://www.reddit.com/r/haxe/comments/fsa28y/a_couple_of_words_about_haxe_for_an_article/)

**Comment by Beeblerox** [comment]
- [ ] HaxeFlixel tips by [ninja_muffin](https://twitter.com/ninja_muffin99):
    - [Command line basics](https://ninjamuffin99.newgrounds.com/news/post/1090480)
    - [Working with Flash animation](https://ninjamuffin99.newgrounds.com/news/post/1090580)
    - [Some HTML5 export tips](https://ninjamuffin99.newgrounds.com/news/post/1091199)

**Comment by Beeblerox** [comment]
- [ ] [Quick video](https://twitter.com/jimmygunawanapp/status/1242254479644188672) showing ArmorPaint running on iPad with Apple Pencil

**Comment by Beeblerox** [comment]
- [ ] fedellen is [working on another mechanic](https://twitter.com/fedellen/status/1243591664863784964) for the new prototype

**Comment by Beeblerox** [comment]
- [ ] Couple of creative coding skethes by [Matthijs Kamstra](https://twitter.com/MatthijsKamstra):
    - Finally have THAT pesky [elastic collision working](https://www.instagram.com/p/B-PnrFjn7me/?igshid=zdtn7ks44jyz)
    - [Covid19 series: Free for all](https://www.instagram.com/p/B-UDqx1nMVS/)

**Comment by Beeblerox** [comment]
- [ ] [One Page Dungeon Generator 1.1.1](https://www.patreon.com/posts/35396692) by [Oleg Dolya](https://twitter.com/watawatabou). Now with hatching parameters, water level, legend and a number of smaller improvements

**Comment by Beeblerox** [comment]
- [ ] [New screenshot](https://twitter.com/mauvecow/status/1243746147685953537) from WIP turn based puzzle game by mauve

**Comment by Beeblerox** [comment]
- [ ] New arts from SUPER Cute Alien:
    - [Upcoming Advanced System Corruption](https://twitter.com/SUPERCuteAlien/status/1243662966005923841)
    - Improving game's economy. [In this case, "coins"](https://twitter.com/SUPERCuteAlien/status/1245067966712086529)

**Comment by Beeblerox** [comment]
- [ ] Quick videos from the game Ben Simms is making for Stencyl Jam #19:
    - [game mechanics visualisation](https://twitter.com/zerosimms/status/1243930144877744129) but with placeholder art
    - Now starting to work on the art, [going for full-on pixel art](https://twitter.com/zerosimms/status/1244216933802795009)
    - [See the madness ;)](https://twitter.com/zerosimms/status/1244883055673819136)

**Comment by Beeblerox** [comment]
- [ ] [New screenshot](https://twitter.com/SpirkopGames/status/1243890963182956544) from WIP Electric City Manager 2 by Spirkop Games

**Comment by Beeblerox** [comment]
- [ ] [Latitude & Longitude](https://github.com/nanjizal/latLongUK) < - > Ordnance Survey National Grid reference system by [Nanjizal](https://twitter.com/Nanjizal_net/status/1244101995230834688)

**Comment by Beeblerox** [comment]
- [ ] JanoGames has [added a bouncer](https://twitter.com/jano_games/status/1243919732027338752) into level 1 of Stage Dive. Don't land on him otherwise he will launch you into next week

**Comment by Beeblerox** [comment]
- [ ] [Squidly](https://twitter.com/squuuidly/status/1243925472121151488) has opened up [a bounties page](https://github.com/chosencharacters/squidBounties) for HaxeFlixel features. And one of the them is [already claimed](https://github.com/chosencharacters/squidBounties/issues/2)

**Comment by Beeblerox** [comment]
- [ ] [Danny Yaroslavski](https://twitter.com/dannyaroslavski/status/1244066889896046592) has looped back around to his 3dplatformer again

**Comment by Beeblerox** [comment]
- [ ] [Mayur Patil](https://twitter.com/__Mayur___/status/1243971599931334656) decided to finish his Space shooter

**Comment by Beeblerox** [comment]
- [ ] Some screenshots from Stencyl Jam #19 entry by The Jobless Coder:
    - [Great first day](https://twitter.com/TheJoblessCoder/status/1243826259731173376) at the Stencyl Jam
    - [Another great day of progress](https://twitter.com/TheJoblessCoder/status/1244049395240165377)

**Comment by Beeblerox** [comment]
- [ ] Robert Alvarez has [added a second door type](https://twitter.com/Rob1221dev/status/1244268497678581761) that closes after combining some blocks

**Comment by Beeblerox** [comment]
- [ ] [New title screen](https://twitter.com/Pizzamakesgames/status/1244339054302441475) for Skullz'n'Skeletons by Pizza? Text is hard

**Comment by Beeblerox** [comment]
- [ ] Couple of GIFs from WIP game by librorumque:
    - sprites check. sounds check. some code check. [that's it that's the game](https://twitter.com/librorumque/status/1244314337772216323)
    - [Girl now can finish a long list of tasks on her own](https://twitter.com/librorumque/status/1244702215589318658)

**Comment by Beeblerox** [comment]
- [ ] A year late, but [fifth devlog](https://antriel.com/post/rpg-devlog-5/) is out. By [Antriel](https://twitter.com/PeterAchberger/status/1244718088102326274)

**Comment by Beeblerox** [comment]
- [ ] [Testing collision avoidance](https://twitter.com/dazKind/status/1244769122249998339) like a... well I'd love to say pro, but, u know... AT LEAST IT WORKS xD. By Michael Bickel. Here is also [Quad Autonomy Test](https://www.youtube.com/watch?v=Du2sHf-fVDA&feature=youtu.be) video

**Comment by Beeblerox** [comment]
- [ ] torcado is also [participating in Stencyl Jam](https://twitter.com/torcado/status/1244054125358153728)

**Comment by Beeblerox** [comment]
- [ ] [Alex Johansson](https://twitter.com/alexvscoding/status/1245347348349423617) been working on some music for PARcentage!

**Comment by Beeblerox** [comment]
- [ ] [Armory Digest April 2020](https://github.com/Naxela/Armory_Digest/blob/master/April-2020/AD-april-2020.md)

**Comment by Beeblerox** [comment]
- [ ] Go! Go! PogoGirl by Andrej now has [parallax scrolling](https://twitter.com/ohsat_games/status/1245417650093686784)

**Comment by Beeblerox** [comment]
- [ ] luboslenco has released [Iron 2020.4](https://github.com/armory3d/iron/releases/tag/20.04) and [Armory 2020.4](https://github.com/armory3d/armory/releases/tag/20.04)

**Comment by Beeblerox** [comment]
- [ ] [Gameplay video](https://twitter.com/CoryAlexMartin/status/1245425830492241920) of Leapin Lads by Cory Martin
