### ISSUE TITLE
Haxe Roundup 524

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#734]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by anissen** [comment]
- [ ] Haxe blog post: [Shiro Games Technology Stack](https://haxe.org/blog/shirogames-stack/)
- [ ] _Game from Scratch_: [Shiro's Game Tech -- Amazing, Battle Tested & Relatively Unknown Game Engine](https://www.youtube.com/watch?v=Nm4eFGE-cps)

**Comment by anissen** [comment]
_And pimping my own stuff as usual_ 😉
- [ ] [The Cosy programming language now has a foreign function interface!](https://twitter.com/andershnissen/status/1247625590775087105)

**Comment by skial** [comment]
- [ ] Heaps `1.8.0` has been [released](https://github.com/HeapsIO/heaps/releases/tag/1.8.0).

**Comment by skial** [comment]
- [ ] `[Abstracts]` `this` modification in non-inlined method doesn't error [fixed](https://github.com/HaxeFoundation/haxe/issues/9295).

**Comment by skial** [comment]
- [ ] Wrong `var` shadowing [issue](https://github.com/HaxeFoundation/haxe/issues/9296).

**Comment by skial** [comment]
- [ ] `[Abstracts]` `this` modification lost in tempvaring [fixed](https://github.com/HaxeFoundation/haxe/issues/9290).

**Comment by skial** [comment]
- [ ] libs
  - [heaps `1.8.0`](https://lib.haxe.org/p/heaps/)
  - [json2object `3.7.0`](https://lib.haxe.org/p/json2object/)
  - [hxnodejs-request `2.69.4`](https://lib.haxe.org/p/hxnodejs-request/)
  - [hxnodejs-ecdsa-secp256r1 `1.0.3`](https://lib.haxe.org/p/hxnodejs-ecdsa-secp256r1/)
  - [hxnodejs-smart-buffer `1.0.0`](https://lib.haxe.org/p/hxnodejs-ecdsa-secp256r1/)
  - [extype `2.2.1`](https://lib.haxe.org/p/extype/)
  - [hx-delaunator `1.0.0`](https://lib.haxe.org/p/hx-delaunator/)
  - [callfunc `1.1.0`](https://lib.haxe.org/p/callfunc/)
  - [seedyrng `1.1.0`](https://lib.haxe.org/p/seedyrng/)
  - [broker `0.1.0`](https://lib.haxe.org/p/broker/)
  - [banker `0.4.0`](https://lib.haxe.org/p/banker/)
  - [ripper `0.3.0`](https://lib.haxe.org/p/ripper/)
  - [sneaker `0.8.1`](https://lib.haxe.org/p/sneaker/)
  - [markdown `1.1.1`](https://lib.haxe.org/p/markdown/)
  - [hxTypedArray `0.0.1`](https://lib.haxe.org/p/hxTypedArray/)
  - [HxDoom `0.0.4-alpha`](https://lib.haxe.org/p/HxDoom/)
  - [asys `0.4.0`](https://lib.haxe.org/p/asys/)
  - [zame-particles `1.3.0`](https://lib.haxe.org/p/zame-particles/)
  - [deepnightLibs `0.0.36`](https://lib.haxe.org/p/deepnightLibs/)
  - [vshaxe `2.19.0`](https://lib.haxe.org/p/vshaxe/)
  - [hxbolts `1.1.2`](https://lib.haxe.org/p/hxbolts/)

**Comment by Beeblerox** [comment]
- [ ] [Sewing in ArmorPaint](https://twitter.com/luboslenco/status/1247550026647244801) by Lubos Lenco

**Comment by Beeblerox** [comment]
- [ ] Slide Together by [Robert Alvarez](https://twitter.com/Rob1221dev/status/1245756351021821952) is available on [Itch](https://rob1221.itch.io/slide-together) and [Newgrounds](https://www.newgrounds.com/portal/view/751503)

**Comment by Beeblerox** [comment]
- [ ] PARcentage by [Alex Johansson](https://twitter.com/alexvscoding/status/1246357743943942145) is available for beta-testing at [TestFlight](https://testflight.apple.com/join/SspVW0pO)

**Comment by Beeblerox** [comment]
- [ ] New creative coding sketches by [Matthijs Kamstra](https://twitter.com/MatthijsKamstra):
    - Covid19 series: [Social Distancing](https://www.instagram.com/p/B-fZ1g3CxJ6/?igshid=1dnyyndzhkrxr)
    - Covid19 series: [Free for all version 2](https://www.instagram.com/p/B-oXKXfHcVt/)
    - Here are also [couple of screenshots](https://twitter.com/MatthijsKamstra/status/1246195264085544965) of his pattern generator

**Comment by Beeblerox** [comment]
- [ ] [Submissions to Stencyl Jam #19](https://itch.io/jam/stencyl-jam-19/entries) Itch page

**Comment by Beeblerox** [comment]
- [ ] If you interested in Haxe history and its predecessors, [Nicolas Cannasse](https://twitter.com/ncannasse/status/1246179126052032514) has put together [some old sources archives](https://github.com/ncannasse/archives) with notes

**Comment by Beeblerox** [comment]
- [ ] [High score sound](https://twitter.com/CoryAlexMartin/status/1246204704742354944) from Leapin Lads by Cory Martin

**Comment by Beeblerox** [comment]
- [ ] [New stage selection](https://twitter.com/mauvecow/status/1246292045758525440) screen from WIP turn based puzzle game by mauve.

**Comment by Beeblerox** [comment]
- [ ] [Mayur Patil](https://twitter.com/__Mayur___/status/1246298414100271105) has finished the work on Space Shooter Reloaded. You could [play it at Itch](https://mayurpatil.itch.io/space-shooter)

**Comment by Beeblerox** [comment]
- [ ] [Charles Matthews](https://twitter.com/voter96/status/1246215668141187072) is making game for Newgrounds during the HaxeFlixel game jam

**Comment by Beeblerox** [comment]
- [ ] [Nanjizal](https://twitter.com/Nanjizal_net/status/1246449581702946816) has made more tweaks for his [Covid19 UK test](https://nanjizal.github.io/covid19/bin/index.html?test7)

**Comment by Beeblerox** [comment]
- [ ] PogoGirl by Andrej is [still bouncing and chargejumping around](https://twitter.com/ohsat_games/status/1246533193324347393)

**Comment by Beeblerox** [comment]
- [ ] New screenshots from City Generator by Oleg Dolya:
    - [Tiny towns](https://twitter.com/watawatabou/status/1246576546703388679)
    - [Slightly improved tiny towns](https://twitter.com/watawatabou/status/1247194165470994433)

**Comment by Beeblerox** [comment]
- [ ] [WIP main menu](https://twitter.com/SyoPic/status/1246759085166526465) from JitterSandbox by Syo

**Comment by Beeblerox** [comment]
- [ ] [Aidan Lee](https://twitter.com/aidanleegames/status/1246837773727936518) has spent a few afternoons getting Haxe / hxcpp running on the PSVita with the homebrew SDK. Modified version of hxcpp can be [found at github](https://github.com/Aidan63/hxcpp/tree/psvita-toolchain) as well as [sample project](https://github.com/Aidan63/hx_vitasdk)

**Comment by Beeblerox** [comment]
- [ ] Couple of quick videos of VR 3D platformer by Danny Yaroslavski:
    - Wait, can I block out levels with TiltBrush?? [... 10 mins later...](https://twitter.com/dannyaroslavski/status/1246879388013973504)
    - [Sketched out another one!](https://twitter.com/dannyaroslavski/status/1246914631035006976)

**Comment by Beeblerox** [comment]
- [ ] [New title screen](https://twitter.com/Pizzamakesgames/status/1247139323427856386) of Skullz'n'Skeletons is coming along. Thoughts / suggestions?

**Comment by Beeblerox** [comment]
- [ ] [Balancing Quarantine](https://www.fortressofdoors.com/balancing-quarantine-defenders-quest-2-progress-for-march-2020/): Defedner's Quest 2 Progress for March 2020 by [Lars Doucet](https://twitter.com/larsiusprime/status/1247214102289752064)

**Comment by Beeblerox** [comment]
- [ ] [Darek Greenly](https://twitter.com/Zielakpl/status/1247446371109687297) has started improving his old GrayScale gamejam game

**Comment by Beeblerox** [comment]
- [ ] [The wait is nearly over](https://twitter.com/motiontwin/status/1247555720872108036) - Dead Cells is coming to Android on June 3rd! [Pre-register on the Play Store](https://play.google.com/store/apps/details?id=com.playdigious.deadcells.mobile) to get a notification on release day

**Comment by Beeblerox** [comment]
- [ ] Kirby's Dreamland 3 Inspired [Level Clear Conditions](https://twitter.com/mnrART/status/1247662563896238084) by MortMort

**Comment by Beeblerox** [comment]
- [ ] [No No Solo](https://www.newgrounds.com/portal/view/751870) is puzzle game were you have to get to each other. It is also a HaxeFlixel game jam entry by [Fab](https://twitter.com/fabtjar/status/1247908880342044672)

**Comment by Beeblerox** [comment]
- [ ] From Haxe discord: [WikiAdventure](https://github.com/Sacramentix/WikiAdventure) is a game based on the wikipedia api made with hxNodeJS. Here is also [a GIF from it](https://media.discordapp.net/attachments/162664383082790912/697064071463436298/wikiGame.gif)

**Comment by Beeblerox** [comment]
- [ ] [Sonar Smash](https://www.pixelpajamastudios.com/sonarsmash.html) by [fedellen](https://twitter.com/fedellen/status/1247927671646011393) should be released for iOS, Android, PC, and Mac on April, 8th

**Comment by Beeblerox** [comment]
- [ ] Simple Stencyl game [running on Raspberry Pi 3](https://twitter.com/kokoscript/status/1248083197210099718). By Koko

**Comment by skial** [comment]
- [ ] Added `Ast.mk_type_path` to check every type_path creation [merged](https://github.com/HaxeFoundation/haxe/pull/9297).
