### ISSUE TITLE
Haxe Roundup 532

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#763]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] Review https://github.com/skial/haxe.io/issues/761

**Comment by skial** [comment]
- [ ] Syntax class for all targets [discussion](https://github.com/HaxeFoundation/haxe/issues/9502)

**Comment by skial** [comment]
- [ ] `[hxcpp]` Support new and super for native classes [pr](https://github.com/HaxeFoundation/haxe/pull/9516)

**Comment by skial** [comment]
- [ ] The Haxe Summit 2020 is dead - long live the HaxeIn 2020 [blog post](https://haxe.org/blog/haxein-2020/) and [community thread](https://community.haxe.org/t/the-haxe-summit-2020-is-dead-long-live-the-haxein-2020/2502).

**Comment by skial** [comment]
- [ ] [Vadim](https://twitter.com/yellowafterlife) has added emoji and other Unicode support to Pixel Font Converter in the [latest release](https://yellowafterlife.itch.io/pixelfont/devlog/151233/emoji-support-some-convenience).

**Comment by skial** [comment]
- [ ] Why does `@:privateAccess` exit? [community question & discussion](https://community.haxe.org/t/why-does-privateaccess-exist/2500).

**Comment by skial** [comment]
- [ ] The Haxe nightly PHP target is now [tested against versions](https://github.com/HaxeFoundation/haxe/pull/9523) `7.0` ... `7.4`

**Comment by skial** [comment]
- [ ] `[php]` Add some missing functions related to the file system [merged](https://github.com/HaxeFoundation/haxe/pull/9522).

**Comment by skial** [comment]
- [ ] What is Haxe? Introduction video by Richard Oliver Bray https://github.com/skial/haxe.io/issues/764

**Comment by skial** [comment]
- [ ] `[lua]` String API is broken with `--no-inline` [issue](https://github.com/HaxeFoundation/haxe/issues/9530).

**Comment by skial** [comment]
- [ ] libs
  - [electron `9.0.2`](https://lib.haxe.org/p/electron/)
  - [gmodhaxe `0.1.0`](https://lib.haxe.org/p/gmodhaxe/)
  - [thenshim `1.1.0`](https://lib.haxe.org/p/thenshim/)
  - [buddy `2.10.5`](https://lib.haxe.org/p/buddy/)
  - [hxbitmini `1.0.1`](https://lib.haxe.org/p/hxbitmini/)
  - [robotlegs `1.5.0`](https://lib.haxe.org/p/robotlegs/)
  - [fuse `0.0.60`](https://lib.haxe.org/p/fuse/)
  - [haxe-doctest `3.1.1`](https://lib.haxe.org/p/haxe-doctest/)
  - [wronganswer `0.2.0`](https://lib.haxe.org/p/wronganswer/)
  - [HxDoom `0.0.5-alpha`](https://lib.haxe.org/p/HxDoom/)
  - [info `1.1.2`](https://lib.haxe.org/p/info/)
  - [haxefmod `0.3.0-alpha`](https://lib.haxe.org/p/haxefmod/)
  - [hxdefold `1.2.164`](https://lib.haxe.org/p/hxdefold/)
  - [createjs-full `1.5.1`](https://lib.haxe.org/p/createjs-full/)

**Comment by skial** [comment]
- [ ] [Alex Johansson](https://twitter.com/alexvscoding/status/1268147611803975680) previews a ten minute play through of the latest MORSE build.

**Comment by skial** [comment]
- [ ] [Nanjizal](https://twitter.com/Nanjizal_net/status/1267837861728071680) shares an Trilateral3 Simple Colour animation, which uses PalletNine for colours and shapes.

**Comment by skial** [comment]
- [ ] [Robert Alvarez](https://twitter.com/Rob1221dev/status/1267510332957904897) has released Wall Roller, his one-button puzzle game available on itch.io, Newgrounds and Kongregate, made with Stencyl.

**Comment by skial** [comment]
- [ ] [Natinusala](https://twitter.com/natinusala/status/1267132820130070530) has released [switch-haxe `git`](https://github.com/retronx-team/switch-haxe), a sample project for running Haxe on the Nintendo Switch using devkitA64 and libnx.

**Comment by skial** [comment]
- [ ] [Samir Sabri](https://twitter.com/hopewise/status/1267000134065364992) has added new wave and time interactive measurements for the oscilloscope to `dcaclab.com`.

**Comment by skial** [comment]
- [ ] [Michael Walter](https://twitter.com/MVD_Vandie/status/1266742269757001730) gamedev progress, little by little.

**Comment by Beeblerox** [comment]
- [ ] [Dicey Dungeons v1.8](https://steamcommunity.com/games/861540/announcements/detail/2223036005137550234) is out now on Steam and Itch! Featuring new enemies, gamepad controls, and the long awaited Irish translation!

**Comment by Beeblerox** [comment]
- [ ] [The Northgard Map Editor](http://northgard.net/map-editor/) update is out now!

**Comment by Beeblerox** [comment]
- [ ] Couple of GIFs from platformer prototype by Robert Alvarez:
    * [collisions based on color](https://twitter.com/Rob1221dev/status/1266016213576175616)
    * [keys open locks](https://twitter.com/Rob1221dev/status/1266736909054889984) that match their colors

**Comment by Beeblerox** [comment]
- [ ] [Chapter-1 of KhaMC's tutorial](https://blackgoku36.github.io/BG36-tutorials/Kha/book/MarchingCubes/MC_CH_1.html) by [Urjasvi Suthar](https://twitter.com/UrjasviS/status/1266364923157680133)

**Comment by Beeblerox** [comment]
- [ ] [The wait is over](https://twitter.com/Playdigious/status/1268107351900532739)! Android version of Dead Cells is live [on Google Play](https://play.google.com/store/apps/details?id=com.playdigious.deadcells.mobile)

**Comment by Beeblerox** [comment]
- [ ] Castle Pals is the [first Stencyl game on consoles](https://twitter.com/Stencyl/status/1266804760625242113)!

**Comment by Beeblerox** [comment]
> * [ ]  [Alex Johansson](https://twitter.com/alexvscoding/status/1268147611803975680) previews a ten minute play through of the latest MORSE build.

- [ ] Here are [bloopers](https://twitter.com/alexvscoding/status/1267028842914426881) made while recording it :)

**Comment by Beeblerox** [comment]
- [ ] Andrej is working on [some graphics](https://twitter.com/ohsat_games/status/1266836813139841030) for the color-coded doors in Go! Go! PogoGirl

**Comment by Beeblerox** [comment]
- [ ] Sadly, http://try-haxe.mrcdk.com by [Justo Delgado Baudí](https://twitter.com/jdbaudi/status/1267380945704890369) is now dead. [The source code](https://github.com/mrcdk/try-haxe) is available at github if anyone wants to keep working on it

**Comment by Beeblerox** [comment]
- [ ] [Back in the Saddle](https://www.fortressofdoors.com/back-in-the-saddle/): Defender's Quest 2 / my life progress report for May 2020 by [Lars Doucet](https://twitter.com/larsiusprime/status/1267471472450318350)

**Comment by Beeblerox** [comment]
- [ ] [HxBitMini - Lightweight serialization library for Haxe](https://blog.kyubuns.dev/entry/2020/06/02/013520) (it is in Japanese) by [kyubuns](https://twitter.com/kyubuns/status/1267495082141204485)

**Comment by Beeblerox** [comment]
- [ ] [[Insert Platform Name Here] When?](http://www.radicalfishgames.com/?p=6946) CrossCode has passed all console certifications!

**Comment by Beeblerox** [comment]
- [ ] [Edu Alonso](https://twitter.com/sodapillo/status/1268188019527467012) is working on a game called "100 vacas", and planning to release it on Steam

**Comment by Beeblerox** [comment]
- [ ] Lubos Lenco has released 2020.6 versions of [Armory](https://github.com/armory3d/armory/releases/tag/20.06), [Iron](https://github.com/armory3d/iron/releases/tag/20.06) and [Armory tutorials](https://github.com/armory3d/armory_tutorials/releases/tag/20.06)

**Comment by Beeblerox** [comment]
- [ ] Will Blanton has made [Underneath Planet Monster](https://github.com/01010111/card-tactics) repo public

**Comment by Beeblerox** [comment]
- [ ] [Armory3D | Body Aura & Shield effect](https://www.youtube.com/watch?v=hwLoN2EfW_U&feature=emb_logo) video by [ArmoryBlender](https://twitter.com/ArmoryBlender/status/1268392231691526144)

**Comment by Beeblerox** [comment]
- [ ] [Bit size tutorial levels](https://twitter.com/mnrART/status/1268375352285573120) from WIP Stencyl game by MortMort

**Comment by Beeblerox** [comment]
- [ ] [Trilateral rotation and movement](https://trilateralx.github.io/TrilateralRotateMove/) demo by [Nanjizal](https://twitter.com/Nanjizal_net/status/1268455208599924736)
