### ISSUE TITLE
Haxe Roundup 534

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#768]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] check:
  + https://github.com/skial/haxe.io/issues/764
  + https://github.com/skial/haxe.io/issues/761

**Comment by skial** [comment]
- [ ] tink_core `v2` [pull request](https://github.com/haxetink/tink_core/pull/123)!

**Comment by miriti** [comment]
Basic Grid-Based Ray Casting with Haxe and OpenFL: https://github.com/miriti/openfl-raycasting

**Comment by skial** [comment]
- [ ] `@:structInit` creates non exist but typeable constructor [issue](https://github.com/HaxeFoundation/haxe/issues/9567).

**Comment by skial** [comment]
- [ ] Forwarded abstract fields are not available through a constrained type parameter [issue](https://github.com/HaxeFoundation/haxe/issues/9571).

**Comment by skial** [comment]
- [ ] `[ide]` Everything is red if a single struct in an array is missing a field [issue](https://github.com/HaxeFoundation/haxe/issues/9584).

**Comment by skial** [comment]
- [ ] `[macro]` Meta for TypeParamDecl ignored during reification and printing [fixed](https://github.com/HaxeFoundation/haxe/issues/9565).

**Comment by skial** [comment]
- [ ] Exhaustive matching for enum abstract null value [issue](https://github.com/HaxeFoundation/haxe/issues/9563).

**Comment by skial** [comment]
- [ ] `[jvm]` `OutOfMemoryError` with `~/\b/g.split()` [issue](https://github.com/HaxeFoundation/haxe/issues/9601).

**Comment by skial** [comment]
- [ ] `[js]` Improve generation of dynamic methods to avoid unnecessary `$bind` [issue](https://github.com/HaxeFoundation/haxe/issues/9598).

**Comment by skial** [comment]
- [ ] Add method inlining to `inline` constructors filter [pull request](https://github.com/HaxeFoundation/haxe/pull/9599).

**Comment by Beeblerox** [comment]
- [ ] [Vadim Dyachenko](https://twitter.com/YellowAfterlife/status/1271111257022779392) has released a [little companion tool](https://yal.cc/r/20/pixelfont/frombmf/) which lets you convert a BitFontMaker2 font for use with [Pixel Font Converter](https://yal.cc/r/20/pixelfont/)

**Comment by Beeblerox** [comment]
- [ ] [Vadim Dyachenko](https://twitter.com/YellowAfterlife/status/1272231550034247683) has also released a set of [3 map-like implementations](https://github.com/GameMakerDiscord/Map.gml) for GameMaker Studio 2.3

**Comment by Beeblerox** [comment]
- [ ] [Haxe/OpenFL Devlog #21](https://www.kickstarter.com/projects/feathersui/feathers-ui-cross-platform-components-for-haxe-and-openfl/posts/2856481): CLI create-project, VSCode extension, and preparing for alpha.2

**Comment by Beeblerox** [comment]
- [ ] [Missile alert](https://twitter.com/filipp8/status/1271161889695977473) by 𝙵𝚒𝚕𝚒𝚙𝚙𝚘 𝙱𝚘𝚍𝚎𝚒

**Comment by Beeblerox** [comment]
- [ ] 100% Golf by [Alex Johansson](https://twitter.com/alexvscoding/status/1271205667236438016) got a USA number 2 listing on “New Games We Love”. Here are also [map doodles](https://twitter.com/alexvscoding/status/1272955036729999361) for the game

**Comment by Beeblerox** [comment]
- [ ] Spellbreak by Proletariat Inc. is going [to Xbox and Switch too](https://twitter.com/cwaneck/status/1271206285963415554)

**Comment by Beeblerox** [comment]
- [ ] [ArmorPaint running on iPadOS](https://twitter.com/luboslenco/status/1271409832541773824). Powered by Metal at 120fps with Apple Pencil support

**Comment by Beeblerox** [comment]
- [ ] [Gregory Seed](https://twitter.com/gregorysreed/status/1269269182731911168) is working on Android port of LITTLE SQUARE THINGS. And you can [sign up](https://play.google.com/apps/testing/com.greed.lst) for the open beta

**Comment by Beeblerox** [comment]
- [ ] With [hashlink-debugger 1.1.0](https://marketplace.visualstudio.com/items/HaxeFoundation.haxe-hl/changelog) which was just released to the VSCode marketplace, debugging Lime projects now works out of the box! via [HaxeFlixel](https://twitter.com/HaxeFlixel/status/1271823998775672833)

**Comment by Beeblerox** [comment]
- [ ] [Combat balance](https://twitter.com/kennygoff/status/1271861334892781574) update and a [new Versus match type](https://twitter.com/kennygoff/status/1271990055498854400) called Scramble for [Double Turn](https://doubleturngame.com/)

**Comment by Beeblerox** [comment]
- [ ] torcado has implemented [a new shop system](https://twitter.com/torcado/status/1271933043813449728) in [Heck Deck](https://torcado.itch.io/heck-deck), allowing you to sell and trade cards for health

**Comment by Beeblerox** [comment]
- [ ] It's decision time! [Left or right?](https://twitter.com/Pizzamakesgames/status/1272120559338434561) by Pizza

**Comment by Beeblerox** [comment]
- [ ] [A bunch of bouncy blocks](https://twitter.com/Rob1221dev/status/1272214473034563591) from WIP platformer game by Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] The [Renaine Demo](https://store.steampowered.com/app/662340/Renaine/?beta=0) is LIVE on the Steam Games Festival

**Comment by Beeblerox** [comment]
- [ ] [Jens Fischer](https://twitter.com/Gama11_/status/1272280741305552897) is working on HXML completion tool for VSCode

**Comment by Beeblerox** [comment]
- [ ] [Joaquin Bello](https://twitter.com/JoaquinBelloD/status/1272343860111388672) is working on a small FPS. An example to introduce 3d concepts (projection, shaders, 3d transforms, zbuffer). And he is planning to make code available at some time

**Comment by Beeblerox** [comment]
- [ ] [CrossCode AMA](https://www.reddit.com/r/nintendo/comments/ha6fjf/we_are_radical_fish_games_deck13_developer_and/)

**Comment by Beeblerox** [comment]
- [ ] Couple of quick videos by Geokureli:
    * [2P custom input UI](https://twitter.com/Geokureli/status/1272654579247742983)
    * [Straight up stealing UI juice effects](https://twitter.com/Geokureli/status/1272935140336054272)

**Comment by Beeblerox** [comment]
- [ ] [Andrej](https://twitter.com/ohsat_games/status/1272861063218892800) has started a devlog for his platformer game Go! Go! PogoGirl! [The first post](https://www.ohsat.com/post/pogogirl-devlog/post1/) is now up!

**Comment by Beeblerox** [comment]
- [ ] [JavaScript Mini Projects](https://matthijskamstra.github.io/javascript-mini-projects/) by [Matthijs Kamstra](https://twitter.com/MatthijsKamstra/status/1271370649383120905)

**Comment by Beeblerox** [comment]
- [ ] [New visual style](New visual style for the Village Generator) for the Village Generator by Oleg Dolya

**Comment by Beeblerox** [comment]
- [ ] [Chapter-2](https://blackgoku36.github.io/BG36-tutorials/Kha/book/MarchingCubes/MC_CH_2.html) of Kha's MC tutorial on terrain generation by [Urjasvi Suthar](https://twitter.com/UrjasviS/status/1273285034372411398)

**Comment by Beeblerox** [comment]
- [ ] [TrilateralSamples](https://github.com/TrilateralX/TrilateralSamples) and [hxSpiro2020](https://github.com/nanjizal/hxSpiro2020) (a haxe port of [Spiro](https://github.com/raphlinus/spiro) library) by [Nanjizal](https://twitter.com/Nanjizal_net)

**Comment by Beeblerox** [comment]
- [ ] [HxWren](https://github.com/darmie/HxWren) by 'Damilare Darmie Akinlaja is a Haxe implementation of the Wren scripting language virtual Machine

**Comment by Beeblerox** [comment]
- [ ] [Sébastien Bénard](https://twitter.com/deepnightfr) has started creating [a generic 2D level editor](https://github.com/deepnight/led). Some intended features of the editor: 
    * Tile layers, IntGrid layers and Entities
    * fully customizable entities, with each field being optionaly displayed on the level 
    * strong focus on making something simple, easy to use and lightweight
    * open source

Here are couple of screenshots: 
    * [Mob editor](https://media.discordapp.net/attachments/162664383082790912/720905858464350279/unknown.png)
    * [Project Entitites](https://media.discordapp.net/attachments/162664383082790912/720905969059758100/unknown.png)

**Comment by Beeblerox** [comment]
- [ ] Skyfire2008 from Haxe discrord server has released demo of [Spork Asteroids](https://kurt-c0caine.itch.io/spork-asteroids). Everything is WIP, even the player ship has 1000 lives for the purpose of testing

**Comment by skial** [comment]
- [ ] libs
  - [mithril `2.2.1`](https://lib.haxe.org/p/mithril/)
  - [HaxeContracts `0.14.4`](https://lib.haxe.org/p/HaxeContracts/)
  - [buddy `2.12.0`](https://lib.haxe.org/p/buddy/)
  - [dataclass `2.0.2`](https://lib.haxe.org/p/dataclass/)
  - [apollo `0.2.4`](https://lib.haxe.org/p/apollo/)
  - [bind `0.4.8`](https://lib.haxe.org/p/bind/)
  - [banker `0.6.1`](https://lib.haxe.org/p/banker/)
  - [ripper `0.3.3`](https://lib.haxe.org/p/ripper/)
  - [sneaker `0.10.0`](https://lib.haxe.org/p/sneaker/)
  - [prayer `0.1.3`](https://lib.haxe.org/p/prayer/)
  - [hlc-compiler `0.2.0`](https://lib.haxe.org/p/hlc-compiler/)
  - [locator `0.4.0`](https://lib.haxe.org/p/locator/)
  - [greeter `0.1.0`](https://lib.haxe.org/p/greeter/)
  - [sinker `0.3.0`](https://lib.haxe.org/p/sinker/)
  - [udprotean `0.3.0`](https://lib.haxe.org/p/udprotean/)
  - [info `1.1.3`](https://lib.haxe.org/p/info/)
  - [quadtree `0.5.1`](https://lib.haxe.org/p/quadtree/)
  - [bytetype `0.7.0`](https://lib.haxe.org/p/bytetype/)
  - [buw `0.8.6`](https://lib.haxe.org/p/buw/)
  - [typepacker `1.1.1`](https://lib.haxe.org/p/typepacker/)
  - [Spork `0.7.1`](https://lib.haxe.org/p/Spork/)
  - [signals `1.3.2`](https://lib.haxe.org/p/signals/)
  - [pool `0.1.0`](https://lib.haxe.org/p/pool/)
  - [vscode-debugadapter `1.41.0`](https://lib.haxe.org/p/vscode-debugadapter/)
  - [vscode `1.46.0`](https://lib.haxe.org/p/vscode/)

**Comment by skial** [comment]
- [ ] `@:forward`-ed abstract fields prevent object inlining [issue](https://github.com/HaxeFoundation/haxe/issues/9606).

**Comment by Beeblerox** [comment]
- [ ] [Water demo](https://www.youtube.com/watch?v=lGVjdXJPmaA&feature=emb_logo) (Haxe + Heaps) video by [Edwin Syarief](https://twitter.com/edmozgaming/status/1273299475742650368)

**Comment by Beeblerox** [comment]
- [ ] [SUPER Cute Alien](https://twitter.com/SUPERCuteAlien/status/1273361784150335491) is featured on Platformers category on Steam Games Festival. [Play the limited demo](https://store.steampowered.com/app/1099790/SUPER_Cute_Alien/)

**Comment by Beeblerox** [comment]
- [ ] [Away3D with OimoPhysics](https://github.com/vujadin/Away3D_with_OimoPhysics) demo by Krtolica Vujadin

**Comment by skial** [comment]
- [ ] Rewrite the JAR loader [pull request](https://github.com/HaxeFoundation/haxe/pull/9608).

**Comment by skial** [comment]
- [ ] [coconut.json `git`](https://github.com/kevinresol/coconut.json) Serialize coconut models with tink_json
