### ISSUE TITLE
Haxe Roundup 540

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#782]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[tink_sql]` Support `IFNULL()` function [pull request](https://github.com/haxetink/tink_sql/pull/115).

**Comment by skial** [comment]
- [ ] `[tink_core]` Cleanup `or()` functions [pull request](https://github.com/haxetink/tink_core/pull/141).

**Comment by skial** [comment]
- [ ] Fix comparing underlying recursive type in variance unification [pull request](https://github.com/HaxeFoundation/haxe/pull/9761).

**Comment by skial** [comment]
- [ ] `(get, default)` vs `OpAssignOp` [issue](https://github.com/HaxeFoundation/haxe/issues/9750).

**Comment by skial** [comment]
- [ ] `[Kinc]` Improve Vulkan backend [merged](https://github.com/Kode/Kinc/pull/534).

**Comment by skial** [comment]
- [ ] Refactor operator handling [merged](https://github.com/HaxeFoundation/haxe/pull/9751).

**Comment by skial** [comment]
- [ ] Threading API for the Python target [pull request](https://github.com/HaxeFoundation/haxe/pull/9754).

**Comment by skial** [comment]
- [ ] Support `@:using` on typedefs [pull request](https://github.com/HaxeFoundation/haxe/pull/9749).

**Comment by skial** [comment]
- [ ] Detailed [explanation](https://github.com/HaxeFoundation/haxe/issues/9752#issuecomment-663903622) of the recent `@:transitive` abstracts changes, type variance and interfaces. 📝

**Comment by skial** [comment]
- [ ] Rework unary operator handling [pull request](https://github.com/HaxeFoundation/haxe/pull/9766).

**Comment by skial** [comment]
- [ ] New coverage and profiling library [announcement thread](https://community.haxe.org/t/new-coverage-and-profiling-library/2598) 🌟

**Comment by Beeblerox** [comment]
- [ ] Couple of GIFs from Robert Alvarez:
    * [A new level](https://twitter.com/Rob1221dev/status/1286310383435816960) with negative control pickups
    * [A prototype](https://twitter.com/Rob1221dev/status/1287035739125972992) about switching colors to get the right number of each

**Comment by Beeblerox** [comment]
- [ ] Couple of quick videos from Stage Dive by JanoGames:
    * [Finished up creating the menu screen](https://twitter.com/jano_games/status/1286329892397895681)
    * Added in a redtop [Newspaper headline transition](https://twitter.com/jano_games/status/1286422840363843584) after each level

**Comment by Beeblerox** [comment]
- [ ] [New wrestler palettes](https://twitter.com/doubleturngame/status/1287053570366418951) in Double Turn

**Comment by Beeblerox** [comment]
- [ ] [NEW RELEASE](https://www.youtube.com/watch?v=Hxz1IwUen90&feature=youtu.be) of PRG Playground: 5 extra characters: dragons and skeleton. Copy maps functionality was also added. And 5 bonus characters when PRG Playground's YouTube channel reaches 400 subscribers! So subscribe now!

**Comment by Beeblerox** [comment]
- [ ] Couple of GIFs by Luyren:
    * You know its serious when [the boss attacks from the background](https://twitter.com/LuyrenStencyl/status/1286374598209134592)
    * [At 174 events, this is the longest attack script I've made](https://twitter.com/LuyrenStencyl/status/1286759084092424194)

**Comment by Beeblerox** [comment]
- [ ] Guys from Stencyl are [working on code reload implementation](https://twitter.com/Stencyl/status/1286315133363527682) for their engine

**Comment by Beeblerox** [comment]
- [ ] An interview with [Sébastien Bénard](https://twitter.com/deepnightfr): [Fin de Twinoid : « il n’y a plus d’envie pour du jeu web »](https://www.portables4gamers.com/fin-de-twinoid-il-ny-a-plus-denvie-pour-du-jeu-web/)

**Comment by Beeblerox** [comment]
- [ ] [Trilateral3 texture kiwi test](https://www.codeply.com/p/D2FhTDBLpD) by [Nanjizal](https://twitter.com/Nanjizal_net/status/1286985058654576640)

**Comment by Beeblerox** [comment]
- [ ] Tomasz Kwiatek is [working on SVG import to box2d](https://twitter.com/lleqsnoom/status/1287051650683801600). Concave polygons [are separated on runtime](https://twitter.com/lleqsnoom/status/1287051652479016961)

**Comment by Beeblerox** [comment]
- [ ] [Lops](https://marcosd.itch.io/lops) by [Marcos Donnantuoni](https://twitter.com/marcos_don/status/1287029656793817089)

**Comment by Beeblerox** [comment]
- [ ] Couple of diagrams from Game Maker's Toolkit survey results (they've asked he developers of 5,400 game jam games):
    * [what they used to make their game](https://twitter.com/gamemakerstk/status/1287115875624071171)
    * [the engines used by the 250 top ranked GMTK Game Jam games](https://twitter.com/gamemakerstk/status/1287285671007342592) (strangely Haxe became an engine)

**Comment by Beeblerox** [comment]
- [ ] [torcado](https://twitter.com/torcado/status/1287156619797659648) is looking for a publisher/indie fund to help him fund the rest of the development for [Heck Deck](https://torcado.itch.io/heck-deck). He would love to know any recomendations you have

**Comment by Beeblerox** [comment]
- [ ] Check out [Hugh Sanderson](https://twitter.com/GameHaxe/status/1287569908591599622)'s novel [Five-by-5](https://play.google.com/store/apps/details?id=com.fundieware.fiveby5) card came on the Google play store, - a mashup between Solitaire and Match-3 (but harder).  Made with Haxe and NME.

**Comment by Beeblerox** [comment]
- [ ] [The lad gallery UI](https://twitter.com/CoryAlexMartin/status/1287851571670405120) from Leapin Lads by Cory Martin

**Comment by Beeblerox** [comment]
- [ ] [Kikker](https://voskip.itch.io/kikker) is a puzzle game (made by [Voskip](https://twitter.com/voskip/status/1286653481697398786) with HaxeFlixel) about a frog returning the colors to its pond after they were stolen by a witch.

**Comment by Beeblerox** [comment]
- [ ] Malody Hoe been working on [binding physx into Haxe/hxcpp](https://twitter.com/undefinist/status/1286593654136508416)

**Comment by Beeblerox** [comment]
- [ ] [President of Space](https://twitter.com/matzieq/status/1286963647030288384) had switched to HaxeFlixel for development of Caverns of Xantarus

**Comment by Beeblerox** [comment]
- [ ] [Andreas Drewke](https://twitter.com/andreas_drewke/status/1288269756273917952) is looking for a part time job

**Comment by Beeblerox** [comment]
- [ ] [Call for Developers: Remaining Items for OpenFL 9](https://community.openfl.org/t/call-for-developers-remaining-items-for-openfl-9/12623) by Joshua Granick

**Comment by Beeblerox** [comment]
- [ ] [Hscript with classes, aka “hscript-ex”](https://community.haxe.org/t/hscript-with-classes-aka-hscript-ex/2597) by Ian Harrigan

**Comment by Beeblerox** [comment]
- [ ] [Abstract_Panic](https://twitter.com/abstract_panic) from 1speed studio is implementing [2d lighting](https://cdn.discordapp.com/attachments/501447516852715525/737570132808826950/test.gif) for their WIP game "Croaking Hill"

**Comment by Beeblerox** [comment]
- [ ]  Sébastien Bénard is continuing his work on [L-Ed](https://github.com/deepnight/led), a generic 2D level editor for Haxe (and other targets as well). It's now possible to directly [import one of your HX files](https://cdn.discordapp.com/attachments/162664383082790912/736157522058281000/import.png) in the editor to use the Enums declared in it (for example for entities placed in a level). Here is the [loaded HX source file](https://cdn.discordapp.com/attachments/162664383082790912/736157601288552509/source.png). He'll also support CastleDB import, and I'll give a try to ExpDB from Kevin Leung

**Comment by Beeblerox** [comment]
- [ ] [hxspine-g4](https://github.com/sh-dave/hxspine-g4) and [hxspine-g4-playground](https://github.com/sh-dave/hxspine-g4-playground) by David Klein

**Comment by skial** [comment]
- [ ] `[abstracts]` Add support for constructor forwarding with `@:forward.new` [merged](https://github.com/HaxeFoundation/haxe/pull/9735).

**Comment by skial** [comment]
- [ ] `@:build` on typedef is not allowed [issue](https://github.com/HaxeFoundation/haxe/issues/9779).

**Comment by skial** [comment]
- [ ] libs
  - [sbComponents `0.0.9`](https://lib.haxe.org/p/sbComponents/)
  - [fuse `0.1.0`](https://lib.haxe.org/p/fuse/)
  - [cacher `1.0.3`](https://lib.haxe.org/p/cacher/)
  - [tink_parser `0.4.1`](https://lib.haxe.org/p/tink_parse/)
  - [hscript-ex `0.0.0`](https://lib.haxe.org/p/hscript-ex/)
  - [wire `0.7.0`](https://lib.haxe.org/p/wire/)
  - [instrument `1.0.0`](https://lib.haxe.org/p/instrument/)
  - [utest `1.12.1`](https://lib.haxe.org/p/utest/)
  - [StoryblokClient `0.4.0`](https://lib.haxe.org/p/StoryblokClient/)

**Comment by skial** [comment]
- [ ] In development brushes coming to [Realmkit](https://twitter.com/RealmkitApp), a tool for illustrating, designing and generating fictional worlds by [Daniel B](https://twitter.com/5Mixer) made with Haxe, Kha and HaxeUI.

**Comment by skial** [comment]
- [ ] [Work in progress](https://twitter.com/kevinresol/status/1288452210246877186) drag/drop support for `#MVCoconut` by Kevin Leung.

**Comment by skial** [comment]
- [ ] [three.hx `git`](https://github.com/tong/three.hx) : Haxe→Three.js type definitions have been upgraded to three.js `r119`.

**Comment by skial** [comment]
- [ ] The first version of the HaxeUI theme `haxeui-theme-material` is available on HaxeLib, take a look at the [preview](https://twitter.com/AdrianVeith/status/1288485762351140872).
