### ISSUE TITLE
Haxe Roundup 543

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#790]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [HxDoom `0.0.6 alpha`](https://github.com/kevansevans/HxDoom/releases/tag/A0.0.6) has been released.

**Comment by skial** [comment]
- [ ] libs
  - [utest `1.13.1`](https://lib.haxe.org/p/utest/)
  - [openfl `9.0.2`](https://lib.haxe.org/p/openfl/)
  - [coconut.react-core `0.2.2`](https://lib.haxe.org/p/coconut.react-core/)
  - [tink_lang `0.7.0`](https://lib.haxe.org/p/tink_lang/)
  - [tink_hxx `0.24.3`](https://lib.haxe.org/p/tink_hxx/)
  - [dataclass `2.2.1`](https://lib.haxe.org/p/dataclass/)
  - [HxDoom `0.0.6-alpha`](https://lib.haxe.org/p/HxDoom/)
  - [dropecho.lib_example `0.5.2`](https://lib.haxe.org/p/dropecho.lib_example/)
  - [vscode `1.48.0`](https://lib.haxe.org/p/vscode/)
  - [test-adapter `1.2.9`](https://lib.haxe.org/p/test-adapter/)
  - [swf `3.0.0`](https://lib.haxe.org/p/swf/)

**Comment by skial** [comment]
- [ ] [Adrain Veith](https://twitter.com/AdrianVeith/status/1296051053432049665) has revived the nim lang experimental target, with the first benchmarks showing good performance compared to other targets.

**Comment by skial** [comment]
- [ ] [bitmapkid](https://twitter.com/btmpkd/status/1295267381154021376) has released kurushi to itch.io for `#LOWRESJAM`. Check out the [devlog](http://www.bitmapk.id/kurushi/) for in-depth details.

**Comment by skial** [comment]
- [ ] [Alex Lanzetta](https://twitter.com/Zanzlanz/status/1295005682333294595) has released the Haxe port of A.R.B.F.

**Comment by skial** [comment]
- [ ] [Mine Blocks](https://twitter.com/Mine_Blocks/status/1294688009422610435), in beta, is a classic Flash game being rewritten in Haxe, currently 20% complete.

**Comment by skial** [comment]
- [ ] [GlassySundew](https://twitter.com/GlassySundew) previews the command bridge for the Pascal class ship mockup made in Heaps. Check out the [pre-production source code](https://github.com/GlassySundew/heapsGame) of the game.

**Comment by skial** [comment]
- [ ] [StateGo](https://twitter.com/stategotool/status/1294241562713415681), a visual programming tool has added support for Haxe. Check out their [sample project](https://github.com/NNNIC/psgg-haxe-sample) on GitHub.

**Comment by skial** [comment]
- [ ] 5 Reasons why I enjoy using HaxeFlixel and why you should give it a try [video](https://www.youtube.com/watch?v=XE3lx5GtihE) by [Richard Oliver Bray](https://twitter.com/ceiga).

**Comment by skial** [comment]
- [ ] [Double Turn](https://twitter.com/doubleturngame/status/1296066148132364288) Combat Experiment #2: Environmental Stuns devlog.

**Comment by skial** [comment]
- [ ] [Edu Alonso](https://twitter.com/sodapillo/status/1295773274689933312) shares a deNaves update showing bombs and a HUD, which was mentioned in [last weeks roundup](https://haxe.io/roundups/542/#OpenSource:~:text=Edu%20Alonso%20decided%20to%20make%20a%20shmup%20game%20in%20a%20couple%20of%20days).

**Comment by Beeblerox** [comment]
- [ ] [Jim Stormdancer](https://twitter.com/mogwai_poet/status/1292573275126558720) wrote a blog post ["How I Modernized My Flash Game"](http://twinbeard.com/how-i-modernized-my-flash-game.html)

**Comment by Beeblerox** [comment]
- [ ] [Saving / loading implemented](https://twitter.com/Pizzamakesgames/status/1294344739735711749) for Skullz 'n Skeletonz by Pizza

**Comment by Beeblerox** [comment]
- [ ] A few GIFs from Go! Go! PogoGirl by Andrej:
    * [I...I don't think this is right](https://twitter.com/ohsat_games/status/1294718834885242880)
    * [nevermind I fixed it](https://twitter.com/ohsat_games/status/1294788451292909568)
    * So, I wanted to make the gems flash again to make them look more fancy. [Think I overdid it?](https://twitter.com/ohsat_games/status/1295047518426988555)

- [ ] And Andrej' patrons can now play [an early demo of Go! Go! PogoGirl!](https://twitter.com/ohsat_games/status/1295477675772059651)

**Comment by Beeblerox** [comment]
- [ ] [Defenders Quest 2 progress tweet](https://twitter.com/larsiusprime/status/1295729529844051969) by Lars Doucet

**Comment by Beeblerox** [comment]
- [ ] [Redrawn player sprites](https://twitter.com/mauvecow/status/1294495934890430464) for WIP turn based puzzle game by mauve.

**Comment by Beeblerox** [comment]
- [ ] [100 vacas](https://store.steampowered.com/app/1335820/100_vacas/) by [Edu Alonso](https://twitter.com/sodapillo/status/1295367593377832966) is now available for purchase with a 15% launch discount!

**Comment by Beeblerox** [comment]
- [ ] [Combat Experiment #2](https://steamcommunity.com/games/762680/announcements/detail/2762349656052194791): Environmental Stuns in Double Turn.

**Comment by Beeblerox** [comment]
- [ ] [Create RPG's on Android, iPhone & iPad](https://www.youtube.com/watch?v=EuTaS7u2Hzs&feature=youtu.be) with RPG Playground. And RPG Playground's YouTube channel reached 400 subscribers, so [5 new dog characters are released](https://www.youtube.com/watch?v=N1t_fWZ07KM&feature=youtu.be)

**Comment by Beeblerox** [comment]
- [ ] [Armorpaint | Hydrant - Getting Started #0](https://www.youtube.com/watch?v=mkcFpaudl8U&feature=youtu.be) by [ArmoryBlender](https://twitter.com/armoryblender/status/1295759854427152384)

**Comment by Beeblerox** [comment]
- [ ] The name of [Lewis Lepton](https://twitter.com/lewislepton/status/1296005259203141632)'s HaxeIn talk will be "Do can? Teaching I good"

**Comment by Beeblerox** [comment]
- [ ] Even the Ocean (originally made with HaxeFlixel) has been ported by [Ratalaika Games](https://twitter.com/RatalaikaGames/status/1295861897078734849) to game consoles: [PlayStation 4](https://store.playstation.com/en-us/product/UP0891-CUSA19416_00-RATAEVENTHEOCEAN), XBox One and Switch

**Comment by Beeblerox** [comment]
- [ ] [OpenFL 9 is here!](https://community.openfl.org/t/openfl-9-is-here/12637)

**Comment by Beeblerox** [comment]
- [ ] [HotDog 64](https://bitdecaygames.itch.io/hotdog-64) made for The LOWREZJAM 2020 using: HaxeFlixel, FMOD, FL Studio and Pyxel Edit

**Comment by Beeblerox** [comment]
- [ ] [LunaTea](https://github.com/LunaTechsDev/LunaTea) is a Haxe Core Library for RPGMaker MZ/MV plugin and tool development

**Comment by Beeblerox** [comment]
- [ ] [Stencyl 4.0.3 is officially released!](http://community.stencyl.com/index.php/topic,60936.0.html)

**Comment by Beeblerox** [comment]
- [ ] Help save your aging guitarist - [bat away the pint glasses](https://twitter.com/jano_games/status/1296190311576801281) in Stage Dive by Jano Games
