### ISSUE TITLE
Haxe Roundup 545

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#794]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] [Double Turn](https://twitter.com/doubleturngame/status/1299006256619966466) Combat Experiment `#3`: Signature Rework.

**Comment by skial** [comment]
- [ ] [Double Kick Heroes](https://twitter.com/headbang_club/status/1299270879176687616) - The METAL Rhythm Shooter is now live on Xbox One & Windows 10 store 🤘

**Comment by skial** [comment]
- [ ] [StateGo's](https://twitter.com/stategotool/status/1299954084196184064) successfully converting C# to Haxe and out to C# & C++  with a Cs2hx tool.

**Comment by skial** [comment]
- [ ] Per-thread event loop [pull request](https://github.com/HaxeFoundation/haxe/pull/9868).

**Comment by skial** [comment]
- [ ] `[community]` Some [questions](https://community.haxe.org/t/some-questions-to-ongenerate/2632/1) about `onGenerate` and custom targets.

**Comment by jeremyfa** [comment]
- [ ] [Make More Views](https://twitter.com/LaGamerieStudio/status/1298972259646922752) has been released (in french, english soon), a free to play game on ios & android made with haxe & [ceramic engine](https://github.com/ceramic-engine/ceramic)

**Comment by skial** [comment]
- [ ] `[tink_state`] Attempt to optimize subscription & update benchmark [merged](https://github.com/haxetink/tink_state/pull/43). Appears to be twice as fast as MobX.

**Comment by skial** [comment]
- [ ] `[jvm]` `Float * Int` invalid multiplication [issue](https://github.com/HaxeFoundation/haxe/issues/9870).

**Comment by skial** [comment]
- [ ] [ty](https://twitter.com/zzo__x/status/1301005335612850176) previews a HaxeFlixel powered prototype for a fishing rhythm game.

**Comment by skial** [comment]
- [ ] [GlassySundew's](https://twitter.com/GlassySundew/status/1300932413862932482) Heaps powered pixel art preview.

**Comment by skial** [comment]
- [  ] [Edu Alonso](https://twitter.com/sodapillo/status/1300915399870087173) has stealthily released his shmup practice game made with HaxeFlixel onto itch.io.

**Comment by skial** [comment]
- [ ] [Robert Alvarez](https://twitter.com/Rob1221dev/status/1300855787544285186) has released Color Count, his newest puzzle game, now available on itch.io and Newgrounds. Made with Stencyl.

**Comment by skial** [comment]
- [ ] libs
  - [nme-applovin-ios `6.13.0`](https://lib.haxe.org/p/nme-applovin-ios/)
  - [firedancer `0.1.0`](https://lib.haxe.org/p/firedancer/)
  - [firedancer-vm `0.1.0`](https://lib.haxe.org/p/firedancer-vm/)
  - [broker `0.5.0`](https://lib.haxe.org/p/broker/)
  - [banker `0.7.0`](https://lib.haxe.org/p/banker/)
  - [sneaker `0.11.0`](https://lib.haxe.org/p/sneaker/)
  - [ripper `0.4.0`](https://lib.haxe.org/p/ripper/)
  - [reckoner `0.2.0`](https://lib.haxe.org/p/reckoner/)
  - [sinker `0.5.0`](https://lib.haxe.org/p/sinker/)
  - [hxnodejs-agentkeepalive `4.1.0`](https://lib.haxe.org/p/hxnodejs-agentkeepalive/)
  - [led-haxe-api `1.0.1`](https://lib.haxe.org/p/led-haxe-api/)
  - [yweak `0.0.1`](https://lib.haxe.org/p/yweak/)
  - [dataclass `3.1.0`](https://lib.haxe.org/p/dataclass/)

**Comment by skial** [comment]
- [ ] [Dmitry Hryppa](https://twitter.com/dmitryhryppa/status/1300792695481348096) finding time to develop his pet project.

**Comment by skial** [comment]
- [ ] [Dimitri Pomier](https://twitter.com/dimitripomier/status/1300782976536641536) is making progress with out of the box compatibility of the compiler-plugin & ecso with the offical Haxe builds using GitHub Actions.

**Comment by skial** [comment]
- [ ] [Syo](https://twitter.com/SyoPic/status/1300448123622510592) is using a markdown based dialog system allowing him to quickly test directly in VSCode or on GitHub.

**Comment by skial** [comment]
[Matzieq](https://twitter.com/matzieq/status/1299650387402805248) continues to work on the minimap for Caverns of Ksantarus with HaxeFlixel and has also published their first devlog.

**Comment by skial** [comment]
- [ ] [Caribou](https://twitter.com/caribouloche/status/1299386809294761985) shows a weird controller experiment, an old unfinished project.

**Comment by skial** [comment]
- [ ] [Joseph Azar](https://twitter.com/parazar/status/1299090629457326081) Heaps exploratory creative coding demo.

**Comment by Beeblerox** [comment]
- [ ] [Darksburg](https://twitter.com/Darksburg/status/1299010893360107521) will be leaving Early Access and officially releasing into 1.0 on the 23rd of September. Watch [Official Release Announcement trailer](https://www.youtube.com/watch?v=QgpDqjV9O3M&feature=emb_logo)

**Comment by Beeblerox** [comment]
- [ ] Couple of patreon posts by [Oleg Dolya](https://twitter.com/watawatabou):
    * [Perilous Shores](https://www.patreon.com/posts/40917180)
    * [Generation in Perilous Shores](https://www.patreon.com/posts/41103311)

**Comment by Beeblerox** [comment]
- [ ] [PogoGirl Devlog #4: Road to SAGE 2020](https://www.ohsat.com/post/pogogirl-devlog/post4/) by [Andrej](https://twitter.com/ohsat_games)

**Comment by Beeblerox** [comment]
- [ ] [Some great progress](https://twitter.com/austinweast/status/1300311489295921152) on the gbjam project by Austin East

**Comment by Beeblerox** [comment]
- [ ] [Spellbreak](https://twitter.com/PlaySpellbreak) by Proletariat Inc. launches on September 3, 2020 on PS4, PC, Xbox, and Switch! Watch [Official Launch Cinematic Trailer](https://www.youtube.com/watch?v=pSmvbSFUDf8&feature=emb_title)

**Comment by Beeblerox** [comment]
- [ ] [FAL](https://twitter.com/falworks/status/1300811291456544769) released "Firedancer" v0.1.0 - a Haxe based language for defining 2D shmup bullethell patterns. [See examples](https://firedancer-lang.com/)

**Comment by Beeblerox** [comment]
- [ ] [Trail debugging](https://imgur.com/a/opv9Kev) in WIP racing game by [Ed Ryzhov](https://twitter.com/ryzzed/status/1300805819290791939)

**Comment by Beeblerox** [comment]
- [ ] [Slide for Lewis Lepton's](https://twitter.com/lewislepton/status/1301107519125884928) talk for HaxeIn 2020

**Comment by Beeblerox** [comment]
- [ ] [LEd (generic 2D level editor)](https://deepnight.net/tools/led-2d-level-editor/) by Sébastien Bénard was updated to Alpha 4, with tons of fixes, polish & love. It features an auto-updater so you won't miss any future update. It's available for free with tutorials & documentation

**Comment by Beeblerox** [comment]
- [ ] [Armory Digest September 2020](https://forums.armory3d.org/t/armory-digest-september-2020/4193)

**Comment by Beeblerox** [comment]
- [ ] Lubos Lenco has released ]Armory 2020.9](https://github.com/armory3d/armory/releases/tag/20.09), [haxebullet 2020.9](https://github.com/armory3d/haxebullet/releases/tag/20.09) and [iron 2020.9](https://github.com/armory3d/iron/releases/tag/20.09)

**Comment by Beeblerox** [comment]
- [ ] [kha-sdf-painter](https://github.com/tizilogic/kha-sdf-painter) is a custom g2 extension for Kha to draw shapes using Signed distance fields

**Comment by Beeblerox** [comment]
- [ ] [Multi-texture support for 2D batch renderers (SpriteBatch, TileGroup and Graphics)](https://github.com/HeapsIO/heaps/pull/844) Pull Request by Pavel Alexandrov got merged in Heaps

**Comment by Beeblerox** [comment]
- [ ] [Kaelan Evans](https://twitter.com/kbeevans/status/1301218576238391297) is working on a wiki for [HxDoom](https://github.com/kevansevans/HxDoom/wiki/Wad-Reading-Basics), and looking for feedback

**Comment by Beeblerox** [comment]
- [ ] [Custom Actor Behaviors - RPG Playground 0.46 DevLog](https://www.youtube.com/watch?v=xUqPPS6UgF0&feature=youtu.be) by [RPG Playground](https://twitter.com/RPGplayground/status/1301207648147247106)

**Comment by Beeblerox** [comment]
- [ ] [Toy programming language](https://snekky.senkju.net/#) by Senk Ju written in Haxe

**Comment by Beeblerox** [comment]
- [ ] [LunaSense - RPGMakerMV/MZ Intellisense](https://forums.rpgmakerweb.com/index.php?threads/lunasense-rpgmakermv-mz-intellisense.126646/) by [Kino Rose](https://twitter.com/EISKino/status/1301321336669831168)

**Comment by Beeblerox** [comment]
- [ ] [Quick video](https://twitter.com/tizilogic/status/1301279806450020353) of a game made by Kha by tizilogic

**Comment by skial** [comment]
- [ ] [ActionScapeUX `git`](https://github.com/Dimensionscape/ActionScapeUX) - Graphical User Experience Framework.

**Comment by skial** [comment]
- [ ] [ProjectEuler `git`](https://github.com/davzrm/ProjectEuler) - Attempt at solving the Project Euler problems.

**Comment by skial** [comment]
- [ ] [cphl `git`](https://github.com/nevergarden/cphl) - Cairo + Pango + Hashlink: Adds Pango and Cairo functions for text rendering to Hashlink.
