### ISSUE TITLE
Haxe Roundup 549

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#804]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by deepnight** [comment]
- [ ] LEd is an open-source 2D level editor for the indie dev community [LEd 0.2](https://deepnight.net/tools/led-2d-level-editor/)

**Comment by skial** [comment]
- [ ] `[jvm]` Strange behaviour with a conditional [issue](https://github.com/HaxeFoundation/haxe/issues/9897).

**Comment by skial** [comment]
- [ ] libs
  - [uuid `2.3.0`](https://lib.haxe.org/p/uuid/)
  - [yloader `0.0.1`](https://lib.haxe.org/p/yloader/)
  - [led-haxe-api `1.0.12`](https://lib.haxe.org/p/led-haxe-api/)
  - [deepnightLibs `1.0.49`](https://lib.haxe.org/p/deepnightLibs/)
  - [nwjs `1.0.0`](https://lib.haxe.org/p/nwjs/)
  - [DomWires `1.0.0-alpha.14`](https://lib.haxe.org/p/DomWires/)
  - [extype `3.0.3`](https://lib.haxe.org/p/extype/)
  - [littleBigInt `0.1.0`](https://lib.haxe.org/p/littleBigInt/)
  - [wrenparse `0.0.3`](https://lib.haxe.org/p/wrenparse/)
  - [grig.osc `0.0.3`](https://lib.haxe.org/p/grig.osc/)
  - [munit `2.3.5`](https://lib.haxe.org/p/munit/)
  - [robotlegs `2.0.6`](https://lib.haxe.org/p/robotlegs/)
  - [echo `2.2.0`](https://lib.haxe.org/p/echo/)
  - [grig.midi `0.0.5`](https://lib.haxe.org/p/grig.midi/)

**Comment by skial** [comment]
- [ ] [hx-gcode `git`](https://github.com/helkebir/hx-gcode) - A lightweight G-code generation framework in Haxe.

**Comment by skial** [comment]
- [ ] PogoGirl [devlog `#6`](https://www.ohsat.com/post/pogogirl-devlog/post6/) Springtime is Here! by [Andrej](https://twitter.com/ohsat_games).

**Comment by skial** [comment]
- [ ] [Shiro Games](https://twitter.com/shirogames/status/1310519488132120578) has made it possible for you to upload your own custom translations for Northgard to the Steam Workshop!

**Comment by skial** [comment]
- [ ] The [Renaine](https://twitter.com/OctosoftUS/status/1309885442859302912) team is proud to announce Bees! 🐝

**Comment by skial** [comment]
- [ ] Take a listen to "Cave Theme" from [Poor Thief](https://twitter.com/beepyeahgames/status/1310697084828315648), made with Stencyl and available for Pre-order for iOS.

**Comment by skial** [comment]
- [ ] [Sinh Nguyen](https://twitter.com/ixiagames/status/1310495155770720256) previews their Defold and Haxe powered game with their newly commissioned art.

**Comment by skial** [comment]
- [ ] [1speed](https://twitter.com/robdangerous/status/1310005868432429062) has released a demo of their adventure game about ghosts and... some other stuff... onto [itch.io](https://one-speed.itch.io/croaking-hill-demo) called Croaking Hill, made with Kha. 👻

**Comment by skial** [comment]
- [ ] [openfl-jsrunner `git`](https://github.com/ixiagames/openfl-jsrunner) - Use JS codes & libraries in your native OpenFL Android apps by [Sinh Nguyen](https://twitter.com/ixiagames/status/1309919060574912517).

**Comment by skial** [comment]
- [ ] [Vsio](https://twitter.com/VsioS/status/1309877127475470336) implements UI for mouse input in stage selection for KelinKelilin.

**Comment by skial** [comment]
- [ ] [Havana24](https://twitter.com/hav24/status/1309557854320328705) has released Hop Hop Miner, their entry for the `#vimjam`, which is also their first game with procedural levels. Made in Stencyl.

**Comment by skial** [comment]
- [ ] How to display Haxe errors in the Defold console [GitHub readme](https://github.com/ixiagames/hxdefold-journey/tree/master/display-haxe-errors-in-the-defold-console) by [Sinh Nguyen](https://twitter.com/ixiagames/status/1309422926970593281).

**Comment by skial** [comment]
- [ ] The senseless death of the Death Star by [Syo](https://twitter.com/SyoPic/status/1309107846047510529) made with Heaps.

**Comment by skial** [comment]
- [ ] [three.hx `git`](https://github.com/tong/three.hx) - Haxe→Three.js type definitions by [disktree](https://twitter.com/disktree/status/1311295683865919488).

**Comment by Beeblerox** [comment]
- [ ] Matthijs Kamstra's presentation for the HaxeIn 2020 [is going good!](https://twitter.com/MatthijsKamstra/status/1309059058993975299)

**Comment by Beeblerox** [comment]
> * [ ]  The senseless death of the Death Star by [Syo](https://twitter.com/SyoPic/status/1309107846047510529) made with Heaps.

- [ ] Syo is also planning to publish the build on itch.io. The project is closed, but there will be many opportunities for customization. In particular, it is being made [using Tiled](https://twitter.com/SyoPic/status/1309130260101976071)

**Comment by Beeblerox** [comment]
- [ ] Use [nodes to control layer masks](https://twitter.com/luboslenco/status/1309133536230858755) in ArmorPaint. 
- [ ] And [painting translucency](https://twitter.com/luboslenco/status/1310951391280664577) in the upcoming ArmorPaint ray-tracing update.

**Comment by Beeblerox** [comment]
- [ ] [Bad candy](https://twitter.com/CoryAlexMartin/status/1309228219414065158) in Leapin Lads by Cory Martin

**Comment by Beeblerox** [comment]
- [ ] Screenshots and quick videos from The Grand Grimoire Chronicles by Jeffrey Driver:
    * Something different with [in-game menu](https://twitter.com/JeffreyDriver/status/1309121182071951363)
    * [Map now fully functional](https://twitter.com/JeffreyDriver/status/1310261165025624064)
    * [New map system](https://twitter.com/JeffreyDriver/status/1311058589302362121) is finally finished

**Comment by Beeblerox** [comment]
- [ ] WIP: [trees in Village Generator](https://www.patreon.com/posts/42144467) by [Oleg Dolya](https://twitter.com/watawatabou/status/1310906952713728001)

**Comment by Beeblerox** [comment]
- [ ] [Destroying the laser barriers](https://twitter.com/Rob1221dev/status/1309549368731750402) in puzzle Stencyl game by Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] The first [devlog video](https://www.youtube.com/watch?v=O5dWWEyAxNQ&feature=emb_logo) by [Dave Doublee](https://twitter.com/DaveDoublee/status/1309813356191191040) about WIP turn-based RPG game being made with Stencyl

**Comment by Beeblerox** [comment]
- [ ] [Who wants some Haxe cookies?](https://twitter.com/Onehourgamestud/status/1309874442563186690)

**Comment by Beeblerox** [comment]
- [ ] Check out [LEd video](https://www.youtube.com/watch?v=pYBWGt8wbsU) by [GameFromScratch](https://twitter.com/gamefromscratch/status/1309876278057676805)

**Comment by Beeblerox** [comment]
- [ ] [Making RPG's with RPG Playground: Q&A](https://www.youtube.com/watch?v=ZclU5QaZ1oQ) by [RPG Playground](https://twitter.com/RPGplayground/status/1309900763225829376)

**Comment by Beeblerox** [comment]
- [ ] [h2d API documentation finished, status update and wishlist box](https://ko-fi.com/post/h2d-API-documentation-finished-status-update-and-F1F02A643) by [Pavel Alexandrov](https://twitter.com/Yanrishatum)

**Comment by Beeblerox** [comment]
- [ ] Luyren Stencyl Devlog #3 - [AI Showcase](https://www.youtube.com/watch?v=dC7nI6ZsnnM&feature=youtu.be) by [Luyren](https://twitter.com/LuyrenStencyl/status/1309899257982394368)

**Comment by Beeblerox** [comment]
- [ ] Little [devlog twitter thread](https://twitter.com/mauvecow/status/1310305847050862593) by Mauve and [visual novel/adv game level ++](https://twitter.com/mauvecow/status/1310718781384060930) quick video

**Comment by Beeblerox** [comment]
- [ ] The ANNIVERSARIES update for Little Square Things by [Gregory Seed](https://twitter.com/gregorysreed/status/1310706223365447680) is [live on Steam](https://store.steampowered.com/app/945490/Little_Square_Things/)

**Comment by Beeblerox** [comment]
- [ ] [doors](https://twitter.com/zzo__x/status/1310785021939200002) transition by ty

**Comment by Beeblerox** [comment]
- [ ] [Jaming with a PS4 controller](https://twitter.com/jeremyfaivre/status/1311060874044608512) turned into a music instrument by Jérémy Fa

**Comment by Beeblerox** [comment]
- [ ] Everyone's making an ECS, so here's [another one](https://github.com/Aidan63/ecs) by Aidan Lee

**Comment by Beeblerox** [comment]
- [ ] Austin East has added [slopes and custom shapes](https://cdn.discordapp.com/attachments/162664383082790912/758769974037971065/tilemap-slopes.gif) to echo's tilemap generator

**Comment by Beeblerox** [comment]
- [ ] [LEd in Flixel](https://pastebin.com/uwFbeBu7) code sample

**Comment by Beeblerox** [comment]
- [ ] [FlxEcho.hx](https://gist.github.com/AustinEast/524db026a4fea298a0eebf19459131cc): Quick Flixel <-> Echo integration

**Comment by Beeblerox** [comment]
- [ ] Antriel created a repository [phaser3-hx](https://github.com/Antriel/phaser3-hx)

**Comment by Beeblerox** [comment]
- [ ] [𝙵𝚒𝚕𝚒𝚙𝚙𝚘 𝙱𝚘𝚍𝚎𝚒](https://twitter.com/filipp8/status/1311362331755130880) has released [GoGoSpace!](https://filipp8.itch.io/gogospace)

**Comment by Beeblerox** [comment]
- [ ] [Who brings a sheep to a gig?](https://twitter.com/jano_games/status/1311353650682494981) by JanoGames

**Comment by Beeblerox** [comment]
- [ ] [Some progress](https://twitter.com/tizilogic/status/1311449483314712577) again on In-Game UI... by tizilogic

**Comment by Beeblerox** [comment]
- [ ] [Vinnie's Tomb: Chapter One](https://github.com/reldni/vintomb_html5) is a faithful HTML5 recreation of Vinnie's Tomb, a free game created by Reldni Productions and released in 1997 for Windows 95

**Comment by Beeblerox** [comment]
- [ ] [Pavel Alexandrov](https://twitter.com/Yanrishatum) is implementing [text appearance effects](https://wb.yanrishatum.ru/i/g/acF9G.gif) for RichText from Heaps
