### ISSUE TITLE
Haxe Roundup 552

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#813]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] Local variable might be uninitialized [issue](https://github.com/HaxeFoundation/haxe/issues/9919).

**Comment by skial** [comment]
- [ ] `final var x` parses successfully in expressions [issue](https://github.com/HaxeFoundation/haxe/issues/9923).

**Comment by skial** [comment]
- [ ] `[hl]` Skip compilation if no module has been changed [merged](https://github.com/HaxeFoundation/haxe/pull/9922).

**Comment by skial** [comment]
- [ ] `[server]` Weird `ECast` count when `fatalError` occurs [issue](https://github.com/HaxeFoundation/haxe/issues/9918).

**Comment by skial** [comment]
- [ ] [PogoGirl Devlog `#7`](https://www.ohsat.com/post/pogogirl-devlog/post7/): Pogo Splash & Swim by [Ohsat Games](https://twitter.com/ohsat_games).

**Comment by skial** [comment]
- [ ] [Petit Tracteur Bleu](https://deepnight.net/games/petit-tracteur-bleu/), _"you are Little Blue Tractor and your goal is to find all the cows and bring them back home before night falls"_, by [Sébastien Bénard](http://twitter.com/deepnightfr), created for his 2 year old son. Also available on [itch.io](https://deepnight.itch.io/petit-tracteur-bleu).

**Comment by skial** [comment]
- [ ] libs
  - [colyseus `0.14.2`](https://lib.haxe.org/p/colyseus/)
  - [lex `0.10.0`](https://lib.haxe.org/p/lex/)
  - [ihx `0.4.2`](https://lib.haxe.org/p/ihx/)
  - [ase `1.1.1`](https://lib.haxe.org/p/ase/)
  - [heaps-aseprite `0.0.4`](https://lib.haxe.org/p/heaps-aseprite/)
  - [coconut.feathersui `1.0.0`](https://lib.haxe.org/p/coconut.feathersui/)
  - [vscode `1.50.1`](https://lib.haxe.org/p/vscode/)
  - [hxmpp `1.0.0-alpha.2`](https://lib.haxe.org/p/hxmpp/) :star2:

**Comment by skial** [comment]
- [ ] The Linerian Mouse Society 🐭 is getting some new decorations in [Renaine](https://twitter.com/OctosoftUS/status/1317495586850000898).

**Comment by skial** [comment]
- [ ] [Dicey Dungeons](https://twitter.com/diceydungeons/status/1317077215301885954) will be taking part in `#DigitalTabletopFest` on Steam from the 21st till the 26th of October!

**Comment by skial** [comment]
- [ ] [Jérémy Fa](https://twitter.com/jeremyfaivre/status/1318316276247351297) is just messing around with low resolution abstract visuals in his generative creative coding art, available [online](https://apps.jeremyfa.com/lowres-generative/) to try out yourself.
   - [ ] Same program, different [output](https://twitter.com/jeremyfaivre/status/1318317796548280326).
   - [ ] Still messing around at low [resolution](https://twitter.com/jeremyfaivre/status/1318322828018618368).
   - [ ] More output from the same [program](https://twitter.com/jeremyfaivre/status/1318323295733821441).
   - [ ] Same program [again](https://twitter.com/jeremyfaivre/status/1318326505005584385).
   - [ ] Different [output](https://twitter.com/jeremyfaivre/status/1318327218767015936).
   - [ ] And one last out of the same [program](https://twitter.com/jeremyfaivre/status/1318329755398295554).

**Comment by skial** [comment]
- [ ] The shock troopers, Tankers, Grenadier, Gunner, Hunter, Striker and Support from [Steel Seraph](https://twitter.com/steelseraphgame/status/1317669218654060544), who will be introduced in Act 4 on the space elevator.

**Comment by skial** [comment]
- [ ] [Jérémy Fa](https://twitter.com/jeremyfaivre/status/1317160983882878976) has made a [bunny-mark](https://apps.jeremyfa.com/bunnymark/) app for his Ceramic Engine, which doesn't reflect real usage of the tech, but still useful to compare raw performance between iteration of the code.

**Comment by skial** [comment]
- [ ] [Alex Lanzetta](https://twitter.com/Zanzlanz/status/1317157070832062466) has released [Mirror Road](https://www.youtube.com/watch?v=CJK30mzQ0-w) which Celebrates the release of "A Festival in Sand", made with Haxe, Lime and grig.midi!

**Comment by skial** [comment]
- [ ] [Luyren](https://twitter.com/LuyrenStencyl/status/1317127488171106305) is testing 8-way movement from their Stencyl AI and Combat pack.

**Comment by skial** [comment]
- [ ] [How to add collisions to our Tiled Map Editor level in HaxeFlixel](https://www.youtube.com/watch?v=h_dBcYSiiFk) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] [oto `git`](https://github.com/lewislepton/oto) - Shapes buggering you over.

**Comment by skial** [comment]
- [ ] [tankuki `git`](https://github.com/lewislepton/tanuki) - It was my pet. now its yours.

**Comment by skial** [comment]
- [ ] [haxe-markdown-openfl-textfield `git`](https://github.com/BowlerHatLLC/haxe-markdown-openfl-textfield) - A Markdown parser in Haxe, targeting the OpenFL TextField class.

**Comment by skial** [comment]
- [ ] [feathersui-coconut-samples `git`](https://github.com/BowlerHatLLC/feathersui-coconut-samples) - Sample projects using Feathers UI and Coconut.

**Comment by skial** [comment]
- [ ] [heaps-aseprite `git`](https://github.com/AustinEast/heaps-aseprite) - An Aseprite File Parser for Heaps.

**Comment by skial** [comment]
- [ ] [LunaDepotize `git`](https://github.com/LunaTechsDev/LunaDepotize) - LunaTechs Depot Haxe integration for structured data support in Haxe when working with data.

**Comment by skial** [comment]
- [ ] [Oleg Dolya](https://twitter.com/watawatabou/status/1317901492955787264) has released a new procedural generator called "Fantasy Manor" which produces top-down images of random fantasy manors, available from [itch.io](https://watabou.itch.io/fantasy-manor).

**Comment by skial** [comment]
- [ ] Angel Statue painted in Armorpaint and rendered in Blender [video](https://www.youtube.com/watch?v=ewz78ddx9_g) by [ArmoryBlender](https://twitter.com/armoryblender/status/1318220807311589377).

**Comment by Beeblerox** [comment]
> * [ ]  [Jérémy Fa](https://twitter.com/jeremyfaivre/status/1318316276247351297) is just messing around with low resolution abstract visuals in his generative creative coding art, available [online](https://apps.jeremyfa.com/lowres-generative/) to try out yourself.
>   
>   * [ ]  Same program, different [output](https://twitter.com/jeremyfaivre/status/1318317796548280326).
>   * [ ]  Still messing around at low [resolution](https://twitter.com/jeremyfaivre/status/1318322828018618368).
>   * [ ]  More output from the same [program](https://twitter.com/jeremyfaivre/status/1318323295733821441).
>   * [ ]  Same program [again](https://twitter.com/jeremyfaivre/status/1318326505005584385).
>   * [ ]  Different [output](https://twitter.com/jeremyfaivre/status/1318327218767015936).
>   * [ ]  And one last out of the same [program](https://twitter.com/jeremyfaivre/status/1318329755398295554).

- [ ] You can [try the program yourself](https://apps.jeremyfa.com/lowres-generative/) to get more outputs

**Comment by Beeblerox** [comment]
- [ ] As you may remember from previous roundup, Dan Korostelev has [shared his code](https://twitter.com/nadako/status/1316494639424245761) for image previews for typed asset access in Haxe and VS Code. And Pavel Alexandrov has [adapted it for Heaps Res](https://twitter.com/Yanrishatum/status/1316694085005082627)

**Comment by Beeblerox** [comment]
- [ ] Poor Thief! by [Tom Brinton](https://twitter.com/brintown) is out on [iOS](https://apps.apple.com/us/app/poor-thief/id1487235318) and [Android](https://play.google.com/store/apps/details?id=com.beepyeah.poorthief)

**Comment by Beeblerox** [comment]
- [ ] Copuld of quick videos from WIP puzzle game by Robert Alvarez:
    * [Lasers block the way](https://twitter.com/Rob1221dev/status/1317098495195701248), but holding down buttons can turn them off
    * [Avoiding and blocking bullets](https://twitter.com/Rob1221dev/status/1318565509428903937)

**Comment by Beeblerox** [comment]
- [ ] [Level Design in Rogue of Vallas](https://www.youtube.com/watch?v=AGAYfjXuDLA&feature=youtu.be) devlog video by [rlwatson](https://twitter.com/merrak/status/1317193744416935936)

**Comment by Beeblerox** [comment]
- [ ] [Fried Rich](https://twitter.com/ratrogue/status/1317198678239727616) has released [It rains](https://ratrogue.itch.io/it-rains) which is a small forest simulation sandbox game on itch, made with Haxe and Heaps for a Climate Change Jam

**Comment by Beeblerox** [comment]
- [ ] [100+ new secrets added to the Frog Fractions hat DLC](https://store.steampowered.com/app/1366091/Frog_Fractions_GotDE__Hops_Iconic_Cap/). via [Jim Stormdancer](https://twitter.com/mogwai_poet/status/1317155951292510209)

**Comment by Beeblerox** [comment]
- [ ] Menu in The Grand Grimoire Chronicles by Jeffrey Driver is [now 99% complete](https://twitter.com/JeffreyDriver/status/1317581439836311552)

**Comment by Beeblerox** [comment]
- [ ] [Kaelan Evans](https://twitter.com/kbeevans/status/1317708539704475648) has ported [ParticleBreaker to Haxe](https://github.com/kevansevans/HxParticleBreaker). You can [play it in browser](https://kevansevans.github.io/hxparticle/)

**Comment by Beeblerox** [comment]
- [ ] [Sheepolution](https://twitter.com/Sheepolution/status/1317496964829904897) has remade game [SNAKE SNAKE SNAKE](https://www.newgrounds.com/portal/view/768898) with HaxeFlixel so that it can now be played in browser.

**Comment by Beeblerox** [comment]
- [ ] [AI fighting each other](https://twitter.com/kennygoff/status/1317813575268827137) by Kenny Goff

**Comment by Beeblerox** [comment]
- [ ] [how it started / how it's going](https://twitter.com/mauvecow/status/1317966439723069440) by mauve

**Comment by Beeblerox** [comment]
- [ ] Dead Cells [Legacy update](https://twitter.com/Playdigious/status/1318537451141386240) is out on iOS and Android

**Comment by Beeblerox** [comment]
- [ ] [Caption this](https://twitter.com/mknol/status/1318951920426430464) by Mark Knol

**Comment by Beeblerox** [comment]
- [ ] Based on available triggers and actions, Syo can already [do a simple runner in Tiled](https://twitter.com/SyoPic/status/1318969992864538624)

**Comment by Beeblerox** [comment]
- [ ] The latest version of Nme has an experimental metal backend for iOS and mac. You can try it with `<haxedef name="nme_metal" />` in your projects. The downside is that you can't use WebGL Api with this backend. The upside is that the BunnyMark runs literally 10x faster on Hugh Sanderson's laptop, although on older iOS hardware. via [NME gitter](https://gitter.im/haxenme/nme?at=5f9015b5a7e77a0ff15ed7f9)

**Comment by Beeblerox** [comment]
- [ ] Colby Klein has made [hashlink-exts](https://github.com/shakesoda/hashlink-exts) public

**Comment by Beeblerox** [comment]
- [ ] [wrenparse](https://github.com/darmie/wrenparse) is Wren-lang parser implemented in Haxe by 'Damilare Darmie Akinlaja

**Comment by Beeblerox** [comment]
- [ ] [A game by its cover 2020 gogo space](https://andretchen.itch.io/a-game-by-its-cover-2020-gogo-space) made by andretchen with Haxe, Heaps and Deepnight's gamebase

**Comment by Beeblerox** [comment]
- [ ] [A little preview](https://twitter.com/filipp8/status/1319023252698779648) of Dungeon Pest Control by 𝙵𝚒𝚕𝚒𝚙𝚙𝚘 𝙱𝚘𝚍𝚎𝚒

**Comment by Beeblerox** [comment]
- [ ] [LunaTechsDev](https://twitter.com/LunaTechsDev/status/1319071239776907264) has released the minimal map inventory and hot key customizer for rpgmaker

**Comment by skial** [comment]
- [ ] Spellbreak - Prologue: The Gathering Storm update release notes have been [published](https://go.playspellbreak.com/blog/prologue), with the update coming to the Epic Games store, PlayStation 4, Xbox One, Nintendo Switch, and Geforce Now soon.

**Comment by skial** [comment]
- [ ] [hiss `git`](https://github.com/hissvn/hiss) - A minimal embedded Lisp for Haxe programs.

**Comment by Beeblerox** [comment]
- [ ] [source code](https://github.com/Yanrishatum/cherry-jam/tree/master/ld47) for LD47 entry game [Despairship](https://ldjam.com/events/ludum-dare/47/despairship)
