### ISSUE TITLE
Haxe Roundup 555

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#819]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] [ldtk `0.5.2-beta`](https://github.com/deepnight/ldtk/releases/tag/v0.5.2-beta) has been released.

**Comment by skial** [comment]
- [ ] `[js]` `-D analyzer-optimize` can re-order API (extern) calls which can cause a mess [issue](https://github.com/HaxeFoundation/haxe/issues/9943).

**Comment by skial** [comment]
- [ ] [snekky `0.7.0`](https://github.com/snekkylang/snekky/releases/tag/0.7.0) has been released, which adds support for REPL, ranges, basic string escaping, regexes and more!

**Comment by skial** [comment]
- [ ] `[ammer]` Lua CI [merged](https://github.com/Aurel300/ammer/pull/43).

**Comment by skial** [comment]
- [haxe-swt-playground `git`](https://github.com/davidbruce/haxe-swt-playground) - A repo for experimenting with haxe-swt.

**Comment by skial** [comment]
- [ ] [iso3166 `git`](https://github.com/kevinresol/iso3166) - ISO3166 Country Codes.

**Comment by skial** [comment]
- [ ] libs
  - [inotify `2.0.1`](https://lib.haxe.org/p/inotify/)
  - [haxe-poco `1.0.2`](https://lib.haxe.org/p/haxe-poco/)
  - [ldtk-haxe-api `0.5.1-rc.1`](https://lib.haxe.org/p/ldtk-haxe-api/)
  - [deepnightLibs `1.0.53`](https://lib.haxe.org/p/deepnightLibs/)
  - [jsasync `1.2.1`](https://lib.haxe.org/p/jsasync/)
  - [dragonbones `5.1.1`](https://lib.haxe.org/p/dragonbones/)
  - [mc2it_rte `1.0.1`](https://lib.haxe.org/p/mc2it_rte/) :star2:

**Comment by skial** [comment]
- [ ] PogoGirl Devlog `#8`: [Shader Journey](https://www.ohsat.com/post/pogogirl-devlog/post8/) by [Andrej](https://twitter.com/ohsat_games) from Ohsat Games.

**Comment by skial** [comment]
- [ ] The Moonshine `3.0.0` is the first release that [includes Feathers UI](https://twitter.com/feathersui/status/1326214679044091904) views written in Haxe.

**Comment by skial** [comment]
- [ ] Double Kick Heroes are offering the [chance to win](https://twitter.com/headbang_club/status/1325848123026108417) a Delta Headset, thanks to the ASUS ROG team and a Double Kick Heroes Steam Key! 🤘

**Comment by skial** [comment]
- [ ] Darksburg `1.0.5` has been [released](https://twitter.com/Darksburg/status/1325834097357451264) with full controllers support, curios updates, a whole new boss fight and more!

**Comment by skial** [comment]
- [ ] [Double Turn](https://twitter.com/doubleturngame) has [just released](https://store.steampowered.com/newshub/app/762680/view/2950381282548134102) version `1.0`, now available from Steam!

**Comment by skial** [comment]
- [ ] [Shiro Games](https://twitter.com/shirogames/status/1324742634636824576) are still looking for a Senior Gameplay Programmer to join their team of passionate developers in Bordeaux.

**Comment by skial** [comment]
- [ ] Its official, Northgard, by [Shiro Games](https://twitter.com/shirogames/status/1324373440032362496), is coming to mobile!

**Comment by skial** [comment]
- [ ] [Sébastien Bénard](https://twitter.com/deepnightfr/status/1325832835559788546) has posted a sneak peak of the upcoming world editor in the LDtk `0.6.0` release.

**Comment by skial** [comment]
- [ ] [Vsio](https://twitter.com/VsioS/status/1325061279908728832) has posted a post mortem of Loop Heart, an LD47 game made with HaxeFlixel.

**Comment by skial** [comment]
- [ ] The [President of Space](https://twitter.com/matzieq/status/1325045335048114177) has made a new tileset for the obligatory lava level in Caverns of Ksantarus. Expect an assortment of burning floors, fireballs and flamethrowers! 🔥 An indie game made with HaxeFlixel.

**Comment by skial** [comment]
- [ ] [Steel Seraph](https://twitter.com/steelseraphgame/status/1326165089062440960) has been updated to `1.9.0` for Windows, Linux and Mac.

**Comment by skial** [comment]
- [ ] [Miels](https://twitter.com/mielsmiels/status/1325059029022855170) is creating a game for the `#GameOff2020` jam using HaxeFlixel.

**Comment by skial** [comment]
- [ ] [Merrak](https://twitter.com/merrak/status/1324951559571173377) has posted Rogue of Vallas Devlog `#4`: Persistence and Style bonuses [video](https://www.youtube.com/watch?v=5NM02ufazv0), a game made in Stencyl.

**Comment by Beeblerox** [comment]
- [ ] [Dicey Dungeons v1.10 out now!](https://store.steampowered.com/newshub/app/861540/view/2933493419297354415) Featuring our new Catalan translation, plus lots of little bug fixes and optimisations!

**Comment by Beeblerox** [comment]
- [ ] [hx-neutralino-lite](https://github.com/MatthijsKamstra/hx-neutralino-lite) by [Matthijs Kamstra](https://twitter.com/MatthijsKamstra/status/1324454634673623044)

**Comment by Beeblerox** [comment]
- [ ] [LDtk The Level Designer Toolkit](https://gamefromscratch.com/ldtk-the-level-designer-toolkit/) article and video by [Game From Scratch](https://twitter.com/gamefromscratch/status/1324779940865286145)

**Comment by Beeblerox** [comment]
- [ ] Benny Heller is [working the night shift](https://twitter.com/e1sif/status/1325193321484963840)

**Comment by Beeblerox** [comment]
- [ ] [Snappy Sloth](https://twitter.com/Snappy_Sloth/status/1323310149944049664) are working on the game for GitHub Game Off game jam and using Heaps for it. [Mat' "Tipyx" PISTOL](https://twitter.com/Tipyx_FR) is streaming his daily work on the game [on twitch](https://www.twitch.tv/tipyx_fr)

**Comment by Beeblerox** [comment]
- [ ] [Congrats to Will Blanton](https://twitter.com/devolverdigital/status/1325827875518476291) on winning the DiscRoomGameJam with [DISC WHEEL](https://01010111.itch.io/discwheel)!

**Comment by Beeblerox** [comment]
- [ ] Robert Alvarez [started a new game](https://twitter.com/Rob1221dev/status/1325818077607579648) where you step on tiles to change the active spell

**Comment by Beeblerox** [comment]
- [ ] Squidly has [shared progress](https://twitter.com/squuuidly/status/1326348731076186113) of a couple small enemies in Renaine

**Comment by Beeblerox** [comment]
- [ ] CrossCode is now [out for Xbox Series X](https://twitter.com/robdangerous/status/1326184091516014593)! Witness pixelart in glorious sharp 4k and fluid 120fps! Powered by Kha

**Comment by Beeblerox** [comment]
- [ ] [WIP platformer game](https://cdn.discordapp.com/attachments/774020763149271062/775876225032912927/platpeng.gif) which is being made with Kha by Xano from Kha discord server

**Comment by Beeblerox** [comment]
- [ ] [dracula 9000x](https://www.youtube.com/watch?v=lARIZa2i_A8) by [Joaquin Bello](https://twitter.com/JoaquinBelloD). The game is being made with Kha. Most of the gameplay is done, need to add more art and add more effects. Here is [the version with infinite jumps](https://www.newgrounds.com/portal/view/770331)

**Comment by Beeblerox** [comment]
- [ ] Some helper classes for OpenFL [zerolib-openfl](https://github.com/01010111/zerolib-openfl) by Will Blanton

**Comment by Beeblerox** [comment]
- [ ] [Pixel-Perfect 2D Water Shader](https://www.ohsat.com/tutorial/flixel/pixel-perfect-water-shader/) in HaxeFlixel tutorial by [Andrej](https://twitter.com/ohsat_games/status/1326608886657409029)

**Comment by Beeblerox** [comment]
- [ ] [The new logic node editor](https://twitter.com/armoryblender/status/1326619189696671746) in Armory3D. via ArmoryBlender

**Comment by skial** [comment]
- [ ] How to format FlxText and change fonts globally in Haxeflixel [video](https://www.youtube.com/watch?v=yQeBUvk8O-o) by Richard Oliver Bray.

**Comment by skial** [comment]
- [zsparticle `git`](https://github.com/rainyt/zsparticle) - Sparticle HAXE for Away3D project.

**Comment by skial** [comment]
- [ ] [smartfox-android `git`](https://github.com/uwongke/smartfox-android) - Externs for smartfox Android.

**Comment by skial** [comment]
- [ ] [GmxGen `git`](https://github.com/YAL-GameMaker-Tools/GmxGen) - Updates GameMaker extensions with function/macro definitions and documentation extracted from source files.

**Comment by skial** [comment]
- [ ] [similitude `git`](https://github.com/theodore-norvell/similitude) - A web-based digital logic simulator.

**Comment by skial** [comment]
- [ ] [Foundry2D `git`](https://github.com/foundry2D/foundry2d) - Data-oriented and data-driven 2D Game engine built on Kha with a built in editor.

**Comment by skial** [comment]
- [ ] Pixel Perfect 2D Water Shader [tutorial](https://www.ohsat.com/tutorial/flixel/pixel-perfect-water-shader/) used in Go! Go! PogoGirl by [Andrej](https://twitter.com/ohsat_games) from Ohsat Games.

**Comment by davidbruce** [comment]
>     * [x]  [haxe-swt-playground `git`](https://github.com/davidbruce/haxe-swt-playground) - A repo for experimenting with haxe-swt.

I was reading the roundup and saw my repo.  I'm curious how you stumbled upon it.   Thanks either way!

**Comment by skial** [comment]
@davidbruce I found it while browsing the recently updated [Haxe repos](https://github.com/search?o=desc&p=3&q=created%3A%22%3E+2020-11-05%22+language%3AHaxe&s=updated&type=Repositories) on GitHub. 👍

**Comment by davidbruce** [comment]
Neat, I had no idea that was a feature of Github.  Thanks for getting back to me. :)
