### ISSUE TITLE
Haxe Roundup 557

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#823]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by Cleod9** [comment]
- [ ] [McLeodGaming](https://twitter.com/McLeodGaming/status/1330725252087779331) discusses their OpenFL-powered homebrew editor [FrayTools](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3028934?utm_source=haxe&utm_medium=other&utm_campaign=fmksbegin&ref=cpk5lz) for their upcoming Heaps-based game, Fraymakers.

**Comment by skial** [comment]
- [ ] HxDoom `0.0.7-Alpha` has been [released](https://github.com/kevansevans/HxDoom/releases/tag/0.0.7A).

**Comment by skial** [comment]
- [ ] `[evolution]` Null coalescing operator [proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/85).

**Comment by skial** [comment]
- [ ] Abstract type cannot modify itself with `--no-inline` [issue](https://github.com/HaxeFoundation/haxe/issues/9960).

**Comment by skial** [comment]
- [ ] Algebra math implementation in Game Engine [community](https://community.haxe.org/t/algebra-math-implementation-in-game-engine/2779) question.

**Comment by skial** [comment]
- [ ] `[ceramic]` Unity [backend](https://github.com/ceramic-engine/ceramic/issues/42).

**Comment by skial** [comment]
- [ ] Variable / Rest arguments [pull request](https://github.com/HaxeFoundation/haxe/pull/9961). - This implements rest arguments as an abstract over targets native corresponding features.

**Comment by skial** [comment]
- [ ] `[evolution]` Enum abstract instances [proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/86).

**Comment by skial** [comment]
- [ ] [HaxeFlixel Tutorials!](https://www.ohsat.com/post/haxeflixel-tutorials/) by [Andrej](https://twitter.com/ohsat_games) from Ohsat Games.

**Comment by skial** [comment]
- [ ] _Oh yeah, it's all coming together_ 🔪🐦 via [Renaine](https://twitter.com/OctosoftUS/status/1330249546199392258).

**Comment by Beeblerox** [comment]
- [ ] CrossCode is in early access on [Amazon Luna](https://twitter.com/robdangerous/status/1327309769833648128)

**Comment by Beeblerox** [comment]
- [ ] [Shiro Games](https://twitter.com/shirogames/status/1329416523937615874) are working on new unannounced project and they are looking for a Senior Game Designer

**Comment by skial** [comment]
- [ ] [Ludovic Bas](https://twitter.com/loudoweb/status/1330873197848383488) has ported the Flash Starling particle editor to HTML5 with OpenFL.

**Comment by Beeblerox** [comment]
- [ ] New screenshots from WIP GitHubGameOff entry by Snappy Sloth:
    * [A first look](https://twitter.com/Snappy_Sloth/status/1329469488153174023) at the module screen
    * [More modules](https://twitter.com/Snappy_Sloth/status/1330974602495995912) have been drawn

**Comment by skial** [comment]
- [ ] The [President of Space](https://twitter.com/matzieq/status/1330240697572659200) has added a new font, tests bubbles and tutorial messages in Caverns of Ksantarus, a metroidvania game made with HaxeFlixel.

**Comment by skial** [comment]
- [ ] Getting started with Cocos Creator and Pony guide by [AxG](https://twitter.com/axgord/status/1330207950179332096).

**Comment by Beeblerox** [comment]
- [ ] [ninja_muffin99](https://twitter.com/ninja_muffin99/status/1329765585278832641) been busy these past few weeks, and released Friday Night Funkin 0.2.2 update

**Comment by skial** [comment]
- [ ] [Kino Rose](https://twitter.com/EISKino/status/1329987945760129024) has [published](https://kinocreates.io/development-blog/why-i-use-haxe-as-my-language-of-choice/) "Why I Use Haxe As My Language of Choice".

**Comment by Beeblerox** [comment]
- [ ] [Village Generator 1.2.3](https://www.patreon.com/posts/44111493): new trees, SVG export by [Oleg Dolya](https://twitter.com/watawatabou/status/1329817482975121409)

**Comment by skial** [comment]
- [ ] libs
  - [dropecho.langgen `0.6.1`](https://lib.haxe.org/p/dropecho.langgen/)
  - [HxDoom `0.8.3`](https://lib.haxe.org/p/HxDoom/)
  - [dropecho.storygen `0.8.2`](https://lib.haxe.org/p/dropecho.storygen/)
  - [fast-xml-parser `3.0.0`](https://lib.haxe.org/p/fast-xml-parser/)
  - [fuse `0.1.5`](https://lib.haxe.org/p/fuse/)
  - [pony `1.3.2`](https://lib.haxe.org/p/pony/)
  - [hcc `2.0.3`](https://lib.haxe.org/p/hcc/)

**Comment by Beeblerox** [comment]
- [ ] [A very nice lady](https://twitter.com/mauvecow/status/1330062054821154819) from WIP game by mauve

**Comment by skial** [comment]
- [ ] [DDOM `git`](https://github.com/aartzrc/DDOM) - Agnostic data access. DDOM uses selectors to access data in an agnostic way. It is similar to DOM/CSS/JQuery selectors, but has some unique aspects due to how data can be managed and the potentially circular nature of data references.

**Comment by skial** [comment]
- [ ] [DDOM-DB `git`](https://github.com/aartzrc/DDOM-DB) - DDOM database access helpers.

**Comment by skial** [comment]
- [ ] [DrakoSpace `git`](https://github.com/TripleSmevenGames/DrakoSpace) - A rouge-like game.

**Comment by skial** [comment]
- [ ] [peote-layout `git`](https://github.com/maitag/peote-layout) - Nested layout containers in Haxe based on Jasper library.

**Comment by Beeblerox** [comment]
- [ ] [These doors open](https://twitter.com/Rob1221dev/status/1330939862657228802) only when a certain number of enemies are killed in the WIP puzzle game by Robert Alvarez

**Comment by skial** [comment]
- [ ] [HaxeDOM `git`](https://github.com/VolkovRA/HaxeDOM) - A tiny Haxe framework for working with the DOM API.

**Comment by Beeblerox** [comment]
- [ ] [Tom Brinton](https://twitter.com/brintown/status/1331056300269076481) is working on some new levels for Poor Thief! (made with Stencyl)

**Comment by skial** [comment]
- [ ] [haxe-lwjgl `git`](https://github.com/davidbruce/haxe-lwjgl) - Helper library for using LWJGL with the Haxe JVM target.

**Comment by skial** [comment]
- [ ] [ola `git`](https://github.com/ProRpProjectejejehehe/ola) - Synchronized video viewing with chat and other features. Lightweight modern implementation and very easy way to run locally.

**Comment by skial** [comment]
- [ ] [bson `git`](https://github.com/kevinresol/bson) - Pure Haxe implementation of the BSON spec.

**Comment by skial** [comment]
- [ ] [WikiAdventure `git`](https://github.com/Sacramentix/WikiAdventure) - A multiplayer browser game with Wikipedia API. Challenge your friend and be the first to go from one page to another. Made with Haxe and HxNodeJS.

**Comment by Beeblerox** [comment]
- [ ] [Daniel Blaker](https://github.com/5Mixer) is working on  little Minecraft-like thing with Kha and Haxe:
    * The first (incorrectly lit) [dirt house](https://cdn.discordapp.com/attachments/774020763149271062/780705543068450906/unknown.png) was made
    * [Work on ambient occlusion](https://cdn.discordapp.com/attachments/162664383082790912/780772306703745074/unknown.png)

**Comment by Beeblerox** [comment]
- [ ] A small [cheat-sheet on HXSL shaders](https://gist.github.com/Yanrishatum/6eb2f6de05fc951599d5afccfab8d0a9) by Pavel Alexandrov

**Comment by skial** [comment]
- [ ] [setup-dart `git`](https://github.com/cedx/setup-dart) - Set up your GitHub Actions workflow with a specific version of the Dart SDK.

**Comment by Beeblerox** [comment]
- [ ] [Simple platformer prototype](https://kiwwisk.github.io/simple-haxe-platformer/) by [Andrej Kesely](https://github.com/kiwwisk) made using Haxe and Heaps.io

**Comment by skial** [comment]
- [ ] [whiplash `git`](https://github.com/firefalcom/whiplash) - HTML5 game framework combining Haxe, Phaser, Babylon.js and Ash.

**Comment by Beeblerox** [comment]
- [ ] [Jérémy Fa](https://twitter.com/jeremyfaivre) is almost feature complete regarding handling graphics for Ceramic engine using Unity as backend. [In the GIF](https://cdn.discordapp.com/attachments/162664383082790912/779852334997962792/unity-bunnymark.gif) you can Bunnymark test running within the editor.

**Comment by skial** [comment]
- [ ] [cavegen `git`](https://github.com/miltoncandelero/cavegen) - A Cave Generator based on Cellular Automata​.

**Comment by skial** [comment]
- [ ] [hsluv `git`](https://github.com/hsluv/hsluv) - Human-friendly HSL, reference implementation.

**Comment by skial** [comment]
- [ ] Rogue of Vallas Devlog `#6`: State Governance [video](https://www.youtube.com/watch?v=206G8Ol4AUA) by [Merrak](https://twitter.com/merrak/status/1329666198410289153).

**Comment by skial** [comment]
- [ ] How to use FlxSubState to create a level complete screen in HaxeFlixel [video](https://www.youtube.com/watch?v=86mR84jmZ9s) by Richard Oliver Bray.

**Comment by Beeblerox** [comment]
- [ ] [The Clan of the Dragon](https://twitter.com/shirogames/status/1331597257733517317) from Northgard is now available on Nintendo Switch and Xbox One, and will be released on Playstation 4 a bit later

**Comment by Beeblerox** [comment]
- [ ] [haxeflixel-snake](https://harpwood.itch.io/haxeflixel-snake?password=pass) prototype made by [Harpwood](https://twitter.com/GeorgeHarpwood/status/1331608307451240457). With the source code available [at github](https://github.com/harpwood/HaxeFlixel---Snake-Game)

**Comment by Beeblerox** [comment]
- [ ] A platformer, a hard to reach collectible and a HUD that keeps track of them. [You know how this goes](https://twitter.com/ohsat_games/status/1331675782733844489), right? from Go! Go! PogoGirl by Andrej

**Comment by Beeblerox** [comment]
- [ ] [Floor and ceiling triangulation](https://twitter.com/kbeevans/status/1331674340270563328) is almost done for Kealan Evens' Doom engine

**Comment by Beeblerox** [comment]
- [ ] [Fraymakers are going great](https://twitter.com/McLeodGaming/status/1331794655638274048) with their Kickstarter campaign! The next stretch goal is a full metal alternate soundtrack

**Comment by Beeblerox** [comment]
- [ ] Arachnowopunk by [Benny Heller](https://twitter.com/e1sif) is now [free on Android](https://play.google.com/store/apps/details?id=com.arachnowopunk.revolution). Here are also couple of new GIFs from the game:
    * [block-pushing puzzle meets infinite-runner](https://twitter.com/e1sif/status/1330173536569352200)
    * [hat shop!](https://twitter.com/e1sif/status/1331675319430950915)

**Comment by skial** [comment]
- [ ] [Ian Harrigan](https://twitter.com/IanHarrigan1982/status/1331888580889894919) has made some small but [nice additions](https://community.haxeui.org/t/dynamic-tableview/299/6?u=skial) to HaxeUI's tables to make working with dynamic data and variable item renderers more pleasant!

**Comment by 5Mixer** [comment]
>     * [x]  [Daniel Blaker](https://github.com/5Mixer) is working on  little Minecraft-like thing with Kha and Haxe:
>       
>       * The first (incorrectly lit) [dirt house](https://cdn.discordapp.com/attachments/774020763149271062/780705543068450906/unknown.png) was made
>       * [Work on ambient occlusion](https://cdn.discordapp.com/attachments/162664383082790912/780772306703745074/unknown.png)
Hello, thanks for roundup work & feature. Just a heads up that this voxel engine is open source (MIT). https://github.com/5Mixer/voxel

**Comment by skial** [comment]
Thanks @5Mixer, just moved it from closed source to open source 👍
