### ISSUE TITLE
Haxe Roundup 558

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#826]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] In array comprehensions, empty objects match any structure [issue](https://github.com/HaxeFoundation/haxe/issues/9971).

**Comment by skial** [comment]
- `[haxeparser]` Add `StringLiteralKind` values to string consts [merged](https://github.com/Simn/haxeparser/pull/57).

**Comment by skial** [comment]
- [ ] [ldtk `0.6.0`](https://github.com/deepnight/ldtk/releases/tag/v0.6.0) "Take over the world!" edition, has been released.

**Comment by skial** [comment]
- [ ] `[eval]` Max input for `Std.random` [fixed](https://github.com/HaxeFoundation/haxe/issues/9974).

**Comment by skial** [comment]
- [ ] `Float64Array` actually use 64bit floats [pull request](https://github.com/HaxeFoundation/haxe/pull/9972).

**Comment by skial** [comment]
- [ ] [haxebullet `2020.12`](https://github.com/armory3d/haxebullet/releases/tag/20.12) has been released.
- [ ] [iron `2020.12`](https://github.com/armory3d/iron/releases/tag/20.12) has been released.
- [ ] [zui `2020.12`](https://github.com/armory3d/zui/releases/tag/20.12) has been released.
- [ ] [armory `2020.12`](https://github.com/armory3d/armory/releases/tag/20.12) has been released.

**Comment by skial** [comment]
- [ ] `isInt64` is true for `Int` value on cpp [issue](https://github.com/HaxeFoundation/haxe/issues/9976).

**Comment by skial** [comment]
- [ ] libs
  - [ldtk-haxe-api `06.0-rc.1`](https://lib.haxe.org/p/ldtk-haxe-api/)

**Comment by skial** [comment]
- [ ] [hxnodejs-stream-json `git`](https://github.com/proletariatgames/hxnodejs-stream-json) - Haxe/hxnodejs externs for the stream-json npm library.

**Comment by skial** [comment]
- [ ] [hxnodejs-stream-chain `git`](https://github.com/proletariatgames/hxnodejs-stream-chain) - Haxe/hxnodejs externs for the stream-chain npm library.

**Comment by skial** [comment]
- [ ] [promisehx `git`](https://github.com/Dimous/promisehx) - Simple promises implementation for Haxe ported from [promise.ts](https://github.com/BabylonJS/Babylon.js/blob/master/src/Misc/promise.ts).

**Comment by skial** [comment]
- [ ] [Luna-social-system `git`](https://github.com/LunaTechsDev/Luna-social-system) - An RPGMakerMV/MZ plugin that creates a social system within your game.

**Comment by skial** [comment]
- [ ] [tixy-haxe `git`](https://github.com/mfoda/tixy-haxe) - A t.i.x.y Haxe clone.

**Comment by skial** [comment]
- [ ] [Luna-rogue-engine `git`](https://github.com/LunaTechsDev/Luna-rogue-engine) - An RPGMakerMV/MZ plugin that adds Rogue-Like elements to your game.

**Comment by skial** [comment]
- [ ] Linking states/levels together in HaxeFlixel - Part 1 [video](https://www.youtube.com/watch?v=nDfXeVMbRjA) by Richard Oliver Bray.
- [ ] Linking states/levels together in Haxeflixel - Part 2 [video](https://www.youtube.com/watch?v=vgTXmAmL-mk) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] Content Spotlight `#7`: Rockman and Lea Kickstarter [article](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3036887?utm_source=mgtwit&utm_medium=social&utm_campaign=fmksbegin&ref=ztw48b) from [McLeadGaming](https://twitter.com/McLeodGaming/status/1333511683654914048).

**Comment by skial** [comment]
- [ ] PogoGirl Devlog `#9`: Making Enemies [article](https://www.ohsat.com/post/pogogirl-devlog/post9/) by [Andrej](https://twitter.com/ohsat_games/status/1333746418272579585) from Ohsat Games.

**Comment by skial** [comment]
- [ ] The Clan of the Dragon, plus the latest console updates for Northgard, by [Shiro Games](https://twitter.com/shirogames/status/1334097772627243009), are now officially available on the Nintendo Switch, Xbox One and PS4.

**Comment by skial** [comment]
- [ ] [Dicey Dungeons](https://twitter.com/diceydungeons/status/1333951045995687940) and Darksburg are part of this year's [Jingle Jam Charity Bundle](https://jinglejam.tiltify.com/) with 100% of the proceeds going to charity!

**Comment by skial** [comment]
- [ ] Use the stun bombs from the Surprise Roll emblem to flash your enemies in [Renaine](https://twitter.com/OctosoftUS/status/1332812094803152900)!

**Comment by skial** [comment]
- [ ] [Fire Falcom](https://twitter.com/FireFalcom/status/1333869049743290373) have released their entry for the `#GithubGameOff` jam, called [MoonLander](https://firefalcom.itch.io/moonlander).

**Comment by skial** [comment]
- [ ] In level 5 of Stage Dive by [Jano Games](https://twitter.com/jano_games/status/1333867872041496579), you got to hit fans with the t-shirt cannon! Made with Stencyl.

**Comment by skial** [comment]
- [ ] [Robert Alvarez](https://twitter.com/Rob1221dev/status/1333852479122010113) has released his newest puzzle game, Elemental Tiles, available on [itch.io](https://rob1221.itch.io/elemental-tiles) and [Newgrounds](https://www.newgrounds.com/portal/view/773193).

**Comment by skial** [comment]
- [ ] [Ty](https://twitter.com/zzo__x/status/1333805442187849728) has released their entry for the `#GitHubGameOff` jam, created with HaxeFlixel, called [Nite](https://zzox.itch.io/nite).

**Comment by skial** [comment]
- [ ] [Mark Knol](https://twitter.com/mknol/status/1333701121290932224) from [MediaMonks](https://twitter.com/MediaMonks/) has released [Cable Detective](https://reinvent.awsevents.com/play/cable-detective/), a point and click adventure game, to celebrate this years AWS `re:Invent` virtual conference!

**Comment by skial** [comment]
- [ ] [Kino Rose](https://twitter.com/EISKino/status/1333568082854350848) has published [Haxe Builds files & Compilation](https://kinocreates.io/tutorials/programming/haxe-build-files-compilation/), a quick look at an example Haxe Build file that they use for their plugins and games.

**Comment by skial** [comment]
- [ ] [Havana24](https://twitter.com/hav24/status/1333502263000784896) has released [Relic Splatter](https://havana24.itch.io/relic-splatter) for the `#WebMonetization` jam. Made with Stencyl.

**Comment by skial** [comment]
- [ ] [Jeremy Fa](https://twitter.com/jeremyfaivre/status/1332806848060256260) shows off exporting a LD46 game created with Ceramic, exported for and running inside Unity!

**Comment by skial** [comment]
- [ ] [Vsio](https://twitter.com/VsioS/status/1332728668691386368) shows off another level with arrow gimmicks in Loop Heart, made with HaxeFlixel.

**Comment by skial** [comment]
- [ ] [Jeremy Meltingtallow](https://twitter.com/Meltingtallow/status/1332414880435998720) is spending their quarantine holiday on a renoise tool for the Akai Fire, focusing on sequencing and made with Haxe.

**Comment by skial** [comment]
- [ ] Alexander has published [Новости из вселенной Haxe](https://habr.com/en/post/530716/), a transcript of Aleksandr Kuzmenko's talk given at HaxeIn 2020. via [Haxe.ru](https://twitter.com/haxe_ru/status/1333692994013294592).

**Comment by skial** [comment]
- [ ] [Samir Sabri](https://twitter.com/hopewise/status/1333131777045655553) has published [Normalized Waveforms](https://dcaclab.com/en/experiments/19479-normalized-waveforms) over on DCACLab.

**Comment by skial** [comment]
- [ ] [LeHaine](https://twitter.com/_lehaine/status/1332868815584169985) has finished their first game jam with `#GitHubGameOff` by releasing [Moon Liberator](https://lehaine.itch.io/moonshot-liberator).

**Comment by Beeblerox** [comment]
- [ ] [WIP texture test](http://plnkr.co/plunk/AB4PXu59tLAHjAif) by [Nanjizal](https://twitter.com/Nanjizal_net/status/1332005550293475331)

**Comment by Beeblerox** [comment]
- [ ] [Snappy Sloth](https://twitter.com/Snappy_Sloth/status/1333891736045760519) have released their entry for the #GitHubGameOff jam, called ["Are you there?"](https://snappysloth.itch.io/are-you-there)

**Comment by Beeblerox** [comment]
- [ ] [Test/dev stream](https://www.twitch.tv/videos/816684497) of puzzle game by [mauve](https://twitter.com/mauvecow). Thanks to this stream he has [fixed a dozen bugs](https://twitter.com/mauvecow/status/1332246910455873537), a couple of which were actually critical.

**Comment by Beeblerox** [comment]
- [ ] [ArmorPaint. Concept. New Mask system interface](https://www.youtube.com/watch?v=4p0XrL5jaMw&feature=emb_logo) video by [Alexandr Kiryanov](https://twitter.com/AlexandrKiryan3/status/1332278470811021312)

**Comment by Beeblerox** [comment]
- [ ] [Perilous Shores 1.1.0](https://www.patreon.com/posts/44405211): legend, visual & UI improvements by [Oleg Dolya](https://twitter.com/watawatabou/status/1332747098102566915)

**Comment by Beeblerox** [comment]
- [ ] [Steel Seraph](https://twitter.com/steelseraphgame/status/1332853634883858432) is in the middle of the final update

**Comment by Beeblerox** [comment]
- [ ] An article about [level creation in Armory3D](https://habr.com/ru/post/530484/) (in Russian)

**Comment by Beeblerox** [comment]
- [ ] Motion Twin has [announced new DLC for Dead Cells](https://twitter.com/motiontwin/status/1333819560852660224) called "Fatal Falls". You could [wishlist it on Steam](https://store.steampowered.com/app/1451460/Dead_Cells_Fatal_Falls/)

**Comment by Beeblerox** [comment]
- [ ] [Demo Armory3D learning website](https://armoryblender.netlify.app/) by [ArmoryBlender](https://twitter.com/armoryblender/status/1334148022763196424). Please share your suggestions for possible improvements

**Comment by Beeblerox** [comment]
- [ ] [Armory Digest - December 2020](https://forums.armory3d.org/t/armory-digest-december-2020/4376)

**Comment by Beeblerox** [comment]
- [ ] LDtk by [Sébastien Bénard](https://twitter.com/deepnightfr) now has an [official shiny website](https://ldtk.io/)

**Comment by Beeblerox** [comment]
- [ ] [Orbeetles](https://5evergames.itch.io/orbeetles) is another #GitHubGameOff jam entry 9made with OpenFL)

**Comment by Beeblerox** [comment]
- [ ] [New game by ustance incoming](https://cdn.discordapp.com/attachments/774020763149271062/782676273885216848/unknown.png). #YesWeKha
