### ISSUE TITLE
Haxe Roundup 559

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#828]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] Operator overloading – wrong function used _(definition order-dependent)_ [issue](https://github.com/HaxeFoundation/haxe/issues/9980).

**Comment by skial** [comment]
- [ ] [LDTk `0.6.1`](https://github.com/deepnight/ldtk/releases/tag/v0.6.1) has been released.

**Comment by skial** [comment]
- [ ] Support overloading `is` operator in abstract types [pull request](https://github.com/HaxeFoundation/haxe/pull/9988).

**Comment by skial** [comment]
- [ ] Array type inference with local function [issue](https://github.com/HaxeFoundation/haxe/issues/9987).

**Comment by skial** [comment]
- [ ] Feathers UI `1.0.0-beta.2` [pre-release](https://github.com/BowlerHatLLC/feathersui-openfl/releases/tag/v1.0.0-beta.2) for Haxe and OpenFL is now available.

**Comment by skial** [comment]
- [ ] libs
  - [feathersui `1.0.0-beta.2`](https://lib.haxe.org/p/feathersui/)
  - [gitea `0.2.2`](https://lib.haxe.org/p/gitea/)
  - [pony `1.3.4`](https://lib.haxe.org/p/pony/)

**Comment by skial** [comment]
- [ ] Adding music and sound effects to a game in HaxeFlixel [video](https://www.youtube.com/watch?v=qR1OntJJVKk) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] [vanGraph `git`](https://github.com/OmegaTheManiac/vanGraph) - A graph theory based visualizer for the Haxe programming language.

**Comment by skial** [comment]
- [ ] [haxe-rename `git`](https://github.com/HaxeCheckstyle/haxe-rename) - A code renaming tool for Haxe.

**Comment by skial** [comment]
- [ ] [TheDandyLion `git`](https://github.com/OmegaTheManiac/TheDandyLion) - An opensource wellness app written in Haxe.

**Comment by skial** [comment]
- [ ] [HxLox `git`](https://github.com/UnholySheep/HxLox) - Haxe implementation of [A Tree-Walk Interpreter](http://craftinginterpreters.com/a-tree-walk-interpreter.html).

**Comment by skial** [comment]
- [ ] [QueueManagementSystem `git`](https://github.com/AxGord/QueueManagementSystem) - Queue Management System - Pony Web Example.

**Comment by skial** [comment]
- [ ] [FastifyExterns `git`](https://github.com/omnicells/FastifyExterns) - Fastify externs for Haxe usage.

**Comment by skial** [comment]
- [ ] [Luna-shooter-engine `git`](https://github.com/LunaTechsDev/Luna-shooter-engine)

**Comment by skial** [comment]
- [ ] [MongoDBExterns `git`](https://github.com/omnicells/MongoDBExterns) - Haxe externs for MongoDB.

**Comment by skial** [comment]
- [ ] The first Kickstarter backer created chompy is in [Renaine](https://twitter.com/OctosoftUS/status/1335320539020214272)!

**Comment by skial** [comment]
- [ ] Haxe conditional compilation saves the day [article](https://kinocreates.io/tutorials/programming/haxe-conditional-compilation-saves-the-day/) by [Kino Rose](https://twitter.com/EISKino/status/1336082073589846016).

**Comment by skial** [comment]
- [ ] [Nanjizal](https://twitter.com/Nanjizal_net/status/1335039818531827713) has shared a WebGL, Texture and vectors demo using HaxeUI for controls.

**Comment by skial** [comment]
- [ ] [Anders Nissen](https://twitter.com/andershnissen/status/1334960708602179588) has a small interpreted stack machine made in [Cosy`git`](https://github.com/anissen/cosy), his interpreted language, run in the eval target of Haxe.

**Comment by skial** [comment]
- [ ] Rogue of Vallas Devlog 7: "Quality of Life" Updates [video](https://www.youtube.com/watch?v=Li1951NT7hE) by [Merrak](https://twitter.com/merrak/status/1334969683058044929).

**Comment by skial** [comment]
- [ ] [Joel](https://twitter.com/joelgervasi/status/1334929708086136832) shares a snippet of combat, testing to see how ruthless enemies should be.

**Comment by skial** [comment]
- [ ] [Fraymakers](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3045495) have passed $200k, on their way to funding the Nintendo Switch port! In the meantime check out [Content Spotlight `#8` - Fancy Pants Man](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3040774) and [Content Spotlight `#9` - Octodad](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3043019).

**Comment by skial** [comment]
This roundup will be the last one for 2020, with the next one _planned_ for 7th January.

**Comment by Beeblerox** [comment]
- [ ] Use [decals as a brush mask](https://twitter.com/luboslenco/status/1334501334083637248) in the latest ArmorPaint builds

**Comment by Beeblerox** [comment]
- [ ] Dead Cells [surpasses 3.5 million sold](https://www.gamasutra.com/view/news/374624/Dead_Cells_surpasses_35_million_sold_ahead_of_second_DLC_announce.php) ahead of second DLC announce

**Comment by Beeblerox** [comment]
- [ ] [Another WIP update](https://aeveis.tumblr.com/post/636507019232395265/another-wip-update-for-curlys-chase-from-ludum) for Curly’s Chase from ludum dare 47 by [Dan Lin ](https://twitter.com/aeveis/status/1334566502004125700)

**Comment by Beeblerox** [comment]
- [ ] [Ship docking](https://twitter.com/SyoPic/status/1334888440941457410) in Jitter Sandbox by Syo

**Comment by Beeblerox** [comment]
> * [ ]  [Anders Nissen](https://twitter.com/andershnissen/status/1334960708602179588) has a small interpreted stack machine made in [Cosy`git`](https://github.com/anissen/cosy), his interpreted language, run in the eval target of Haxe.

- [ ] His [cat's being cozy](https://twitter.com/andershnissen/status/1334957823403433984) while he hack away at the bytecode generator for Cosy

**Comment by Beeblerox** [comment]
- [ ] [Spellbreak is coming to Steam](https://twitter.com/PlaySpellbreak/status/1335313053559246849)

**Comment by Beeblerox** [comment]
- [ ] Time it right, and you can [use enemies to save time](https://twitter.com/ohsat_games/status/1335324585106018308) and bypass platforming sections in Go! Go! PogoGirl by Andrej

**Comment by Beeblerox** [comment]
- [ ] New FlashDevelop features by [SlavaRa](https://twitter.com/Slava_Ra):
    * [improved support for `Import with alias`](https://www.patreon.com/posts/flashdevelop-5-3-44707337?utm_medium=social&utm_source=twitter&utm_campaign=postshare) code completion
    * [Improved behavior of code completion](https://github.com/fdorg/flashdevelop/issues/3120)
    * [Added completion after `return`, `case`, etc](https://www.patreon.com/posts/flashdevelop-5-3-44737757?utm_medium=social&utm_source=twitter&utm_campaign=postshare)

**Comment by Beeblerox** [comment]
- [ ] [Diggy Diggy Deck](https://axolstudio.itch.io/diggy-diggy-deck) made by [Axol Studio](https://twitter.com/AxolStudio/status/1335677311807594496) for the Yogscast Game Jam 2020

**Comment by Beeblerox** [comment]
- [ ] Inno Games are [still looking for a Haxe developer](https://twitter.com/nadako/status/1336030515565092867)

**Comment by Beeblerox** [comment]
- [ ] Look who are [using Haxe for Advent of Code](https://github.com/search?l=Haxe&o=desc&q=adventofcode&s=updated&type=Repositories) solutions. via [Jordon Replogle](https://twitter.com/JordonRep/status/1336448313562820608)

**Comment by Beeblerox** [comment]
- [ ] [Sébastien Bénard](https://twitter.com/deepnightfr/status/1336591322493427713) is making a tiny Dungeon Master / Eye of the Beholder engine for the #7DFPS. And using Haxe and Heaps for it

**Comment by Beeblerox** [comment]
- [ ] Two articles (in Russian) about Armory3D:
    * [Armory basics. Traits](https://habr.com/ru/post/531670/)
    * [Wasm in Armory Engine](https://habr.com/ru/post/531964/)

**Comment by Beeblerox** [comment]
- [ ] [Spooksville beta 1](https://axolstudio.com/misc/chill2/) by Axol Studio is available for testing

**Comment by Beeblerox** [comment]
- [ ] [2D raytracing](https://cdn.discordapp.com/attachments/162664383082790912/785465059941023784/Screen_Shot_2020-12-07_at_4.44.58_PM.png) in [Rice2D](https://github.com/BlackGoku36/Rice2D) by [Urjasvi Suthar](https://github.com/BlackGoku36)

**Comment by Beeblerox** [comment]
- [ ] [Richard Oliver Bray](https://twitter.com/Ceiga) has created Udemy course - [Making GLSL shaders for 2D game development - HaxeFlixel](https://www.udemy.com/course/making-glsl-shaders-for-2d-game-development/)

**Comment by Beeblerox** [comment]
- [ ] [Lacuna](https://bitdecaygames.itch.io/lacuna) is another entry for the Game Off 2020 jam. Made with OpenFL

**Comment by Beeblerox** [comment]
- [ ] Defender's Quest 2 [Progress Report for November 2020](https://www.fortressofdoors.com/defenders-quest-2-progress-report-for-november-2020/) by [Lars Doucet](https://twitter.com/larsiusprime/status/1336733547231653888)

**Comment by Beeblerox** [comment]
- [ ] [Feathers UI beta.2 preview build on Haxelib](https://feathersui.com/blog/2020/12/08/feathers-ui-beta-2-preview/) by Josh Tynjala

**Comment by Cleod9** [comment]
- [Fraymakers](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter?utm_source=haxe&utm_medium=other&utm_campaign=fmksbegin&ref=cpk5lz) is powering through stretch goals on Kickstarter surpassing $235k! Just this week they've confirmed the addition of a 9th playable character, super attacks, announcer packs voiced by [Alpharad](https://twitter.com/Alpharad) and [Tomamoto](https://twitter.com/tomamoto/), and Switch port, with more to hopefully come during its final stretch!

**Comment by Beeblerox** [comment]
- [ ] [More interesting terrain](https://cdn.discordapp.com/attachments/774020763149271062/786454021673713695/unknown.png) in [Voxel engine](https://github.com/5Mixer/voxel) by Daniel Blaker

**Comment by Beeblerox** [comment]
- [ ] DESEEDER is now [the 11th game ported to Haxe](https://twitter.com/Zanzlanz/status/1336750017969786887) by Alex Lanzetta

**Comment by Beeblerox** [comment]
> * [ ]  The first Kickstarter backer created chompy is in [Renaine](https://twitter.com/OctosoftUS/status/1335320539020214272)!

- [ ] ["Directors cut"](https://twitter.com/squuuidly/status/1336743131254034448) of birb GIF

**Comment by Beeblerox** [comment]
> * [ ]  [Nanjizal](https://twitter.com/Nanjizal_net/status/1335039818531827713) has shared a WebGL, Texture and vectors demo using HaxeUI for controls.

- [ ] [Example](https://trilateralx.github.io/TrilateralSamples/webgl/ItileSheetText/) of using spritesheet for simple text. via [Nanjizal](https://twitter.com/Nanjizal_net/status/1336753833121378310)

**Comment by skial** [comment]
- [ ] [wasm_haxe `git`](https://github.com/traxys/wasm_haxe) - WASM parser in Haxe, made to be fully compatible with Lua.
