### ISSUE TITLE
Haxe Roundup 560

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#830]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] Haxe TODO list for beginners - EP1 [video](https://www.youtube.com/watch?v=rMjq9LpEE_w) by Coding Reaction.

**Comment by skial** [comment]
- [ ] GADT type params and inlining [issue](https://github.com/HaxeFoundation/haxe/issues/9989).

**Comment by skial** [comment]
- [ ] [PolyStreamer](https://polystreamer.com/) - multistreaming service built with Haxe! [community announcement](https://community.haxe.org/t/polystreamer-multistreaming-service-built-with-haxe/2804) by [Jeff Ward](https://twitter.com/Jeff__Ward).

**Comment by skial** [comment]
- [ ] `[heaps]` HXSL: Implement borrow qualifier [pull request](https://github.com/HeapsIO/heaps/pull/916).

**Comment by skial** [comment]
- [ ] [Dicey Dungeons](https://distractionware.com/blog/2020/12/dicey-dungeons-is-out-now-on-switch/) is out now on the [Nintendo Switch](https://www.nintendo.com/games/detail/dicey-dungeons-switch/)! via [Terry Cavanagh](https://twitter.com/terrycavanagh/status/1339013557380210689). 🎲

**Comment by skial** [comment]
- [ ] [Tommy](https://twitter.com/d0oo0p/status/1338839822304153601) is working on a Kha LibVLC binding!

**Comment by skial** [comment]
- [ ] [Renaine](https://twitter.com/OctosoftUS/status/1338900903034818564) Kickstarter Update `#32` - [Updates and Crossovers](https://www.kickstarter.com/projects/585676804/renaine-a-game-about-overcoming-failure/posts/3048670).

**Comment by skial** [comment]
- [ ] `[ILIB]` Add Linux & OSX Amd64 [merged](https://github.com/HaxeFoundation/haxe/pull/9996) - Needed for .NET `5.0` std dlls.

**Comment by skial** [comment]
- [ ] `[ide/cache]` Signature based module invalidation [ideas](https://github.com/HaxeFoundation/haxe/issues/9995).

**Comment by skial** [comment]
- [ ] `[js]` Use `Array.prototype.slice.call(arguments, offset)` for rest args and still generate non-rest args normally in ES5 [pull request](https://github.com/HaxeFoundation/haxe/pull/9993).

**Comment by skial** [comment]
- [ ] `[cpp]` Support new and super for native classes [merged](https://github.com/HaxeFoundation/haxe/pull/9516).

**Comment by skial** [comment]
- [ ] Custom map implementations perform poorly at large sizes [issue](https://github.com/HaxeFoundation/haxe/issues/9994).

**Comment by Jarrio** [comment]
- [ ] The Haxe community discord just hit 3,000 members - [come join!](https://discord.gg/9rwb7D7)

**Comment by skial** [comment]
- [ ] `[draft]` Start working on `Void` unit type [pull request](https://github.com/HaxeFoundation/haxe/pull/10027).

**Comment by skial** [comment]
- [ ] `[tink_macro]` Deduce common base type from a list of types [merged](https://github.com/haxetink/tink_macro/pull/33).

**Comment by skial** [comment]
- [ ] Haxe-Checkstyle `2.7.0` has been [released](https://github.com/HaxeCheckstyle/haxe-checkstyle/releases/tag/v2.7.0).

**Comment by skial** [comment]
- [ ] `[neko]` Port from GTK2 to GTK3 [pull request](https://github.com/HaxeFoundation/neko/pull/220).

**Comment by skial** [comment]
- [ ] Formalize/design/unit-test IDE-support API for macros [discussion](https://github.com/HaxeFoundation/haxe/issues/10013).

**Comment by skial** [comment]
- [ ] Ceramic `0.6.0` has been [released](https://github.com/ceramic-engine/ceramic/releases/tag/v0.6.0).

**Comment by skial** [comment]
- [ ] `[cpp]` Overload resolution for `TNew` [merged](https://github.com/HaxeFoundation/haxe/pull/9807).

**Comment by skial** [comment]
- [ ] `[cs]` Avoid CA2200 warning when rethrowing [merged](https://github.com/HaxeFoundation/haxe/pull/9999).

**Comment by skial** [comment]
- [ ] `[cs/java]` Do not check abstract fields in libs [merged](https://github.com/HaxeFoundation/haxe/pull/9998).

**Comment by skial** [comment]
- [ ] Simplify the OpenFL library structure [merged](https://github.com/openfl/openfl/pull/2442).

**Comment by skial** [comment]
- [ ] `[js]` Generate export with `@:expose` and `-D js-es=6` [pull request](https://github.com/HaxeFoundation/haxe/pull/10003).

**Comment by skial** [comment]
- [ ] `@:structInit` can be used to bypass final assignment [issue](https://github.com/HaxeFoundation/haxe/issues/10017).

**Comment by skial** [comment]
- [ ] `[haxeparser]` Syntax updates [merged](https://github.com/Simn/haxeparser/pull/58), with add Lix support.

**Comment by skial** [comment]
- [ ] `@:forward.new` breaks with constructor closures [fixed](https://github.com/HaxeFoundation/haxe/issues/10007).

**Comment by skial** [comment]
- [ ] `[code example]` Pseudo Random Number Generator by Kaelan Evans [community thread](https://community.haxe.org/t/pseudo-random-number-generator-i-wanted-to-share/2818).

**Comment by skial** [comment]
- [ ] Go2hx community [announcement](https://community.haxe.org/t/go2hx-work-in-progress/2821?u=skial). 🌟

**Comment by skial** [comment]
- [ ] `[kha]` Update `Random` with faster implementation, SFC32 [pull request](https://github.com/Kode/Kha/pull/1284).

**Comment by skial** [comment]
- [ ] Haxe `4.1.5` has been [released](https://community.haxe.org/t/haxe-4-1-5-is-released/2825/1). 🌟

**Comment by skial** [comment]
- [ ] OGMO Editor `3.4.0` The Ohmnivorening, has been [released](https://github.com/Ogmo-Editor-3/OgmoEditor3-CE/releases/tag/3.4.0).

**Comment by skial** [comment]
- [ ] Add .NET `5.0` [pull request](https://github.com/HaxeFoundation/hxcs/pull/46).

**Comment by skial** [comment]
- [ ] LDtk `0.6.2` has been [released](https://github.com/deepnight/ldtk/releases/tag/v0.6.2).

**Comment by skial** [comment]
- [ ] Armory `2021.1` has been [released](https://github.com/armory3d/armory/releases/tag/21.01).
- [ ] Iron `2021.1` has been [released](https://github.com/armory3d/iron/releases/tag/21.01).
- [ ] Zui `2021.1` has been [released](https://github.com/armory3d/zui/releases/tag/21.01).
- [ ] HaxeBullet `2021.1` has been [released](https://github.com/armory3d/haxebullet/releases/tag/21.01).

**Comment by skial** [comment]
- [ ] Ceramic `0.6.2` has been [released](https://github.com/ceramic-engine/ceramic/releases/tag/v0.6.2).

**Comment by skial** [comment]
- [ ] InnoGames are looking to [hire a Frontend Haxe Developer](https://community.haxe.org/t/calling-all-haxe-developers-we-are-hiring/2834) for their Forge of Empire games.

**Comment by skial** [comment]
- [ ] libs
  - [Haxentric `1.0.0`](https://lib.haxe.org/p/Haxentric)
  - [echo `3.0.0`](https://lib.haxe.org/p/echo)
  - [hxp `1.2.1`](https://lib.haxe.org/p/hxp)
  - [cog `2.0.0`](https://lib.haxe.org/p/cog)
  - [ldtk-haxe-api `0.6.2-rc.1`](https://lib.haxe.org/p/ldtk-haxe-api)
  - [atom `1.53.0`](https://lib.haxe.org/p/atom)
  - [checkstyle `2.7.0`](https://lib.haxe.org/p/checkstyle)
  - [tokentree `1.1.0`](https://lib.haxe.org/p/tokentree)
  - [ceramic `0.2.7`](https://lib.haxe.org/p/ceramic)
  - [vscode `1.52.0`](https://lib.haxe.org/p/vscode)
  - [jsoni18n `1.0.2`](https://lib.haxe.org/p/jsoni18n)
  - [redistHelper `0.4.7`](https://lib.haxe.org/p/redistHelper)
  - [haxe-injection `0.0.1`](https://lib.haxe.org/p/haxe-injection)
  - [pony `1.3.7`](https://lib.haxe.org/p/pony)
  - [newgrounds `1.1.3`](https://lib.haxe.org/p/newgrounds)
  - [fuse `0.1.6`](https://lib.haxe.org/p/fuse)
  - [tink_core `2.0.0-rc.2`](https://lib.haxe.org/p/tink_core)
  - [which `2.0.2`](https://lib.haxe.org/p/which)
  - [deepnightLibs `1.0.55`](https://lib.haxe.org/p/deepnightLibs)

**Comment by skial** [comment]
- [ ] [Vadim](https://twitter.com/yellowafterlife) has written [2020 in review](https://yal.cc/2020-in-review/).

**Comment by skial** [comment]
- [ ] [Lars Doucet](https://twitter.com/larsiusprime) has written [Defender's Quest 2 Progress Report for November 2020](https://www.fortressofdoors.com/defenders-quest-2-progress-report-for-november-2020/).

**Comment by skial** [comment]
- [ ] `[cs]` Implement `cs.Syntax.code` and `cs.Syntax.plainCode` [pull request](https://github.com/HaxeFoundation/haxe/pull/10051).

**Comment by skial** [comment]
- [ ] [clay `git`](https://github.com/ceramic-engine/clay) - Clay is a lightweight toolkit to build apps, games and frameworks on native platforms and web browser, written with the Haxe Programming Language. Clay is a rewite and successor to snowkit's snow library.

**Comment by skial** [comment]
- [ ] [hxScene `git`](https://github.com/moonhappy/hxscene) - Haxe Scene: Manage game objects using a theatre/stage like paradigm.

**Comment by skial** [comment]
- [ ] [hxasync `git`](https://github.com/botsman/hxasync) - This library allows you to add async and await keywords in Python and JavaScript code almost the same way you would do it in the native code.

**Comment by skial** [comment]
- [ ] [spil `git`](https://github.com/ariebovenberg/spil) - A simple lisp parser written in Haxe.

**Comment by skial** [comment]
- [ ] [atom `git`](https://github.com/wartman/atom) - Atomic CSS for Haxe.

**Comment by skial** [comment]
- [ ] [SequentCalculi `git`](https://github.com/zoqol/SequentCalculi) - A Haxe implementation of G3cp & G4ip, two cutfree and decidable proof system for classical and intuitionistic propositional logic.

**Comment by skial** [comment]
- [ ] [hawk `git`](https://github.com/scottPlusPlus/hawk) - Haxe Webkit -> make web apps quickly.

**Comment by skial** [comment]
- [ ] [Luna-oxygen `git`](https://github.com/LunaTechsDev/Luna-oxygen) - An RPGMakerMV/MZ plugin that adds additionial widgets and UI elements to improve your game with.

**Comment by skial** [comment]
- [ ] [Luna-config `git`](https://github.com/LunaTechsDev/Luna-config) - An RPGMakerMV/MZ plugin that allows you to modify additional presets in MZ/MV.

**Comment by skial** [comment]
- [ ] [netlog `git`](https://github.com/YAL-GameMaker/netlog) - An external debug log window. Supports colors!

**Comment by skial** [comment]
- [ ] [extension-yy-to-gmx `git`](https://github.com/YAL-GameMaker-Tools/extension-yy-to-gmx) - _very partially_ convert GameMaker Studio 2 extensions to GameMaker: Studio format.

**Comment by skial** [comment]
- [ ] [NT-Background-Colors `git`](https://github.com/YAL-Game-Tools/NT-Background-Colors) - A small program to aid with changing background\shadow colors when doing texture mods for Nuclear Throne.
- [ ] [NTT-Assemble `git`](https://github.com/YAL-Game-Tools/NTT-Assemble) - Patcher/reassembler program for Nuclear Throne Together.
- [ ] [BaronyBoolStatsViewer `git`](https://github.com/YAL-Game-Tools/BaronyBookStatsViewer) - A small web app to check what books you are missing for an achievement in Barony.
- [ ] [GmxOrg `git`](https://github.com/YAL-GameMaker-Tools/GmxOrg) - Exports .project.gmx structure to a YAML-like format and back. Intended for quickly organizing large numbers of assets in projects.

**Comment by skial** [comment]
- [ ] [BMFontToGMFont `git`](https://github.com/YAL-GameMaker-Tools/BMFontToGMFont) - Converts BMFont-format fonts into GMS/GMS2 font resources.

**Comment by skial** [comment]
- [ ] [McLeodGaming](https://twitter.com/McLeodGaming/status/1339773496491012097) have [completed](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3053812) the Fraymaker's Kickstarter campaign with 9885 backers who pledged $364,922, funded `793%` above their original goal! 👏 Remember to [wishlist](https://store.steampowered.com/app/1420350/Fraymakers/?utm_source=kickstarter&utm_medium=other&utm_campaign=fmsteam) it on Steam.

**Comment by skial** [comment]
- [ ] Rogue of Vallas Devlog `#8`: State Manager Finale [video](https://www.youtube.com/watch?v=NVklCkFiMdg) by [Merrak](https://twitter.com/merrak)
- [ ] Rogue of Vallas Devlog `#9`: Level Design Strategies [video](https://www.youtube.com/watch?v=lxw5YZ2xA1Q) by [Merrak](https://twitter.com/merrak)

**Comment by skial** [comment]
- [ ] How to remove the HaxeFlixel branding i.e. _splash screen, auto pause. mouse cursor_ [video](https://www.youtube.com/watch?v=kEXeCx2W18g) by [Richard Oliver Bray](https://twitter.com/ceiga).
- [ ] How to create a custom preloader in HaxeFlixel [video](https://www.youtube.com/watch?v=XHTkOKROebc) by [Richard Oliver Bray](https://twitter.com/ceiga).
- [ ] How to export and publish your game in Haxeflixel [video](https://www.youtube.com/watch?v=hazPGvI5DfA) by [Richard Oliver Bray](https://twitter.com/ceiga).
- [ ] Adding a finite state machine (FSM) to a HaxeFlixel sprite - Part 1 - Setting up [video](https://www.youtube.com/watch?v=z3qQpGHozso) by [Richard Oliver Bray](https://twitter.com/ceiga).

**Comment by skial** [comment]
- [ ] ArmorPaint. Nutcracker. PBR painted wood material with scratches [video](https://www.youtube.com/watch?v=31ki8qT9bP8&feature=emb_title) by [Alexandr Kiryanov](https://twitter.com/AlexandrKiryan3/status/1343569733355008001).

**Comment by skial** [comment]
- [ ] [Kino Rose](https://twitter.com/EISKino/status/1338629739079090177) has written [Compile Projects In Haxe Fast](https://kinocreates.io/tutorials/compile-projects-in-haxe-fast/).

**Comment by skial** [comment]
- [ ] [Oleg Dolya](https://twitter.com/watawatabou/status/1341808575669264387) has written [City Viewer `1.1.0`](https://www.patreon.com/posts/city-viewer-1-1-45360377) - support for trees and islands, improve UI & more.

**Comment by skial** [comment]
- [ ] Large bird friend does big tackle in Renaine by [Squidly](https://twitter.com/squuuidly/status/1346528662615707648).

**Comment by skial** [comment]
- [ ] Poor Thief by [Tom Brinton](https://twitter.com/brintown/status/1346471326769299462), made in Stencyl, was Game of the Day on the App Store.

**Comment by skial** [comment]
- [ ] [Robert Alvarez](https://twitter.com/Rob1221dev/status/1345387045322174466) has release their first game of 2021, Chessformer, now available on [itch.io](https://rob1221.itch.io/chessformer) and [Newgrounds](https://www.newgrounds.com/portal/view/776595), made with Stencyl.

**Comment by skial** [comment]
- [ ] [Nanjizal](https://twitter.com/Nanjizal_net/status/1345156519722151936) has added the [Oklab colour space](https://bottosson.github.io/posts/oklab/) to [pallette `git`](https://github.com/nanjizal/pallette).

**Comment by Skyfire2008** [comment]
- [ ] [Skyfire2008](https://github.com/Skyfire2008) released Asteroids on [Newgrounds](https://www.newgrounds.com/portal/view/776269).

**Comment by skial** [comment]
- [ ] [Jonas Nystrom](https://twitter.com/cambiatajonas/status/1344634960481812489) has recorded an introduction [video](https://www.youtube.com/watch?v=e8gqN0PDJos&feature=youtu.be) on how to use Haxe with React Native CLI project running on a Android virtual device. Source code available on [gist.github.com](https://gist.github.com/cambiata/3ee4cd413e9e555db05c5af38476333c).

**Comment by skial** [comment]
- [ ] [Blackgoku36](https://twitter.com/UrjasviS/status/1343494469593620482) is writing their own rendering engine in Kha for learning purposes.

**Comment by skial** [comment]
- [ ] [Tommy](https://twitter.com/d0oo0p/status/1342571229417500672) previews his LibVLC bindings with two 4K streams and two HD streams with high bitrate all playing at 60 FPS in the same Kha app.

**Comment by skial** [comment]
- [ ] [Sébastien Bénard](https://twitter.com/deepnightfr/status/1341720368403386368) has updated his LD35 game, [SubDragon](https://deepnight.net/games/subdragon/), which is now vastly optimised and runs at close to 60 FPS. Source code available on [GitHub](https://github.com/deepnight/ld35-subDragon).

**Comment by skial** [comment]
- [ ] [Syo](https://twitter.com/SyoPic/status/1346430019682398208) previews ships docking in Jitter Sandbox, an indie game made with Heaps.

**Comment by skial** [comment]
- [ ] Luna Tech plugins have been featured in RPG Maker [Resource Spotlight: Lunatech's Plugins](https://www.rpgmakerweb.com/blog/resource-spotlight-lunatechs-plugins) article.

**Comment by skial** [comment]
- [Dustin Auxier](https://twitter.com/dustinaux/status/1344377404475772928) is offering a `$100` bounty to identify and fix an OpenFL issue.

**Comment by skial** [comment]
- [ ] One of [Cédric Belin](https://twitter.com/cedxbelin/status/1340021716798623746) projects, [setup-dart-action `git`](https://github.com/marketplace/actions/setup-dart-action) is being used by Google, in [mono_repo.dart `git`](https://github.com/google/mono_repo.dart/blob/master/.github/workflows/dart.yml).

**Comment by Beeblerox** [comment]
> * [ ]  [Syo](https://twitter.com/SyoPic/status/1346430019682398208) previews ships docking in Jitter Sandbox, an indie game made with Heaps.

- [ ] [Management and flight modes](https://twitter.com/SyoPic/status/1337064235776561153)

**Comment by Beeblerox** [comment]
- [ ] [The First Month of Mine Blocks Beta!](https://zanzlanz.com/n/89) by [Alex Lanzetta](https://twitter.com/Zanzlanz/status/1339231308011237377)

**Comment by Beeblerox** [comment]
- [ ] [Fault by GhostID team](https://twitter.com/TeamGhostID/status/1337891501129478147) is on it's way back. [Fault 0.0.3a demo is out](https://twitter.com/TeamGhostID/status/1341221105055502337)

**Comment by Beeblerox** [comment]
- [ ] New screenshots and GIFs from WIP puzzle game by mauve:
    * [concepts for stuff, unpolished/incomplete](https://twitter.com/mauvecow/status/1337552072888094720)
    * [trap switches and popup floors](https://twitter.com/mauvecow/status/1338261512004112384): a new puzzle gimmick to be expanded on
    * [fixed reflections](https://twitter.com/mauvecow/status/1338311460032679941) of the torches on the water
    * [personal gamedev progress summary for 2020](https://twitter.com/mauvecow/status/1344522255489929220)

**Comment by Beeblerox** [comment]
- [ ] [JanoGames](https://twitter.com/jano_games/status/1337766038340067329) has updated the demo of Stage Dive with better Firefox support
- [ ] And also JanoGames has [started a prototype called One Season Wonder](https://twitter.com/jano_games/status/1341306106656780290)

**Comment by Beeblerox** [comment]
> * [ ]  [Kino Rose](https://twitter.com/EISKino/status/1338629739079090177) has written [Compile Projects In Haxe Fast](https://kinocreates.io/tutorials/compile-projects-in-haxe-fast/).

- [ ] [Haxe: What Are Anonymous Structures?](https://kinocreates.io/tutorials/haxe-what-are-anonymous-structures/) by [Kino Rose](https://twitter.com/EISKino/status/1346973196285861890)

**Comment by Beeblerox** [comment]
> * [ ]  Large bird friend does big tackle in Renaine by [Squidly](https://twitter.com/squuuidly/status/1346528662615707648).

- [ ] Here also stream recording: [Exploring some ruins with a bird 🐦 in Renaine](https://www.twitch.tv/videos/861745769)

**Comment by Beeblerox** [comment]
- [ ] [Sébastien Bénard](https://twitter.com/deepnightfr/status/1339179893171646466) has taken some time to learn new things with shaders in Heaps engine. With the [source code](https://github.com/deepnight/deepnightLibs/tree/master/src/dn/heaps/filter) available at his github

**Comment by Beeblerox** [comment]
> * [ ]  [Sébastien Bénard](https://twitter.com/deepnightfr/status/1341720368403386368) has updated his LD35 game, [SubDragon](https://deepnight.net/games/subdragon/), which is now vastly optimised and runs at close to 60 FPS. Source code available on [GitHub](https://github.com/deepnight/ld35-subDragon).

- [ ] And has [ported Memento XII](https://twitter.com/deepnightfr/status/1339853682947600384) from Flash to WebGL (took me ~2 days, including bonus bug fixes & retakes)

**Comment by Beeblerox** [comment]
- [ ] Couple of new screenshots from WIP game by Rob Clemmons Jr:
    * [Formatting close to being done](https://twitter.com/RobClemmonsJr/status/1339347407855902722)
    * [Sometimes, I do things correctly](https://twitter.com/RobClemmonsJr/status/1346032736260284416)
    * [Wow, that was, actually way easier then I thought](https://twitter.com/RobClemmonsJr/status/1346593304704471040)

**Comment by Beeblerox** [comment]
- [ ] [Non-destructive decal layers](https://twitter.com/luboslenco/status/1339557657863200768) now available in ArmorPaint. via Lubos Lenco

**Comment by Beeblerox** [comment]
- [ ] [Stick figures](https://watabou.itch.io/stick-figures) - is a submission by [Oleg Dolya](https://twitter.com/watawatabou/status/1339602135684550656) for procjam 2020

**Comment by Beeblerox** [comment]
- [ ] Nanjizal has [added linear gradient to Trilateral3](https://twitter.com/Nanjizal_net/status/1340103594134138881)

**Comment by Beeblerox** [comment]
- [ ] New GIFs and screenshots from Caverns of Ksantarus by President of Space:
    * [the obligatory lava floor for the obligatory lava level!](https://twitter.com/matzieq/status/1340262605156478976)
    * [got the GNU/Linux build working!](https://twitter.com/matzieq/status/1342734379278336000)
    * [creating obnoxious traps and fiery challenges](https://twitter.com/matzieq/status/1345345345648254977)

**Comment by Beeblerox** [comment]
> * [ ]  Rogue of Vallas Devlog `#8`: State Manager Finale [video](https://www.youtube.com/watch?v=NVklCkFiMdg) by [Merrak](https://twitter.com/merrak)
> * [ ]  Rogue of Vallas Devlog `#9`: Level Design Strategies [video](https://www.youtube.com/watch?v=lxw5YZ2xA1Q) by [Merrak](https://twitter.com/merrak)

- [ ] [Enjoy a 2020 GIF Christmas card!](https://twitter.com/merrak/status/1340745532214489090)

**Comment by Beeblerox** [comment]
- [ ] [Double Turn v1.0.5](https://twitter.com/doubleturngame/status/1341451031268515840) Winter Update is out [on Steam](https://store.steampowered.com/app/762680)

**Comment by Beeblerox** [comment]
- [ ] [Catchup Interview](https://randroll.com/archive/interview-watabou-2/) with Watabou of Fantasy City Generator by [Duncan Thomson](https://twitter.com/DuncanThom/status/1341394821580279811)

**Comment by Beeblerox** [comment]
- [ ] [Puppy string](https://torcado.itch.io/puppy-string) by [torcado](https://twitter.com/torcado/status/1341873719644475394).

**Comment by Beeblerox** [comment]
- [ ] [Joaquin Bello](https://twitter.com/JoaquinBelloD/status/1343475127925796866) got the basic flash shapes and animation working in Unity. The parsing and animation logic and interpolation was coded using haxe using [swf parser](https://github.com/HaxeFoundation/format), and then compiled into C# and interpret the data in Unity

**Comment by Beeblerox** [comment]
- [ ] New GIFs from Go! Go! PogoGirl by Andrej:
    * Don't you love it when you [mess up your tilesheet code](https://twitter.com/ohsat_games/status/1346902013699878913) and enemies become a long stretch of beach?
    * [The hidden gems now work!](https://twitter.com/ohsat_games/status/1345458608285380608)

**Comment by Beeblerox** [comment]
- [ ] [Windows version of Baston](https://www.txori.com/index.php?static12/baston) is available. via [Etienne](https://twitter.com/TxoriCom/status/1344420022190551040)

**Comment by Beeblerox** [comment]
- [ ] [guess I'm spending a lot of time on this little project](https://twitter.com/EltonSilvaArt/status/1345143244544495618) by Elton Silva

**Comment by Beeblerox** [comment]
- [ ] [Haxe with Defold progress update](https://www.youtube.com/watch?v=2YI54w16IuE&feature=emb_logo) by [Sergey Lerg](https://twitter.com/SergeyLerg/status/1346930183023046656)

**Comment by Beeblerox** [comment]
- [ ] jefvel has built [a game launcher/updater](https://twitter.com/jefvel/status/1346853211068637198) using Haxe and Hashlink. [Source code is available](https://twitter.com/jefvel/status/1346877259634913281) at github

**Comment by Beeblerox** [comment]
- [ ] [Rice2D-Examples](https://github.com/BlackGoku36/Rice2D-Examples) by Urjasvi Suthar

**Comment by Beeblerox** [comment]
- [ ] HaxeFlixel [multiplayer movie theatre was a huge success](https://twitter.com/tictacsnack/status/1340457622194024449?s=20).via [Geokureli](https://twitter.com/Geokureli)

**Comment by Beeblerox** [comment]
- [ ] [Tankmas ADVENTure 2020](https://www.newgrounds.com/portal/view/773236) by [Geokureli](https://twitter.com/Geokureli). With the [source code available at github](https://github.com/Geokureli/Advent2020)

**Comment by Beeblerox** [comment]
- [ ] [echo-flixel](https://github.com/AustinEast/echo-flixel) - a library to integrate echo physics with Haxeflixel

**Comment by Beeblerox** [comment]
- [ ] [Practical Shader Development done in HX](https://community.haxe.org/t/practical-shader-development-done-in-hx/2822) by Uldis Baurovskis

**Comment by Beeblerox** [comment]
- [ ] [OpenTower: A Resource Management Puzzle](https://community.openfl.org/t/opentower-a-resource-management-puzzle/12824)

**Comment by Beeblerox** [comment]
- [ ] [Hiring Haxe fullstack developer in Taipei](https://community.haxe.org/t/hiring-haxe-fullstack-developer-in-taipei/2836)

**Comment by Beeblerox** [comment]
- [ ] GIFs from WIP game by ustance (taken from Kha discord server):
    * [chests](https://cdn.discordapp.com/attachments/774020763149271062/793927376911466525/chests.gif)
    * [autotiling test](https://cdn.discordapp.com/attachments/162664383082790912/796423761414062080/autotiling3.gif)
    * [moving and eating](https://cdn.discordapp.com/attachments/774020763149271062/787658784058769428/test.gif)

**Comment by Beeblerox** [comment]
- [ ] [Austin East](https://twitter.com/austinweast) is [prototyping a curvy platformer](https://cdn.discordapp.com/attachments/162664383082790912/796100102699352094/monke-curves.gif) (made with [echo](https://lib.haxe.org/p/echo/) with recently added support for cubic and quadratic curves)

**Comment by Beeblerox** [comment]
- [ ] [Quarantine](https://int.jefvel.net/~jefvel/karanten/20201219/) made by [jefvel](https://twitter.com/jefvel). The game currently has two chapters but there will be more

**Comment by Beeblerox** [comment]
- [ ] Hugh Sanderson has added `nme.Lib.createSecondaryWindow` to create additional windows on desktop targets! See also [sample project](https://github.com/haxenme/nme/blob/master/samples/MultiWindow/src/Main.hx) showing new functionality

**Comment by Beeblerox** [comment]
- [ ] [Ceramic editor running inside Unity editor](https://cdn.discordapp.com/attachments/162664383082790912/787365797336842250/Capture_decran_2020-12-12_a_18.05.48.png). As the editor is made with ceramic, it can be exported as Unity project like any other ceramic app! via Jeremy Fa on Haxe discord server

**Comment by skial** [comment]
- [ ] Regression in operators handling [issue](https://github.com/HaxeFoundation/haxe/issues/10052).
