### ISSUE TITLE
Haxe Roundup 561

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#832]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[cpp]` Fix typing of `cpp.Native.star` [pull request](https://github.com/HaxeFoundation/haxe/pull/10058).

**Comment by skial** [comment]
- [ ] How to get `Map` size on via native methods for various targets [comment](https://github.com/HaxeFoundation/hashlink/pull/437#issuecomment-757579451).

**Comment by skial** [comment]
- [ ] Macro reification of abstract/final class/interface [issue](https://github.com/HaxeFoundation/haxe/issues/10060).

**Comment by skial** [comment]
- [ ] `[openfl]` Implement UDP via DatagramSocket [pull request](https://github.com/openfl/openfl/pull/2456).

**Comment by skial** [comment]
- [ ] Problem with overloading of compound assignment operators [issue](https://github.com/HaxeFoundation/haxe/issues/10066).

**Comment by skial** [comment]
- [ ] libs
  - [deepnightLibs `1.0.58`](https://lib.haxe.org/p/deepnightLibs)
  - [externs `0.3.0`](https://lib.haxe.org/p/externs)
  - [nwjs `1.1.1`](https://lib.haxe.org/p/nwjs)
  - [pony `1.3.9`](https://lib.haxe.org/p/pony)

**Comment by skial** [comment]
- [ ] [Poga](https://twitter.com/devpoga) has written a Chip-8 simulator that can be run in the browser and locally with HashLink, check out the [vis-chip-8 `git`](https://github.com/poga/vis-chip-8) GitHub repo.

**Comment by skial** [comment]
- [ ] [Techy Wrinkles](https://twitter.com/techywrinkles/status/1349096344766590979) is using OpenFL for their turn based roguelike game.

**Comment by skial** [comment]
- [ ] [Nanijzal](https://twitter.com/Nanjizal_net/status/1348978209992433666) shows how to use inlines, typedefs and abstracts in his [NextTo](https://try.haxe.org/#d82D9) `try.haxe.org` demo and over on [`gist`](https://gist.github.com/nanjizal/6614efcb878a8f4c62c78eb7b32c1e1b).

**Comment by skial** [comment]
- [Syo](https://twitter.com/SyoPic/status/1348665648373764099) shows off full ship docking in Jitter Sandbox, his indie Heaps powered game.

**Comment by skial** [comment]
- [ ] [Sergey Lerg](https://twitter.com/SergeyLerg/status/1348048995311112193) previews his current progress with Haxe and Defold with scene transitioning, with a [screenshot](https://twitter.com/SergeyLerg/status/1348048999677374464) showing the code.

**Comment by skial** [comment]
- [ ] Rogue of Vallas Devlog 10: RPG Balance and Design [video](https://www.youtube.com/watch?v=1crnGS21yMg&feature=youtu.be) by [Merrak](https://twitter.com/merrak/status/1347725177170374657).

**Comment by skial** [comment]
- [ ] [Cory](https://twitter.com/CoryAlexMartin/status/1347660212031909890) has made some long overdue improvements to the puddle VFX in Leapin Lads.

**Comment by skial** [comment]
- [ ] [Kaelan Evans](https://twitter.com/kbeevans/status/1347451599489101825) previews multiplayer Line Rider made in Haxe and Heaps using WebRTC and PeerHX. Source code for [OpenLR `git`](https://github.com/kevansevans/OpenLR) is available on GitHub.

**Comment by skial** [comment]
- [ ] [Nanjizal](https://twitter.com/Nanjizal_net/status/1347275965739753474) previews experimental class and typedef abstract code and the generated JavaScript source.

**Comment by skial** [comment]
- [ ] Adding a finite state machine (FSM) to a HaxeFlixel sprite - Part 2 - using switch case and enums [video](https://www.youtube.com/watch?v=hNgXIlCHEls) by [Richard Oliver Bray](https://twitter.com/ceiga).

**Comment by skial** [comment]
- [ ] [hxrx `git`](https://github.com/Aidan63/hxrx) - Haxe 4.2 reactive extensions.

**Comment by skial** [comment]
- [ ] [externs.hx `git`](https://github.com/cedx/externs.hx) - Partial Haxe externs for common JavaScript and PHP libraries.

**Comment by skial** [comment]
- [ ] [fure `git`](https://github.com/zheng0716/fure) - Functional Reactive Framework.

**Comment by skial** [comment]
- [ ] [HExt `git`](https://github.com/aartzrc/HExt) - HTML templating with code-completion.

**Comment by skial** [comment]
- [ ] [Haxe-C-Bridge `git`](https://github.com/haxiomic/haxe-c-bridge) - `[WIP]` Easily embed a multi-threaded Haxe program within a native application via an automatically generated C header.

**Comment by skial** [comment]
- [ ] [LucidText `git`](https://github.com/bitDecayGames/LucidText) - LucidText is a HaxeFlixel library designed to give easy access to juicy text in the style of games like Paper Mario, Animal Crossing, and Celeste.

**Comment by Beeblerox** [comment]
- [ ] [PogoGirl Devlog #10](https://www.ohsat.com/post/pogogirl-devlog/post10/): Gems and Goals by [Andrej](https://twitter.com/ohsat_games/status/1349470085300281345)
- [ ] Plus some new GIFs and screenshots:
    * [*menu selection intensifies*](https://twitter.com/ohsat_games/status/1347277459226558465)
    * [Improved the HUD](https://twitter.com/ohsat_games/status/1348013322034180097) a little. Replaced the text with icons
    * In the process of mocking up a [better level end screen](https://twitter.com/ohsat_games/status/1349436361707823105)

**Comment by Beeblerox** [comment]
- [ ] [Where was I?](https://ghostid.ca/post/5) by [GhostID](https://twitter.com/TeamGhostID/status/1347350951351508995)
- [ ] Many optimizations and fixes on [the chunk system for Fault](https://twitter.com/TeamGhostID/status/1348410266128707584) by GhostID

**Comment by Beeblerox** [comment]
- [ ] Couple of new GIFs from WIP curvy plaftormer by Austin East:
    * [making a game](https://twitter.com/austinweast/status/1347352461007343616) about my favorite monke, sonic the hedgehog
    * [rolling added](https://twitter.com/austinweast/status/1347836595123216384)

**Comment by Beeblerox** [comment]
- [ ] ArmorPaint. [New functions of the program. January 8 2021](https://www.youtube.com/watch?v=qQn58tvd0Ls&feature=emb_logo) video by [Alexander Kiryanov](https://twitter.com/AlexandrKiryan3/status/1347567566194176000)

**Comment by Beeblerox** [comment]
- [ ] President of Space is [working on new obstacle types](https://twitter.com/matzieq/status/1347889323119685632) for the Caverns of Ksantarus

**Comment by Beeblerox** [comment]
- [ ] Terry Cavanagh announced that the next update to Dicey Dungeons [will have an Arabic translation](https://twitter.com/terrycavanagh/status/1348599868630003713).  A public beta is live on Steam branch "arabic" right now! More tech stuff soon, but this means that OpenFl will possibly have support for RTL and ligatures text rendering (at least for native platforms)

**Comment by Beeblerox** [comment]
- [ ] [The markdown-based dialogue system](https://syopic.itch.io/jitter/devlog/212492/the-markdown-based-dialogue-system) by [Syo](https://twitter.com/SyoPic/status/1349402357533188100)

**Comment by Beeblerox** [comment]
- [ ] mundusnine has [streamed the process](https://www.twitch.tv/videos/872211506) of making a platformer example project for [Foundry2d engine](https://github.com/foundry2D)

**Comment by Beeblerox** [comment]
- [ ] [Sébastien Bénard](https://twitter.com/deepnightfr) is working on [LDtk levels loading & rendering in HaxeFlixel](https://cdn.discordapp.com/attachments/165234904815239168/797087466988896317/unknown.png)

**Comment by Beeblerox** [comment]
- [ ] [Maze Genius](https://some-code-person.itch.io/maz) made with HaxeFlixel by newlibarian user of Haxe Discord server

**Comment by Beeblerox** [comment]
- [ ] [Character creation](https://cdn.discordapp.com/attachments/162664383082790912/797587196302327818/Capture.PNG) using HaxeFlixel + HaxeUI screenshot by guifes from Haxe Discord server

**Comment by Beeblerox** [comment]
- [ ] R.c from Haxe Discord server is working on [fully procedural island generator](https://cdn.discordapp.com/attachments/162664383082790912/797133606609879081/island_generator_2.png) for the next game. Made with Heaps

**Comment by Beeblerox** [comment]
- [ ] [Michael Bickel](https://twitter.com/dazKind) has finished the first draft of a [simple verlet-based physics engine](https://www.youtube.com/watch?v=ZFWBl7e9jCk&feature=youtu.be). The demo is running on top of Snow

**Comment by Beeblerox** [comment]
- [ ] [postgres-ext](https://gitlab.com/benjamin.dasnois/postgres-ext) by Benjamin Dasnois provides sys.db.Connection for PostgreSQL

**Comment by Beeblerox** [comment]
- [ ] [Tankmas ADVENTure 2020](https://www.newgrounds.com/portal/view/773236) got the Newgrounds award for best game based on original content for the month of December

**Comment by skial** [comment]
- [ ] How To Change Output Names In Haxe [article](https://kinocreates.io/tutorials/how-to-change-output-names-in-haxe/) by [Kino Rose](https://twitter.com/EISKino/status/1349530746587926536).

**Comment by skial** [comment]
- [ ] [HaxeTools `git`](https://github.com/VolkovRA/HaxeTools) - Набор часто используемых инструментов для Haxe / A set of frequently used tools for Haxe.

**Comment by skial** [comment]
- [ ] [Kat `git`](https://github.com/mundusnine/Kat) - Music Player for music listeners and streamers.
