### ISSUE TITLE
Haxe Roundup 565

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#841]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[genes]` Rough support of multiple types in dynamic import [merged](https://github.com/benmerckx/genes/pull/34).

**Comment by skial** [comment]
- [ ] `[community]` Pecan coroutines [announcement](https://community.haxe.org/t/pecan-coroutines/2885?u=skial).
  - > pecan 12 is a macro-based library for Haxe that lets you write coroutines 7, which are functions that can suspend their execution at any point

**Comment by skial** [comment]
- [ ] `[community]` Vshaxe `2.22.0` has been [released](https://community.haxe.org/t/vshaxe-2-22-0-released-implement-missing-fields-quickfix/2890?u=skial).

**Comment by skial** [comment]
- [ ] `[community]` Haxe `4.2.0` has been [released](https://community.haxe.org/t/haxe-4-2-0-is-released/2888?u=skial)!

**Comment by skial** [comment]
- [ ] `[core]` `@:using` not working as intended when handling `Class<>` and `Enum<>` [issue](https://github.com/HaxeFoundation/haxe/issues/10106).

**Comment by skial** [comment]
- [ ] `[armory3d]` Add support for shadow map atlasing [pull request](https://github.com/armory3d/armory/pull/2102).

**Comment by skial** [comment]
- [ ] `[core]` Suggestion: cpp `Int64` should not implicitly cast to `Int32` [discussion](https://github.com/HaxeFoundation/haxe/issues/10108).

**Comment by skial** [comment]
- [ ] libs
   - [genes `0.3.1`](https://lib.haxe.org/p/genes)
   - [hxcpp `4.2.1`](https://lib.haxe.org/p/hxcpp)
   - [hxcs `4.2.0`](https://lib.haxe.org/p/hxcs)
   - [hxjava `4.2.0`](https://lib.haxe.org/p/hxjava)
   - [hxasync `0.3.6`](https://lib.haxe.org/p/hxasync)
   - [electron `11.2.3`](https://lib.haxe.org/p/electron)
   - [avenyrhEngine `0.1.0`](https://lib.haxe.org/p/avenyrhEngine)
   - [css-types `0.2.4`](https://lib.haxe.org/p/css-types)

**Comment by skial** [comment]
- [ ] Packaging NPM dependencies into a [JS/Haxe Application](https://gist.github.com/TomByrne/9495dba331ed8365b06abc1d9fa50d2d) by Tom Byrne.

**Comment by skial** [comment]
- [ ] PogoGirl Devlog `#12`: [Power Up!](https://www.ohsat.com/post/pogogirl-devlog/post12/) by [Andrej](https://twitter.com/ohsat_games).

**Comment by skial** [comment]
- [ ] `[close source]` [Syo](https://twitter.com/SyoPic/status/1359503756661043200) has transferred the mechanics from the old prototype to the Jitter Sandbox game, made with Heaps.

**Comment by skial** [comment]
- [ ] `[app releases]` [Michael Miriti](https://twitter.com/michael_miriti/status/1359502648999829504) has made a _demake_ of UnRailed! by [Indoor Astronaut](https://twitter.com/IndoorAstronaut/) for `#nokiajam`, available on [itch.io](https://twitter.com/michael_miriti/status/1359502648999829504), made with Heaps.

**Comment by skial** [comment]
- [ ] `[video/music]` [FierceTheBandit](https://twitter.com/FierceTheBandit/status/1359303046782722049) has released Super Cosmic Land's OST, available on [Newgrounds](https://www.newgrounds.com/playlists/view/f789666e927954d2d1c3f377b14b5d90).

**Comment by skial** [comment]
- [ ] `[closed source]` [Jano Games](https://twitter.com/jano_games/status/1359239047084978177) is starting work on the game simulator for One Season Wonder, made with Stencyl.

**Comment by skial** [comment]
- [ ] `[closed source]` [Fresh Juice](https://twitter.com/F_J_GAMES/status/1358818695523491840) previews prison break: _stealth mode_ in Sharpeye, a pixel art game made with Stencyl.

**Comment by skial** [comment]
- [ ] `[closed source]` [Snsvrno](https://twitter.com/snsvrno/status/1358519346201387011) previews a prototype game, which has been a challenge to code due to complex curves, made with Heaps.

**Comment by skial** [comment]
- [ ] [Gepatto](https://twitter.com/gepatto/status/1358120319869984768) previews FlxTeroids running on a Raspberry Pi 4 using HaxeFlixel.

**Comment by skial** [comment]
- [ ] `[video]` Rogue of Vallas Devlog 12: AI Redesign (Part 1) [video](https://www.youtube.com/watch?v=60BrJNArwC0&feature=youtu.be) by [Merrak](https://twitter.com/merrak/status/1357918370700607490).

**Comment by skial** [comment]
- [ ] `[open source]` littleBigInt `0.1.3` has been [released](https://github.com/maitag/littleBigInt/releases/tag/0.1.3).

**Comment by skial** [comment]
- [ ] `[video]` 3. How to quickly setup HaxeFlixel from scratch - Shader course [video](https://www.youtube.com/watch?v=AMDpLtWSzpw) by Richard Oliver Bray.

**Comment by Beeblerox** [comment]
- [ ] [ArmorPaint. News. February 4, 2021](https://www.youtube.com/watch?v=VQC37g4Ogi8&feature=youtu.be) by [Alexander Kiryanov](https://twitter.com/AlexandrKiryan3/status/1357337743991296008)

**Comment by Beeblerox** [comment]
- [ ] [Heck House](https://axolstudio.itch.io/heck-house) and [Spooksville, USA](https://axolstudio.itch.io/spooksville-usa) by [Axol Studio](https://twitter.com/AxolStudio/status/1357691354655121411) now have playable Mac and Linux versions
- [ ] Axol Studio has also [introduced](https://twitter.com/AxolStudio/status/1359185038449856520) their 2nd Monthly Mini-Game: The Pawspector! Explore a rugged & dangerous valley to collect gold - but be careful! This valley carries a deadly curse!

**Comment by Beeblerox** [comment]
- [ ] [Modern-looking procgen mansion](https://twitter.com/watawatabou/status/1359186526257741828) by Oleg Dolya

**Comment by Beeblerox** [comment]
- [ ] RobClemmonsJr got some [new plant shop pixelart](https://twitter.com/RobClemmonsJr/status/1358060722564005888) for [Moon plants of horror](https://claybrickentertainment.itch.io/moon-plants-of-horror)

**Comment by Beeblerox** [comment]
- [ ] Lubos Lenco is working on [procedural edge wear materials](https://twitter.com/luboslenco/status/1358067349182701571) for ArmorPaint.

**Comment by Beeblerox** [comment]
- [ ] Rosa Hernández has shared some photos and GIFs of Hvem Spiser Hvem? by [ʇ0mmy](https://twitter.com/d0oo0p):
    * Level 1: [find out what the cod eats](https://twitter.com/stereoscopica/status/1358039538057289729)
    * Level 2: [Now find out what the goby fish eats...](https://twitter.com/stereoscopica/status/1358039984696135681)
    * Level 3: [Finally find out what copepods eat...](https://twitter.com/stereoscopica/status/1358040455053791233)
    * [a scoreboard at the end](https://twitter.com/stereoscopica/status/1358041462252965891)
    * Hvem Spiser Hvem? is [a part of a bigger installation](https://twitter.com/stereoscopica/status/1358043746982637571) showcasing research in the Oslo fiord by the Frisk Oslofjord project

**Comment by Beeblerox** [comment]
- [ ] norDev has shared some progress on node based fluid solver:
    * [Finally have shaders running](https://twitter.com/norDevSoft/status/1358210517949534209)
    * [A terrible quality video](https://twitter.com/norDevSoft/status/1359377962538176512) of the software working with a shader and mouse input

**Comment by Beeblerox** [comment]
- [ ] [Upcoming new arena setup](https://twitter.com/kennygoff/status/1359312796580724737) in [Double Turn](https://doubleturngame.com/) by Kenny Goff

**Comment by Beeblerox** [comment]
> * [ ]  [Gepatto](https://twitter.com/gepatto/status/1358120319869984768) previews FlxTeroids running on a Raspberry Pi 4 using HaxeFlixel.

- [ ] And [another video](https://www.youtube.com/watch?v=rR4z3xchAd8&feature=youtu.be) showing HaxeFlixel Pong on a Raspberry Pi 4 with a custom USB rotary Encoder. Based on [HaxeFlixel Crash Course](https://www.ohsat.com/tutorial/flixel/hf-pong/) tutorial by Andrej

**Comment by Beeblerox** [comment]
- [ ] andretchen from Haxe Discord server has made [Crush course](https://andretchen.itch.io/crush-course) for  Weekly Game Jam 186 using using Haxe, Heaps and deepnightlibs

**Comment by Beeblerox** [comment]
- [ ] [torcado](https://twitter.com/torcado/status/1359632373051195406) is working on Heck Deck full time now. The game will be published by Plug In Digital.

**Comment by Beeblerox** [comment]
- [ ] Haxe 4.2 release got much [attention on Hacker News](https://news.ycombinator.com/item?id=26082347)!

**Comment by skial** [comment]
- [ ] `[core/analyzer]` `String -> ConstCharStar` generates invalid code [issue](https://github.com/HaxeFoundation/haxe/issues/10112).

**Comment by skial** [comment]
- [ ] `[core/jvm]` Request for implementation of JSR-45 Source Maps to allow for debugging with IDEs and JDB [feature request](https://github.com/HaxeFoundation/haxe/issues/10111).
