### ISSUE TITLE
Haxe Roundup 568

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#848]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[open source]` [hx-terminal-colors `git`](https://github.com/dyoung2019/hx-terminal-colors) - For displaying colored console/terminal output with haxe (i.e.chalk).

**Comment by skial** [comment]
- [ ] `[community]` Try the **new** [try.haxe.org](https://community.haxe.org/t/try-the-new-try-haxe/2921?u=skial)! :star:

**Comment by skial** [comment]
- [ ] `[community]` Haxe `4.2.1` has been [released](https://community.haxe.org/t/haxe-4-2-1-is-released/2920?u=skial)!

**Comment by skial** [comment]
- [ ] `[open source]` LDtk version `0.8.0` has been [released](https://github.com/deepnight/ldtk/releases/tag/v0.8.0).
  > Level custom fields, resizable entities and more!

**Comment by skial** [comment]
- [ ] `[open source]` [Studio `git`](https://github.com/twinspire/Studio) - An integrated editor for building video games, software applications and more.

**Comment by skial** [comment]
- [ ] `[open source]` [android-orientation `git`](https://github.com/danielpancake/android-orientation) - Haxe extension which allows you to set screen orientation on Android.

**Comment by skial** [comment]
- [ ] `[closed source]` [Game editor](https://twitter.com/IanHarrigan1982/status/1365249040624066564) written by [JKB Games](https://twitter.com/JKBGames) using HaxeUI targeting OpenFL.

**Comment by skial** [comment]
- [ ] `[open source]` Heaps `1.9.0` has been [released](https://twitter.com/ncannasse/status/1365979027987693569).

**Comment by skial** [comment]
- [ ] `[core/null safety]` Possible null safety hole with structs and/or monomorphs [issue](https://github.com/HaxeFoundation/haxe/issues/10147).

**Comment by skial** [comment]
- [ ] `[jobs]` Remove solar powered games job listing.

**Comment by skial** [comment]
- [ ] `[community]` Haxe: Using class reification in @:build macros [article](https://yal.cc/haxe-using-class-reification-in-build-macros/) by [Vadam](https://twitter.com/yellowafterlife).

**Comment by skial** [comment]
- [ ] `[core/type system]` Type inference vs call return types vs abstract casts [issue](https://github.com/HaxeFoundation/haxe/issues/10149).

**Comment by skial** [comment]
- [ ] `[core]` Unexpected behavior when using #if with an unspecified define [issue](https://github.com/HaxeFoundation/haxe/issues/10152).

**Comment by skial** [comment]
- [ ] `[core]` Typedef unification [issue](https://github.com/HaxeFoundation/haxe/issues/10154).

**Comment by skial** [comment]
- [ ] libs
  - [zenscriptbuilder `0.1.0`](https://lib.haxe.org/p/zenscriptbuilder)
  - [graphql_lib `0.0.1`](https://lib.haxe.org/p/graphql_lib)
  - [redistHelper `0.4.8`](https://lib.haxe.org/p/redistHelper)
  - [sfhaxe `0.1.1`](https://lib.haxe.org/p/sfhaxe)
  - [fonthx `0.0.3`](https://lib.haxe.org/p/fonthx)
  - [ldtk-haxe-api `0.8.1-rc.1`](https://lib.haxe.org/p/ldtk-haxe-api)
  - [ecso `1.0.0-alpha.3`](https://lib.haxe.org/p/ecso)
  - [pony `1.4.3`](https://lib.haxe.org/p/pony)
  - [haxentric `1.1.1`](https://lib.haxe.org/p/Haxentric)
  - [formatter `1.12.0`](https://lib.haxe.org/p/formatter)
  - [externs `0.5.2`](https://lib.haxe.org/p/externs)
  - [heaps `1.9.0`](https://lib.haxe.org/p/heaps)
  - [screeps-externs `0.0.4`](https://lib.haxe.org/p/screeps-extern)
  - [pancake `1.0.14`](https://lib.haxe.org/p/Pancake)

**Comment by skial** [comment]
- [ ] `[open source]` [Phidgets.hx `git`](https://github.com/LogicInteractive/Phidgets.hx) - Phidgets for the Haxe c++ target by [ʇ0mmy](https://twitter.com/d0oo0p).

**Comment by skial** [comment]
- [ ] `[closed source]` _"Win a match, jump in the bath, simple"_ by [Jano Games](https://twitter.com/jano_games/status/1366685531321602052), made with Stencyl.

**Comment by skial** [comment]
- [ ] `[community]` Haxe `4.2.0` – Module Level Fields Update [article](https://kinocreates.io/development-blog/haxe-4-2-0-module-level-fields-update/) by [Kino Rose](https://twitter.com/EISKino/status/1366209125701607427).

**Comment by skial** [comment]
- [ ] `[app releases]` [Goldspace](https://mabafu.com/goldspace/), _a twin-stick shooter pixel game, packaged in space exploration_ has been released. Check out the release [trailer](https://www.youtube.com/watch?v=9RJWBixbcuI&feature=emb_logo). Made with Stencyl, via [Luyren](https://twitter.com/LuyrenStencyl/status/1366107280719175686).

**Comment by skial** [comment]
- [ ] `[closed source]` Check out some random gameplay from Go! Go! PogoGirl by [Andrej](https://twitter.com/ohsat_games/status/1365698647627857922) from Oshat Games.

**Comment by skial** [comment]
- [ ] `[video]` Check out the [mobile preview](https://www.youtube.com/watch?v=vglsK81ymLk) of Northgard via [Playdigious](https://twitter.com/Playdigious/status/1365376525336510467).

**Comment by skial** [comment]
- [ ] `[open source]` Collapsible labels are now in HaxeUI core as pure CSS, by [Ian Harrigan](https://twitter.com/IanHarrigan1982/status/1365256206294650883).

**Comment by skial** [comment]
- [ ] `[closed source]` [Techy Wrinkles](https://twitter.com/techywrinkles/status/1366926182814474242) has spent some time experimenting with Heaps & HashLink.

**Comment by skial** [comment]
- [ ] `[closed source]` _"The Hordes are coming"_ a HaxeFlixel test by [Questionable Programming](https://twitter.com/QuestionablePr5/status/1366335400369913856).

**Comment by skial** [comment]
- [ ] `[closed source]` To celebrate their complete attack & animation overhaul, [Renaine](https://twitter.com/OctosoftUS/status/1365731209121259520) devs shares a new combo video!

**Comment by skial** [comment]
- [ ] `[closed source]` Check out [Mine Blocks](https://twitter.com/Mine_Blocks/status/1365325639327375367) weekly _last_ Friday Mine Blocks Beta update!

**Comment by skial** [comment]
- [ ] `[community`] Newgrounds is hosting the [Friday Night Funkin' Animation Jam](https://www.newgrounds.com/bbs/topic/1464702)!
  > Many of you have likely noticed Friday Night Funkin’ is a huge hit, on its way to becoming the most popular game in the history of NG.
  > To celebrate, we’re hosting a Friday Night Funkin’ Animation Jam, with a $5K prize pool from the Funkin’ team and over $1.4k from the community!

**Comment by Beeblerox** [comment]
- [ ] [Some UI elements](https://twitter.com/SyoPic/status/1364906984152182784) from Jitter Sandbox by Syo

**Comment by Beeblerox** [comment]
- [ ] New quick videos from WIP puzzle game by mauve:
    * friendly reliable [library guardians](https://twitter.com/mauvecow/status/1365765745011945472) (enemy)
    * [little bit of effects go a long way](https://twitter.com/mauvecow/status/1366116605055275011)
    * [lil' devil](https://twitter.com/mauvecow/status/1366803400143167491) animation
    * and [non-gameplay code todos](https://twitter.com/mauvecow/status/1365948380346650626)

**Comment by Beeblerox** [comment]
- [ ] [Pushing boxes and avoiding spikes](https://twitter.com/Rob1221dev/status/1365347428250091526) from WIP game by Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] HaxeFlixel Breakout Tutorial. [Part 2 - Balls and Walls](https://www.ohsat.com/tutorial/flixel/hf-breakout/hf-breakout-2/) by [Andrej](https://twitter.com/ohsat_games/status/1366380697120890880)
- [ ] [PogoGirl Devlog #13](https://www.ohsat.com/post/pogogirl-devlog/post13/): The Tools of Pogo by [Andrej](https://twitter.com/ohsat_games/status/1367123475354308610)

**Comment by Beeblerox** [comment]
- [ ] torcado has [added two more new cards](https://twitter.com/torcado/status/1365864708876738562). Both offensive this time

**Comment by Beeblerox** [comment]
- [ ] [Copy-paste + exciting news!](https://www.youtube.com/watch?v=zmocV6z9x14&feature=youtu.be) video by [RPG Playground](https://twitter.com/RPGplayground)

**Comment by Beeblerox** [comment]
- [ ] Some news from Axol Studio:
    * "Spooksville, USA" is [available to play FREE on Newgrounds with Medals](https://twitter.com/AxolStudio/status/1366410626311012353)!
    * [The Pawspector Launch stream](https://www.twitch.tv/videos/933625398)

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` _"The Hordes are coming"_ a HaxeFlixel test by [Questionable Programming](https://twitter.com/QuestionablePr5/status/1366335400369913856).

- [ ] And [Introduction to HaxeFlixel Part 0](https://www.youtube.com/watch?v=c9N-KBVRHFM) video on their YouTube channel

**Comment by Beeblerox** [comment]
- [ ] Lubos Lenco has released 2021.3 versions of [iron](https://github.com/armory3d/iron/releases/tag/21.03), [armory](https://github.com/armory3d/armory/releases/tag/21.03) and [zui](https://github.com/armory3d/zui/releases/tag/21.03)

**Comment by Beeblerox** [comment]
- [ ] [New screenshot](https://cdn.discordapp.com/attachments/774020763149271062/815524137254518795/4yp7d-kOXls.png) of inventory and crafting UI from WIP Kha-based game. via [Abstract_Panic](https://twitter.com/abstract_panic)

**Comment by Beeblerox** [comment]
- [ ] [Custom syntax highlight](https://cdn.discordapp.com/attachments/162664383082790912/816357000459583580/code-editor-2.gif) in scintilla (haxeui-html5 & haxeui-hxwidgets) by Ian Harrigan

**Comment by Beeblerox** [comment]
- [ ] [DAGGONE TROUBLE MAKIN SLIME](https://www.youtube.com/watch?v=ddD7aw1FWxI&feature=youtu.be) video from WIP OpenFl-based game by [Will Blanton](https://twitter.com/x01010111)

**Comment by Beeblerox** [comment]
- [ ] [Beginning of a decompiler](https://cdn.discordapp.com/attachments/162664383082790912/815025073751982090/unknown.png) for custom language. Made by Senk Ju with HaxeUI (hxwidgets backend)

**Comment by Beeblerox** [comment]
> * [ ]  `[open source]` LDtk version [`0.8.0`](https://github.com/deepnight/ldtk/releases/tag/v0.8.0) and [`0.8.1`](https://github.com/deepnight/ldtk/releases/tag/v0.8.1) have been released.
>   > Level custom fields, resizable entities and more!

- [ ] See [release notes](https://ldtk.io/release-notes/)

**Comment by Beeblerox** [comment]
- [ ] [Walking around and picking up items](https://cdn.discordapp.com/attachments/162664383082790912/814599723183767644/Picking_up__droping.gif) in WIP game by Nyrh from Haxe Discord server

**Comment by Beeblerox** [comment]
- [ ] [Typing game, maybe rhythm-based-adjacent](https://cdn.discordapp.com/attachments/162664383082790912/815718180152541204/snake.gif) by [MSGhero](https://twitter.com/MSGhero16). Made using [firedancer library](https://lib.haxe.org/p/firedancer/)

**Comment by Beeblerox** [comment]
- [ ] [timetrack](https://github.com/ZwodahS/timetrack) is a command line time tracking tool.
- [ ] [FlixelLightShader](https://github.com/IADenner/FlixelLightShader) is an alpha example of a simple lighting shader implemented in HaxeFlixel

**Comment by Beeblerox** [comment]
- [ ] [Medieval Fantasy City Generator 0.8.2](https://www.patreon.com/posts/48290708): basic integration with Armoria by [Oleg Dolya](https://twitter.com/watawatabou/status/1367216202729324548)

**Comment by skial** [comment]
- [ ] `[open source]` [psxcdmeta `git`](https://github.com/john32b/psxcdmeta) - Read metadata from PlayStation 1 CD images.
