### ISSUE TITLE
Haxe Roundup 571

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#854]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` No-op switch not eliminated by analyzer [issue](https://github.com/HaxeFoundation/haxe/issues/10188).

**Comment by skial** [comment]
- [ ] `[core]` Abstract implicit cast prevents finding explicit one [issue](https://github.com/HaxeFoundation/haxe/issues/10187).

**Comment by skial** [comment]
- [ ] `[crypto]` FIX: Aes, Blowfish, Des and Twofish decrypt() functions [pull request](https://github.com/HaxeFoundation/crypto/pull/16).

**Comment by skial** [comment]
- [ ] `[core]` Compiler define flags switching dash to underscore can result in flag defined with two values [issue](https://github.com/HaxeFoundation/haxe/issues/10184).

**Comment by skial** [comment]
- [ ] `[tink_web]` A way to just obtain a route's URL without invoking it [issue](https://github.com/haxetink/tink_web/issues/122).

**Comment by skial** [comment]
- [ ] `[video]` Introduction to HaxeFlixel [Part 3](https://www.youtube.com/watch?v=wPylW0g2Dfw&widget_referrer=haxe.io) by Questionable Programming.

**Comment by joshtynjala** [comment]
In the _People & Projects to support_ section:

- [ ] [Josh Tynjala](https://github.com/sponsors/joshtynjala) is working on Feathers UI — open source, cross-platform UI components built with OpenFL

Thanks! 🍻

**Comment by skial** [comment]
- [ ] `[open source]` [colyseus-haxe `0.14.8`](https://github.com/colyseus/colyseus-haxe/releases/tag/0.14.8) has been released.

**Comment by skial** [comment]
- [ ] libs
  - [colyseus `0.14.8`](https://lib.haxe.org/p/colyseus)
  - [cctweaked `2.1.0`](https://lib.haxe.org/p/cctweaked)
  - [vshaxe `2.23.0`](https://lib.haxe.org/p/vshaxe)
  - [dropecho.dungen `1.4.0`](https://lib.haxe.org/p/dropecho.dungen)
  - [dropecho.ds `1.4.0`](https://lib.haxe.org/p/dropecho.ds)
  - [dropecho.interop `0.3.0`](https://lib.haxe.org/p/dropecho.interop)
  - [pancake `1.0.17`](https://lib.haxe.org/p/Pancake)
  - [godot `3.2.3`](https://lib.haxe.org/p/godot)

**Comment by skial** [comment]
- [ ] `[community]` HF Breakout 3 - Hitting Bricks [tutorial](https://www.ohsat.com/tutorial/hf-breakout/hf-breakout-3/index.php) by  [Andrej](https://twitter.com/ohsat_games), publicly available on the 27th March.

**Comment by skial** [comment]
- [ ] `[open source]` [haxelock `git`](https://github.com/snsvrno/haxelock) - A basic Haxe build tool for keeping the dependencies and Haxe locked.

**Comment by skial** [comment]
- [ ] `[open source]` [haxe-stretch `git`](https://github.com/nadako/haxe-stretch) - Experimental port of https://github.com/vislyhq/stretch to Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [haxe_macro_compiler_example `git`](https://github.com/PXshadow/haxe_macro_compiler_example) - An example Haxe macro compiler.

**Comment by skial** [comment]
- [ ] `[closed source]` [Renaine](https://twitter.com/OctosoftUS/status/1373313886972112897) testing out their new combo counter by breaking it.

**Comment by skial** [comment]
- [ ] `[closed source]` [LDenner](https://discord.com/channels/162395145352904705/162664383082790912/822973675791319058) has added a target for testing actual weapon DPS via the [Haxe Discord](https://discord.com/invite/0uEuWH3spjck73Lo) channel.

**Comment by skial** [comment]
- [ ] `[closed source]` [Mig Moog](https://twitter.com/Mig_Moog/status/1373672964969889792?s=20) is _"making a fangame of [@Levi__Ramirez's](https://twitter.com/Levi__Ramirez) The Glutton's Spray. It's made with HaxeFlixel and Austin East's physics library echo"_.

**Comment by skial** [comment]
- [ ] `[closed source]` Failed docking of the "Soyuz" spacecraft in Jitter Sandbox by [Syo](https://twitter.com/SyoPic/status/1373241425610076168), made with Heaps.

**Comment by skial** [comment]
- [ ] `[closed source]` `WIP` Super Cosmic Heist [World 2-4](https://twitter.com/FierceTheBandit/status/1374194154310369280) by Fierce, made in Stencyl.

**Comment by skial** [comment]
- [ ] `[closed source]` _"Look at those little guys go! Made this game in a week with Haxe and HaxeFlixel ."_ by [Kino Rose](https://www.instagram.com/p/CMt_--9De8t/?igshid=17j3pfmvzshf4).

**Comment by skial** [comment]
- [ ] `[community]` LunaTechs - Case Files RPGMaker Plugin [article](https://kinocreates.io/resources/rpgmaker/lunatechs-case-files-rpgmaker-plugin/) by [Kino Rose](https://twitter.com/EISKino/status/1373349208456105986).

**Comment by skial** [comment]
- [ ] `[closed source]` _"👺get him, boys!"_ by [1speed](https://twitter.com/1speed2gamedev/status/1373223124263649284).

**Comment by skial** [comment]
- [ ] `[closed source]` Today's weekly [Mine Blocks](https://twitter.com/Mine_Blocks/status/1372954839513235462) Beta update includes xp orbs, functioning eyes of ender and 5000 lines of code for mobs being ported.

**Comment by AndreiRudenko** [comment]
`[open source]` [nuc `git`](https://github.com/nuclibs/nuc) - Lightweight Cross-platform 2D game framework.

**Comment by Beeblerox** [comment]
- [ ] Dicey Dungeons v1.11 is now live on Steam and Itch! [Read all about it here](https://store.steampowered.com/news/app/861540/view/3025829261298867272). via [Terry Cavanagh](https://twitter.com/terrycavanagh/status/1372519494145376261)

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` Failed docking of the "Soyuz" spacecraft in Jitter Sandbox by [Syo](https://twitter.com/SyoPic/status/1373241425610076168), made with Heaps.

- [ ] And Syo has launched [a simple site for Jitter Sandbox](https://jittergame.com/)

**Comment by Beeblerox** [comment]
- [ ] Couple of videos from gepatto:
    * [Haxeflixel Breakout Example](https://twitter.com/gepatto/status/1372582178815623173) on a RaspberryPi 4 with a RaspberryPi Pico as a usb-gamepad
    * [Haxeflixel demo “Flixius” running on a Raspberry Pi 4 at 800x600](https://twitter.com/gepatto/status/1373254705372131330). You can also [get binary](https://t.co/o0ttvuHMc1?amp=1) to run it on your device

**Comment by Beeblerox** [comment]
- [ ] [3B New Hallucination Effects](https://www.youtube.com/watch?v=MKr-qLq47eE) from [Steel Seraph](https://twitter.com/steelseraphgame/status/1372583020943785993)

**Comment by Beeblerox** [comment]
> * [ ]  `[video]` Stencyl Tutorial Series: Actor Aura and After Image Update [video](https://www.youtube.com/watch?v=a6ro_pspcd4&widget_referrer=haxe.io) by [Luyren](https://twitter.com/LuyrenStencyl/status/1372735790313316355).

- [ ] And [Luyren](https://twitter.com/LuyrenStencyl/status/1374436284228276237) has [added an input buffer](https://luyren.itch.io/luyren-ai-and-combat-pack/devlog/234945/input-buffer-update) for all attacks/commands in AI and Combat pack

**Comment by Beeblerox** [comment]
- [ ] [The first attempt](https://twitter.com/QuestionablePr5/status/1374672369093124100) at creating a proper boss by Questionable Programming

**Comment by Beeblerox** [comment]
- [ ] The BadSeed DLC for Dead Cells is coming March 30th on your mobile devices! via [Playdigious](https://twitter.com/Playdigious/status/1372850339196456964)

**Comment by Beeblerox** [comment]
- [ ] Some experiments from Oleg Dolya, which i believe will end up in Medieval Fantasy City Generator:
    * This kind of [polygon partitioning](https://twitter.com/watawatabou/status/1372871896266588161) looks promising
    * [Neighbourhoods](https://twitter.com/watawatabou/status/1374726659870449664)

**Comment by Beeblerox** [comment]
- [ ] [New quick video](https://twitter.com/GlassySundew/status/1373415776368144384) by GlassySundew showcasing savegames management

**Comment by Beeblerox** [comment]
- [ ] A proof-of-concept [generator for a Truncated Cone](https://twitter.com/MatthijsKamstra/status/1372892962804367361) by Matthijs Kamstra. 
- [ ] [Another generated papertoy](https://twitter.com/MatthijsKamstra/status/1372892972413501440) from an unfinished book

**Comment by Beeblerox** [comment]
- [ ] Dead Cells sold [1 million copes in China](https://www.gamasutra.com/view/news/378717/Dead_Cells_sold_1_million_copes_in_China_within_a_few_days_of_launch.php) 'within a few days' of launch

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` _"japanese_goblinget him, boys!"_ by [1speed](https://twitter.com/1speed2gamedev/status/1373223124263649284).

- [ ] And [a night-day GIF](https://discord.com/channels/162395145352904705/162664383082790912/824369275702738954) from Haxe Discord server

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` [Renaine](https://twitter.com/OctosoftUS/status/1373313886972112897) testing out their new combo counter by breaking it.

- [ ] this game does [look a lot better zoomed in](https://twitter.com/squuuidly/status/1374773291710287876)

**Comment by Beeblerox** [comment]
- [ ] [Music Teaser](https://www.youtube.com/watch?v=onyUQfgMM2s&feature=youtu.be) for [Patches Of Adventure](https://claybrickentertainment.itch.io/patches-of-adventure)

**Comment by Beeblerox** [comment]
- [ ] [Screenshot from shakesode](https://twitter.com/shakesoda/status/1373544208523354113) showing Haxe hl/c + bgfx running happily on m1 mac mini

**Comment by Beeblerox** [comment]
- [ ] mauve is [back to making obnoxious puzzles again](https://twitter.com/mauvecow/status/1373798465432555521)

**Comment by Beeblerox** [comment]
- [ ] [hmm.. what could this be?](https://twitter.com/torcado/status/1373766865735069702) from WIP game Heck Deck by torcado

**Comment by Beeblerox** [comment]
- [ ] SCRAPS OF LIGHT GAME is [working on really dark hallways](https://twitter.com/joelgervasi/status/1372577383388229633), using really old rendering techniques.

**Comment by Beeblerox** [comment]
- [ ] [Simple physics with Heaps](https://twitter.com/techywrinkles/status/1373612375270645763) by Techy Wrinkles

**Comment by Beeblerox** [comment]
- [ ] [The industrial scenario](https://twitter.com/SpirkopGames/status/1374308930554302473) of [Energy Island Corp.](https://store.steampowered.com/app/1241710/Energy_Island_Corp/) by Spirkop games

**Comment by Beeblerox** [comment]
- [ ] [community.haxe.org](https://community.haxe.org/) is back up again!

**Comment by Beeblerox** [comment]
- [ ] [Portals and gravity](https://twitter.com/Rob1221dev/status/1374369669537222656) from WIP game by Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] Arachnowopunk by [Benny Heller](https://twitter.com/e1sif/status/1374808201825288196) is now available free o[n IOS](https://apps.apple.com/app/id1556964377)!

**Comment by Beeblerox** [comment]
- [ ] [does this count as a chorus line?](https://twitter.com/ohsat_games/status/1374804187716915201) from Go! Go! PogoGirl by Andrej

**Comment by Beeblerox** [comment]
- [ ] [A HaxeUI Basic Gui](https://github.com/fredlangva/HaxeUI_Base) by Fred Langva

**Comment by Beeblerox** [comment]
- [ ] [The palindromes are actually really hard to type](https://cdn.discordapp.com/attachments/162664383082790912/822936804969545748/got_ourselves_a_game.gif). You're typing LTR but then the remaining letters are back where you started. By [Nick](https://twitter.com/MSGhero16)

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` `_dyn` can make HXCPP fail [issue](https://github.com/HaxeFoundation/haxe/issues/10191).

**Comment by skial** [comment]
Thank you @joshtynjala and @AndreiRudenko for this weeks contributions 👍 

And as always, thank you @Beeblerox for the continued contributions making each roundup better 🙏🌟
