### ISSUE TITLE
Haxe Roundup 572

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#856]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by kevinresol** [comment]
BeeInventor is now also recruiting in Hong Kong.

https://community.haxe.org/t/hiring-haxe-fullstack-developer-in-taipei/2836/2

**Comment by skial** [comment]
- [ ] `[core]` Type param constraint regression [issue](https://github.com/HaxeFoundation/haxe/issues/10198).

**Comment by skial** [comment]
- [ ] `[core/draft]` Tackle field inits in this-before-super situaton [pull request](https://github.com/HaxeFoundation/haxe/pull/10197).

**Comment by skial** [comment]
- [ ] `[core]` Parametrized constraints choke on inheritance [fixed](https://github.com/HaxeFoundation/haxe/issues/5890#event-4509847594).

**Comment by skial** [comment]
- [ ] `[core/hl]` Values assigned inside of nested `catch` are discarded [issue](https://github.com/HaxeFoundation/haxe/issues/9174).

**Comment by skial** [comment]
- [ ] `[evolution]` `enum abstract` over `enum` [proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/87).

**Comment by skial** [comment]
- [ ] libs
  - [externs `0.5.5`](https://lib.haxe.org/p/externs)
  - [Haxentric `1.1.2`](https://lib.haxe.org/p/Haxentric)
  - [sfhaxe `0.3.0`](https://lib.haxe.org/p/sfhaxe)
  - [hxasync `1.1.0`](https://lib.haxe.org/p/hxasync)
  - [genes `0.4.1`](https://lib.haxe.org/p/genes)

**Comment by skial** [comment]
- [ ] `[video]` Rogue of Vallas Devlog 14: World Building [video](https://www.youtube.com/watch?v=wqZF9dTL0QE&widget_referrer=haxe.io) by [Merrak](https://twitter.com/merrak/status/1375333237686427650).
- [ ] `[video]` Rogue of Vallas Level 1-1 Playthrough [video](https://www.youtube.com/watch?v=3ZW_x-uA9AI&widget_referrer=haxe.io) by Merrak.

**Comment by skial** [comment]
- [ ] `[video]` EP10. Adding a border / outline to a HaxeFlixel spite using a shader - Shader Course [video](https://www.youtube.com/watch?v=LCIBJutZPT0&widget_referrer=haxe.io) by Richard Oliver Bray.
- [ ] `[video]` You can now use Haxe to make a Godot gamev | HaxeGodot [video](https://www.youtube.com/watch?v=WlZGJ5c2FFE&widget_referrer=haxe.io) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] `[closed source]` `WIP` [Kino Rose](https://twitter.com/EISKino/status/1377203744899751937) dynamically loading Aseprite files and their animation tags in HaxeFlixel.

**Comment by skial** [comment]
- [ ] `[closed source]` The chairman's cat in [Jano Games](https://twitter.com/jano_games/status/1376630545711517702) football manager game, is causing all sorts of problems. Made in Stencyl.

**Comment by skial** [comment]
- [ ] `[community]` Database with Depot [article](https://kinocreates.io/tutorials/haxe-database-with-depot/) by [Kino Rose](https://twitter.com/EISKino/status/1376607127960174599).

**Comment by skial** [comment]
- [ ] `[community]` Closed Hands Interview - Challenging Our Perception Of A "Video Game" [article](https://www.thegamer.com/closed-hands-interview-video-game-perception/) via [PΔSSENGER](https://twitter.com/passengergames/status/1376466836896776193).

**Comment by skial** [comment]
- [ ] `[closed source]` Some visual improvements by [1speed](https://twitter.com/1speed2gamedev/status/1375751149949714434) from their indie game.

**Comment by skial** [comment]
- [ ] `[community]` HaxeFlixel Groups & Collisions [article](https://kinocreates.io/tutorials/haxeflixel-groups-collisions/) by [Kino Rose](https://twitter.com/EISKino/status/1375557451693559818).

**Comment by skial** [comment]
- [ ] `[video/music]` [PΔSSENGER](https://twitter.com/passengergames/status/1375435473850675206) have released the soundtrack of CLOSED HANDS available now on itch.io.

**Comment by skial** [comment]
- [ ] `[closed source]` [Joel](https://twitter.com/joelgervasi/status/1375810198376439809) shows off the animation for picking up discs in their dungeon crawler made with Heaps.

**Comment by skial** [comment]
- [ ] `[community]` The pieces of the Pi Puzzle [article](https://www.patreon.com/posts/pieces-of-pi-49269562) by [Patrick](https://twitter.com/gepatto/status/1375775090844049410).
- [ ] `[patreon]` [Patrick](https://www.patreon.com/gepatto) is creating Raspberry Pi 4 support for Haxe/Lime/Openfl/HaxeFlixel.

**Comment by skial** [comment]
- [ ] `[closed source]` In a recent [Realmkit](https://twitter.com/realmkitapp?lang=en) stream, Daniel made it so the eraser & normal brushes toggled between the physical part of the tablet stylus, shared over on the Haxe Discord [channel](https://discord.com/channels/162395145352904705/162664383082790912/825875956215840818).

**Comment by Beeblerox** [comment]
i'm really sorry, but i can't help this week. i'm under strict deadline, which i'm failing to achieve :(

**Comment by skial** [comment]
No problem @Beeblerox, I always appreciate your help. I hope you make the deadline 🙏👍

**Comment by skial** [comment]
- [ ] `[core]` Functions in macro parameters are not correctly processed [fixed](https://github.com/HaxeFoundation/haxe/issues/8605).

**Comment by skial** [comment]
- [ ] `[releases]` [IriySofts](https://twitter.com/IriySoft/status/1377301119827898378) latest HTML5 game made with OpenFL, Cycle Extreme, has been released onto [Game Disribution](https://gamedistribution.com/games/cycle-extreme).

**Comment by skial** [comment]
- [ ] `[closed source]` Lore character cards from Renaine, NFT-less claimable cards for [Mr. Bird Dad](https://twitter.com/OctosoftUS/status/1375482870651838465) and [Josephine Elizabeth Factoria](https://twitter.com/OctosoftUS/status/1377299061640998916)! 🎀

**Comment by skial** [comment]
- [ ] `[community]` HaxeFlixel Crash Course: Make a Pong Game in Under 1 Hour [article](https://www.ohsat.com/tutorial/flixel/hf-pong/) by [Andrej](https://twitter.com/ohsat_games/status/1377533695704322050) from Ohsat Games.

**Comment by skial** [comment]
- [ ] `[closed source]` Meet The Striker 💪 from [Double Turn](https://twitter.com/doubleturngame/status/1377282037640486914) who's signature move is Leaping Knee Strike! 💥

**Comment by skial** [comment]
- [ ] `[closed source]` Check out all of the [Chapter 2 teases](https://www.reddit.com/r/Spellbreak/comments/m20ssa/spellbreak_chapter_2_teases_megathread/) from Spellbreak's upcoming The Fracture release, releasing on April 8th!
