### ISSUE TITLE
Haxe Roundup 574

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#860]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core/php]` enum/class named Attribute will fail at runtime with PHP 8 [issue](https://github.com/HaxeFoundation/haxe/issues/10207).

**Comment by skial** [comment]
- [ ] `[community]` Feature Showcase: `overload`'s in Haxe `4.2` [article](https://community.haxe.org/t/feature-showcase-overloads-in-haxe-4-2/2971?u=skial) by George Corney.

**Comment by skial** [comment]
- [ ] `[open source]` Feathers UI `1.0.0-beta.3` for Haxe and OpenFL has been [released](https://github.com/BowlerHatLLC/feathersui-openfl/releases/tag/v1.0.0-beta.3).

**Comment by skial** [comment]
- [ ] `[community]` The HaxeIn 2021 [schedule](https://community.haxe.org/t/the-first-haxein-of-2021-is-just-around-the-corner/2968/4?u=skial) for tomorrows event has been released.

**Comment by skial** [comment]
- [ ] `[core/hxcs]` You need to define `unsafe` to be able to use unsafe code in hxcs with dotnet `5.0` [issue](https://github.com/HaxeFoundation/hxcs/issues/51).

**Comment by skial** [comment]
- [ ] libs
  - [electron `12.0.4`](https://lib.haxe.org/p/electron)
  - [Console.hx `0.2.14`](https://lib.haxe.org/p/Console.hx)
  - [redistHelper `0.4.10`](https://lib.haxe.org/p/redistHelper)
  - [feathersui `1.0.0-beta.3`](https://lib.haxe.org/p/feathersui)
  - [cctweaked `2.3.0`](https://lib.haxe.org/p/cctweaked)
  - [hxfsm `2.0.2`](https://lib.haxe.org/p/hxfsm)
  - [Haxentric `1.1.3`](https://lib.haxe.org/p/Haxentric)
  - [flixel-addons `2.10.0`](https://lib.haxe.org/p/flixel-addons)
  - [flixel `4.9.0`](https://lib.haxe.org/p/flixel)
  - [openfl `9.1.0`](https://lib.haxe.org/p/openfl)
  - [pony `1.4.4`](https://lib.haxe.org/p/pony)

**Comment by skial** [comment]
- [ ] `[community]` Parade of Parasites: DQ2 [progress report](https://www.fortressofdoors.com/parade-of-parasites-dq2-progress-report-for-february-2021/) for March 2021 by [Lars Doucet](https://twitter.com/larsiusprime).

**Comment by skial** [comment]
- [ ] `[community]` Feathers UI beta.3 preview build on Haxelib [article](https://feathersui.com/blog/2021/04/12/feathers-ui-beta-3-preview.html) by [Josh Tynjala](https://twitter.com/feathersui/status/1382047275577348096).

**Comment by skial** [comment]
- [ ] `[community]` PogoGirl Devlog `#14`: How I Build Levels [article](https://www.ohsat.com/post/pogogirl-devlog/post14/) by [Andrej](https://twitter.com/ohsat_games/status/1380717170645155843).

**Comment by skial** [comment]
- [ ] `[open source]` [yaku_core `git`](https://github.com/scottPlusPlus/yaku_core) - Utils / helper methods for working with some core data types (Nullable, Outcome, etc).

**Comment by skial** [comment]
- [ ] `[open source]` [pmmp-haxe `git`](https://github.com/pmmp-haxe/pmmp-haxe) - Haxe Externs for @pmmp Minecraft Bedrock Edition Server Software.

**Comment by skial** [comment]
- [ ] `[video]` Rogue of Vallas Devlog 15: NPC Strategies [video](https://www.youtube.com/watch?v=FctzAGUPHng) by Merrak.

**Comment by skial** [comment]
- [ ] `[video]` Introduction to HaxeFlixel [Part 6](https://www.youtube.com/watch?v=kaztW_sH1W0&widget_referrer=haxe.io) by Questionable Programming.

**Comment by skial** [comment]
- [ ] `[community]` An in depth [guide](https://mig-moog.newgrounds.com/news/post/1157692) on setting up HaxeFlixel by [Mig Moog](https://twitter.com/Mig_Moog/status/1381707687910576129).

**Comment by skial** [comment]
- [ ] `[open source]` [TPLinkSmartcontroller.hx `git`](https://github.com/LogicInteractive/TPLinkSmartcontroller.hx) - TP-Link WiFi SmartPlug Controller for written for Haxe `4.2`+ by [ʇ0mmy](https://twitter.com/d0oo0p/status/1381884391308337153).

**Comment by skial** [comment]
- [ ] `[closed source]` The look of the chairman has changed in [Jano Games](https://twitter.com/jano_games/status/1381849461203341318) football manager, to a lilac shirt and pony tail.

**Comment by skial** [comment]
- [ ] `[closed source]` [Fab](https://twitter.com/fab_jar/status/1381502370476089345) is playing around with Haxe and Heaps again.

**Comment by skial** [comment]
- [ ] `[open source]` [Patrick](https://twitter.com/gepatto/status/1381310229267251201) is testing HaxeFlixel on the RaspberryPi and different screens, with the results coming to his Patreon page soon.

**Comment by skial** [comment]
- [ ] `[community]` HaxeFlixel – Pathing In Your Game [article](https://kinocreates.io/tutorials/haxeflixel-pathing-in-your-game/) by [Kino Rose](https://twitter.com/EISKino/status/1381298819351076864).

**Comment by skial** [comment]
- [ ] `[code sample]` Abstract Enum methods & properties example by [Nanjizal](https://twitter.com/Nanjizal_net/status/1380989643987025926).

**Comment by skial** [comment]
- [ ] `[video/audio]` Digital artist [Dan Hett](https://twitter.com/danhett) discussing CLOSED HANDS, an interactive fiction game that spawned out of tragedy, about the politics behind and within the game, and the role it could play in tackling extremism in [The Bunker: Politics on Lockdown](https://twitter.com/bunker_pod/status/1380535983515561984) podcast.

**Comment by skial** [comment]
- [ ] `[closed source]` HaxeUI running in [`cmd.exe`](https://discord.com/channels/162395145352904705/162664383082790912/831632556284969060)...?

**Comment by Beeblerox** [comment]
- [ ] [CovalentLib](https://github.com/kevansevans/CovalentLib) by [Kaelan Evans](https://twitter.com/kbeevans) is a tool to read Pokemon Crystal rom. Sort of reverse engineered

**Comment by Beeblerox** [comment]
- [ ] [Peter Achberger](https://discord.com/channels/162395145352904705/162664383082790912/830062665904554014) has released public beta of [NextRealm Bubbles](https://nextrealm.io/bubbles/). Any feedback is appreciated. The game's client is Haxe + Phaser, and server is Haxe + NodeJS.

**Comment by Beeblerox** [comment]
- [ ] verdog from Haxe discord server is [making a state machine simulator](https://discord.com/channels/162395145352904705/162664383082790912/830518463860572231) thing for a CS course. You can play around with it at https://dogspluspl.us/nfal if you want to

**Comment by Beeblerox** [comment]
- [ ] [Shift day calendar test](https://discord.com/channels/162395145352904705/162664383082790912/830765135856795678) by Nanjizal

**Comment by Beeblerox** [comment]
- [ ] Baturinsky from Haxe discord server is making a game with Heaps, so here are two videos:
    * Melee weapon is [just a gun with inverse recoil](https://discord.com/channels/162395145352904705/162664383082790912/830825354930946088), short range and an invisible bullet.
    * Main theme of the game is the "contramotion" - [continuous travel back in time](https://discord.com/channels/162395145352904705/162664383082790912/831211672156241941).

**Comment by Beeblerox** [comment]
- [ ] [A very small demo](https://goop.wtf/haxeflixel/goldenaxe/) of progress by [bloodninja](https://discord.com/channels/162395145352904705/162664383082790912/830924780181258262) from Haxe discord server. Made with HaxeFlixel and LDtk. You need a controller attached to actually get past the start screen (press A on the xbox layout) but keyboard arrow buttons work in game too. ACCEPT = A (on xbox pad), PAUSE = start on gamepad, Enter on KB.

**Comment by Beeblerox** [comment]
- [ ] [Random Kha terminal](https://discord.com/channels/162395145352904705/162664383082790912/831139899632517150) by [Daniel Blaker](https://twitter.com/5Mixer). And a [video with added boot sound](https://discord.com/channels/162395145352904705/162664383082790912/831162551748132874)

**Comment by Beeblerox** [comment]
- [ ] [An Update/Poll](https://www.patreon.com/posts/is-this-actually-49792180) by [Axol Studio](https://twitter.com/AxolStudio/status/1380218721868906504)

**Comment by Beeblerox** [comment]
- [ ] Techy Wrinkles found time to get [player shots moving/changing smoothly](https://twitter.com/techywrinkles/status/1380406498128453632) by power level

**Comment by Beeblerox** [comment]
> * [ ]  `[community]` PogoGirl Devlog `#14`: How I Build Levels [article](https://www.ohsat.com/post/pogogirl-devlog/post14/) by [Andrej](https://twitter.com/ohsat_games/status/1380717170645155843).

- [ ] [Coyote physics thing](https://twitter.com/ohsat_games/status/1380949640225378309)

**Comment by Beeblerox** [comment]
- [ ] This week's Friday update of Mine Blocks [has all things pigs!](https://twitter.com/Mine_Blocks/status/1380584929185124355)

**Comment by Beeblerox** [comment]
- [ ] [Bestiary](https://twitter.com/SyoPic/status/1380772585529544706) of Jitter Sandbox by Syo

**Comment by Beeblerox** [comment]
- [ ] [Steel Seraph](https://twitter.com/steelseraphgame/status/1379954926974087172) had updated to 1.10.0 on Itch.io, Steam and GameJolt for Windows, Mac and Linux

**Comment by Beeblerox** [comment]
- [ ] hm.. [something happened](https://twitter.com/torcado/status/1380954916580175880) to torcado's cards in [Heck Deck](https://torcado.itch.io/heck-deck)

**Comment by Beeblerox** [comment]
> * [ ]  `[open source]` [Patrick](https://twitter.com/gepatto/status/1381310229267251201) is testing HaxeFlixel on the RaspberryPi and different screens, with the results coming to his Patreon page soon.

- [ ] [Testing Raspberry Pi support](https://twitter.com/gepatto/status/1381606983267143681) for HaxeFlixel on a Pi4 with a hyperpixel weirdly square display and a custom built rotaryencoder.

**Comment by Beeblerox** [comment]
- [ ] The harsh lands of Northgard by [Shiro Games](https://twitter.com/shirogames/status/1381957155708936193) can now officially be [conquered on iOS!](https://apps.apple.com/us/app/northgard/id1533979882)

**Comment by Beeblerox** [comment]
- [ ] [WIP construction](https://twitter.com/1speed2gamedev/status/1380895661260963846) from WIP game by 1speed Studio

**Comment by Beeblerox** [comment]
- [ ] [Strange guy](https://twitter.com/joelgervasi/status/1380904925434118147) from SCRAPS OF LIGHT GAME

**Comment by Beeblerox** [comment]
- [ ] [Drop and Merge Numbers](https://grantech.ir/matchs/) game by [Mansour Djawadi](https://twitter.com/MansourDjawadi/status/1381589698771046405). Made with OpenFL

**Comment by skial** [comment]
- [ ] `[community]` OpenFL `9.1.0` has been [released](https://community.openfl.org/t/openfl-9-1-0-release/12959?u=skial.bainn)!

**Comment by skial** [comment]
- [ ] `[open source/tink_sql]` Initial PostgreSQL support [pull request](https://github.com/haxetink/tink_sql/pull/129).

**Comment by skial** [comment]
- [ ] `[core]` Missing uninitialized local error when using local functions inside one of the branches [issue](https://github.com/HaxeFoundation/haxe/issues/10219).

**Comment by skial** [comment]
- [ ] `[releases]` [Fresh Juice Games](https://twitter.com/F_J_GAMES/status/1382393148538765325) is releasing the remastered edition of Food Forecast on April 28th to iOS and Android. Made with Stencyl.
