### ISSUE TITLE
Haxe Roundup 580

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#873]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[job]` HaxeFlixel RPG project [thread](https://community.haxe.org/t/haxeflixel-rpg-project/3056).

**Comment by anissen** [comment]
- [ ] [Ludum Dare 48 staff picks](https://github.blog/2021-05-19-ludum-dare-48-staff-picks/) article by GitHub highlights [Nuclear Blaze](https://github.blog/2021-05-19-ludum-dare-48-staff-picks/#nuclear-blaze) (Heaps), [Fetal Fury](https://github.blog/2021-05-19-ludum-dare-48-staff-picks/#fetal-fury) (HaxeFlixel), [Fishing Trouble](https://github.blog/2021-05-19-ludum-dare-48-staff-picks/#fishing-trouble) (Heaps) as well as a mention of [LDtk](https://github.blog/2021-05-19-ludum-dare-48-staff-picks/#deeper-and-deeper) (Heaps, Electron)

**Comment by anissen** [comment]
- [ ] The [Haxe](https://github.com/HaxeFoundation/haxe) git repository has reached 20,000 commits!

**Comment by skial** [comment]
- [ ] libs
  - [electron `13.0.0`](https://lib.haxe.org/p/electron)
  - [openfl-spine `1.6.2`](https://lib.haxe.org/p/openfl-spine)
  - [coconut.feathersui `1.0.3`](https://lib.haxe.org/p/coconut.feathersui)
  - [openfl-glsl `0.0.8`](https://lib.haxe.org/p/openfl-glsl)
  - [coconut.diffing `0.3.0`](https://lib.haxe.org/p/coconut.diffing)
  - [coconut.vdom `0.9.0`](https://lib.haxe.org/p/coconut.vdom)
  - [coconut.react-core `0.3.0`](https://lib.haxe.org/p/coconut.react-core)
  - [coconut.ui `0.12.0`](https://lib.haxe.org/p/coconut.ui)

**Comment by skial** [comment]
- [ ] `[community]` PogoGirl Devlog `#18`: A New Move + Demo Date [article](https://www.ohsat.com/post/pogogirl-devlog/post18/) by [Andrej](https://twitter.com/ohsat_games).

**Comment by skial** [comment]
- [ ] `[video]` Introduction to HaxeFlixel [Part 12](https://www.youtube.com/watch?v=l302BKWnJQo&widget_referrer=haxe.io) by Questionable Programming.

**Comment by skial** [comment]
- [ ] `[video]` Optional arguments in Haxe explained | Better than the way Typescript does it [video](https://www.youtube.com/watch?v=crEdJ8T_49c&widget_referrer=haxe.io) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] `[closed source]` [Jérémy Fa](https://twitter.com/jeremyfaivre/status/1397495120510033921) has managed to get Dear ImGui work with Haxe on both C# and JS targets. Check out their [demo](https://apps.jeremyfa.com/breaking-the-line/).

**Comment by skial** [comment]
- [ ] `[closed source]` [Syo](https://twitter.com/SyoPic/status/1397464668034187265) previews restrictive constructions from ARP Inc in their Jitter Sandbox, made with Heaps. How about [one more](https://twitter.com/SyoPic/status/1397467304888356866) ARP Inc test.

**Comment by anissen** [comment]
> * [ ]  `[closed source]` [Jérémy Fa](https://twitter.com/jeremyfaivre/status/1397495120510033921) has managed to get Dear ImGui work with Haxe on both C# and JS targets. Check out their [demo](https://apps.jeremyfa.com/breaking-the-line/).

A correction: the demo may be closed source, but the Dear ImGUI library bindings are open source (https://github.com/jeremyfa/imgui-hx) as is the game engine that uses the library (https://github.com/ceramic-engine/ceramic).

**Comment by skial** [comment]
- [ ] `[closed source]` Enemy sprite designs for Super Cosmic Heist by [Fierce](https://twitter.com/FierceTheBandit/status/1397337636239515651).

**Comment by skial** [comment]
- [ ] `[releases]` [Axel de Conti](https://twitter.com/AxelDeConti/status/1397110240374661120), Camille Berring, Benjamin Gobbé and Martin Ringot have released Greenwitch Grove, available from [itch.io](https://martinrgt.itch.io/greenwitch-grove). Made with Heaps.
  > In this plant-based puzzle game, you rebuild our post-collapse world by helping a plant to grow through the metal junk ruins from ancient times. Bend the five elements – Water, Earth, Air, Fire and Ether – and grow your way up - or down -  to the pentacle!

**Comment by skial** [comment]
- [ ] `[closed source]` Insightful football quotes are being added to Bad Soccer Manager by [Jano Games](https://twitter.com/jano_games/status/1397086233721966594), made with Stencyl.

**Comment by skial** [comment]
- [ ] `[community]` Learn how to create a full Breakout game in just 6 steps by [Andrej](https://twitter.com/ohsat_games/status/1397014563195953154) with his HaxeFlixel Breakout series.

**Comment by skial** [comment]
- [ ] `[releases]` [Ty](https://twitter.com/zzo__x/status/1397012628023689217) has released a rhythm game called Burgerline created for a jam, available on [itch.io](https://zzox.itch.io/burgerline) and [Newgrounds](https://www.newgrounds.com/portal/view/796227). Made with HaxeFlixel.

**Comment by skial** [comment]
- [ ] `[releases]` [Alessandro Pezzetti](https://twitter.com/hav24/status/1396861793327267844) has releases [Leap of Synth](https://www.havana24.net/?pag=games&sub=leap_the_synth), a rhythm platformer based on Synthwave music onto the [Apple Store](https://apps.apple.com/app/leap-the-synth/id1558083370) and the [Web](https://www.havana24.net/index.php?pag=play&sub=leap_the_synth).

**Comment by skial** [comment]
- [ ] `[closed source]` [Michael Bickel](https://twitter.com/dazKind/status/1395836060861612032) doing more Haxe Godot stuff...

**Comment by skial** [comment]
- [ ] `[closed source]` In [George Harpwood's](https://twitter.com/GeorgeHarpwood/status/1395722544997613572) game, if a mob kills you, they will celebrate it over your corpse. :clap: Made with HaxeFlixel.

**Comment by skial** [comment]
- [ ] `[open source]` [Squidly](https://twitter.com/squuuidly/status/1395465073527828494) is looking for collaborators to help make the ultimate tactics engine!

**Comment by skial** [comment]
- [ ] `[videos]` Haxe and OpenFL Tutorials: Part 1.2 "Setting up IntelliJ IDEA" [video](https://www.youtube.com/watch?v=5mFoLLsE4T0&widget_referrer=haxe.io) by Chris.

**Comment by skial** [comment]
- [ ] `[videos]` Haxe Godot [Experiment `#2`](https://www.youtube.com/watch?v=wYVBvDc0p7E) by Michael Bickel.

**Comment by skial** [comment]
- [ ] `[closed source/discord]` Skyfire [previews](https://discord.com/channels/162395145352904705/162664383082790912/845810797049544724), a new enemy type to Avoider, available on [itch.io](https://kurt-c0caine.itch.io/avoider).

**Comment by skial** [comment]
- [ ] `[releases/discord]` [Wayward](https://discord.com/channels/162395145352904705/162664383082790912/846507739613233153) has released Mammoth Herder, built for a class project, available on [itch.io](https://mammothherder.itch.io/mammoth-herder). Made with HaxeFlixel.

**Comment by skial** [comment]
- [ ] `[closed source/discord]` Dan [previews](https://discord.com/channels/162395145352904705/162664383082790912/846740027927953449) a marble sim!

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` In [George Harpwood's](https://twitter.com/GeorgeHarpwood/status/1395722544997613572) game, if a mob kills you, they will celebrate it over your corpse. clap Made with HaxeFlixel.

- [ ] You can play it on [itch.io](https://harpwood.itch.io/hxroguelike-a-roguelike-prototype-for-haxeflixel) and get source code [from github](https://github.com/harpwood/HxRogueLike)

**Comment by Beeblerox** [comment]
- [ ] Dylan Navas is [making progress](https://twitter.com/dylnavas36/status/1395903255297896452) on "Latin American needs... GRAPE SODA!"

**Comment by Beeblerox** [comment]
- [ ] the Clan of the Squirrel and their unrivaled skill in both the kitchen and on the battlefield [have arrived ashore the mystical land of Northgard](https://twitter.com/shirogames/status/1395723696325734401)!

**Comment by Beeblerox** [comment]
- [ ] Mauve has showed [new tileset](https://twitter.com/mauvecow/status/1396585682143825924) for Addlemoth puzzle game. Aaaaaaanyway got [all the tileset stuff together](https://twitter.com/mauvecow/status/1397446543989379073), except for the water animation and the edges.

**Comment by Beeblerox** [comment]
- [ ] You [can't pass through these red walls](https://twitter.com/Rob1221dev/status/1395790874462855173) in new puzzle platformer game by Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] torcado has added [a new border design](https://twitter.com/torcado/status/1396287925529235456) for larger resolutions in Heck Deck

**Comment by Beeblerox** [comment]
- [ ] [Little peek](https://twitter.com/TeamGhostID/status/1396453780762284037) at the next update of Fault by GhostID

**Comment by Beeblerox** [comment]
- [ ] [Interview with Sébastien Bénard](https://www.twitch.tv/videos/1033648877) of Deepnight Games

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` [Michael Bickel](https://twitter.com/dazKind/status/1395836060861612032) doing more Haxe Godot stuff...

- [ ] [Haxe Godot Experiment #2](https://www.youtube.com/watch?v=wYVBvDc0p7E) video

**Comment by Beeblerox** [comment]
- [ ] Touch controls are [now working](https://discord.com/channels/162395145352904705/162664383082790912/845837989296078878) in WIP game by bloodninja

**Comment by Beeblerox** [comment]
- [ ] [OverWorld](https://github.com/notdonxd/OverWorld) is a platformer game [made by 1337](https://discord.com/channels/162395145352904705/162664383082790912/846413177402294322)

**Comment by Beeblerox** [comment]
- [ ] [Adobe AIR left, OpenFL Native Windows, right](https://discord.com/channels/415681294446493696/436230004251164672/846365273183354880), same code by Chris

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source/discord]` Dan [previews](https://discord.com/channels/162395145352904705/162664383082790912/846740027927953449) a marble sim!

- [ ] you can [try it online](https://danielblaker.com/marblesim/)

**Comment by Beeblerox** [comment]
- [ ] belowdecent from Haxe Discord server is making a [simple polygon editor](https://discord.com/channels/162395145352904705/162664383082790912/847212783917465662) in haxeflixel

**Comment by Beeblerox** [comment]
- [ ] [Small animation](https://discord.com/channels/162395145352904705/162664383082790912/847221586939346985) created with code by jeremyfa

**Comment by Beeblerox** [comment]
- [ ] Allan Dowdeswell is [looking for Haxe developer for outsourcing relationship](https://community.haxe.org/t/looking-for-haxe-developer-for-outsourcing-relationship/3062)

**Comment by Beeblerox** [comment]
- [ ] Matthijs Kamstra is making a [paper-toy-builder desktop app](https://twitter.com/MatthijsKamstra/status/1396455834792730624)

**Comment by Beeblerox** [comment]
- [ ] [RPGMaker Template For Plugins](https://kinocreates.io/resources/rpgmaker/rpgmaker-template-for-plugins/) by [Kino Rose](https://twitter.com/EISKino/status/1397685877858570247)

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` Enemy sprite designs for Super Cosmic Heist by [Fierce](https://twitter.com/FierceTheBandit/status/1397337636239515651).
> * [ ]  `[closed source]` Super Cosmic Heist - World 3-2 `WIP` by [Fierce](https://twitter.com/FierceTheBandit/status/1396959149586538499).

- [ ] [More Lethal Mountain Level Screenshots](https://twitter.com/FierceTheBandit/status/1397730751030906880)

**Comment by skial** [comment]
- [ ] `[open source]` [binaryen.hx `git`](https://github.com/gideongrinberg/binaryen.hx) - Haxe externs for binaryen.js.
