### ISSUE TITLE
Haxe Roundup 581

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#875]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` JSON parsing slow and memory intense on eval - due to `Reflect.setField` [issue](https://github.com/HaxeFoundation/haxe/issues/10284).

**Comment by skial** [comment]
- [ ] `[open source]` [hx-ios-uikit `git`](https://github.com/rainyt/hx-ios-uikit) - An extern for Haxe to write native IOS applications.

**Comment by skial** [comment]
- [ ] `[community]` Nullable/Non-Nullable function return type depending on nullability of input [question](https://community.haxe.org/t/nullable-non-nullable-function-return-type-depending-on-nullability-of-input/3070?u=skial).

**Comment by skial** [comment]
- [ ] `[core/js]` Added `-D js-global` to customizes the global object name [pull request](https://github.com/HaxeFoundation/haxe/pull/10282).

**Comment by skial** [comment]
- [ ] `[core]` Allow passing `null` values to `Std.string()` when null-safety is enabled [pull request](https://github.com/HaxeFoundation/haxe/pull/10276).

**Comment by skial** [comment]
- [ ] `[core/python/php]` Null Safety false positive [issue](https://github.com/HaxeFoundation/haxe/issues/10274).

**Comment by skial** [comment]
- [ ] libs
  - [tink_macro `0.24.0`](https://lib.haxe.org/p/tink_macro)
  - [hx-ios-uikit `0.0.1`](https://lib.haxe.org/p/hx-ios-uikit)
  - [pony `1.4.7`](https://lib.haxe.org/p/pony)
  - [hxweixin-mini `0.1.1`](https://lib.haxe.org/p/hxweixin-mini)
  - [openfl-glsl `0.0.9`](https://lib.haxe.org/p/openfl-glsl)

**Comment by skial** [comment]
- [ ] `[community]` PogoGirl Devlog `#19`: Demo Time! [article](https://www.ohsat.com/post/pogogirl-devlog/post19/) by [Andrej](https://twitter.com/ohsat_games/status/1398248691748769799).

**Comment by skial** [comment]
- [ ] `[videos]` Introduction to HaxeFlixel [Part 13](https://www.youtube.com/watch?v=uAD9hQE3jAQ&widget_referrer=haxe.io) by [Questionable Programming](https://twitter.com/QuestionablePr5/status/1398307685808885766).

**Comment by skial** [comment]
- [ ] `[videos]` The importance of a game design document - 2D Stealth indie game [devlog `#1`](https://www.youtube.com/watch?v=d0q9LpTJCIw&widget_referrer=haxe.io) by [Richard Oliver Bray](https://twitter.com/Ceiga).

**Comment by skial** [comment]
- [ ] `[open source]` [monaxe `git`](https://github.com/ClementWeeSG/monaxe) - Monaxe - ReactiveX Library For Haxe Inspired By Monix.

**Comment by skial** [comment]
- [ ] `[open source]` [walker `git`](https://github.com/ohmrun/walker) - Immutable asynchronous state charts.

**Comment by skial** [comment]
- [ ] `[releases]` [Tommy Søreide Kjær](https://twitter.com/tommysoereide/status/1400024127436517379) has released PSYCHOFUNK available on [iOS](https://apps.apple.com/us/app/psychofunk/id1547164915) and [Android](https://play.google.com/store/apps/details?id=com.tommysoereide.psychofunk). Made with Stencyl.

**Comment by skial** [comment]
- [ ] `[closed source]` Change the speed of the game with triggers assigned to different shapes in [Syo's](https://twitter.com/SyoPic/status/1400015959243567106) Jitter Sandbox.

**Comment by skial** [comment]
- [ ] `[closed source]` [Matthijs Kamstra](https://twitter.com/MatthijsKamstra/status/1399821365285380102) progress with his `WIP` paper toy builder app menus and pattern.

**Comment by skial** [comment]
- [ ] `[releases]` [Robert Alvarez](https://twitter.com/Rob1221dev/status/1399785495769583619) has released Jumphase, their newest puzzle platformer available on [itch.io](https://rob1221.itch.io/jumphase) and [Newgrounds](https://www.newgrounds.com/portal/view/797557). Made with Stencyl.

**Comment by skial** [comment]
- [ ] `[closed source]` [Kino Rose](https://twitter.com/EISKino/status/1399503349289041924) previews their macro generated Aseprite script commands in a type safe language.

**Comment by skial** [comment]
- [ ] `[closed source]` Super Cosmic Heist - World 3-3 `WIP` by [Fierce](https://twitter.com/FierceTheBandit/status/1399114567477825545).

**Comment by skial** [comment]
- [ ] `[releases]` [Gauthier](https://twitter.com/gogoprog/status/1398617277591953411) made a little recruitment game [Fire Falcom](https://twitter.com/FireFalcom) game studio.

**Comment by skial** [comment]
- [ ] `[closed source]` Watch out for motion sensors, they will set off a trap! in [Fierce](https://twitter.com/FierceTheBandit/status/1398488704453382146)'s Super Cosmic Heist.

**Comment by skial** [comment]
- [ ] `[closed source/openfl discord]` [Chris](https://discord.com/channels/415681294446493696/436230004251164672/848356820296400906) previews their `WIP` small GUI tool built with OpenFL & FeathersUI to help manage dependencies, project configuration alongside any IDE.

**Comment by skial** [comment]
- [ ] `[releases/armory discord]` [Duke](https://discord.com/channels/486771218599510021/492256943398977556/849199115292246077) has released Road to Eternity, available on [itch.io](https://officialduke99.itch.io/road-to-eternity).

**Comment by skial** [comment]
- [ ] `[releases/haxe discord]` [Zwodah](https://discord.com/channels/162395145352904705/162664383082790912/848213368480202824) has released an early prototype of Explore the Abyss, available on [itch.io](https://discord.com/channels/162395145352904705/162664383082790912/848213368480202824) and is looking for feedback!

**Comment by skial** [comment]
- [ ] `[open source/haxe discord]` [Tyler](https://discord.com/channels/162395145352904705/162664383082790912/849405075272892476) has shared [Snapper `gist`](https://gist.github.com/zzox/aa321c832de9af54d50de41c553a237a) which _"implements coyote time, jump buffering and squash-and-stretch in HaxeFlixel"_. Check out the [preview](https://twitter.com/zzo__x/status/1399719854949666817).

**Comment by skial** [comment]
- [ ] `[releases/haxe discord]` [Type](https://discord.com/channels/162395145352904705/162664383082790912/849576943484403762) and team have released Type-a-Latte, a cafe themed game for a university class project, using OpenFL, available on [itch.io](https://typinggame.itch.io/type-a-latte).

**Comment by skial** [comment]
- [ ] `[open source]` More _awesome_ water FX by [ Sébastien Bénard](https://discord.com/channels/162395145352904705/162664383082790912/849621016590286899) for [Nuclear Blaze](https://deepnight.net/games/nuclear-blaze/).

**Comment by skial** [comment]
- [ ] `[open source/haxe discord]` [Harpwood](https://discord.com/channels/162395145352904705/162664383082790912/849651129271844874) has released [FlxRes `git`](https://github.com/harpwood/FlxRes), their initial version of easy multi resolution handling lib for HaxeFlixel, also available on [itch.io](https://harpwood.itch.io/flxres).

**Comment by MoritzBrueckner** [comment]
- [ ] `[releases]` Armory SDK [2021.6](https://armory.itch.io/armory3d) was released, now with support for Blender 2.93 LTS versions. Other changes include the new Nishita sky model, lightmapping improvements and a redesigned add-on UI ([changelog](https://github.com/armory3d/armory/pull/2082)).

**Comment by Beeblerox** [comment]
- [ ] Mauve had been doing some notes on how to fix up / finalize [new tileset for Addlemoth](https://twitter.com/mauvecow/status/1398107050652037124)

**Comment by Beeblerox** [comment]
> * [ ]  `[open source/haxe discord]` More _awesome_ water FX by [ Sébastien Bénard](https://discord.com/channels/162395145352904705/162664383082790912/849621016590286899) for [Nuclear Blaze](https://deepnight.net/games/nuclear-blaze/).

- [ ] And recently Sébastien discovered the crazy rich SCP Foundation universe and decided to [connect the story of Nuclear Blaze to it](https://twitter.com/deepnightfr/status/1398229267822133248).

**Comment by Beeblerox** [comment]
- [ ] [General Progress Update For Download](https://claybrickentertainment.itch.io/patches-of-adventure/devlog/258274/general-progress-update-for-download - Patches Of Adventure) by [RobClemmonsJr](https://twitter.com/RobClemmonsJr/status/1398485141098487809)

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` Super Cosmic Heist - World 3-3 `WIP` by [Fierce](https://twitter.com/FierceTheBandit/status/1399114567477825545).

- [ ] [Watch out for Motion Sensors](https://twitter.com/FierceTheBandit/status/1398488704453382146)

**Comment by Beeblerox** [comment]
- [ ] The last two Friday updates about Mine Blocks [introduced enchanting and brewing](https://twitter.com/Mine_Blocks/status/1398673297072590849) into the port! Also, there are now slimes, magma cubes, and alerts when you get achievements

**Comment by Beeblerox** [comment]
- [ ] Defender's Quest 2 progress: [leeches!](https://twitter.com/larsiusprime/status/1398763618624225281) by Lars Doucet

**Comment by Beeblerox** [comment]
- [ ] New GIFs from WIP game by SavanDev:
    * [...](https://twitter.com/dylnavas36/status/1400020429998379009)
    * [Why are you not moving?](https://twitter.com/dylnavas36/status/1399825706440400900)
    * [Welcome to ColorLess!](https://twitter.com/dylnavas36/status/1398866987523129347)

**Comment by Beeblerox** [comment]
- [ ] [Twitter thread](https://twitter.com/joelgervasi/status/1399742462537744386) about Scraps of Light RPG

**Comment by Beeblerox** [comment]
- [ ] Alex Lanzetta has [made a text field](https://twitter.com/Zanzlanz/status/1399727062605312000) which is working in WebGL/OpenGL rendering mode in Lime

**Comment by Beeblerox** [comment]
- [ ] disktree has [updated Haxe type definitions for Three.js ](https://twitter.com/disktree/status/1398153780554838026)

**Comment by Beeblerox** [comment]
- [ ] Seifer Tim has opened [merge request](https://github.com/HaxeFlixel/flixel/pull/2309) which adds support for Unicode Combining Diacritical Marks in FlxBitmapText. [THERE we GO!](https://discord.com/channels/162395145352904705/165234904815239168/848170346125590528)

**Comment by Beeblerox** [comment]
- [ ] Skyfire has [added bullet time](https://discord.com/channels/162395145352904705/162664383082790912/847583196568092722)

**Comment by Beeblerox** [comment]
- [ ] [FlappyGame](https://aloalto.pe/flappy/) by [edu0112](https://discord.com/channels/162395145352904705/162664383082790912/847675306381672478) from Haxe Discord server. With the [source code](https://github.com/educc/flappy-game) available on Github

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` [Kino Rose](https://twitter.com/EISKino/status/1399503349289041924) previews their macro generated Aseprite script commands in a type safe language.

- [ ] it's [available on Github](https://github.com/KinoCreatesGames/aseprite-hapi)

**Comment by Beeblerox** [comment]
- [ ] New version of [Mammoth Herder](https://www.newgrounds.com/portal/view/797204?updated=1622404135) had been released on Newgrounds. via [wayward](https://discord.com/channels/162395145352904705/162664383082790912/849056874003431424)

**Comment by Beeblerox** [comment]
- [ ] [Slow but steady progress](https://discord.com/channels/162395145352904705/162664383082790912/849263673226035221) by bloodninja

**Comment by Beeblerox** [comment]
- [ ] OpenFl showcase: [Restaurant Streets](https://community.openfl.org/t/restaurant-streets-feed-friends-in-your-own-restaurant/13047): feed friends in your own restaurant

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source/openfl discord]` [Chris](https://discord.com/channels/415681294446493696/436230004251164672/848356820296400906) previews their `WIP` small GUI tool built with OpenFL & FeathersUI to help manage dependencies, project configuration alongside any IDE.

- [ ] And it [will be opensourced!](https://discord.com/channels/415681294446493696/436230004251164672/849728770428633148)

**Comment by Beeblerox** [comment]
- [ ] [jefvel](https://discord.com/channels/162395145352904705/162664383082790912/849743342945173512) is working a bit on a postjam version of their LDjam game

**Comment by Beeblerox** [comment]
- [ ] Premium version of RPG Playground [news next week](https://twitter.com/RPGplayground/status/1400314339102498816)

**Comment by skial** [comment]
- [ ] `[core]` Breaking change macro `CString` backslashes [issue](https://github.com/HaxeFoundation/haxe/issues/10285).

**Comment by skial** [comment]
-  [ ] `[community]` How to emulate `@:native` metadata for typedefs? [question](https://community.haxe.org/t/how-to-emulate-native-metadata-for-typedefs/3084?u=skial).
