### ISSUE TITLE
Haxe Roundup 583

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#879]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` Add methods to get `Map` and `EReg` sizes [pull request](https://github.com/HaxeFoundation/haxe/pull/10290).

**Comment by skial** [comment]
- [ ] `[open source]` [ceramic `0.7.8`](https://github.com/ceramic-engine/ceramic/releases/tag/v0.7.8) has been released.

**Comment by skial** [comment]
- [ ] libs
  - [bootstrap_bundle `0.2.1`](https://lib.haxe.org/p/bootstrap_bundle)
  - [udprotean `0.3.3`](https://lib.haxe.org/p/udprotean)
  - [poke-api `0.7.1`](https://lib.haxe.org/p/poke-api)
  - [openfl-aseprite `1.3.2`](https://lib.haxe.org/p/openfl-aseprite)
  - [ase `2.0.0`](https://lib.haxe.org/p/ase)
  - [externs `0.5.6`](https://lib.haxe.org/p/externs)
  - [lc-hotp `1.0.1`](https://lib.haxe.org/p/lc-hotp)
  - [openfl-spine `1.6.3`](https://lib.haxe.org/p/openfl-spine)
  - [aseprite-api `0.9.5`](https://lib.haxe.org/p/Aseprite-Api)

**Comment by skial** [comment]
- [ ] `[releases]` PogoGirl Devlog `#21`: [Demo Updated!](https://ohsat-andrej.itch.io/go-go-pogogirl/devlog/263902/devlog-21-demo-updated) by [Andrej](https://twitter.com/ohsat_games/status/1404538579574050816).

**Comment by skial** [comment]
- [ ] `[videos]` Introduction to HaxeFlixel [Part 15](https://www.youtube.com/watch?v=pTR5qRTI1Ww&widget_referrer=haxe.io) by Questionable Programming.

**Comment by skial** [comment]
- [ ] `[videos]` Sprite packing & player movement in HaxeFlixel | 2D Stealth indie game [devlog #3](https://www.youtube.com/watch?v=M0zoWgOgx-A&widget_referrer=haxe.io) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] `[closed source]` After 26 attempts, [Jano Games](https://twitter.com/jano_games/status/1404904140308877315) finally lands him in the bath, more bath celebration levels to follow in Bad Soccer Manager. ⚽🛁👀 Made with Stencyl.

**Comment by skial** [comment]
- [ ] `[closed source]` [Gepatto](https://twitter.com/gepatto/status/1404813249435082754) has gotten Friday Night Funkin running on the RaspberryPi as a proof of concept.

**Comment by skial** [comment]
- [ ] `[open source]` [Michael Miriti](https://twitter.com/michael_miriti/status/1404545810617049092) has made the Ase library able to create, write and modify aseprite files.

**Comment by skial** [comment]
- [ ] `[community]` [Jérémy Fa](https://twitter.com/jeremyfaivre/status/1404034008036556805) has [written](https://jeremyfa.com/getting-started-with-ceramic/) "Getting started with ceramic", guiding you step by step creating your first project with ceramic.

**Comment by skial** [comment]
- [ ] `[closed source]` Hello from [Syo](https://twitter.com/SyoPic/status/1403658171927908353)'s Jitter Sandbox, made with Heaps.

**Comment by skial** [comment]
- [ ] `[community]` "Haxe Aseprite Scripting" [article](https://kinocreates.io/development-blog/aseprite-api-haxe/) by [Kino Rose](https://twitter.com/EISKino/status/1403452097203482632).

**Comment by skial** [comment]
- [ ] `[open source]` [Disktree](https://twitter.com/disktree/status/1403286328649912321) has released [Noise Gen](https://disktree.net/app/noisegen/), a white, pink and brown noise generator, with the source available on [GitHub](https://github.com/disktree/noisegen).

**Comment by skial** [comment]
- [ ] `[closed source]` [Matthijs Kamstra](https://twitter.com/MatthijsKamstra/status/1403050700859392003) continues to improve Paper-Toy-Builder `WIP` ✂ by working on trapezoid and the splash screen.

**Comment by skial** [comment]
- [ ] `[closed source]` Nuclear Blaxe SCP by [Sébastien Bénard](https://twitter.com/deepnightfr/status/1403010470127280130) gets a title screen, Options menu & is coming out soon!

**Comment by skial** [comment]
- [ ] `[closed source]` [Nicolas Cannasse](https://twitter.com/ncannasse/status/1404199641948819459) has [announced](https://www.pcgamer.com/wartales-is-a-gritty-mercenary-epic-from-the-makers-of-northgard/?utm_campaign=socialflow&utm_medium=social&utm_source=twitter.com) WarTales, a gritty mercenary game from ShiroGames.

**Comment by skial** [comment]
- [ ] `[closed source]` The latest [Mine Blocks](https://twitter.com/Mine_Blocks/status/1403806807521382416) Beta update is out, with fishing 🎣, clouds & lightning ⚡, mobs and more.

**Comment by skial** [comment]
- [ ] `[closed source/haxe discord]` [01010111](https://discord.com/channels/162395145352904705/162664383082790912/852534511317417994) shares a video of a game they are making for work inspired by Super Crate Box, made with PixiJS, OGMO and [Echo](https://austineast.dev/echo/).

**Comment by skial** [comment]
- [ ] `[open source/haxe discord]` [Ian Harrigan](https://discord.com/channels/162395145352904705/162664383082790912/852990144733642792) shows further progress with HaxeUI-pdcurses.

**Comment by skial** [comment]
- [ ] `[releases/haxe discord]` [Sodap](https://discord.com/channels/162395145352904705/162664383082790912/853752396416155649) has released [Tres Mangueras](https://sodap.itch.io/tres-mangueras) available on `itch.io` made for `#gmtk2021` using HaxeFlixel.

**Comment by skial** [comment]
- [ ] `[releases/haxe discord]` [Pirhana](https://discord.com/channels/162395145352904705/162664383082790912/853917856710262785) has released [Pangaea](https://pirhanalab.itch.io/pangaea) available on `itch.io` made `#gmtk2021`.

**Comment by Beeblerox** [comment]
- [ ] [Defenders Quest 2 progress - tar!](https://twitter.com/larsiusprime/status/1403089417783422988) by Lars Doucet

**Comment by Beeblerox** [comment]
- [ ] [Feathers UI Devlog #33](https://www.kickstarter.com/projects/feathersui/feathers-ui-cross-platform-components-for-haxe-and-openfl/posts/3196384): NumericStepper, app scaling, item renderer accessories, TextInput errorString

**Comment by Beeblerox** [comment]
- [ ] [Matching arrow blocks](https://twitter.com/Rob1221dev/status/1403415648215183364) to move obstacles in WIP puzzle game by Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] New GIFs and video from Renaine:
    * The mouse society's [got a new mayor](https://twitter.com/OctosoftUS/status/1403439638308601858)
    * Hmm [let's see how the first area I haven't touched since the big backend rework is looking](https://twitter.com/squuuidly/status/1404519551405113350) 2 days before the major demo.
    * [What bee sound](https://twitter.com/squuuidly/status/1404646975572688900) do you guys like the most?
- [ ] A Renaine demo will be [available today or tomorrow](https://twitter.com/OctosoftUS/status/1405196088492036100) on Steam Next Fest. Stay tuned to [the game's Steam page](https://store.steampowered.com/app/662340/Renaine/)

**Comment by Beeblerox** [comment]
- [ ] Double Turn [Update v1.1.2](https://twitter.com/doubleturngame/status/1404167201880412169) is out. [Full patch notes](https://store.steampowered.com/news/app/762680/view/4975895695808819036)

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` [Nicolas Cannasse](https://twitter.com/ncannasse/status/1404199641948819459) has [announced](https://www.pcgamer.com/wartales-is-a-gritty-mercenary-epic-from-the-makers-of-northgard/?utm_campaign=socialflow&utm_medium=social&utm_source=twitter.com) WarTales, a gritty mercenary game from ShiroGames.

- [ ] [Free demo](https://store.steampowered.com/app/1527950/Wartales/) is now available as part of the Steam Next Fest

**Comment by Beeblerox** [comment]
- [ ] mauve has spent some time tonight and added [The Good Kind of Button Config](https://twitter.com/mauvecow/status/1404309966920372225) for WIP Addlemoth game

**Comment by Beeblerox** [comment]
- [ ] [Fried Bandit](https://twitter.com/FierceTheBandit/status/1404551169725378562) on the other hand... from Super Cosmic Heist by Fierce.

**Comment by Beeblerox** [comment]
- [ ] [edu](https://twitter.com/edward1738/status/1403183084900659207) has shared [source code](https://github.com/educc/flappy-game) of their version of FlappyBird game developed with Haxe language and Haxeflixel

**Comment by Beeblerox** [comment]
- [ ] [Elton Silva](https://twitter.com/EltonSilvaArt/status/1403356503189471235) has made a new feature for Ogmo Editor: show all levels together.

**Comment by Beeblerox** [comment]
- [ ] [ColorLess v1.0.1 is here](https://savandev.itch.io/colorless/devlog/264348/v101) by [SavanDev](https://twitter.com/dylnavas36/status/1405084231764697089). And the game's [source code](https://github.com/SavanDev/FlxColorLess) is available as well

**Comment by Beeblerox** [comment]
- [ ] fantomon is coding [a fake command line console](https://twitter.com/fantomongames/status/1404915756991717383) with Haxe and HaxeFlixel

**Comment by Beeblerox** [comment]
- [ ] [RPG Playground](https://twitter.com/RPGplayground/status/1405181746006659075) has shared plans on project tree improvements

**Comment by Beeblerox** [comment]
- [ ] [Energy Island Corp.](https://store.steampowered.com/app/1241710/Energy_Island_Corp/) demo is now available as part of the Steam Next Fest. via [SpirkopGames](https://twitter.com/SpirkopGames/status/1405211795267231745)

**Comment by Beeblerox** [comment]
- [ ] [CLYDE](https://discord.com/channels/162395145352904705/162664383082790912/852427245498269719) is making a game with Heaps.io. It's inspired by Diablo and Path of Exile. All about stacking up crazy items with interactive effects to get through harder and harder levels of a dungeon

**Comment by Beeblerox** [comment]
- [ ] Skyfire2008 has [added a preloader](https://discord.com/channels/162395145352904705/162664383082790912/853203237741264916) to avoider.

**Comment by Beeblerox** [comment]
- [ ] Ceramic engine now has its [own channel](https://discord.com/channels/162395145352904705/853414608747364352) on Haxe Discord server

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` Nuclear Blaxe SCP by [Sébastien Bénard](https://twitter.com/deepnightfr/status/1403010470127280130) gets a title screen, Options menu & is coming out soon!

- [ ] And [Steam page](https://store.steampowered.com/app/1662480/Nuclear_Blaze/) too! It's not 100% public right now, so all your feedback would be super useful to Sébastien

**Comment by skial** [comment]
- [ ] `[job]` Hiring full-time software engineer - web / edtech / Saga Education [job listing](https://community.haxe.org/t/hiring-full-time-software-engineer-web-edtech-saga-education/3120?u=skial). US only.
  - > Saga Education, is hiring a senior-level software engineer. We use a lot of tech, both frontend and backend, but a lot of our frontend code is in Haxe. We build cool, meaningful EDTech products like this digital whiteboard: [Woot Math Scratchpad](https://wootmath.com/dsp).

**Comment by skial** [comment]
- [ ] `[community]` Lars Doucet's [thoughts](https://twitter.com/larsiusprime/status/1405380977887678464) on "Instant Games", Friday Night Funkin, Flash games & monetization.

**Comment by skial** [comment]
- [ ] `[releases/armoury discord]` [Phour](https://discord.com/channels/486771218599510021/492256943398977556/853704491034738738) has released [Bleep Bloop Power Bot](https://phour.itch.io/bleep-bloop-power-bot) made with Armory3D onto `itch.io`, made for `#gmtk2021`.
