### ISSUE TITLE
Haxe Roundup 594

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#904]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[job/bounty]` `$100` - `FlxG.collide` with simple object "mass" for HaxeFlixel [bounty](https://github.com/chosencharacters/squidBounties/issues/6).

**Comment by skial** [comment]
- [ ] `[job/bounty]` `$150` - Basic Platformer Pathfinding AI for HaxeFlixel [bounty](https://github.com/chosencharacters/squidBounties/issues/5).

**Comment by skial** [comment]
- [ ] `[community]` Is Haxe good for [writing compilers?](https://www.reddit.com/r/haxe/comments/pcqaxk/is_haxe_good_for_writing_compilers/)

**Comment by skial** [comment]
- [ ] libs
  - [redistHelper `0.4.15`](https://lib.haxe.org/p/redistHelper)
  - [deepnightLibs `1.0.61`](https://lib.haxe.org/p/deepnightLibs)
  - [electron `14.0.0`](https://lib.haxe.org/p/electron)
  - [gmodhaxe `0.2.3`](https://lib.haxe.org/p/gmodhaxe)
  - [watch `0.0.4`](https://lib.haxe.org/p/watch)
  - [bou `0.0.1`](https://lib.haxe.org/p/buo)

**Comment by skial** [comment]
- [ ] `[community]` PogoGirl Devlog `#24`: SAGE 2021 Happened [article](https://www.ohsat.com/post/pogogirl-devlog/post24/).

**Comment by skial** [comment]
- [ ] `[videos]` Introduction to HaxeFlixel [Part 26](https://www.youtube.com/watch?v=a4X4567Ux60&widget_referrer=haxe.io) - Adding music and sound to our menus by Questionable Programming.

**Comment by skial** [comment]
- [ ] `[videos]` How popular is HaxeFlixel on Steam? Top game engines on Steam [video](https://www.youtube.com/watch?v=heOCukBp2n8&widget_referrer=haxe.io) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] `[open source]` [Ian Harrigan](https://twitter.com/IanHarrigan1982/status/1431719763030458374) has been _"playing around with a HaxeLib / GitHub project manager ... to try and make project management a little easier"_.

**Comment by skial** [comment]
- [ ] `[closed source]` [Jano Games](https://twitter.com/jano_games/status/1431602774152781825) is getting Bad Soccer Manager ready for iOS and Android.

**Comment by skial** [comment]
- [ ] `[closed source]` [Andrej](https://twitter.com/ohsat_games/status/1431396144144437251) has made the _"music dynamically change when you're under water"_ and is considering making a HaxeFlixel tutorial based around the idea.

**Comment by skial** [comment]
- [ ] `[closed source]` Super Cosmic Heist - Snap Trap Sr. Boss Battle by [Fierce](https://twitter.com/FierceTheBandit/status/1430967383104106496).

**Comment by skial** [comment]
- [ ] `[open source]` [Justin](https://twitter.com/Nanjizal_net/status/1430920442399887361) has added `ShapeXML` to [cornerContour `git`](https://github.com/nanjizal/cornerContour/blob/main/README.md#using-the-svg-shapexml-in-addition-to-path) and works on canvas and in Ceramic.

**Comment by skial** [comment]
- [ ] `[community]` [Dan Hett](https://twitter.com/danhett/status/1433010693515644930) describes his writing process while working on [Closed Hands](https://passenger.itch.io/closed-hands).

**Comment by skial** [comment]
- [ ] `[closed source]` _"If regular bouncing is not enough, PogoGirl can do a Mega Bounce!"_ by [Andrej](https://twitter.com/ohsat_games/status/1432841287686819841).

**Comment by skial** [comment]
- [ ] `[releases]` [The Overload Game](https://twitter.com/made_by_ia/status/1431874972088143873) was made for the band, Yard Act, by Industrial Assets using Haxe & HaxeFlixel, via [John Bower](https://twitter.com/beclamide/status/1432633241425567744).

**Comment by skial** [comment]
- [ ] `[community]` Generating Uniform Block Types Using Spirv-Cross and Haxe Macros [article](https://blog.aidanlee.uk/generating-shader-uniform-abstracts/) by Aidan Lee.

**Comment by skial** [comment]
- [ ] `[closed source/haxe discord/🔐]` [Will](https://discord.com/channels/162395145352904705/162664383082790912/881265828333506581) shares a video of a full game loop from his robot battle sim game.

**Comment by Beeblerox** [comment]
- [ ] [Part of new area](https://twitter.com/jmw327/status/1430880274036953089) in Frontier Story by jmw327

**Comment by Beeblerox** [comment]
> * [ ]  `[open source]` [Justin](https://twitter.com/Nanjizal_net/status/1430920442399887361) has added `ShapeXML` to [cornerContour `git`](https://github.com/nanjizal/cornerContour/blob/main/README.md#using-the-svg-shapexml-in-addition-to-path) and works on canvas and in Ceramic.

- [ ] And [Justin](https://twitter.com/Nanjizal_net/status/1432348545546428418) has also created [TraceCount](https://github.com/nanjizal/TraceCount) which allows a particular trace statement to output only a limited number of times

**Comment by Beeblerox** [comment]
- [ ] Mig Moog is working on their entry for NG jam:
    * [Bounce bounce bounce](https://twitter.com/migmoog/status/1431010377589006336)
    * [You can hit people now](https://twitter.com/migmoog/status/1431248964054134785)
    * [Flying Goober](https://twitter.com/migmoog/status/1431353998729224200)

**Comment by Beeblerox** [comment]
- [ ] [Sigil Generator](https://www.patreon.com/posts/55579904) by [Oleg Dolya](https://twitter.com/watawatabou)

**Comment by Beeblerox** [comment]
- [ ] mauve has shown [in-game editor](https://twitter.com/mauvecow/status/1432065024407732228) for Addlemoth and [comparison of old and new](https://twitter.com/mauvecow/status/1432515231176028160) wolf sprites from the game

**Comment by skial** [comment]
- [ ] `[community]` Attacks, Effects and Combos! - August 2021 [Fraymakers Roundup](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3263200).

**Comment by skial** [comment]
- [ ] `[open source]` [ob.exposehtml `git`](https://github.com/jobf/ob.exposehtml) - Quickly expose haxe application via HTML.
