### ISSUE TITLE
Haxe Roundup 604

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#925]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] Haxe Evolution meeting [has taken place](https://github.com/HaxeFoundation/haxe-evolution/issues/94) to discuss proposal statues.

**Comment by skial** [comment]
- [ ] `[core/java]` `@:java.default` vs interface order [issue](https://github.com/HaxeFoundation/haxe/issues/10467).

**Comment by skial** [comment]
- [ ] `[community]` iOS / Android Native Extension [thread](https://community.haxe.org/t/ios-android-native-extension/3318?u=skial).

**Comment by Beeblerox** [comment]
- [ ] [Go! Go! PogoGirl](https://store.steampowered.com/app/1681010/Go_Go_PogoGirl/) by Andrej [will be released this year](https://twitter.com/ohsat_games/status/1456433151962718217)
- [ ] [Winter is coming](https://twitter.com/ohsat_games/status/1458515384001237005) to Go! Go! PogoGirl

**Comment by Beeblerox** [comment]
- [ ] [Sidebars and splitters](https://twitter.com/IanHarrigan1982/status/1456614190861459460) working in haxeui-pdcurses (text mode user interface)... because... ... why not!
- [ ] HaxeUI now has a very simple, but very useful ["card" component](https://twitter.com/IanHarrigan1982/status/1458106177858965507)!

**Comment by Beeblerox** [comment]
- [ ] [Setup HashLink VM](https://github.com/marketplace/actions/setup-hashlink-vm) GitHub Action by [Cédric Belin](https://twitter.com/cedxbelin/status/1456690438539198471)

**Comment by Beeblerox** [comment]
- [ ] Super Cosmic Heist - [Machinery Repairs Station](https://twitter.com/FierceTheBandit/status/1457890227515805699)
- [ ] Super Cosmic Heist - [World 5-1 WIP](https://twitter.com/FierceTheBandit/status/1457027226218766340)

**Comment by Beeblerox** [comment]
- [ ] Nuclear Blaze by [Sébastien Bénard](https://twitter.com/deepnightfr/status/1457363461470625796) released [on Itch](https://deepnight.itch.io/nuclear-blaze)

**Comment by Beeblerox** [comment]
- [ ] [IriySoft](https://twitter.com/IriySoft/status/1457660503757578241) has ported Battalion Commander [to Android](https://play.google.com/store/apps/details?id=com.iriysoft.BattalionCommander), the iOS version is coming soon!

**Comment by Beeblerox** [comment]
- [ ] [Memory Match Game Prototype](https://harpwood.itch.io/memory-match-game-prototype-for-openfl) for OpenFl by [George Harpwood](https://twitter.com/GeorgeHarpwood/status/1457711711402741762)

**Comment by Beeblerox** [comment]
- [ ] Knock! Knock! The Drifter from Heart Machine will be [soon in Dead Cells](https://twitter.com/motiontwin/status/1457755293291528193)

**Comment by Beeblerox** [comment]
- [ ] [Surprise!](https://twitter.com/terrycavanagh/status/1457771183512850434) This Thursday the 11th, Dicey Dungeons is coming to Xbox One and Xbox Series X|S!

**Comment by Beeblerox** [comment]
- [ ] [Taking Hostages](https://www.fortressofdoors.com/taking-hostages-dq2-progress-report-for-october-2021/) -- DQ2 Progress Report for October 2021 by [Lars Doucet](https://twitter.com/larsiusprime/status/1457813324796682244)

**Comment by Beeblerox** [comment]
- [ ] Oleg Dolya is back to the idea of ["neighbourhood generator"](https://twitter.com/watawatabou/status/1458134989061562374)

**Comment by Beeblerox** [comment]
- [ ] Cliff Hall's [tweet about Haxe](https://twitter.com/seaofarrows/status/1456723371278864392)

**Comment by Beeblerox** [comment]
- [ ] ddmills has written first Haxe Heaps shader in order [to shroud any entities in the fog](https://twitter.com/ddmillsy/status/1456785596886683648)

**Comment by Beeblerox** [comment]
- [ ] Kaelan Evans has added an arbitrary angle snap to LineRider and here is some cool effect when [using 179 degree snapping](https://twitter.com/kbeevans/status/1457164846575673344)

**Comment by Beeblerox** [comment]
- [ ] [Heck Deck](https://store.steampowered.com/app/1606210) by torcado will be released on PC and mobile [on January 11th, 2022](https://twitter.com/torcado/status/1458445678015827968)

**Comment by Beeblerox** [comment]
- [ ] [Moonshine IDE's code editor powered by Feathers UI](https://feathersui.com/blog/2021/11/09/moonshine-ide-feathers-ui-code-text-editor/)

**Comment by Beeblerox** [comment]
- [ ] Bumble Bee been [working on a lil game](https://discord.com/channels/162395145352904705/162664383082790912/905780453859000330) for a while now, its supposed to be a beat em up bullet hell. Here is [WIP boss](https://discord.com/channels/162395145352904705/162664383082790912/905823894252965919)

**Comment by Beeblerox** [comment]
- [ ] [Early WIP](https://discord.com/channels/162395145352904705/162664383082790912/905865489182515200) of a 3D game by Kino

**Comment by Beeblerox** [comment]
- [ ] [jefvel](https://discord.com/channels/162395145352904705/162664383082790912/907050647898165279) has released an endless mode for [Grandpa's Minigun](https://www.newgrounds.com/portal/view/820650)

**Comment by skial** [comment]
- [ ] libs
    - [mc2it_theme `1.4.0`](https://lib.haxe.org/p/mc2it_theme)
    - [mc2it_rte `1.2.2`](https://lib.haxe.org/p/mc2it_rte)
    - [itertools `0.0.5`](https://lib.haxe.org/p/itertools)
    - [tyd.hx `1.0.1`](https://lib.haxe.org/p/tyd.hx)
    - [advanced-layout `0.11.0`](https://lib.haxe.org/p/advanced-layout)
    - [linc_luajit `0.0.4`](https://lib.haxe.org/p/linc_luajit)
    - [markov-namegen `1.0.9`](https://lib.haxe.org/p/markov-namegen)
    - [wasm-c `0.1.0`](https://lib.haxe.org/p/wasm-c)
    - [chaos-framework `2.0.3`](https://lib.haxe.org/p/chaos-framework)

**Comment by skial** [comment]
- [ ] `[community]` PogoGirl Devlog [`#26`: Shwing!](https://www.ohsat.com/post/pogogirl-devlog/post26/) by Andrej Preradovic.

**Comment by skial** [comment]
- [ ] `[videos]` How get sprite to follow path HaxeFlixel [tutorial](https://www.youtube.com/watch?v=qq1pwd9FWiY&widget_referrer=haxe.io) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] `[videos]` Make your first game with Armory3D beginner [tutorial](https://www.youtube.com/watch?v=_xyHt4W00Xc&widget_referrer=haxe.io) by Willbot Studio.

**Comment by skial** [comment]
- [ ] `[videos]` Make your first game in Armory3D part 2 beginner [tutorial](https://www.youtube.com/watch?v=5t9BHjs85YA&widget_referrer=haxe.io) by Willbot Studio.

**Comment by skial** [comment]
- [ ] `[open source]` [math-parser `git`](https://github.com/TheDrawingCoder-Gamer/math-parser) - A simple math parser, used more of as a learning experience.

**Comment by skial** [comment]
- [ ] `[closed source]` [Tyler](https://twitter.com/zzo__x/status/1458086552119169034) shows some bird-flying physics made in HaxeFlixel.

**Comment by skial** [comment]
- [ ] `[community]` [Happy anniversary](https://inwavelabs.com/news/double-turn-anniversary) to Double Turn!

**Comment by skial** [comment]
- [ ] `[community]` [Personal website](https://forums.armory3d.org/t/personal-website-made-with-armory/4723?u=skial) made entirely with Armory3D by Rogério Perdiz.
