### ISSUE TITLE
Haxe Roundup 605

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#927]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core/haxelib]` Library name capitalisation [issues](https://github.com/HaxeFoundation/haxelib/issues/529).

**Comment by skial** [comment]
- [ ] `[evolution]` A type for meaningless values (similar to unit type) [proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/95).

**Comment by skial** [comment]
- [ ] `[core/hashlink]` Build a library usable for embedding & FFI [pull request](https://github.com/HaxeFoundation/hashlink/pull/492).

**Comment by skial** [comment]
- [ ] `[core/hashlink]` Phantom fields appear in typedef argument in 64-bit Hashlink [closed](https://github.com/HaxeFoundation/hashlink/issues/491).

**Comment by skial** [comment]
- [ ] `[community]` Promising project for Haxe to Flutter [thread](https://community.haxe.org/t/promising-project-for-haxe-to-flutter/3342?u=skial).

**Comment by skial** [comment]
- [ ] `[jobs]` AS3 to JavaScript (React) via Haxe [job offers](https://community.haxe.org/t/as-3-to-js-react-via-haxe/3337?u=skial).

**Comment by skial** [comment]
- [ ] `[core/hashlink]` Implement profiler for Linux [merged](https://github.com/HaxeFoundation/hashlink/pull/490).

**Comment by skial** [comment]
- [ ] `[core]` Implement number separator [discussion](https://github.com/HaxeFoundation/haxe/issues/10480).

**Comment by skial** [comment]
- [ ] `[community]` Haxe Evolution meeting 2021 proposal verdict [article](https://haxe.org/blog/evolution-meeting-2021/) by Aurel Bílý.

**Comment by skial** [comment]
- [ ] `[community]` Haxe Godot externs updated for Godot `3.4` [thread](https://community.haxe.org/t/haxe-godot-externs-updated-for-godot-3-4/2990/2?u=skial).

**Comment by skial** [comment]
- [ ] libs
   - [electron `16.0.0`](https://lib.haxe.org/p/electron)
   - [tweener `1.33.74`](https://lib.haxe.org/p/tweener)
   - [which `3.0.1`](https://lib.haxe.org/p/which)
   - [collections `0.0.2`](https://lib.haxe.org/p/collections)
   - [nwjs `1.2.1`](https://lib.haxe.org/p/nwjs)
   - [lcov `2.0.1`](https://lib.haxe.org/p/lcov)
   - [free_mobile `1.0.1`](https://lib.haxe.org/p/free_mobile)
   - [godot `3.4.1`](https://lib.haxe.org/p/godot)
   - [bootstrap_bundle `1.2.1`](https://lib.haxe.org/p/bootstrap_bundle)
   - [akismet `1.0.2`](https://lib.haxe.org/p/akismet)
   - [json2object `3.10.0`](https://lib.haxe.org/p/json2object)

**Comment by Beeblerox** [comment]
- [ ] [CRT shader](https://twitter.com/ohsat_games/status/1458932518598721538) for Go! Go! PogoGirl
- [ ] [Winter has come](https://twitter.com/ohsat_games/status/1459596936374374419) to Go! Go! PogoGirl's island

**Comment by Beeblerox** [comment]
- [ ] [We have LORE](https://twitter.com/mauvecow/status/1459624228802600962) in Addlemoth by mauve
- [ ] Demo's JP translation [is moving along](https://twitter.com/mauvecow/status/1460173048405917697)

**Comment by Beeblerox** [comment]
- [ ] zzox (tyler) [first custom shader](https://twitter.com/zzo__x/status/1459018391163965440), palette quantization/posterization

**Comment by Beeblerox** [comment]
- [ ] [Nanjizal](https://twitter.com/Nanjizal_net/status/1459593673436540930) has added 'basic' hxDaedalus [WebGL example](https://nanjizal.github.io/contourDaedalus/index.html) using cornerContour

**Comment by Beeblerox** [comment]
- [ ] Next update for Nuclear Blaze by Sébastien Bénard will feature [a NewGame+ mode](https://twitter.com/deepnightfr/status/1459456660481658882). It will affect all levels a LOT, [adding new threats, areas and items](https://twitter.com/deepnightfr/status/1461020659123949576)

**Comment by Beeblerox** [comment]
- [ ] [Neighbourhood Generator](https://www.patreon.com/posts/58808794) by [Oleg Dolya](https://twitter.com/watawatabou/status/1460960887955677195)

**Comment by Beeblerox** [comment]
- [ ] [Shamanic mandala](https://twitter.com/Kanakro13/status/1459906820613496835) in Kanyon Karver represents the score multiplier buff and the elation that one gets from a successful ride.

**Comment by Beeblerox** [comment]
- [ ] Super Cosmic Heist - [World 5-4 WIP](https://twitter.com/FierceTheBandit/status/1459566817991696386) by Fierce

**Comment by Beeblerox** [comment]
- [ ] [Have you ever been picked on?](https://twitter.com/FraymakersGame/status/1459581888071286785)

**Comment by Beeblerox** [comment]
- [ ] Professor at the Universitat de Barcelona who [uses RPG Playground in his Masters degree class](https://twitter.com/RPGplayground/status/1459659782340722691)

**Comment by Beeblerox** [comment]
- [ ] ddmills has [made a little progress}(https://twitter.com/ddmillsy/status/1459734339994927107): brightened up the color palette, started adding crew members and a map

**Comment by Beeblerox** [comment]
- [ ] The actions package by [tong](https://twitter.com/disktree/status/1459826821822832656) for building Armory3d projects in github workflows is now [available at the marketplace](https://github.com/marketplace/actions/armory3d-setup)

**Comment by Beeblerox** [comment]
- [ ] Wartales by [Shiro Games](https://twitter.com/shirogames/status/1460177091744485376) is coming to [Steam](https://store.steampowered.com/app/1527950/Wartales/) Early Access on the 1st of December. 
- [ ] Wartales: [Early Access Announcement Trailer](https://www.youtube.com/watch?v=q8KxwVLzZak)
- [ ] Will you be brave enough to face [the Ghost Pack](https://twitter.com/Wartales_Game/status/1460959824531832845) in Wartales?

**Comment by Beeblerox** [comment]
- [ ] Here is some advance in the [map generation for sandbox scenario](https://twitter.com/SpirkopGames/status/1460999073775992841) in [Energy Island Corp](https://store.steampowered.com/app/1241710/Energy_Island_Corp/) by SpirkopGames

**Comment by Beeblerox** [comment]
- [ ] [HaxeJam 2021: Winter Editon](https://itch.io/jam/haxejam-2021-winter-editon) by [logo4poop](https://twitter.com/logo4poop/status/1460413377059205126)

**Comment by Beeblerox** [comment]
- [ ] New characters in Dead Cells:
    * [Juan, the half-Luchador half-chicken](https://twitter.com/motiontwin/status/1459206102583689218)
    * [Skul: The Hero Slayer](https://twitter.com/motiontwin/status/1460654899578892290)
    * [The Penitent](https://twitter.com/motiontwin/status/1461017035786260480) from Blasphemous

**Comment by Beeblerox** [comment]
- [ ] Skyfire2008 has [added a new enemy](https://discord.com/channels/162395145352904705/162664383082790912/908706635059445830) and showed screenshot of a custom [self-made editor](https://discord.com/channels/162395145352904705/162664383082790912/908763367718674453)

**Comment by Beeblerox** [comment]
- [ ] [Zeta](https://discord.com/channels/162395145352904705/162664383082790912/910091316887711744) has made [pull request](https://github.com/HaxeFoundation/hashlink/pull/490) which adds profiling support for HashLink on Linux! And it's already been merged

**Comment by Beeblerox** [comment]
- [ ] Will Blanton has shared [mockup and progress](https://discord.com/channels/162395145352904705/162664383082790912/910283404799508491) of a turnbased stealth marble deckbuilder

**Comment by Beeblerox** [comment]
- [ ] [A perfectly looping gif](https://twitter.com/squuuidly/status/1461051459085164551) from Renaine

**Comment by Beeblerox** [comment]
- [ ] [kyatt7](https://twitter.com/kyatt7/status/1461094132504580100) has released a magical new [Fiscal Jesters](https://kyatt7.itch.io/fiscal-jesters) update which features a new character [The Bog Jester] and a new currency [Tarot Coins].

**Comment by skial** [comment]
- [ ] `[core]` `...rest` arguments is not perfect [issue](https://github.com/HaxeFoundation/haxe/issues/10490).

**Comment by skial** [comment]
- [ ] `[core/js]` Implement `js.lib.WeakRef` [merged](https://github.com/HaxeFoundation/haxe/pull/10488).

**Comment by skial** [comment]
- [ ] `[core/hxcpp]` Reading from `stdout` of a process can hang on Windows [issue](https://github.com/HaxeFoundation/hxcpp/issues/975).

**Comment by skial** [comment]
- [ ] `[videos]` Check player offscreen Armory3D [tutorial](https://www.youtube.com/watch?v=GD8Ms2iMrSU&widget_referrer=haxe.io) by Willbot Studio.

**Comment by skial** [comment]
- [ ] `[videos]` Collision layers and masks, Armory3D [tutorial](https://www.youtube.com/watch?v=z2lfXupdRcs&widget_referrer=haxe.io) by Willbot Studio.

**Comment by skial** [comment]
- [ ] `[open source]` [blastactic `git](https://github.com/rbourdon/blastactic) - Cross-platform 2D physics-based puzzle game using Nape physics engine, written in Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [tweener `git`](https://github.com/openfl/tweener) - A class for creating tweens in Haxe - because there's infinity between 0 and 1.

**Comment by skial** [comment]
- [ ] `[open source]` [zenflo `git`](https://github.com/zenturi/zenflo) - Flow Based Programming Kit.
