### ISSUE TITLE
Haxe Roundup 609

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#936]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by Antriel** [comment]
- [ ] please remove `Peter Achberger is available for freelance work.`

**Comment by skial** [comment]
- [ ] `[core]` Relative imports [idea](https://github.com/HaxeFoundation/haxe/issues/10527).

**Comment by skial** [comment]
- [ ] `[core]` Allow typing expression with added imports and usings [feature request](https://github.com/HaxeFoundation/haxe/issues/10537).

**Comment by skial** [comment]
- [ ] `[core]` Implement `abstract` to access the abstract has been [merged](https://github.com/HaxeFoundation/haxe/issues/10482).

**Comment by skial** [comment]
- [ ] libs
   - [zenlog `0.2.0`](https://lib.haxe.org/p/zenlog)
   - [openfl-animate-atlas `0.0.1`](https://lib.haxe.org/p/openfl-animate-atlas)
   - [hxasync `1.1.3`](https://lib.haxe.org/p/hxasync)
   - [opentype.hx `0.0.3`](https://lib.haxe.org/p/opentype.hx)
   - [bp_duck `1.0.0`](https://lib.haxe.org/p/bp_duck)
   - [pony `1.6.5`](https://lib.haxe.org/p/pony)
   - [webstorage `2.0.0`](https://lib.haxe.org/p/webstorage)
   - [tink_onbuild `0.1.0`](https://lib.haxe.org/p/tink_onbuild)
   - [haxe-w `0.1.1`](https://lib.haxe.org/p/haxe-w)
   - [boisly_gcp_secrets `1.0.2`](https://lib.haxe.org/p/boisly_gcp_secrets)
   - [dts2hx_aliases `1.0.0`](https://lib.haxe.org/p/dts2hx_aliases)
   - [boisly_config `1.0.0`](https://lib.haxe.org/p/boisly_config)
   - [echo-flixel `0.0.1`](https://lib.haxe.org/p/echo-flixel)
   - [echo `4.0.0`](https://lib.haxe.org/p/echo)
   - [no-vdom `0.8.0`](https://lib.haxe.org/p/no-vdom)
   - [bootstrap_bundle `1.2.3`](https://lib.haxe.org/p/bootstrap_bundle)
   - [KGtools `0.0.1`](https://lib.haxe.org/p/KGtools)
   - [deepnightLibs `1.0.66`](https://lib.haxe.org/p/deepnightLibs)
   - [colictionary `1.0.1`](https://lib.haxe.org/p/colictionary)
   - [kglog `1.0.1`](https://lib.haxe.org/p/kglog)
   - [markov-namegen `1.1.1`](https://lib.haxe.org/p/markov-namegen)
   - [helder.set `0.3.1`](https://lib.haxe.org/p/helder.set)
   - [raycast `1.2.2`](https://lib.haxe.org/p/raycast)
   - [crypto `0.4.0`](https://lib.haxe.org/p/crypto)

**Comment by skial** [comment]
- [ ] `[community]` PogoGirl [Devlog `#28`](https://www.ohsat.com/post/pogogirl-devlog/post28/) Release Date!

**Comment by skial** [comment]
- [ ] `[community]` Heaps/Hashlink saving data for Android [article](https://gigglingcorpse.com/2021/12/13/heaps-hashlink-saving-data-for-android/).

**Comment by skial** [comment]
- [ ] `[community]` Heaps/Hashlink on Android [article](https://gigglingcorpse.com/2021/12/16/heaps-hashlink-on-android/).

**Comment by skial** [comment]
- [ ] `[community]` New Fraymakers Music! December 2021 Fraymakers [Roundup](https://www.kickstarter.com/projects/mcleodgaming/fraymakers-the-infinitely-replayable-indie-platform-fighter/posts/3397501).

**Comment by skial** [comment]
- [ ] `[closed source]` Elevator Music is forbidden inside the Prison Planet by [Fierce](https://twitter.com/FierceTheBandit/status/1476352052871798796).

**Comment by skial** [comment]
- [ ] `[open source]` HaxeUI `actions` are being overhauled by [Ian Harrigan](https://twitter.com/IanHarrigan1982/status/1476242085791547393) in the latest video sneak peek.

**Comment by skial** [comment]
- [ ] `[releases]` [Gepatto](https://twitter.com/gepatto/status/1473989036448661504) released a gift for Christmas, a festive themed version of OpenFL's PiratePig demo available to download for the Raspberry Pi and compiled to HTML5.

**Comment by skial** [comment]
- [ ] `[closed source]` Super Cosmic Heist - World 4-5 `WIP` by [Fierce](https://twitter.com/FierceTheBandit/status/1473790476461424653).

**Comment by skial** [comment]
- [ ] `[releases]` IriySoft have released a simple match 3 game called [Jewel Monsters](https://twitter.com/IriySoft/status/1473224889272352772) made with OpenFL targeting HTML5.

**Comment by skial** [comment]
- [ ] `[community]` Making an Underwater Music Effect in HaxeFlixel [article](https://www.ohsat.com/tutorial/flixel/underwater-music-effect/) by [Andrej](https://twitter.com/ohsat_games/status/1472919405646524421).

**Comment by skial** [comment]
- [ ] `[closed source]` [Merrak](https://twitter.com/merrak/status/1470582301293793284) shows off a quick experimentation with comic book style artwork for cutscenes in Rogue of Vallas.

**Comment by skial** [comment]
- [ ] `[community]` [Nicolas Cannasse](https://twitter.com/ncannasse/status/1469192804215758857) announces that Shiro Games are working on a new Dune strategy game called [Dune: Spice Wars](https://store.steampowered.com/app/1605220/Dune_Spice_Wars/).

**Comment by skial** [comment]
- [ ] `[releases]` [Ionosofts](ionosoft.com/solutions) _"Visual Cath Report, a cardiac catheterization reporting and coronary diagramming application). has updated to latest version of HaxeUI successfully (with minimal changes) allowing it utilise all its latest improvements!"_ via [Ian Harrigan](https://twitter.com/IanHarrigan1982/status/1469023221815164931).

**Comment by skial** [comment]
- [ ] `[community]` [RenchuAye](https://renchuaye.newgrounds.com/news/post/1232646) has posted about their progress, getting into gamedev by using Haxe.

**Comment by skial** [comment]
- [ ] `[community]` Catch-up on the [results](https://itch.io/jam/haxejam-2021-winter-edition/results) from The HaxeJam 2021: Winter Edition!

**Comment by skial** [comment]
- [ ] `[community]` What [do you love](https://www.reddit.com/r/haxe/comments/rcpj1w/what_do_you_love_most_about_haxe/) most about Haxe?

**Comment by skial** [comment]
- [ ] `[video]` Rogue of Vallas Level 2 Construction Zone [video](https://www.youtube.com/watch?v=or8-N5ar5o0&widget_referrer=haxe.io) by Merrak.

**Comment by skial** [comment]
- [ ] `[video]` Adding physics to a HaxeFlixel game with Echo | [FlxEcho tutorial](https://www.youtube.com/watch?v=yEI3T0gSj2w&widget_referrer=haxe.io) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] `[video]` Live previewing in Armory3D [video](https://www.youtube.com/watch?v=Egf2qa9T0zk&widget_referrer=haxe.io) by Willbot Studio.

**Comment by skial** [comment]
- [ ] `[open source]` [light-refraction `git`](https://github.com/KinoCreatesGames/light-refraction) - A small game made in Heaps to test out how to use light within a game for solving puzzles.

**Comment by skial** [comment]
- [ ] `[open source]` [YYTextureView `git`](https://github.com/YAL-GameMaker-Tools/YYTextureView) - A tool for exploring textures in GameMaker games. Available [online](https://yal.cc/game-tools/yytextureview/).

**Comment by skial** [comment]
- [ ] `[open source]` [BlackCat `git`](https://github.com/NaxeCode/BlackCat) - A Sleek, Modern Tarot Card Prediction Tool.

**Comment by skial** [comment]
- [ ] `[open source]` [DocMd `git`](https://github.com/YAL-Tools/DocMd) - A Markdown-esque renderer written in Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [handlebars-hx `git`](https://github.com/snsvrno/handlebars-hx) - A Haxe implementation of the handlebars templating engine.

**Comment by skial** [comment]
- [ ] `[open source]` [rabbhx `git`](https://github.com/logo4poop/rabbhx) - An attempt at a port of the uxn virtual machine to Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [hxLruCache `git`](https://github.com/ianxm/hxLruCache) - Simple LRU cache implemented with a Map.

**Comment by skial** [comment]
- [ ] `[community]` [Oleg Dolya](https://twitter.com/watawatabou/status/1478404546628042760) has released a small [update](https://watabou.itch.io/antlers/devlog/331782/110) for Antlers Generator `1.1.0`.

**Comment by skial** [comment]
- [ ] `[community]` Perilous Shores `1.3.0`: roads and permalinks [article](https://www.patreon.com/posts/60165082) by [Oleg Dolya](https://twitter.com/watawatabou/status/1473284572272025604).

**Comment by skial** [comment]
- [ ] `[closed source]` [Syo](https://twitter.com/SyoPic/status/1477298224515985410) has taught the crew how to turn air controllers on and off in JitterSandbox.

**Comment by skial** [comment]
- [ ] `[releases]` [Advent](https://twitter.com/AdventIslands/status/1476650486967250952) has released Super Dangerous Dungeons onto Poki! Made in Stencyl.

**Comment by skial** [comment]
- [ ] `[releases]` [Bay Riser Games]` has released the demo for Bright Bruiser, available on [itch.io](https://bayrisergames.itch.io/bright-bruiser-demo) and [Newgrounds](https://www.newgrounds.com/portal/view/827583), made with Stencyl.

**Comment by skial** [comment]
- [ ] `[closed source]` [Gepatto](https://twitter.com/gepatto/status/1475508597907939328) has been working on _"a simple ukulele chord finder app in Haxe & OpenFL with it running on a Raspberry PI 4, also runs on cli, a mac and in a browser. Credits to ukulele.nl for original version!"_

**Comment by skial** [comment]
- [ ] `[closed source]` [Mine Blocks 2](https://twitter.com/Mine_Blocks2/status/1475202053857329153) main menu now remade and working in HTML5!

**Comment by Beeblerox** [comment]
- [ ] Ian Harrigan is playing around with [Haxe + Windows + Haxe](https://twitter.com/IanHarrigan1982/status/1474791600521986057). And making it all a little [more "haxey"](https://twitter.com/IanHarrigan1982/status/1475097429255106570)

**Comment by Beeblerox** [comment]
- [ ] A bunch of new GIFs from Jitter Sandbox by Syo:
    * [Debug layer for oxygen](https://twitter.com/SyoPic/status/1468700966685970433)
    * I must say that [these were mannequins](https://twitter.com/SyoPic/status/1469332809013727239)
    * [Infinite Improbability Drive](https://twitter.com/SyoPic/status/1469750558705790978) in action
    * [It's windy today](https://twitter.com/SyoPic/status/1471964752947650561)
    * [Happy New Year!](https://twitter.com/SyoPic/status/1476899102143221760)
    * I taught them to [turn air controllers on and off](https://twitter.com/SyoPic/status/1477298224515985410)

**Comment by Beeblerox** [comment]
- [ ] SavanDev is [learning how to use shaders](https://twitter.com/dylnavas36/status/1469572663316254723)

**Comment by Beeblerox** [comment]
- [ ] So, first pass of multi-tile objects works. [Giant Skeleton](https://twitter.com/mauvecow/status/1477438736505860097) is probably not appearing in Addlemoth but makes a great test

**Comment by Beeblerox** [comment]
- [ ] [Chessformer](https://store.steampowered.com/app/1701190) by Robert Alvarez now [has a release date for Steam](https://twitter.com/Rob1221dev/status/1470423268079243264): January 18, 2022!
- [ ] [Math Push](https://twitter.com/Rob1221dev/status/1478017561438691337) is now available on [itch.io](https://rob1221.itch.io/math-push) and [NewGrounds](https://www.newgrounds.com/portal/view/828230)

**Comment by Beeblerox** [comment]
- [ ] [Dead Cells: The Queen and the Sea](https://store.steampowered.com/app/1580050/Dead_Cells_The_Queen_and_the_Sea/) by [Motion Twin](https://twitter.com/motiontwin/status/1471525539634728961) has landed January 6th on PC & consoles!

**Comment by Beeblerox** [comment]
- [ ] [Placeholder dialogue](https://twitter.com/squuuidly/status/1471520265100214278) in Renaine be like

**Comment by Beeblerox** [comment]
- [ ] Wartales [Community Update #1](https://steamcommunity.com/games/1527950/announcements/detail/4891470233634997467) is now live

**Comment by Beeblerox** [comment]
- [ ] [Energy Island Corp](https://twitter.com/SpirkopGames/status/1476950480752463892) will be available on Steam the 19 January, 2022

**Comment by Beeblerox** [comment]
- [ ] Lars Doucet is doing [a quick experiment](https://twitter.com/larsiusprime/status/1473757099855331332) in Defenders Quest 2 to see if the game feels better with much "chunkier" skill points

**Comment by Beeblerox** [comment]
- [ ] Few quick videos from Kino Rose:
    * [Having fun with shaders](https://twitter.com/EISKino/status/1470105669105823752)
    * [Starting work on a new game](https://twitter.com/EISKino/status/1475566132610449420)
    * Finished another small game [playing with shaders](https://twitter.com/EISKino/status/1475566666130014211)

**Comment by Beeblerox** [comment]
- [ ] [Web Workers in Lime](https://player03.com/openfl/web-workers/)

**Comment by Beeblerox** [comment]
- [ ] [Jeremy Fa](https://discord.com/channels/162395145352904705/162664383082790912/918461730294730762) has started working on a [website for ceramic](https://ceramic-engine.com/)

**Comment by Beeblerox** [comment]
- [ ] ShaharMS is working on a [golf minigame](https://discord.com/channels/162395145352904705/162664383082790912/918609857622458428) in which a player controls both of the balls in the same time

**Comment by Beeblerox** [comment]
- [ ] [ZwodahS](https://discord.com/channels/162395145352904705/162664383082790912/919061668410060830) has released [Dice Kingdom](https://zwodahs.itch.io/dice-kingdom) 0.1.3 with updated graphics and a new tutorial

**Comment by Beeblerox** [comment]
- [ ] Daniel Blaker has [optimised Orbdig perf](https://discord.com/channels/162395145352904705/162664383082790912/919223316022198342)! With [source code](https://github.com/5Mixer/LD48) available at github

**Comment by Beeblerox** [comment]
- [ ] [Package Party](https://swiftrasin.itch.io/package-party) by [New_Cartoon_64_ツ](https://discord.com/channels/162395145352904705/162664383082790912/919486159380434975)

**Comment by Beeblerox** [comment]
- [ ] [George](https://discord.com/channels/162395145352904705/162664383082790912/921869422577213470) has made a waiter that busses tables and serves coffee

**Comment by Beeblerox** [comment]
- [ ] [Tabs are now a thing](https://discord.com/channels/162395145352904705/162664383082790912/925438826137149511) with Ceramic's immediate UI API

**Comment by Beeblerox** [comment]
- [ ] [Gravitational trickshots](https://discord.com/channels/162395145352904705/162664383082790912/925844528664027146) with Minicology's cannons

**Comment by Beeblerox** [comment]
- [ ] [Flocking simulation](https://discord.com/channels/162395145352904705/162664383082790912/926580488867557466) in Haxe by Markl. Here's a [little web build](https://drewbys-games.itch.io/flock?secret=FGJukANLxroIDSKmAY1XR4YU) of the flocking example made with Flixel

**Comment by Beeblerox** [comment]
- [ ] [Benchmark](http://openfl-animate-atlas.surge.sh/) for [Adobe Animate Atlas Player](https://lib.haxe.org/p/openfl-animate-atlas/) for OpenFL Tilemap by [Euro Ali](https://discord.com/channels/415681294446493696/436230004251164672/927057473096020009)

**Comment by skial** [comment]
- [ ] `[community]` Distilling Skills -- [DQ2 Progress Report](https://www.fortressofdoors.com/distilling-dq2-progress-report-for-december-2021/) for December 2021 by Lars Doucet.

**Comment by skial** [comment]
- [ ] `[community]` A guide to threads in Lime [article](https://player03.com/openfl/threads-guide/).

**Comment by skial** [comment]
- [ ] `[community]` FeathersUI [Devlog](https://www.kickstarter.com/projects/feathersui/feathers-ui-cross-platform-components-for-haxe-and-openfl/posts/3398759): TreeGridView, HierarchicalItemRenderer, required FormItems, and FlowRowsLayout.

**Comment by skial** [comment]
- [ ] `[community]` Fixing stutters in Papers Please on Linux [article](https://blog.jhm.dev/posts/papers-please/).
