### ISSUE TITLE
Haxe Roundup 620

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#960]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` Rework internal frontend part 1 [merged](https://github.com/HaxeFoundation/haxe/pull/10629).
- [ ] `[core]` Rework internal frontend part 2 [merged](https://github.com/HaxeFoundation/haxe/pull/10631).

**Comment by skial** [comment]
- [ ] libs
   - [shadertools `0.0.8`](https://lib.haxe.org/p/shadertools)
   - [firefuck `1.0.55`](https://lib.haxe.org/p/fireduck)
   - [cheknikot `1.0.0`](https://lib.haxe.org/p/cheknikot)
   - [deepnightLibs `1.0.70`](https://lib.haxe.org/p/deepnightLibs)
   - [apollo `0.3.0`](https://lib.haxe.org/p/apollo)
   - [texter `1.1.4`](https://lib.haxe.org/p/texter)
   - [echo `4.2.0`](https://lib.haxe.org/p/echo)
   - [formatter `1.13.0`](https://lib.haxe.org/p/formatter)
   - [fast-xml-parser `4.0.0`](https://lib.haxe.org/p/fast-xml-parser)

**Comment by skial** [comment]
- [ ] `[video]` Story Creator - [Episode 4](https://www.youtube.com/watch?v=pQA5INvM2AU&widget_referrer=haxe.io) - Completing File/Folder Management by StoryDev.
- [ ] `[video]` Story Creator - [Episode 5](https://www.youtube.com/watch?v=d6q47SOkcvE&widget_referrer=haxe.io) - Script Executions and Validations by StoryDev.
- [ ] `[video]` Week `#5` Programming - Editing Scripted Events - [Part 1](https://www.youtube.com/watch?v=gq0Qrz5O12s&widget_referrer=haxe.io) by StoryDev.

**Comment by skial** [comment]
- [ ] [syntax-guide `git`](https://github.com/runkanrenchu/syntax-guide) - `WIP` This is a guide for Haxe syntax, fully commented.

**Comment by skial** [comment]
- [ ] `[open source]` [fsm `git`](https://github.com/pecheny/fsm) - Simple finite state machine implementation in Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [Oleg Dolya](https://twitter.com/watawatabou/status/1505569178966798346) has _"improved night mode in which city lights do not obscure details as they used to do"_.

**Comment by skial** [comment]
- [ ] `[community]` Take a deep dive with [Fraymakers](https://twitter.com/FraymakersGame/status/1505226267997605888), _"into a special portion of the engine that handles how stage collisions work in Fraymakers. Introducing: the Environment Collision Body!"_

**Comment by skial** [comment]
- [ ] `[open source]` [Ian Harrigan](https://twitter.com/IanHarrigan1982/status/1505671650578153484) shares the progress made to the HaxeUI "action manager".

**Comment by Beeblerox** [comment]
- [ ] [Pushing blocks of light](https://twitter.com/Rob1221dev/status/1504819921934454787) in new WIP puzzle game by Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] One million tiny fixes later, [crypt tileset with smooth foggy water](https://twitter.com/mauvecow/status/1506853466542551042) is more or less ready to go!

**Comment by Beeblerox** [comment]
- [ ] [Playdigious are releasing](https://twitter.com/motiontwin/status/1506248183235629060) the Queen and the Sea DLC for Dead Cells mobile version on April 7th. And the Practice Makes Perfect and Everyone is Here updates are arriving at the same time

**Comment by Beeblerox** [comment]
> - [ ] optional description [link name](/link/to/item)

- [ ] [UPDATE #1 - Harag's Marshlands](https://steamcommunity.com/games/1527950/announcements/detail/3096794565653039228)

**Comment by Beeblerox** [comment]
> * [ ]  `[closed source]` Take your first foray into Harag's Marshlands in [Wartales](https://twitter.com/Wartales_Game/status/1505897695977824261).

- [ ] [UPDATE #1 - Harag's Marshlands](https://steamcommunity.com/games/1527950/announcements/detail/3096794565653039228)

**Comment by Beeblerox** [comment]
- [ ] A picture of [the menu background](https://twitter.com/InyourbooksGame/status/1505276703328903177) from In your books

**Comment by Beeblerox** [comment]
- [ ] [Jamming out](https://msghero.newgrounds.com/news/post/1257059) by Nick MSGhero

**Comment by Beeblerox** [comment]
- [ ] K Board Games is [showing the progress](https://discord.com/channels/162395145352904705/162664383082790912/954949601268465745) of the board games. And is always looking for help in this open source board game project.

**Comment by Beeblerox** [comment]
- [ ] [LDtk beta 5 is out!](https://ldtk.io/files/beta/)

**Comment by Beeblerox** [comment]
- [ ] Sébastien Benard has [added "9-slice scaling" mode](https://discord.com/channels/761549092677353513/778168731036549130/956217930289385562) for Entity tile rendering.

**Comment by Beeblerox** [comment]
- [ ] [Who's that singing](https://discord.com/channels/162395145352904705/162664383082790912/956327828016754729) in Minicology??

**Comment by Beeblerox** [comment]
- [ ] [ZwodahS](https://discord.com/channels/162395145352904705/162664383082790912/956419535097966622) has released [Dice Tribes: Ambitions](https://zwodahs.itch.io/dice-tribes-ambitions) 0.4.1 update. New Buildings added, a new Tribe.

**Comment by skial** [comment]
- [ ] `[core]` Sort out server module marks [pull request](https://github.com/HaxeFoundation/haxe/pull/10640).
