### ISSUE TITLE
Haxe Roundup 629

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#980]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` Overriding files no longer works as expected in development builds [fixed](https://github.com/HaxeFoundation/haxe/issues/10711).

**Comment by skial** [comment]
- [ ] `[open source]` [ceramic `0.12.2`](https://github.com/ceramic-engine/ceramic/releases/tag/v0.12.2) has been released.

**Comment by skial** [comment]
- [ ] `[open source]` [haxe-rename `2.2.2`](https://github.com/HaxeCheckstyle/haxe-rename/releases/tag/v2.2.2) has been released.

**Comment by skial** [comment]
- [ ] libs
   - [electron `18.3.0`](https://lib.haxe.org/p/electron)
   - [rename `2.2.2`](https://lib.haxe.org/p/rename)
   - [haxe-injection `1.0.1`](https://lib.haxe.org/p/haxe-injection)

**Comment by skial** [comment]
- [ ] `[video]` FPS tutorial for backrooms escape game - Armory3D [tutorial](https://www.youtube.com/watch?v=6hLDVmugm_U&widget_referrer=haxe.io) by Exceptional 3D tutorials.

**Comment by skial** [comment]
- [ ] `[video/audio]` Impetus - Fraymakers Original [Soundtrack](https://www.youtube.com/watch?v=PhuuD-WO4ig&widget_referrer=haxe.io).

**Comment by skial** [comment]
- [ ] `[open source]` [sparrow `git`](https://github.com/nevergarden/sparrow) - `WIP` A 2D Game Framework For Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [Endless-Square-Runner `git`](https://github.com/K1lloByte/Endless-Square-Runner) - A simple xbox/switch compatible endless runner with squares and stuff.

**Comment by skial** [comment]
- [ ] `[open source]` [puremvc-haxe-feathersui-demos `git`](https://github.com/feathersui/puremvc-haxe-feathersui-demos) - Demonstrates how to create projects with PureMVC and Feathers UI.

**Comment by skial** [comment]
- [ ] `[open source]` [Oleg Dolya](https://twitter.com/watawatabou/status/1528757847386996737) has created the _"option to request maps of arbitrary dimensions I can finally generate something like itinerary maps"_.

**Comment by skial** [comment]
- [ ] `[community]` Wartales Community Update `#3` [article](https://store.steampowered.com/news/app/1527950/view/3191375239922134718).

**Comment by skial** [comment]
- [ ] `[closed source]` [In your books](https://twitter.com/InyourbooksGame/status/1528108406816505858) is _"back on track as promised with this `#screenshotsaturday`. With this little one on the right, all the character are finished."_

**Comment by skial** [comment]
- [ ] `[closed source/video]` [Scraps of Light](https://twitter.com/joelgervasi/status/1529183366054125570) shares a _not quite a trailer_ trailer!

**Comment by skial** [comment]
- [ ] `[releases]` [Scraps of Light](https://twitter.com/joelgervasi/status/1528158034240983040) demo has been _"updated, it features 2x the content of the old demo and is better in every way"_!

**Comment by Beeblerox** [comment]
- [ ] [saharan](https://twitter.com/shr_id/status/1527278070444351491) released! 🌊[Real-time 3d water simulation](https://oimo.io/works/water3d/) for PCs & smartphones. Made with [OimoPhysics](https://github.com/saharan/OimoPhysics)

**Comment by Beeblerox** [comment]
- [ ] Dune: Spice Wars - [Community Update #1 Out Now!](https://store.steampowered.com/news/app/1605220/view/3226278286753805585)

**Comment by Beeblerox** [comment]
- [ ] torcado is [working on a big update](https://twitter.com/torcado/status/1528104879184543745) to Heck Deck

**Comment by Beeblerox** [comment]
- [ ] [Andrej](https://twitter.com/ohsat_games/status/1528509888950829056) has finished [Cave of Lexip](https://ohsat-andrej.itch.io/cave-of-lexip). If you played it and liked it, be sure to leave a rating!

**Comment by Beeblerox** [comment]
- [ ] [Naoya](https://twitter.com/RoyalityKnight/status/1528385640148131841) has announced that Hitter is going to be present at the Solutec Gamer Expo v2.22 in Maracay! As a demo of course.

**Comment by Beeblerox** [comment]
- [ ] Super Cosmic Heist Enemy [Showcase #8 - "Trappa"](https://twitter.com/FierceCosmicArt/status/1528518886454398978)

**Comment by Beeblerox** [comment]
- [ ] [Naxie](https://twitter.com/NaxeCode/status/1528644330595811328) is working on starting up a new game development studio for an upcoming project. Technologies they're using: Haxe + OpenFL + HaxeFlixel and LDTK (for level editing)

**Comment by Beeblerox** [comment]
- [ ] Prexot is [getting familiar](https://discord.com/channels/162395145352904705/853414608747364352/978805149365567489) with ceramic and spine

**Comment by Beeblerox** [comment]
- [ ] Rob Clemmons Jr has shared [new screenshot](https://discord.com/channels/162395145352904705/162664383082790912/978003079712624650) from Patches of Adventure

**Comment by Beeblerox** [comment]
- [ ] [ShaharMS](https://discord.com/channels/162395145352904705/162664383082790912/978109095607414856)' first Haxe tutorial in the haxe learning center - [OpenFL - With Multiple Windows](https://spacebubble.io/haxe/?name=Multiple-Windows). Feel free to [contribute to the project](https://github.com/ShaharMS/spacebubble.io/tree/main/haxe) if you'd like to

**Comment by Beeblerox** [comment]
- [ ] [snsvrno](https://discord.com/channels/162395145352904705/162664383082790912/979123032301903892) is working on some libraries to make TUI applications using Haxe. And has splitted out the basic ANSI commands into [ANSI.hx library](https://github.com/snsvrno/ansi-hx). Next will be a little app framework for making "full terminal tui apps"

**Comment by Beeblerox** [comment]
- [ ] Mostly accurate [Sonic CD menu recreation](https://discord.com/channels/162395145352904705/162664383082790912/979200800331014195) in FNF by DaPootisBird

**Comment by skial** [comment]
- [ ] `[core]` Wrong diagnostic range for override keyword [issue](https://github.com/HaxeFoundation/haxe/issues/10714).

**Comment by skial** [comment]
- [ ] `[open source]` [Damilare Akinlaja](https://twitter.com/FourEyedWiz/status/1529465705502068736) is decoding the HashLink bytecode in Rust in their [brass_vm `git`](https://github.com/darmie/brass_vm) library.

**Comment by Beeblerox** [comment]
- [ ] [A block house to keep the lava out](https://twitter.com/Rob1221dev/status/1529477403050921984) by Robert Alvarez
