### ISSUE TITLE
Haxe Roundup 635

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#994]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[core]` Abstract classes and interface [issue](https://github.com/HaxeFoundation/haxe/issues/10748).

**Comment by skial** [comment]
- [ ] `[core]` Monomorph type applied when doing `?? return` [issue](https://github.com/HaxeFoundation/haxe/issues/10744).

**Comment by skial** [comment]
- [ ] `[core/jvm]` `JvmCode.EmptyStack` when using explicit return inside an arrow function stored in a field [issue](https://github.com/HaxeFoundation/haxe/issues/10743).

**Comment by skial** [comment]
- [ ] `[core]` Inline constructor fails when some function returns `this` [issue](https://github.com/HaxeFoundation/haxe/issues/10741).

**Comment by skial** [comment]
- [ ] `[open source]` [hscript `2.5.0`](https://github.com/HaxeFoundation/hscript/releases/tag/2.5.0) has been released!

**Comment by skial** [comment]
- [ ] libs
   - [pony `1.8.8`](https://lib.haxe.org/p/pony)
   - [aeons `0.1.1`](https://lib.haxe.org/p/aeons)
   - [HxShaders `3.2.0`](https://lib.haxe.org/p/HxShaders)
   - [hscript `2.5.0`](https://lib.haxe.org/p/hscript)
   - [hsluv `0.1.0`](https://lib.haxe.org/p/hsluv)
   - [hxhttp `0.0.5`](https://lib.haxe.org/p/hxhttp)

**Comment by skial** [comment]
- [ ] `[community]` Fireworks -- DQ2 [Progress Report](https://www.fortressofdoors.com/great-balls-of-fire-dq2-progress-report-for-june-2022/) for June 2022 by Lars Doucet.

**Comment by skial** [comment]
- [ ] `[video]` Armory3D - Tilt shift [effect](https://www.youtube.com/watch?v=N9S7ENWIADo&widget_referrer=haxe.io) by Alexander Kleemann.

**Comment by skial** [comment]
- [ ] `[open source]` [logisim-assembler `git`](https://github.com/oskar2517/logisim-assembler) - Assembler designed to work in conjunction with my microcode compiler.

**Comment by skial** [comment]
- [ ] `[open source]` Hollow river shapes by [Oleg Doyla](https://twitter.com/watawatabou/status/1544369599289991168).

**Comment by skial** [comment]
- [ ] The final generative art piece being exhibited by [Jérémy Fa](https://twitter.com/jeremyfaivre/status/1543547305013428224), made with ceramic.

**Comment by skial** [comment]
- [ ] `[open source]` [ʇ0mmy](https://twitter.com/d0oo0p/status/1542868517954912256) has released [HL_WMF_Video `git`](https://github.com/LogicInteractive/HL_WMF_Video) which adds VideoTexture Integration for Heaps / HL using Windows Media Foundation.

**Comment by Beeblerox** [comment]
- [ ] Dicey Dungeons Reunion DLC [will be released on July 7th](https://twitter.com/terrycavanagh/status/1542538873175252993).
- [ ] [Coming Soon: Dicey Dungeons Reunion](https://distractionware.com/blog/2022/06/coming-soon-dicey-dungeons-reunion/)
- [ ] [The Reunion Reunion](https://distractionware.com/blog/2022/07/the-reunion-reunion/)

**Comment by Beeblerox** [comment]
- [ ] Couple of quick videos from Purradox by SRDude:
    * i like when the menu loops it just [sends itself around the world](https://twitter.com/SumRndmDde/status/1542688053659160582) instead hopping the shortest distance back
    * [Day 49. File select screen](https://twitter.com/SumRndmDde/status/1543173546414931968). Tastier than ramen cooked in dr. pepper.

**Comment by Beeblerox** [comment]
- [ ] [new lil game soon](https://twitter.com/zzo__x/status/1543074414492880896) by zzox (tyler)

**Comment by Beeblerox** [comment]
- [ ] [Hopefully this will work like I intend it to](https://twitter.com/RobClemmonsJr/status/1543124866815213578) by Rob Clemmons Jr

**Comment by Beeblerox** [comment]
- [ ] [Screens from 3-1](https://twitter.com/RoyalityKnight/status/1543252241859203074) levels of WIP Hitter game by Naoya

**Comment by Beeblerox** [comment]
- [ ] 🔥 [SSSPICY!](https://ssspicy.torcado.repl.co/) 🔥 by [torcado](https://twitter.com/torcado/status/1543687060745224193)

**Comment by Beeblerox** [comment]
- [ ] [Quick video](https://twitter.com/MortMort_/status/1544107618683207680) of a work in progress level by MortMort. Plus a bit of art, level design, programming who knows maybe music too for [a generic mobile platformer](https://twitter.com/MortMort_/status/1543263683756924929).

**Comment by Beeblerox** [comment]
- [ ] [House Corrino](https://steamcommunity.com/games/1605220/announcements/detail/3328738190607959594) is coming to Dune: Spice Wars!

**Comment by Beeblerox** [comment]
- [ ] [New Dead Cells alpha is out](https://store.steampowered.com/news/app/588650/view/3346752589091373474) - panchaku, rebalancing, legendary rework, pet the pet & more

**Comment by Beeblerox** [comment]
- [ ] [Heaps can easily compile Android, IOS, HTML5, MAC, window, etc](https://community.haxe.org/t/heaps-can-easily-compile-android-ios-html5-mac-window-etc/3583)

**Comment by Beeblerox** [comment]
- [ ] [Talk To Strangers](https://store.steampowered.com/app/963280/Talk_to_Strangers/) developed by Post Mortem Pixels is [ported from Stencyl to Nintendo Switch](https://twitter.com/larbacsilva/status/1544103203154837505) and will be available soon on Nintendo eShop

**Comment by skial** [comment]
- [ ] `[core]` Add BigInteger type [pull request](https://github.com/HaxeFoundation/haxe/pull/10750), with this implementation being `5x` faster than others and `3x` faster than native Java.

**Comment by skial** [comment]
- [ ] `[open source]` [multi-window `git`](https://github.com/47rooks/multi-window) - HaxeFlixel Multi-Window POC.
